### ISSUE TITLE
Experimentation spike on ultrasonic data xfer, etc

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#100]
We need to land on the proper mechanism(s) for doing device pairing for standalone devices like oculus go, or linking your desktop to your mobile for cases like screen sharing. Some relevant links:

https://developers.google.com/nearby/messages/overview
https://youtu.be/Acdu2ZdBaZE
https://youtu.be/1a0wII96cpE
http://smus.com/ultrasonic-networking/

**Comment by robertlong** [comment]
Closing. I think we've reduced friction enough with the hubs.link flow.
