### ISSUE TITLE
Object instantiation bugged if client who last touched an object leaves

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#1000]
https://github.com/mozilla/hubs/pull/880 introduced a bug where upon an object can enter a state where it has no owner and therefore no one will send instantiation messages for it if new users join.

Repro: 
1. Client A and Client B enter a room.
2. Client A spawns a duck.
3. Client B takes duck.
4. Client B reloads.
5. Duck now has no owner, but is not deleted.
6. Client B reconnects, but Client A does not know its supposed to send an instantiation message for the duck, so Client B does not ever see the duck.
7. The duck can still be seen and manipulated by Client A.

Possible solutions:
1. Change behavior so that only in the case a client is kicked do the objects they created get removed.
2. Have all clients do a check when a client leaves to see if they are the creator of any of the objects of the client who left, then explicitly retake ownership.

**Comment by gfodor** [comment]
an alternative to 2 could also be to change the contract of who is responsible for sending the full sync to new users. if the owner is in the room, they send it. if the owner is not in the room, the creator sends it. that would probably be simpler to reason through since it won't mutate any state on the object at leave time, it just makes it so we can always be sure at least once responsible party can send the full sync.

**Comment by gfodor** [comment]
to do what I suggested, I believe we'd need to update `canSync` in `networked.js` to return `true` in the condition I mentioned above. currently it returns `true` if the current client is the owner

**Comment by InfiniteLee** [comment]
Would it not be even simpler to just always have the creator do the sync?

**Comment by gfodor** [comment]
I'd be nervous around conditions where there's a current owner who isn't the creator manipulating the object in the room, and the creator sending out-of-date info during initial sync.

**Comment by gfodor** [comment]
https://github.com/MozillaReality/networked-aframe/pull/24
