### ISSUE TITLE
Support GearVR gaze controls

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#101]
We should ensure if you don't have a GearVR controller that you can use the touchpad/gaze cursor. (However up this should be timeboxed to a day or two's efforts for now if it ends up being particularly difficult to support.)

**Comment by gfodor** [comment]
This should be tightly timeboxed for a few hours -- not a must-have for launch but if it's cheap to enable then def worthwhile to increase device support.

**Comment by netpro2k** [comment]
This should be done along with #122
