### ISSUE TITLE
Rooms are black in Chrome, choking on JavaScript error: `Uncaught (in promise) DOMException`

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#1013]
1. Launch Chrome on macOS.
2. Load the [Hubs homepage](https://hubs.mozilla.com).
3. Press the **Create Room** button.
4. When you're in a [room](https://hubs.mozilla.com/q0h8GEC/content-crazy-rendezvous), the scene doesn't load. The screen remains black.
5. Notice rooms load fine in Firefox without any issues.

## Chrome
![image](https://user-images.githubusercontent.com/203725/53798643-87524d80-3eed-11e9-904f-5c31cdf3f482.png)

![image](https://user-images.githubusercontent.com/203725/53798635-83263000-3eed-11e9-853c-1542bca4200c.png)

In the Console, this JavaScript error appears:

> `Uncaught (in promise) DOMException    hub.js: 872`

## Firefox

![image](https://user-images.githubusercontent.com/203725/53798803-d7311480-3eed-11e9-9553-933ce2553c5f.png)

**Comment by gfodor** [comment]
hey @cvan i'm not able to repro this in Chrome on MacOS. I'm not sure what that promise rejection is about, though likely it's symptomatic of a deeper problem. (That error should not terminate control flow afaik.)

I do see some WebXR error messages there which I don't recognize, is there some kind of WebXR polyfill issue potentially?

**Comment by cvan** [comment]
With no extensions installed, I can still reproduce this:

![image](https://user-images.githubusercontent.com/203725/54427855-ea579780-46d8-11e9-9420-97623b67e5c8.png)

Anyone else on Chrome on macOS experience this? I'll try to test different machines to see what's up. Thanks!

**Comment by cvan** [comment]
The error messages are different now and the CSP errors are new: #1285 

Feel free to close and address #1285 instead.

**Comment by brianpeiris** [comment]
This seems to be resolved now. Thanks for reporting it!
