### ISSUE TITLE
Error in console when taking photos with camera

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#1019]
```
media-utils.js:110 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at f (media-utils.js:110)
    at n.updateSrc (open-media-button.js:11)
    at NAF.utils.getNetworkedEntity.then.e (open-media-button.js:39)

media-utils.js:110 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at f (media-utils.js:110)
    at NAF.utils.getNetworkedEntity.then.e (clone-media-button.js:12)
```

Doesn't seem to actually break anything.

**Comment by misslivirose** [comment]
Is there anything specific that has to happen for this, or has this since been resolved? I'm not able to repro using the following steps:

1. Open up the camera tool
2. Open up the console
3. Take a photo
4. Look at console

**Comment by misslivirose** [comment]
Since we've had some updates to the camera within the past few months and I'm not able to get a repro on this, I'm going to close but we can re-open if it's seen again.
