### ISSUE TITLE
hub.link ABC not available in Firefox Reality, works fine in Oculus Browser

### ISSUE THREAD

**Issue by fedormyskin** [mozilla/hubs#1031]
Rooms provide hub.link code with letters only, but when using Oculus GO and Firefox Reality browser the ABC input option is not available, I can only input numbers.
Tried the Oculus browser and it works fine.

Same problem with PC and Firefox browser.

**Comment by brianpeiris** [comment]
Thanks for the report. I've confirmed that this still a problem in FxR

**Comment by johnshaughnessy** [comment]
Similarly we should ensure that ABC shows up on daydream.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/1090
