### ISSUE TITLE
Nonexistent shape

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1034]
repositionToolbar is looking for a nonexistent shape when i enter a room:  
`TypeError: this.el.getAttribute(...) is null`

https://github.com/mozilla/hubs/blob/a621ca51136c40291e5ab557c2511ae2bf971c56/src/components/media-loader.js#L346

**Comment by InfiniteLee** [comment]
`"shape"` should be `"ammo-shape"`. Also note that halfExtents will only be set in some cases, but since this is specifically used for PDF's (in which we specifically define the halfExtents used to generate the box collider), it should be.
