### ISSUE TITLE
Avatar experiments

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#105]
In a rather PHB-like fashion I wanted to write some quick avatar studies I think we should do. Feel free to discard any or all of these ideas if you don't think they make sense:

- Try removing the mouth grate from the face of the robot. Having no mouth at all might feel better than a non-functional one.
- Try changing the pupils to be circular
- Try changing the color of the eyes to be the more typical "black pupils on white background"
- For the heck of it, create a "panda" texture map to get a sense if doing that ends up feeling like a "robot painted like a panda" vs "a robotic panda" vs "a lego panda" etc. Would be good to get a sense of just how far the existing model may be able to be stretched by the community. It also might inform small changes we could make to the model that would radically increase its versatility. (For example, I'm wondering if the deep eye sockets may really 'lock-in' the robot-ness of the model, so we may want to flatten them out if that's one of a few things we could do to reduce it.)

In general I'm wondering if we can bring more life or friendliness to the face of the avatar by making small design tweaks without making them too cartoony or weird.

**Comment by robertlong** [comment]
I think we can close this. There's ongoing avatar research that probably deserves a series of issues when it's ready to be implemented.
