### ISSUE TITLE
hover effect on objects not rendering correctly

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#1107]
![4fa2b113efddc6b89645da0d26cca4c2](https://user-images.githubusercontent.com/1821537/55036644-80909500-4fd8-11e9-86ee-b1fb1fb32a45.gif)

**Comment by gfodor** [comment]
the regression was introduced when we started scaling objects up from 0.001 in the animation, apparently the initial scale of the object affects the shaders behavior: if we start at 0.1 for example, it ends up shading a slice of the duck. (if you look in the image, a small slice is highlighted on the duck's neck at 0.001)

**Comment by gfodor** [comment]
Fixed via #1113
