### ISSUE TITLE
PDF uploads busted

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1119]
![image](https://user-images.githubusercontent.com/4072106/55098592-4926f480-507b-11e9-9ea3-0383c433f4ad.png)

```
 TypeError:  is not a valid URL. media-utils.js:144:20
```

and 

```
 Error loading image https://uploads-prod.reticulum.io/files/58d52436-5c5f-4a6b-bbb1-c3ca9e819029.pdf?token=e97bb4f3f856e41c0bb205b89849318a 'https://uploads-prod.reticulum.io/files/58d52436-5c5f-4a6b-bbb1-c3ca9e819029.pdf?token=e97bb4f3f856e41c0bb205b89849318a' could not be fetched (Error code: undefined; Response: undefined) console.js:35
    e console.js:35
    update media-views.js:745
```

**Comment by johnshaughnessy** [comment]
I suspect the page count being far to the right was caused when https://github.com/mozilla/hubs/pull/1035 was merged when it should not have been. @InfiniteLee was looking into this but had not yet figured out the fix.

I don't know why pdf uploads are broken in general.

**Comment by gfodor** [comment]
confirmed uploading is working but i believe its just failing to use the farspark pagination service

**Comment by johnshaughnessy** [comment]
Nevermind about #1035 having anything to do with it -- I was mistaken in thinking that shouldn't be merged!

**Comment by gfodor** [comment]
https://github.com/mozilla/reticulum/pull/135

**Comment by misslivirose** [comment]
This seems fixed now though I did have trouble parsing through if the linked reticulum fix was indeed rolled back - please re-open if I'm wrong about the fix being in!
