### ISSUE TITLE
Physics: removing objects sometimes causes exception in WASM

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1123]
- Spawn a duck
- Pin it
- Refresh
- Unpin duck
- Remove duck

I get error:

![image](https://user-images.githubusercontent.com/220020/55131674-dcdcdd00-50dc-11e9-8a93-668795a31658.png)

And console log gets spammed because pin button is leaked i think.

**Comment by InfiniteLee** [comment]
I've got a fix for this. Basically there's just a bug where a shape tries to remove itself from a body that already was deleted.

**Comment by InfiniteLee** [comment]
fixed with #1131
