### ISSUE TITLE
Can't type into lobby chat box

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1127]
The closest you can get to typing into the chat box is by pressing "/" to highlight the chatbox and add "/", but everything else is blocked.
![image](https://user-images.githubusercontent.com/4072106/55185874-8316fa00-5152-11e9-986c-916bd3b3acac.png)

**Comment by gfodor** [comment]
this was due to the visual design not making it more clear this is disabled. fixed on master.
