### ISSUE TITLE
Pasting/cloning PDFs cause visual bugs

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#1128]
![d43459e91388ff9e8e0631ee5e1b40e2](https://user-images.githubusercontent.com/1821537/55196538-edd52f00-516c-11e9-86a6-831b514f896b.png)

This screenshot shows the same PDF pasted into hubs 4 times, from left to right. The first time pasted, the page count is offset on the x axis incorrectly. On the second load, the offset is correct, but a duplicate set of non-functional page buttons (with the wrong y offset) appears. Each subsequent paste causes the x-offset of the page count to alternate from being in the correct spot to the wrong spot again, but with the non-functional duplicate page buttons visible.

**Comment by misslivirose** [comment]
I believe this was addressed in #1151 as I'm no longer seeing this behavior but if I'm incorrect there please re-open!
