### ISSUE TITLE
HUD UI buttons could be center-aligned vertically

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1132]
**Details**
The context menu button on the HUD after entering a room is aligned to the top of the containing element, rather than aligning at the center. Illustrated in the screenshot below. This does not apply to the 'Invite' button that is present in place of the HUD while in the lobby.

Priority: Low
Severity: Low
Fix Estimate: Small

**System Information:**
Device: Samsung Galaxy S9+
Browser: Firefox, Chrome (Mobile)
VR: No
Repro's on Desktop: Yes

![image](https://user-images.githubusercontent.com/4313320/55201574-d56f0f80-5180-11e9-903c-72a4df02745d.png)

**Comment by misslivirose** [comment]
Changing title to suggestion instead of bug because this could be a matter of opinion. =) I'd suggest the Suggestion tag!

**Comment by lordbron** [comment]
@misslivirose The linked pulled request has some screenshots if you want to check them out. 😄
