### ISSUE TITLE
New avatars disappear instead of going transparent when you bump into them

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1139]

**Comment by gfodor** [comment]
i haven't seen this in smoke tests - repro?

**Comment by misslivirose** [comment]
I saw this in today's meetup, but it doesn't repro in the default avatars, only the ones that have custom skins.

**Comment by misslivirose** [comment]
I'm going to close this issue since this is now the de facto behavior for avatars, but keep the greater issue about personal space bubble mechanics (#328) open
