### ISSUE TITLE
Can't dismiss muted textbox

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1140]
No way to dismiss the Muted textbox (Desktop, non-VR). By Design? I have Hubs in a quarter view of my screen so it takes up more screen real estate than desired. Suggest making this able to be dismissed and also using color cues to indicate muted state

![image](https://user-images.githubusercontent.com/4072106/55256806-4105bb00-521b-11e9-8bec-3174ee0d6a81.png)

**Comment by gfodor** [comment]
it may make sense to only show this tip on desktop, which would potentially just solve this problem given the extra real estate. the main motivation for adding it was to ensure people catch it when they accidentally press M

**Comment by netpro2k** [comment]
I would 1. make the X on the muted icon red, and 2. make the hotkey ctrl+m, then I think making this tip dismissable would feel better

**Comment by misslivirose** [comment]
I like the idea of making the hotkey ctrl + m instead of m as well and had the same thought about the x being red.

**Comment by misslivirose** [comment]
This blocks the ability to see all the screen share buttons too - the center one is blocked by this message

**Comment by misslivirose** [comment]
Changing this to a bug based on feedback that new users who enter a room with their microphone muted (which can be toggled from the lobby) do not know that they can share their room or invite people. Since we want to get people co-present, this breaks an essential flow.

**Comment by misslivirose** [comment]
Bumping up to P1 - copied from 2249: 

> 
> A number of members of the community have mentioned the pop up warning them they are muted obscures their view of the room and they wish to close it.
> 
> Most recently it was mentioned by a user at the a11y meetup who mentioned that this popup obscured the view of the captions at the top of the screen.

**Comment by gfodor** [comment]
I don’t think it’s a good idea to make it permanently removable, because
the reason it’s so in-your-face is due to the prevalence of people speaking
when muted. A intermediate term solution may be an X that is session-local.

The long term solution i think is a speech detection algorithm that
notifies you when you are speaking when muted, which would let us reduce
the reliance upon a persistent tip.

**Comment by misslivirose** [comment]
Doesn't it already detect when you're speaking? The audio level still shows even when you have the microphone muted. I'd be fine with it re-appearing then.

**Comment by gfodor** [comment]
Right now the highlight is modulated based upon voice level - to actually
create a tip that shows when you are speaking would likely have to do
speech detection (neural net, etc) to reduce false positives

**Comment by gfodor** [comment]
A session-local dismissal is easy and probably solves the biggest pain
point so seems important to get that in first if others agree tho

**Comment by misslivirose** [comment]
Could we estimate based over average threshold over time? e.g. if your volume average is over a specific threshold for a sustained time, trigger the session local dismissal.

Also, I'd be quite happy to have a preference to just turn it off permanently.

**Comment by gfodor** [comment]
We haven’t worked the problem too hard but my assumption right now is any amplitude thresholding is going to result in a lot of mis-detections.

**Comment by misslivirose** [comment]
Closing as the new UI does not rely on this message anymore.
