### ISSUE TITLE
Feature: Youtube API search

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1142]
Proposal: Add a new YouTube tab and have it be the leftmost tab, and move Video search to the right

**Comment by misslivirose** [comment]
Implemented in #1167 and now live. Thanks Greg, great add!

**Comment by gfodor** [comment]
thanks for re-opening. we are blowing through API quota in about an hour across 200 or so requests. TBD what is going on, likely we're doing something wrong in the way we're querying the API resulting in excessive usage costs.

**Comment by misslivirose** [comment]
@gfodor from my observation, the hold on the API featured work seems to be keeping this up - good to resolve this again?

**Comment by gfodor** [comment]
no, unfortunately the quotas are still being blown through, so there's something not adding up. i can dig in further today. either people are using the youtube API more than we expect, or something is querying it improperly.
