### ISSUE TITLE
Opening Developer Console toggles audio stream from videos

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1145]
**Repro Steps**
1. Create a room and enter
2.  Add a video from the video search (I tested with K/DA's Popstars) 
3. Observe that you can hear the audio playing
4. Hit F12 to open the developer console

Expected: The audio is not impacted
Actual: When the console is opened, it appears to toggle the audio stream but the video keeps playing and the volume level isn't changed. When the console is closed, the audio does not toggle again, but re-opening the console a second time turns the audio stream back on. 

**System Information**
Desktop Windows 10 (Not in VR)
Firefox Nightly (68.0a1), repros on Firefox Stable (66.02)

**Comment by brianpeiris** [comment]
This probably needs to be reported against Firefox devtools. It can be reproduced with a basic webaudio API sample: https://webaudioapi.com/samples/visualizer/

**Comment by brianpeiris** [comment]
Reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1540343

**Comment by misslivirose** [comment]
Closing as issue is tracked in the underlying API sample. Thank you for reporting Brian!
