### ISSUE TITLE
Windows Mixed Reality bindings are incorrect

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#1173]
We seem to be using Vive bindings on WMR devices, it feels very wrong since movement occurs when you put your finger down on the on touchpads. It should be using the thumbsticks. Pause mode also seems to be unbound.

**Comment by johnshaughnessy** [comment]
First thing to check is whether the windows mixed reality controllers still match 
```
e.gamepad.id.startsWith("Spatial Controller")
```
in https://github.com/mozilla/hubs/blob/master/src/systems/userinput/userinput.js#L292

**Comment by brianpeiris** [comment]
Not sure what was wrong when I first filed this issue, or whether someone else happened to fix it, but I just tested WMR and it seems to work.
