### ISSUE TITLE
Users shouldn't be able to draw in the lobby

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1177]
If you hold 'P' to create a pen while in the lobby, you can draw lines that appear to come from no where, as you don't have an avatar. 

Reproed in: Desktop mode, Firefox Nightly, Windows 10

![image](https://user-images.githubusercontent.com/4313320/55518350-89ace200-5628-11e9-8c1e-5626fa005693.png)

**Comment by johnshaughnessy** [comment]
Fixed in https://github.com/mozilla/hubs/pull/1204
