### ISSUE TITLE
Pen can stop drawing with a specific sequence of steps

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1186]
Noticed in a smoke test that if you do this sequence of steps, the pen stops drawing. The proximate cause is `currentDrawing` is non-truthy in `pen.js` during `startDraw`, but my debugger crashed during my test run and didn't dig further. I did confirm this is not connected to https://github.com/mozilla/hubs/pull/1152 by going back before that PR and seeing the same behavior.

Specific steps (on desktop):

- Go into a room
- Press P to activate pen
- Draw a stroke and release
- Draw a second stroke and release
- Type Ctrl-Z to undo second stroke
- Right click to drop + destroy pen
- Press P to active a new pen
- Press Shift-Q to change color
- New pen will not draw

Skip any of these steps and it works :)

**Comment by johnshaughnessy** [comment]
Fixed in https://github.com/mozilla/hubs/pull/1194
