### ISSUE TITLE
Camera icon in in-world hud stays highlighted

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1205]
Repro (on oculus Go. Haven't tried other VR devices yet) : 
  Click camera icon
  Dismiss camera
  Camera icon still has blue highlight

**Comment by misslivirose** [comment]
Repro-ed on Quest, still happening. Definitely a lower priority bug (I'd call this a P2) but worth noting that it's still around!

**Comment by SparshKat** [comment]
Is there any way i can test the codes for VR after running a react script?Because i would love to contribute to this issue :) Thanks @johnshaughnessy

**Comment by lordbron** [comment]
Opened PR #2602 for this bug. Hopefully I did it correctly. 😬 This is my first open source code contribution evah. w00t!

**Comment by lordbron** [comment]
One other visual discrepancy for iconButton is that we do a blue highlight on hover inside in-world-hud, but we don't do that when in a browser. Is this intentional?
