### ISSUE TITLE
Deleting an object that is mid-spawning resulted in audio playing on loop

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1208]
**Repro Steps:**
1. Start adding a 3D model from Sketchfab (I reproduced this with what was likely a high-poly model) 
2. While the object is in it's 'adding' state, delete the object through the overlay menu

The audio was repeating for me (and I believe that @gfodor also heard it on a loop) until refreshing the page. 

FF Nightly on Win 10

**Comment by johnshaughnessy** [comment]
Fixed in https://github.com/mozilla/hubs/pull/1209
