### ISSUE TITLE
[UX] You can't invite someone to a room when you're streaming your webcam

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1223]
The dialog box that indicates that you are sharing your screen / camera feed covers the invite button, making it not possible to click the invite link to get a code. 

It's not totally blocking, since the workaround is to pause the stream or just paste them the main URL, but it does feel off. Maybe like the microphone mute dialog, the notification that you're streaming should be able to be dismissed and you could have a different indicator on the HUD (a dot, perhaps?)

**Comment by gfodor** [comment]
this one is tricky. pushing the invite button below will work on larger screens, but we definitely can't hide the tip for streaming (as per privacy review -- that needs to be fully visible at all times video is active)

**Comment by misslivirose** [comment]
Given the privacy implications and relatively easy workaround, I'm going to call this one a "won't do" for now - we can revisit in the future
