### ISSUE TITLE
Custom avatar texture flow can get in broken state with certain Discord bot scenarios

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1228]
@j-conrad and I have been hitting this issue because both of us have Hubs accounts that we sign in with that aren't the same as our Discord identities. I think the root cause is generally known, but filing a bug so I can keep track of the outcome. 

- Sign in with a Hubs account that uses a@email.com
- Change your avatar to one with a custom texture
- Join a room that requires authenticating with Discord and sign in with Discord email (b@email.com)
- Attempt to change the avatar texture

Instead of working or giving an error, it hangs on an indefinite loading for the texture and you have to reload or switch to the default avatar selector. Having a message surfaced to the user would help alleviate the frustration of forgetting which account you originally uploaded an avatar with and ending up with having to change it or reload everything back in.

**Comment by brianpeiris** [comment]
This was fixed in #1331. Your avatar is now when you sign in with discord.
