### ISSUE TITLE
[Suggestion] Indicate that codes have a 72 hour lifetime

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1229]
![image](https://user-images.githubusercontent.com/4313320/56174575-f371a800-5fa7-11e9-8a5e-3b112bb06e93.png)
Based on feedback from users, people do not realize that their 6 digit invite code expires after 24 hours. Suggest that we add a subtitle here that says something like 'Codes are regenerated every 24 hours for security purposes'. 

Alternatively, a larger feature set to consider (may not be feasible for security reasons) is to allow the user to set expiration time (perhaps a la Firefox Send, which puts expiration time behind an account sign in)

**Comment by gfodor** [comment]
I'm going to bump this to 72 hours fyi, before doing a redesign

**Comment by SparshKat** [comment]
i'd like to contribute to this. As far as the expiration date is considered, 72 hours should be the default time limit for the expiration of the link. And how do you want me to put this information up that box, as the easiest way is to write down the information or a question mark icon stating the info.

**Comment by gfodor** [comment]
There was a rough sketch made a few months ago of potential changes here.

- Re-order the permalink to the top
- Alter bits of copy:
  - top copy says "Share room link:"
  - copy above code says: "Or use expiring hub.link code:"
  - below code says in smaller font "new code every 72 hours"

If you put a PR together making these adjustments, happy to review!

**Comment by brianpeiris** [comment]
Here's a mock up with the current UI and gfodor's copy suggestions. I think this ordering makes sense.

![image](https://user-images.githubusercontent.com/79419/71745792-0bcc7000-2e20-11ea-821e-f9f1aa29f729.png)

**Comment by gfodor** [comment]
not to derail you into design-land, but i think we also need to say 'new code every 72 hours' somewhere. maybe in small typeface below "Or use expiring hub.link code"

**Comment by brianpeiris** [comment]
Oh, right. Forgot that bit.

**Comment by brianpeiris** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/79419/71746809-ceb5ad00-2e22-11ea-9504-034ee529001f.png)

The code for this dialog is in invite-dialog.js:
https://github.com/mozilla/hubs/blob/master/src/react-components/invite-dialog.js

And the strings are in translations.data.json:
https://github.com/mozilla/hubs/blob/master/src/assets/translations.data.json#L234-L241

**Comment by gfodor** [comment]
Seems good -- another variant that might break up nicer would be to put the
new code bit under the expiring code: line, but nbd. under this version i'd
probably add some padding between each 'section' since the information
hierarchy is a bit weird between the last two sections.

**Comment by SparshKat** [comment]
Alright Thanks i'll try to fix this one and will issue the PR asap!

**Comment by SparshKat** [comment]
PR #2007 to adhere to the above specifications.

**Comment by SparshKat** [comment]
@gfodor @brianpeiris  Hi #2007 awaits a PR review !  :)
