### ISSUE TITLE
PDF Pager is far below PDF files, especially if the PDF is scaled up

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1233]
Makes it nearly impossible if not totally impossible to change the pages effectively because the pager can end up occluded by other geometry and out of the line of sight

**Comment by gfodor** [comment]
closed via -- https://github.com/mozilla/hubs/commit/120bb729649a8d351503f0003c35d94f29d2822b

this should really look at the half extents directly, but this is reverting things to how they worked before.
