### ISSUE TITLE
"Use scene" should either not show up or tell the user they need to be the room owner

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1238]
People think the "use scene" button is broken because they click it and nothing happens. We need the button to either not show up or we need to tell them that they can't change it unless they're the owner. We could do the latter using the same mechanism by which we show the "pinning this object will send it to discord" message when you hover on the pin button.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/1417
