### ISSUE TITLE
Support HTC Vive Focus Controller

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#1245]
In Firefox Reality, the `Gamepad#id` for the Go and Focus have been changed from `"Gear VR Controller"` to `"Oculus Go Controller"` and `"HTC Vive Focus Controller"`, respectively.

See https://github.com/MozillaReality/FirefoxReality/pull/981/files#diff-d6e5cad7b6d966752af1293c96fc7155R302 and for 6DoF: https://github.com/MozillaReality/FirefoxReality/pull/1004/files

It looks like a new gamepad interface and mappings need to be created and this line changed: https://github.com/mozilla/hubs/blob/bfc3d2b3/src/systems/userinput/userinput.js#L295

Thanks!

**Comment by johnshaughnessy** [comment]
Got it. Thanks @cvan!
