### ISSUE TITLE
Shortlinks for invite codes do not show 'Open Room' when pasted into the spaces

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1246]
![image](https://user-images.githubusercontent.com/4313320/60830124-6041ac00-a16b-11e9-9569-e694f6aab95a.png)

Instead, the short link gives a blank gray-blue rectangle and shows 'Open Link' when 'Open Room' is expected

**Comment by misslivirose** [comment]
Update: in trying this again, shortlinks for invite codes now do not resolve at all. 

Repro: 
1. Open the 'Share' button
2. Paste the hub.link url into a room

Expected: the url resolves to a Hubs room and shows 'Open Room'
Actual: broken link image

![image](https://user-images.githubusercontent.com/4313320/62565323-68a90780-b83b-11e9-9049-a271f2228a11.png)

**Comment by johnshaughnessy** [comment]
I thought I had fixed this issue by changing regex that recognizes room links in the client, but there still seems to be a problem that if I post a room link without an `https://` prefix, the media won't resolve with a thumbnail for the room and instead it will be a broken image.
