### ISSUE TITLE
Nightclub scene broken

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#1251]
From https://github.com/MozillaReality/hubs-discord-bot/issues/27

> The nightclub scene I get when entering on discord does not have proper pathways set up.  I pass through walls and go under the raised areas.

**Comment by brianpeiris** [comment]
I think this is just the old known issue with Spoke scenes, where your avatar starts off on the default floor plane and workaround is to teleport onto the actual nav mesh.

**Comment by misslivirose** [comment]
The new nightclub scene seems to not have these issues, and I suspect that this is going to be a difficult one to try and reproduce without a link to the old version of the scene. We can re-open this if we hit it again, but I think it makes sense to close it for now.
