### ISSUE TITLE
Photos from the camera tool don't load for other people

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1254]
Could be related to https://github.com/mozilla/hubs/issues/1253
Repro:
Player 1 takes photo from camera
It never loads for player 2

**Comment by johnshaughnessy** [comment]
@misslivirose Reporting that we are still seeing this in the meetup

**Comment by misslivirose** [comment]
I don't want to overload this issue, but might be worth noting that this also happened with a camera stream and there were some issues with painted lines not going through in the same meetup
