### ISSUE TITLE
UX: Provide an affordance to unhide a user when they have been hidden

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1259]
The current flow for this requires leaving the room before the user shows up again. There should be some flow inside of Hubs that doesn't force a user to leave and return to unhide someone. I would imagine this being somewhere in the user list (perhaps as an icon when users are hidden that can be clicked to unhide them, sketch below - I don't know that the 'unhidden' state should be shown all the time for all users)

![image](https://user-images.githubusercontent.com/4313320/56512852-6ff31200-64e5-11e9-8343-4fa6ecd35aff.png)

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/1310

**Comment by misslivirose** [comment]
🎉
