### ISSUE TITLE
Images don't resolve in scene preview

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#1269]
Originally posted in Spoke by @misslivirose : https://github.com/MozillaReality/Spoke/issues/533

> If you have an image as a skybox, the scene preview screen (after publishing and viewing) is very vivid because you end up inside the 'loading' cube:

![56769031-e0f42d00-6764-11e9-93a3-51d7f5f3c5b5](https://user-images.githubusercontent.com/1753624/56828206-aeeed380-6815-11e9-9f70-d26327f03c18.png)

**Comment by misslivirose** [comment]
At some point this appears to have been fixed! Closing since I now see images resolving correctly
