### ISSUE TITLE
Media controls showing on videos with controls OFF

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#1276]
Posted in Spoke by @j-conrad https://github.com/MozillaReality/Spoke/issues/435

Seems to be somewhat intermittent-- Created a scene in Spoke that had multiple videos embedded in it. All of them had 'Controls' turned OFF. 
When I ran it in Hubs, the first few times, the videos appeared as expected. Someone else reported the videos had controls overlaid on them that wouldn't go away.
When I ran the room subsequently, I had the same problem-- controls overlaid the whole time. Refreshing the from the scene landing page seems to hit the bug 50% of the time (you can see the controls before you enter the room).

Space:  https://hubs.mozilla.com/scenes/xwi0JNm/vtrainride
![image](https://user-images.githubusercontent.com/31968496/52679133-eb828280-2ee8-11e9-9f7a-62114a93826f.png)

**Comment by misslivirose** [comment]
I tested this about 10 times and don't see this issue any more - I know that there was some work done to fix up controls on videos (#1871) going to close no-repro since this seems fixed now. We can reopen if it appears again.
