### ISSUE TITLE
[UX] Experiment with video controls distance 

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1284]
When videos scale up, it would make sense to have the controls for them also be usable at a greater distance (consider the use case of wanting to control volume on the video screen of a theater). Right now, you have to be very close to even large screens, which makes people have to cluster around the screen at an uncomfortable viewing distance.

**Comment by johnshaughnessy** [comment]
I increased the distance from which you can interact with menus (from 10 meters to 100 meters) here: https://github.com/mozilla/hubs/pull/1677
This will hopefully help with this issue. I did not make the distance vary with the size of the object, but if we continue to have problems (e.g. people are using scale very creatively and in the same room you sometimes want a 10 meter long raycaster or a 1000 meter long raycaster) then we should revisit this.

**Comment by misslivirose** [comment]
I'll resolve this one for now and we can re-open a new case if we think the distance is too far and want to make additional changes
