### ISSUE TITLE
Rooms fail to load due to CSP + WebXR errors in Chrome + Safari on macOS desktop

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#1285]
1. From Chrome on macOS, launch a Hubs room https://hubs.mozilla.com/uLxJbiW/beneficial-superb-park (or Create Room from the [homepage](https://hubs.mozilla.com/))
2. Notice the page is completely blank
3. Look at the Console errors:

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```
```
navigator.xr.requestDevice is not a function
```

## Chrome for macOS
- page fails to load (completely white)
- CSP errors + `navigator.xr.requestDevice is not a function` error in Console
![image](https://user-images.githubusercontent.com/203725/56994081-ef6e8a00-6b52-11e9-9e8b-75d94b2f6ed1.png)

## Safari for macOS
- page fails to load (stuck on loading screen instead of white screen like Chrome)
- can successfully enter VR
- CSP + other errors in Console
![image](https://user-images.githubusercontent.com/203725/56993949-9e5e9600-6b52-11e9-8ddb-811142ba396b.png)

## Oculus Browser
- page successfully loads
- can successfully enter VR
- CSP errors in Console
![image](https://user-images.githubusercontent.com/203725/56993912-8dae2000-6b52-11e9-8d8f-48a9eac267fb.png)
![image](https://user-images.githubusercontent.com/203725/56993915-90107a00-6b52-11e9-9d82-62f1a2addc95.png)

## Firefox Reality
(tested in both Multiprocessing [e10s] and default non-e10s)
- page successfully loads
- can successfully enter VR
- CSP errors in Console

## Firefox for macOS
- page successfully loads
- can successfully enter VR
- CSP errors in Console
![image](https://user-images.githubusercontent.com/203725/56993926-94d52e00-6b52-11e9-881f-92f167340a8e.png)
![image](https://user-images.githubusercontent.com/203725/56993933-9999e200-6b52-11e9-9896-6d70b99845a3.png)

**Comment by gfodor** [comment]
Thanks for reporting @cvan! should be fixed, was a CSP regression

**Comment by cvan** [comment]
verified this works now. thanks for the quick fix :+1:
