### ISSUE TITLE
UX: Add text + informational to lobby to indicate that you are not in the room yet

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1291]
Challenge: Feedback from users is that people do not always realize they are in the lobby instead of the room itself when they first join in to use Hubs. 

Suggestion: When the user is not the owner of a room, use the screen real estate for a message that explains to the user they are in the lobby. I'm not attached to this specific copy but I think that we need to explicitly indicate to the user that there is another layer of experience.

![image](https://user-images.githubusercontent.com/4313320/57032782-04edbd80-6c00-11e9-8cb0-ed93d92a65e4.png)

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/1292

**Comment by gfodor** [comment]
Live now!
