### ISSUE TITLE
Toggling 'M' hot key in lobby shows/hides the 'Invite' button

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1298]
Nightly, Windows 10

Repro: In the lobby, toggle your mute status by hitting the 'M' key. I like that we surface the ability to mute, but shouldn't hide the UI - it's doing something it shouldn't here (re-using the element that shows the 'You are muted' box, perhaps?)

**Comment by brianpeiris** [comment]
I believe this behavior was actually intentional -- mainly because we are out of vertical space on mobile IIRC.
But it is a UX problem, especially since you can now mute yourself before entering a room and also be muted by moderators.
We should think of a redesign,

**Comment by brianpeiris** [comment]
I should say I think at least two users have reported running into this as well.

**Comment by gfodor** [comment]
Hotkey now disabled in lobby
