### ISSUE TITLE
More clearly surface ability to mute your microphone from the lobby before entering a room

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1299]
This was originally going to be a request to allow me to mute my microphone from within the lobby, but after giving this a try on desktop, I've realized you _can_ toggle mute from the lobby if you use the 'M' hot key. However, this surfaced a new bug (#1298). We should provide a visual affordance for people to use to mute themselves from the lobby (maybe by clicking on the mic icon? I'm not sure the best way to toggle this) as there are many scenarios where people might be in a noisy environment and not want to have an open mic right away.

**Comment by gfodor** [comment]
interesting -- i think the current behavior is just a bug/oversight. i am concerned about using the same mute mechanic in the lobby because it might cause users to think their mic is live otherwise. perhaps we could have an optional checkbox in the last screen to let the user start off muted?

**Comment by misslivirose** [comment]
That's a good point about not wanting to scare them into thinking the mic is hot. Maybe something like this? 

![image](https://user-images.githubusercontent.com/4313320/57118294-36a57800-6d17-11e9-8bb1-49490be0f06a.png)

**Comment by gfodor** [comment]
yeah I think that could work!

**Comment by misslivirose** [comment]
Only thing I'd also add is that we'd probably want the whole label to be a hit target so mobile users won't have a small one

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/1313
