### ISSUE TITLE
Stuck on "choose device" modal in development

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#1301]
<img width="1680" alt="Screen Shot 2019-05-03 at 1 12 00 PM" src="https://user-images.githubusercontent.com/1753624/57163225-6bf8a700-6da5-11e9-8625-0b43e8e21af2.png">

This only happens in development. Not on prod.

**Comment by misslivirose** [comment]
Are there any more details for this / still happening?

**Comment by robertlong** [comment]
I haven't seen this one in some time. I think we can close this.
