### ISSUE TITLE
Add 6DoF HTC Vive Focus Plus Controller support

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#1308]
Follow up to PR #1247, https://github.com/mozilla/hubs/pull/1247/files#diff-6cf67576333f77a249532a59f5a82461R295, which was for issue #1245.

See the [`Gamepad#id`](https://github.com/MozillaReality/FirefoxReality/pull/1162/files#diff-d6e5cad7b6d966752af1293c96fc7155R367) string change in PR MozillaReality/FirefoxReality#1162.

<hr>

Related issue: #1296 for Lenovo Mirage 6DoF controllers.

**Comment by misslivirose** [comment]
Appears to have been added in #1341
