### ISSUE TITLE
Spawning sometimes messes up and picks the origin

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#1311]
Seems like a possible race condition, but on all platforms, sometimes the user spawns at the origin instead of one of the spawnpoints. Also seems like a possible regression-- first noticed a week or so ago. (5/1)
There doesn't seem to be any difference when the scene has only one spawnpoint or has multiple spawnpoints.

**Comment by misslivirose** [comment]
Worth checking into logs if we see this happen again

**Comment by misslivirose** [comment]
Going to close this since I don't think we've gotten reports of this given the age of the bug, but we can re-open as needed.
