### ISSUE TITLE
Badges / UI is hoverable and makes sound effects when not visible

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#1314]
As I look around I'm hearing the hover sound effect and the cursor changes color.

![Screen Shot 2019-05-08 at 12 07 50 PM](https://user-images.githubusercontent.com/1753624/57401173-ec465000-7189-11e9-94a3-7e6af79444ee.png)

**Comment by gfodor** [comment]
sorry, which UI do you think the cursor is hitting here?

**Comment by robertlong** [comment]
It looks like it's the volume buttons
![Screen Shot 2019-05-08 at 3 03 00 PM](https://user-images.githubusercontent.com/1753624/57411436-6f73a000-71a2-11e9-9344-1ce7b218e0e9.png)
![Screen Shot 2019-05-08 at 3 03 15 PM](https://user-images.githubusercontent.com/1753624/57411437-700c3680-71a2-11e9-8427-d11dd369fd77.png)
