### ISSUE TITLE
Using an unresolvable avatar url in the lobby flow makes avatar invisible but does not block 

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1315]
I think that I've now got a repro case related to #1302 - if you try to change to a custom GLB avatar in the entry flow, you do not have a fallback avatar when the avatar fails, and you become invisible (and potentially not heard) by other people in the scene.

Repro steps (I'm seeing a 100% repro): 
1) Create or enter a room
2) While in the lobby, open the user list and hit the pencil to edit your avatar
3) In the 'custom URL' field, enter https://fake.glb
4) Observe that this is non blocking and you are able to enter the room without an avatar

**Comment by brianpeiris** [comment]
Yeah, you are definitely not heard by others -- we attach your audio output node to the avatar, so if you don't have an avatar, you don't output audio.

**Comment by misslivirose** [comment]
Saw this at a public event last week - someone tried to use a Sketchfab link as an avatar and was not able to resolve it themselves. Eventually it was resolved by having them connect in a private browser window, but this case is pretty bad because doing it on the first time user flow means that you get stuck in a state where no one can see or hear you and it's not clear to the user how to fix it.
