### ISSUE TITLE
Support for HTC Vive Focus Plus controllers

### ISSUE THREAD

**Issue by larsbergstrom** [mozilla/hubs#1322]
Few issues with the HTC Vive Focus Plus and Firefox Reality (1.1.4):
1) There's only one controller visible
2) No teleport-jump on the touchpad
3) During avatar customization, the page where you choose to use custom image templates does not scroll so you can not accept/save it

Otherwise, it's looking amazing! Permission prompts worked; voice/audio worked great, and the performance is amazing.

**Comment by cvan** [comment]
Thanks for filing! Originally reported in https://github.com/mozilla/hubs/issues/1308 Can you report the other issues in separate issues? And we can close this one?
