### ISSUE TITLE
Discord landing page: "Request Beta Invite" button not visible and cannot scroll

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#1326]
Load https://hubs.mozilla.com/discord on a not-so-large desktop or a phone.

Notice if there is not vertical space, the **Request Beta Invite** button does not show up, and the user cannot scroll:

![image](https://user-images.githubusercontent.com/203725/57652611-cb646d00-7584-11e9-9b20-23bad4738c9e.png)

It does show up if there is enough vertical space:

![image](https://user-images.githubusercontent.com/203725/57652748-17171680-7585-11e9-85ad-d4ab002c8aeb.png)

The CSS style [`body { overflow: hidden }`](https://github.com/mozilla/hubs/pull/1225/files#diff-6e4f11417854633204b26029a3c54fceR13) in [`src/assets/stylesheets/discord.scss`](https://github.com/mozilla/hubs/blob/afab14d/src/assets/stylesheets/discord.scss#L13) is what is preventing the user from being able to scroll.

**Comment by gfodor** [comment]
nice catch!

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/commit/042c64e1b55907bfbd47f8147131db39b5503482
