### ISSUE TITLE
No textures in scene on Firefox Reality for Vive Focus Plus

### ISSUE THREAD

**Issue by larsbergstrom** [mozilla/hubs#1338]
I just created a test scene and dropped in a model from sketchfab:
https://hubs.mozilla.com/scenes/JOICLCj

When opened in the desktop browser, it looks fine, but if I visit in Firefox Reality 1.2 on the HTC Vive Focus Plus the model displays all black. Maybe the same as #747?

**Comment by misslivirose** [comment]
I didn't see this reproduce on Quest with FxR, so it seems like it may be specific to the Vive Focus Plus if it is still reproducing. I tested with making a room from the scene: https://hubs.mozilla.com/QzuoZp7/flashy-reasonable-soiree

**Comment by misslivirose** [comment]
I'll test this when I'm back in the office now that we have a Vive Focus Plus here
