### ISSUE TITLE
Collision remains when choosing a new scene without entering first.

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#1342]
Repro steps:

1. go to hubs.mozilla.com
2. Choose `Create A Room`
3. DON'T ENTER, but instead, `Choose A Scene`
4. Enter the room
5. turn on `/debug`

Result: The collision from the original scene is still present

![image](https://user-images.githubusercontent.com/31968496/57816639-f390cf00-7730-11e9-8e53-17ed1f40eecf.png)

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/1343
