### ISSUE TITLE
One of my older avatars does not appear

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1349]
![image](https://user-images.githubusercontent.com/4313320/57907744-29b67780-7833-11e9-8fdf-0fd08b7f3562.png)

There isn't any error message associated with this, and it lets me edit the avatar but the preview never loads and if I enter the room with it, I don't have a body.

**Comment by misslivirose** [comment]
Avatar: https://hubs.mozilla.com/api/v1/avatars/VDf5ti8

**Comment by brianpeiris** [comment]
I think I wasn't able to repro this, but IIRC, this avatar had very large textures. This may have also been fixed by #1348.

**Comment by misslivirose** [comment]
Resolving and will re-open with more specifics if it happens again
