### ISSUE TITLE
Cannon.js dependency gets re-added anytime package-lock.json is updated

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#1357]
Currently, `aframe-physics-system` lists `cannon.js` as a dependency, although it is not required as `ammo.js` can be used instead. To avoid loading `cannon.js` unnecessarily, it was manually removed from `package-lock.json`. This seems to work fine until any operation like `npm install` or `npm update` is run, which seems to have a side effect of re-adding `cannon.js` to `package-lock.json`, however it does not re-add it correctly and and hubs won't run until `cannon.js` is removed from `package-lock.json` again. 

The two solutions are to either properly re-add `cannon.js` back to the `package-lock.json` or fix `aframe-physics-system` to no longer require it.

**Comment by matthewbcool** [comment]
closing because I believe we are just using ammo now and cannon is removed.
