### ISSUE TITLE
Pen erase is difficult for users to discover

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1369]
I've seen this in several meetups - people draw with the pen but don't understand how to erase things. We may want to reconsider the mechanics for draw/erase or consider ways we can highlight an erase functionality (as opposed to just an undo)

**Comment by chartgerink** [comment]
May I ask where the erase function can be found? I tried removing someone else's pen stroke but was unable to find a way to do this. Help would be much appreciated :)

**Comment by gfodor** [comment]
Right now we don't have an eraser tool or way to erase other people's
strokes. However, you can undo your own strokes, and if a person leaves the
room, their drawings are removed. To undo your strokes on desktop is
ctrl-z, in VR there is a button on the controller you are holding the pen
with that is used for undo (I'm not sure which device you are using)

**Comment by chartgerink** [comment]
Ah cool, I didn't realize the pen strokes are deleted when a user left the room :smile: I was able to remove my own with CTRL+Z, and wondered what to do in case someone came in and graffiti'd the place. Kicking them is enough then :+1:

**Comment by misslivirose** [comment]
You can now also disable the pen from being used by people in the room with the Room Settings dialog and setting object permissions! (as of PR #1517) 

That said, it's still difficult to discover and might be worth revisiting when we pick up pen tool improvements.

**Comment by misslivirose** [comment]
#1730 implements an erase menu

**Comment by arinbasu** [comment]
Pen drawing eraser using Cmd-Z/Ctrl-z do not work with drawings that are already completed and then the pen "de-activated" from the menu. Is there some way where existing drawings can be removed perhaps to make space for new drawings?
