### ISSUE TITLE
Suggestion: Add some kind of audio affordance in the user list to indicate volume

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1381]
During a meeting yesterday, someone mentioned this suggestion as one that could aid moderators of a space in finding and targeting members with loud open mics.

**Comment by gfodor** [comment]
if we were going to work on this issue, maybe we should start with a (sensitive) visual indicator in the avatar menus or nametags, since that'd allow in-VR users to determine where the noise is coming from as well

**Comment by misslivirose** [comment]
I can see where that can be helpful, though I'd add that in cases with a larger number of people in a relatively small space, there's already a fair amount of name tag overlap and adding more information in that space might not be ideal.

**Comment by misslivirose** [comment]
Bumping this, especially with the new humanoid avatars

**Comment by misslivirose** [comment]
(May want to consider this for name tags as well)

**Comment by gfodor** [comment]
One challenge with this (which is solvable) is that this will result in a
lot of react-state updates unless we do this 'out-of-band' - similar to
what we did for the HUD mic indicator.

**Comment by emclaren** [comment]
This is something I've wanted during busier meetups. 

Also related to issue #2504 - it would be nice to know who is/isn't muted in the dropdown user list. 

Adding mute all (as discussed in #1853 ) could be very helpful, as well, for larger events because if you want the volume indicator to figure out who to mute during an event, having the ability to make everyone in the audience quiet at once would reduce this challenge.

**Comment by misslivirose** [comment]
I did a mockup for this feature in Figma. The gist of it: 
* This list doesn't change if you are not a moderator. The new UI would only be available to room owners and moderators. 
* It adds a button to mute all of the people in the room (the downside of this is that in the case where there was a speaker, they would probably have to unmute themselves unless we restrict "mute all" to only apply to non-moderators) 
* Clicking on the audio indicator would also allow a moderator to mute someone (there is no way to unmute someone, for privacy purposes this is an action they only take themselves) 

![image](https://user-images.githubusercontent.com/4313320/83303780-87a1cd00-a1b2-11ea-91d3-bbca4c6bbcad.png)

**Comment by misslivirose** [comment]
The user list part of this was addressed in #2563 - I'm going to resolve this, because we also have #2533 to track the individual indicators that are avatar-driven
