### ISSUE TITLE
Using chat on mobile android causes repeated "Switched to Full Screen" notice

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1382]
Android (Samsung S9+) on Firefox Mobile 67.0

When I enter a room on my phone and use chat, the keyboard opening / closing repeatedly toggles the site going into full screen mode. It's not blocking behavior, but it's not a clean experience and discourages use of chat.

**Comment by brianpeiris** [comment]
This was done in #925 due to this issue in Firefox for Android:

> Fixes a bunch of full screen transition issues. The main thing that I've encountered is that Firefox Android, when dealing with focused input fields, can in certain cases (like when we auto focus I think, or when the user uses the copy/paste functionality) exit full screen but no longer be able to re-enter it even if we request it. The result is that we need to exit full screen explicitly when interacting with text boxes, and re-enter it when that interaction has concluded.

Did we ever report this in bugzilla?

**Comment by gfodor** [comment]
I also think this is unfortunately always necessary for the case of the chat box specifically, since if we do not exit full screen when focusing that text box, the mobile keyboard will end up covering it up. However if the Firefox issue is fixed then we could revisit the old behavior where the chatbox would reposition itself to the top of the screen when focused on mobile to mitigate that issue.

**Comment by brianpeiris** [comment]
Added a minimal test case and notes to this existing bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1517172

**Comment by gfodor** [comment]
This also breaks PWA keyboards since there is no way to exit full screen.

**Comment by brianpeiris** [comment]
Ah, good call. It seems you could work around it by entering and exiting "fullscreen" in the PWA, but that's pretty hacky. I made the test case into a PWA to demonstrate: https://brianpeiris.github.io/fullscreen-bug/fullscreen-bug.html
I'll add that to the bugzilla.

**Comment by misslivirose** [comment]
Resolving this external - Bugzilla was updated a couple of months ago with additional information about the issue extending beyond Hubs.
