### ISSUE TITLE
Cannot click and drag camera over pinned objects

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1389]
If an object is pinned, if you click and drag across it the camera should turn.

**Comment by misslivirose** [comment]
This is particularly painful in rooms where the floor was added in Hubs, rather than as part of the scene itself. We see this frequently in the ['Float in Space' scene](https://hubs.mozilla.com/scenes/xEk0qe9/float-in-space) where people retroactively put in a floor to stand on.
