### ISSUE TITLE
Pressing ESC on link page breaks cancel button <nt>

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1391]

**Comment by brianpeiris** [comment]
Can you elaborate on this? Not entirely sure what the steps to repro are.

**Comment by gfodor** [comment]
Sorry for the poor description. If you click the "Use Standalone VR" button
on the landing page to get an alpha code, and hit ESC, you'll no longer be
able to close the panel with "Cancel", it will just hang with the spinner.
Probably history related.

**Comment by misslivirose** [comment]
Confirmed repro today on Nightly w/ Windows.
