### ISSUE TITLE
Emojis have strange transparency behaviors when placed in front of other objects

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1394]
![image](https://user-images.githubusercontent.com/4313320/58826635-f7a86200-85f5-11e9-8aee-f32cca19b0fa.png)

If you look at the left side of the emoji, you'll notice that the transparency around the emoji is also drawing over the image and text that is behind the emoji, displaying the mesh behind all three objects.

**Comment by johnshaughnessy** [comment]
Same goes the slice9 components we use. I noticed this when working on the sprite rendering but don't know enough about webgl transparency (yet!) to know what the right solution is.

**Comment by netpro2k** [comment]
When batched images now don't use blending anymore, they just use a cutout discard, so this should no longer be an issue most of the time (the exception being on non-webgl2 compatible browsers, namely iOS safari)

**Comment by misslivirose** [comment]
Can confirm that this is now no longer happening, so I will close this bug and I think it's okay to note it as a known issue in Safari specifically.
