### ISSUE TITLE
Spawn points in Firefox doesn't work

### ISSUE THREAD

**Issue by smeybi** [mozilla/hubs#1413]
Hi,
Spawn points created in spoke do not work in Firefox 67. In Chrome they works.

I've tested with 2 Computer, the same issue. You spawn in FF somewhere in the middle.
Here an example, you should spawn at one of the two spawn points at the side.
https://hubs.mozilla.com/K4GiBqf/spry-alarmed-nation

**Comment by gfodor** [comment]
interesting, can confirm!

**Comment by gfodor** [comment]
should be fixed! let us know if you still see this issue.
