### ISSUE TITLE
If hud images fail to load, they show up as black squares.

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1423]
I connected to hubs on my quest in the oculus browser, but some of the images that make up the player-hud failed to load, and showed up as black squares. I opened the networked tab after connecting with chrome dev tools, made sure "Disable cache" was NOT checked, and refreshed the page. Refreshing the page did not fix the issue - the same images failed to load until I checked "disable cache" and refreshed, which makes me think maybe a failed response was cached. 

One part of a solution will be to implement retry logic on image downloading. If a failed response is cached somehow, I don't know what a solution to that looks like. (Where is it being cached? How do we invalidate it?)

**Comment by matthewbcool** [comment]
unable to repro on oculus browser.
