### ISSUE TITLE
Waffle.io link in README directs to a shut down website

### ISSUE THREAD

**Issue by j-dover** [mozilla/hubs#1441]
Hi all,
I am a newcomer interested in learning more about hubs. 

As I was reading the README, I noticed that the [Waffle.io - Columns and their card count link](https://waffle.io/mozilla/socialmr) directs to a "Hmm. We’re having trouble finding that site." error on Firefox 67.01.7088. I have found similar errors on Google Chrome  and Microsoft Edge. The operating system I used was Windows 10.

According to [this](https://help.waffle.io/waffle-shutdown/waffle-shutdown-tldr), Waffle.io has been shut down.

**Comment by brianpeiris** [comment]
Thanks for the report. We stopped using Waffle a while ago. I'll remove the link.
