### ISSUE TITLE
Observer mode

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#145]
Brainstormed some points on observer mode. 

Observer mode is a highly useful metaphor. It will help solve the following use cases:

- I would like to see what is going on inside of a room before I enter, because I want to get a sense of the vibe of the room.

- I would like to be able to exit the room temporarily.

- I would like to exit the room and take actions on individuals in the room or objects in the room from an externalized viewpoint.

- I would like to act as an "audience member" who exclusively views what is going on in the room, but I have no means of entering.

- I am on a phone with AR support and would like to be able to place the room in the physical world to look down into it.

There are more, but this is the gist. The main metaphor that likely needs to be introduced is the idea that when you are using the application, you are either in "avatar mode" or "observer mode." When you are in observer mode, your controls are focused on manipulating the world as a whole. (Zooming, dragging, etc, moves the *world*, not your avatar.) Whereas in avatar mode, you are embodied inside as a member of the world, and controls allow you to locomote, etc.

Potential sequence of development:

- Introduce "observer mode" as an interstitial step before entering a room, after you put on your headset. This will all you to "preview" the room before you enter. You will be blocked from entering if the room is full, but you can still observe. (In observer mode, you will not be sending any data to the room, just subscribing to the streams of room participants.)

- Add the ability to enter and exit observer mode at your will while using the app.

- Introduce additional UI/controls while in observer mode (such as settings, being able to see and act on people in the room, etc.)

- Add ability for room creators to share "observer mode only" links.

- Multiplayer observer mode (parties?) so you can spend time with others in observer mode and pop in and out of the room, watch VR performances/podcasts together, etc.

**Comment by robertlong** [comment]
I think we've covered a good chunk of this in the most recent UI pass. We should break any remaining tasks into smaller issues.
