### ISSUE TITLE
GLTF URL for Custom Scene not working

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#1452]
From a new room I select **Choose a Scene** > **Custom Scene** and I enter a URL to a GLB file such as http://data.avncloud.com/dev/stonehenge.glb then press **Change Scene**.

The room refreshes but loads the existing scene (River in my case).

I would expect the scene to change to the model in the GLB file.

**Comment by brianpeiris** [comment]
Thanks for the report. I've confirmed this breaks with the tutorial scene GLB exported from Spoke as well.

FYI, If you're looking to work around this for now, you could also create a scene with your GLB using Spoke instead of using the Custom Scene dialog.

**Comment by anselm** [comment]
I have the same issue with this example : https://bit.ly/2RJ6UKJ or this example too : https://anselm-servermap-2.glitch.me/?lat=51&lon=-107&lod=13&str=1&pad=0&rad=10000&elev=0&binary=false&cors=.gltf  . There may be a related issue that Spoke ignores anything past the '&' .

**Comment by anselm** [comment]
A funny note by the way - I tried http://data.avncloud.com/dev/stonehenge.glb and it did load - it just did not UNLOAD the default river scene, or it seemed to flush the river scene and then load StoneHenge and then also load the river scene again on top as well.

**Comment by gfodor** [comment]
this seems fixed now i think
