### ISSUE TITLE
[UX Enhancement] Feedback Survey

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1463]
As a Hubs contributor, I would like to receive even better information from my users. For example, WHY are you using hubs today and did you find everything you needed? If not, WHAT was missing?

**Comment by misslivirose** [comment]
We are definitely welcome to suggestions on collecting feedback! Our current feedback form is quite minimal, and we don't automatically collect additional information. We need to avoid collecting personally identifying information, but I agree there are better questions we could include in the survey to get more information about how people are using Hubs and their overall experience! 

For privacy reasons, the form access itself is restricted, but as next steps we can come to a consensus on the changes to make on this thread, and I will be the one on-point to integrate the final updates into the live feedback survey.

**Comment by gfodor** [comment]
Proposed new survey q's:

1. How would you feel if you could no longer use Hubs?
A) Very disappointed 
B) Somewhat disappointed 
C) Not disappointed

2. What type of people do you think would most benefit from Hubs?

3. What is the main benefit you receive from Hubs?

4. How can we improve Hubs for you?

(shamelessly stolen from https://firstround.com/review/how-superhuman-built-an-engine-to-find-product-market-fit/)

**Comment by flowpoly** [comment]
I really like #1 and #2! 

I had these as well which are somewhat similar to 3 and 4:
1.What do you like to do in your free time?
2.How often do you use Hubs?
3.What goals are you're trying to achieve with Hubs?
4.Why are these goals important?
5.What are the biggest challenges that prevent you from achieving these goals?

**Comment by misslivirose** [comment]
Resolving since v2 of the survey is live with Feedback Duck. 🦆
