### ISSUE TITLE
[UX Enhancement] Analytics

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1464]
As a Hubs contributor, I would like to know how many page views Hubs receives on a daily/weekly/monthly/yearly basis so that I can measure the impact of new features or edits to features.

**Comment by gfodor** [comment]
We have some basic internal telemetry (GA instrumentation and some entry funnel flows, which can be seen in the code) but it's intentionally limited to preserve user privacy. Going to close this one for now.
