### ISSUE TITLE
[UX Enhancement] Surface more information about the Hubs Discord community for users who want to connect with one another

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1467]
As a user, I would like to see which rooms have people in them so that I can become part of the community. This would also support user retention. This is probably the most important addition that Hubs could have to improve retention. Would be even better to have analytics before introducing this feature!

An alternative to this would be to show the number of Discord members within Hubs' main website. Which is where the community is growing and developing.

**Comment by gfodor** [comment]
I agree that we could surface more info about our Discord community - that seems like it would be nice to see growing. We've avoided specifically publishing any room information, since we do not want to be facilitators of open public meeting spaces.

**Comment by flowpoly** [comment]
@gfodor Yeah, I feel this could be a way to get more users into Discord and grow the community further without having to have public Hubs rooms which cause the issues we talked about. 

Even having something like 1,345 users in Discord, 153 Online. Join! 

Haha! Something along those lines.

**Comment by misslivirose** [comment]
Updated the title on this to reflect the Discord community use case and how we can think about making that more prominent to users who want to connect
