### ISSUE TITLE
[UX Enhancement] Change the Main Call-to-Action Color to Blue

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1471]
As a user, it can be confusing to see the red/pink as the main call-to-action color. Red tend to represent danger, stop, or delete (which should be used for those actions). The new color could be the same blue used for Spoke.

**Comment by gfodor** [comment]
I agree that the use of red can be tricky because of the connotations -- however I suspect our design chose this scheme in part to deliberately contrast with Spoke.

**Comment by gfodor** [comment]
Also, we do have a few other colors in the scheme:

- We use a ligher blue than the spoke blue for tips, notifications, etc
- We use the spoke blue for the CTAs going to spoke (just one right now, in the custom scene dialog)
- We have a new yellow we use for favorites

**Comment by flowpoly** [comment]
@gfodor I wonder if it would be possible to differentiate them with a logo.
Sort of how Confluence and Jira does it. Also the landing pages are pretty straightforward in the way that one is used to create rooms right away and the other one is to create scenes for my rooms.

**Comment by misslivirose** [comment]
Going to resolve this now that the new UI redesign will be coming out with a different color theme, tracked in #3558
