### ISSUE TITLE
[UX Enhancement] Set Room Name

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1473]
As a user, I should not need to open a new modal to chance my room's name. I should be able to just click an "Edit" button or icon and change the name of my room inline.

**Comment by misslivirose** [comment]
I imagine this looks similar to how the display name edit would work in the cases that the room owner is signed in to their Hubs account: 

![image](https://user-images.githubusercontent.com/4313320/60830798-deeb1900-a16c-11e9-9bb1-6eb764f00fbe.png)

Where clicking on the pencil icon would make the name editable.

**Comment by flowpoly** [comment]
Yup, this is accurate. Let me know if we need any mocks for these UX Enhancements!

**Comment by misslivirose** [comment]
Now that there are additional room settings that a room owner can create rooms with, I think the modal flow makes sense to keep everything related to the room settings in one place instead of making part of the setting editable in this dialog and the rest set in the modal.
