### ISSUE TITLE
[UX Enhancement] 'What's New' Page GIFs

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1474]
As a user, it would be more helpful to understand 'What's New' if I had GIFs showing the action.
https://hubs.mozilla.com/whats-new

**Comment by gfodor** [comment]
good suggestion -- we should try adding more GIFs. the developers who write the PRs typically add the media (this page pulls from our github PRs.)

**Comment by misslivirose** [comment]
Addressed this in the Contributing guidelines per #1618 , so going to go ahead and close this issue. Thanks for the recommendation, @flowpoly!
