### ISSUE TITLE
[UX Enhancement] Show a progress bar instead of Loading 1/2

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1479]
As a user, it is difficult to tell how much more time I need to wait for a page to load. It would be easier to tell if there was a progress bar. This could also be helpful when loading-in 3D models or videos that require loading.

![Loading](https://user-images.githubusercontent.com/38146102/60177344-aea79000-97e6-11e9-87f1-0d5423db27b3.jpg)

**Comment by gfodor** [comment]
Unfortunately this runs up to technical limitations -- we'd have loved to have done a progress bar, but unfortunately hubs rooms load objects recursively, so it'd run into the "progress bar gets shrunk or slower over time" dynamic.

**Comment by gfodor** [comment]
Going to close for now unless there's more thinking here on how to improve this that takes into account the limitation i mentioned above.
