### ISSUE TITLE
[UX Enhancement] Fix Button Inconsistencies

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1482]
Some buttons do not have the first letter capitalized, but others do. The standard should be "Share" and not "share".

**Buttons affected:**
Share
Close (when signing in successfully) 
Choose Scene (button below the 'share' button when Choosing a Device)
Delete Avatar (when creating a new avatar, the styling here is also different)
Object's Menu (pin, clone, open link)

**Comment by Parikshit-Hooda** [comment]
Please let me know the directory and file where I can find the said buttons. I am willing to fix this issue.

**Comment by gfodor** [comment]
The copy for the buttons can largely be found in `src/assets/translations.data.json` -- thanks for offering to help!

**Comment by zufishanali** [comment]
Hi, is this issue still open? If no one has started working on it yet, I would like to attempt it. 

Thanks, 
Zufishan

**Comment by SparshKat** [comment]
Hi, @flowpoly, i am willing to work on the given issue, is this still open and not assigned to anyone? However i checked on the few errors mentioned by you before hand and i can't seem to find few errors like -

- Close (when signing in successfully)

- Delete Avatar (when creating a new avatar, the styling here is also different)

- Object's Menu (pin, clone, open link)
