### ISSUE TITLE
[UX Enhancement] Enhanced Name & Avatar Workflow #2

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1485]
As a user, when I am changing my name & avatar, I should be able to select from Featured Avatars, My Avatars, and Create a New Avatar from the same place. There should also be a smooth transition from on section to another. Perhaps tabs within the same page?

**Comment by misslivirose** [comment]
This is now implemented in the avatar editor, so closing this with the caveat we still need additional work on the overall avatar flow.
