### ISSUE TITLE
[UX Enhancement] Code Room 

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1486]
As a user, when entering a code room, there is no way for me to go back to the previous page easily. This is not a modal experience as the other workflows which breaks user expectations. Also, why do we need a code? Is there an easier experience for this?

**Comment by gfodor** [comment]
The hub.link page is intended to be navigated to directly by either new entrants or by users transfering the room to another device. What flow specifically were you running into?

**Comment by flowpoly** [comment]
@gfodor I see! I am closing this one as it relates more to this issue: https://github.com/mozilla/hubs/issues/1490
