### ISSUE TITLE
[UX Enhancement] Add New Media Wording Enhancements

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1487]
As a system, I do not show the correct naming conventions when adding new media.
- In the Google Poly tab, the search bar's placeholder text should be 'Search Google Poly Models' instead of 'Search Models'
- In the Sketchfab tab, the search bar's placeholder text should be 'Search Sketchfab Models' instead of 'Search Models'

- In the Videos tab, the search bar's placeholder text should be 'Search for Videos' instead of 'Search the Web'
- In the Images tab, the search bar's placeholder text should be 'Search for Images' instead of 'Search the Web'
- In the Twitch tab, the search bar's placeholder text should be 'Search for Twitch Streams' instead of 'Search for Streams'

**Comment by gfodor** [comment]
I agree for providers it should be "Search Google Poly" and "Search Sketchfab" and "Search Twitch" -- however I'm not sure about the videos and images placeholder, since it's intended to convey that it's a generic web search for videos/images, not a specific site. I agree it could be confusing.

**Comment by flowpoly** [comment]
@gfodor Hmm you're searching the web for images and videos. I mean images always return images and videos always return videos, right?

**Comment by misslivirose** [comment]
I think that @flowpoly's point about the fact that the images tab will always return images and videos returning videos imply that they're generic web searches makes sense. It also makes it consistent - GIFs currently already uses this phrasing (_Search for GIFs..._)

**Comment by SparshKat** [comment]
Hi, may i work on this issue? Also it would be a huge help if one could tell me the name of the file being rendered, so as to get the job done fast.

**Comment by brianpeiris** [comment]
These are all just strings in the translations json file: https://github.com/mozilla/hubs/blob/master/src/assets/translations.data.json#L110-L119

**Comment by gfodor** [comment]
thanks for offering to contribute!

please adjust these to:

"Search Google Poly"
"Search Sketchfab"
"Search Twitch
"Search Videos"
"Search Images"
etc

thanks!

**Comment by SparshKat** [comment]
Thanks @gfodor and @brianpeiris , i'd do a PR with the changes. :)

**Comment by SparshKat** [comment]
I have fixed the issue with PR #2006. Review it :)
