### ISSUE TITLE
Burn git commit info into build and let dev see what build is running

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#150]
In order to make it clear when a new version is deployed:

- We should burn the git sha + commit info into the build somehow
- We should make it so that a dev can inspect the git sha + commit info of the running app
- We should (optionally) make it so if you pass a git sha to the app on QS, it will keep refreshing until that version is the one loaded (useful for smoke test and checking when your build goes live.)

**Comment by robertlong** [comment]
Something like this would work for adding commit info: https://github.com/pirelenito/git-revision-webpack-plugin#plugin-api

**Comment by mquander** [comment]
We did this but only for builds using our deploy process. It might be nice to do it in the webpack config for anything that you `yarn build`.

**Comment by joshmarinacci** [comment]
does this matter now?
