### ISSUE TITLE
When muted, camera sharing button dropdown is obscured <n/t>

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1519]

**Comment by misslivirose** [comment]
Would the appropriate fix for this be to bump the z-order of the camera drop down to be in front of the muted warning?

**Comment by gfodor** [comment]
yeah that seems right, or we can hide it too since it's all inside of react
state

**Comment by misslivirose** [comment]
![image](https://user-images.githubusercontent.com/4313320/66346875-f7073b80-e907-11e9-878a-8f2885b5c1fd.png)

Either fix would be acceptable: The camera button shows over the muted indicator, so the muted dialog box is behind the camera drop down, or while the camera menu and its sub-buttons are visible, the blue muted dialog box is hidden only while the button menu is visible.

**Comment by robin-k-wilson** [comment]
I'd like to take a stab a this bug today!

Using Chrome dev tools, I added z-index: 0 to the muted dialogue. It did the first fix @misslivirose suggested. Seemed to continue to work as I resized the window as well.

**Comment by misslivirose** [comment]
Awesome, thank you @robin-k-wilson! Let us know if you need any assistance and keep us updated on progress.

**Comment by robin-k-wilson** [comment]
PR is open. Let me know if this needs anything else for a fix. 

Happy to help a fix that was relevant to my use of hubs!

**Comment by johnshaughnessy** [comment]
Woohoo! Thanks for the fix @robin-k-wilson !
