### ISSUE TITLE
Audio speaker test not working in GearVR flow

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#152]

**Comment by gfodor** [comment]
For some reason the tone loop is not starting when you go in with `vr_entry_type=gearvr`, but it is doing it when i test that on desktop. Seems to be oculus browser specific.

**Comment by gfodor** [comment]
Seems likely this is a 'don't play sound unless user initiated' issue on android, which may be possible to resolve by creating the sound via the web audio api

**Comment by robertlong** [comment]
Hmm, I can't reproduce this on my Pixel 2. Is it Android specific or Oculus Browser specific?
