### ISSUE TITLE
Camera sharing not working on iOS

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1531]
If you share your camera on iOS Safari, you see it, but others don't.

**Comment by misslivirose** [comment]
Reproed the same issue on a different combination of devices / browser: Chromebook running Firefox for Android Beta tried to share camera, didn't show up for client connected on windows. Given the combination of this bug + #1533 + #1561 , there seems to be something (possibly codec related per @gfodor ) consistently breaking streaming features on certain device / browser combos.

**Comment by gfodor** [comment]
Well, oddly enough, with an iPhone and Firefox + Chrome on PC running, I actually saw the camera working once for one session. Dead otherwise. So there's some non-determinism here, and it seems likely to be a Janus issue since it always either worked or didn't work across both PC browsers

**Comment by gfodor** [comment]
This seems like it gets fixed if we remove a hack in naf-janus-adapter I put in for iOS a while back. However, in my testing, it looks like voice is basically broken for me on my iOS device. 80% of the time I do not hear another avatar when joining the room.

**Comment by gfodor** [comment]
Note that the hack I'm referring to here is iOS specific, so it's not going to fix any other platforms (mac, android, etc)

**Comment by gfodor** [comment]
this should be fixed now, please re-open if seen again!
