### ISSUE TITLE
On Oculus Go, user denying mic permission in Oculus Browser prevents re-allowing microphone permissions

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1534]
As reported: https://twitter.com/larsberg_/status/1150776676508459008

We should determine what recovery paths exist for those who deny mic permissions on Oculus Go/Oculus Browser.

**Comment by misslivirose** [comment]
Just tested this on Go in Oculus Browser

1. Open a private window
2. Enter a Hubs room
3. Deny audio permission 
4. Refresh
5. Re-enter

Expected: Audio permission denial is temporary
Actual: Audio permission denial carries over and we don't re-prompt

Workaround: Click the green icon in the status bar and tell the mic permissions to re-prompt. 

However - when I did this, the browser said I already had allowed microphone permissions (I had not) - it seemed to carry this over from the non-private window I had open (the browser normally had these permissions) so I am wondering if there's a possibly bug in the browser permissions?
