### ISSUE TITLE
Pausing livestreams gets clients out of sync

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1541]
Right now, it is very easy for Twitch streams to get out of sync from one another in the room if a user pauses before another user enters the room. The users who enter after the first user will have the state synchronized, but the timestamp is different. 

This makes it hard for remote conference scenarios in particular, because there is no way to jump back to the real-time event. It also means that someone can inadvertently trigger people to be out of sync and the workaround is to pause the video and have all clients reconnect. 

I think that the solution is to jump ahead to the most recent time stamp (which is what happens when you pause on Twitch) but am open to other suggestions (removing the pause button from live stream hovers?)

**Comment by gfodor** [comment]
Disabling pausing seems like a good solution to me

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/1676
