### ISSUE TITLE
Changing your avatar 2x during video recording crashes

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1555]
In smoke test, start video camera and then switch between the avatars pasted in the room. Error:
![image](https://user-images.githubusercontent.com/220020/61680760-a6485500-acbf-11e9-9b57-799cb45cd36f.png)

**Comment by misslivirose** [comment]
I just tried to repro this on production in an empty room with just two avatars and I got a different error but it still broke after changing my avatar. I got this same error after changing avatars during the meetup today, too: 

```
TypeError: this.playerHead.el is null                                           camera-tool.js:543:14
    tock camera-tool.js:543
    Aframe 2
    render three.module.js:25049
    value Aframe
    value self-hosted:1019
    Io three.module.js:24892
    i three.module.js:7642
    o raven.js:377
```
