### ISSUE TITLE
Default spawner model behaves incorrectly in Hubs

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#1558]
The scaling on the default spawner's duck model causes multiple issues in Hubs. The sweeping hover effect is rendered incorrectly, the pause mode menu doesn't appear when you expect it to and when you hit the "clone" button, the resulting model is massive. Hubs has no problem handling the model when loaded directly from its sketchfab URL

**Comment by robertlong** [comment]
I think there must be a bug in the super-spawner component. The glTF component just adds the super-spawner component along with a few other components: https://github.com/mozilla/hubs/blob/master/src/gltf-component-mappings.js#L228

My be would be either there is some sort of race condition with loading the network template or we're just scaling the UI down and it shouldn't be affected by the spawned object scale.

Here's a test scene that reproduced the bugs:
https://hubs.mozilla.com/scenes/sGQpdxF

**Comment by InfiniteLee** [comment]
I think this is fixed now (maybe #1931?)

**Comment by brianpeiris** [comment]
Indeed! It looks to be fixed 🎉
