### ISSUE TITLE
Investigate video playback issues likely related to timekeeper ownership to address video freezing issues

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1559]
**Describe the bug**
In the last spatial assembly event, the speaker played a single video from youtube. During the playback, there were varying reports of success: some didn't see it at all (very few), a good number of people had it freeze mid way through, and it seems the majority had it work properly.

I've definitely seen some mysterious behavior around the shared timekeeper. I think currently we have some contracts around when a person joins a room they try to become the timekeeper for any video. I've also seen videos be reset by bots in the smoke test space.

I think we need to look at the timekeeper ownership interaction closely, and potentially consider moving to a dead-reckoning approach (with perhaps a less periodic, optimistic flush if an owner is actively watching the video.) 

**To Reproduce**
No repro

**Expected behavior**
No repro

**Comment by misslivirose** [comment]
I've also observed this - updating the bug title so that it reflects the action item needed to address this.

**Comment by gfodor** [comment]
I took a closer look, and the contract we have currently is that when someone joins a room, they attempt to join any scene owned videos after a random delay, if they have not been claimed by someone else. We probably need to dig into that further to see if there's any condition which a newly arriving person could take ownership of a (pinned or scene) video inadvertently when joining if they fail to recognize its owned by someone else in time. I don't know if that would explain freezing but it would explain a video resetting to the beginning.

**Comment by misslivirose** [comment]
Closing this issue because there have been a number of other video playback related issues that have since been fixed, and we haven't observed this independently from those known issues. We will create a new bug if we see the original issues reported in the bug.
