### ISSUE TITLE
Report of pinned object disappearing in Spatial Assembly event

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1560]
**Describe the bug**
In the last Spatial Assembly event, the organizer reported that she re-arranged some pinned objects without un-pinning them (from pause mode), and a subsequent refresh had them gone. I did not see them in the room when I joined.

I'm also not sure if we're dealing with re-pinning objects when we use the transform tools, so that may be related (there is no re-pin animation when using the transform tools.)

**To Reproduce**
No repro

**Expected behavior**
Pinned objects should remained pinned if moved in pause mode.

**Comment by gfodor** [comment]
fixed now @brianpeiris ? it seems likely this could all be the same bug.

**Comment by brianpeiris** [comment]
I dunno, this does sound like a different bug. In the scenario I repro'd and fix, objects never actually got un-pinned in the database, they only visually disappeared in the client. So if this bug described things actually losing their persistence in the DB, it ought to be investigated separately.

**Comment by gfodor** [comment]
Ah good point. I checked, and they are no longer in `objects.gltf`, so I guess they were removed somehow. All I can think of is that we have an issue where the `unpin` event is being sent when manipulating pinned objects, or there's something unrelated to what the user reported as the suspected cause.

**Comment by misslivirose** [comment]
I'm going to close this given that there isn't a solid repro for this specific case, and I've made #1891 a more general investigation case for pinning actions being inconsistent - please feel free to re-open if we want to keep this separate from
