### ISSUE TITLE
Cannot see shared camera on Oculus Quest (Firefox Reality)

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1561]
**Describe the bug**
When I attempt to share a webcam stream, the stream never appears in Oculus Quest. I see the object loading indefinitely

**To Reproduce**
Client A and B are in the same room
1. Client A on desktop shares webcam
2. Client B on Oculus Quest observes an infinite loading object

**Expected behavior**
The webcam is visible to users on Oculus Quest

**Desktop (please complete the following information):**
-  Device: Oculus Quest
 - Browser: Firefox Reality (does not repro on Oculus Browser)

**Comment by misslivirose** [comment]
Note - I _may_ be running an older FxR APK. I will do a fresh install and verify this.

**Comment by misslivirose** [comment]
Still repros with store FxR release

**Comment by misslivirose** [comment]
If someone with a different Quest could confirm a repro, that would be helpful.

**Comment by gfodor** [comment]
can confirm still broken in quest + fxr 1.4

**Comment by misslivirose** [comment]
Per #1788 , this also reproduces with screen sharing. I will resolve this as the new bug has additional information about versioning that could be helpful.
