### ISSUE TITLE
Object highlighting should go away while holding object

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#1565]
**Describe the bug**
Object highlighting (blue bling) stays on while holding objects in VR. The bigger the object, the more distracting it can be.

**To Reproduce**
1. Spawn an object
2. Hold the object with your right hand.
3. Object continues to show blue highlight bling.

**Expected behavior**
The highlighting is useful during cursor hover, but should go away while holding the object.

**Screenshots**
https://images-ext-1.discordapp.net/external/b4bVrgcTmPmS1v6WvAlFEFzR9VfmieUVFyeqSEnUreU/%3Ftoken%3D2a51b8973b880b991a55078e0206344e/https/uploads-prod.reticulum.io/files/16c7ca5c-668f-4c86-84a3-38348fa767d6.mp4

**Desktop (please complete the following information):**
-  Device: Desktop (Rift)
 - OS: Windows
 - Browser: Firefox

**Comment by misslivirose** [comment]
This seems like a good bug to fix, as it impacts everyone in VR mode.

**Comment by netpro2k** [comment]
From looking at the code it looks very much like this is working as intended, but I agree we should change the intended behavior.

**Comment by johnshaughnessy** [comment]
I know when blue highlight bling
That could only mean one thing
