### ISSUE TITLE
Shimmer effect shown on held objects

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1570]
**Describe the bug**
When gripping an object in VR, the object shimmers with the hover effect visualization. This seems wrong and is visually distracting when holding/moving an object -- the effect should be shown on cursor hover or in pause mode, but not when holding.

**To Reproduce**
Grab an object with your hand.

**Expected behavior**
No shimmer effet.

**Desktop (please complete the following information):**
Quest

**Comment by misslivirose** [comment]
@gfodor is this the same as #1565 ?

**Comment by gfodor** [comment]
yes will close
