### ISSUE TITLE
Camera / Video Mode Toggle

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#1576]
**Is your feature request related to a problem? Please describe.**
I recently spawned the camera for the first time since the video recording update. I was initially very confused on how to switch to camera mode. I eventually figured it out, but I don't think it's as intuitive as it could be.

**Describe the solution you'd like**
It would be nice if there was a dedicated button for switching between picture/video mode and another for video duration when in video mode and maybe a picture timer when in picture mode.

**Additional context**
Here's a rough design concept:
![CameraUI](https://user-images.githubusercontent.com/1753624/61978809-0df3ee00-afa7-11e9-8f47-5f370fcf69f9.png)

**Comment by gfodor** [comment]
this should help: https://github.com/mozilla/hubs/pull/1629

**Comment by misslivirose** [comment]
Closing since 1629 was merged! Great suggestion & implementation!
