### ISSUE TITLE
Avatars re-appear a few seconds after clicking Hide

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#1580]
**Describe the bug**
Due to the periodic avatar syncing introduced in https://github.com/mozilla/hubs/pull/1545, an avatar will automatically re-appear in the room after you Hide them. Fortunately, their voice still remains blocked, but their avatar and avatar movements do continue to be networked.

**To Reproduce**
1. Hide an avatar
2. See that it comes back after a few seconds even though you haven't un-hidden them.

**Expected behavior**
Avatars should remain hidden until you un-hide them!

**Comment by gfodor** [comment]
Ouch, this is bad. This seems like it's exposing a flaw with the hiding logic -- it def shouldn't be possible for another client to override your request to hide them. We block the voice at the SFU level, I guess we forgot to do this for websockets when we transitioned off of data channels.

**Comment by gfodor** [comment]
I think it should be simple enough to maintain a registry of hidden sessions and just use the same control where we check for `block_naf` in hub channel to also drop those packets.

**Comment by gfodor** [comment]
https://github.com/mozilla/reticulum/pull/207

**Comment by brianpeiris** [comment]
Hmm, I was going to close this, but it seems something is still wrong. Not sure if it's a regression since 207 and #1585 shipped, but I'm seeing avatars re-appear once after hiding them for the first time, but the hide seems to stick the second time. I'll investigate tomorrow.

**Comment by gfodor** [comment]
I saw this at one point while working on the code, but I thought I fixed
it. It's probably a race condition around the person hiding and the other
person getting a sync message in flight before the server updates their hub
channel.

**Comment by brianpeiris** [comment]
It turned out to be a problem with the interaction between `periodic-full-syncs` and pause mode. 
You can reproduce it reliably by:

1. Entering pause mode
2. Wait for more than 5 seconds while in pause mode
3. Hide an avatar
4. Exit pause mode.

If you receive a full sync while in pause mode, before blocking an avatar, it would be queued and then flushed when you exit pause mode.

Fix incoming.

**Comment by gfodor** [comment]
Ah nice find!
