### ISSUE TITLE
Can't grab first pen

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1589]
**Description**
Sometimes the first pen you spawn does not get a body, so you can't pick it up with your hands.

**To Reproduce**
Spawn a pen in quest. Try to grab it with hands.

**Hardware** 
 - Device: [Quest]
 - Browser [Oculus]

**Comment by misslivirose** [comment]
I'm having difficultly reproducing this so I'm going to leave the tag off for now, but I think given that grabbing a second pen sounds like a workaround, I'm going to suggest we put this as a P2 until we can get some more consistent repros.

**Comment by InfiniteLee** [comment]
I think this is/was related to some bugs around permissions which got fixed. Going to close since I haven't seen/heard about this happening for a while now.
