### ISSUE TITLE
First camera that is spawned is too small.

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1590]
**Description**
In Firefox desktop or in Oculus Quest browser, when I spawn a camera, the first one I spawn is small. The next one is at the regular size.

**Expected behavior**
The camera should always spawn at the same size.

**Hardware** 
 - Device: [desktop, quest]
 - OS: [Linux, quest OS]
 - Browser [Firefox, Oculus browser on quest]

**Additional context**
Seems like a familiar kind of race condition.

**Comment by gfodor** [comment]
i think i fixed this: https://github.com/mozilla/hubs/pull/1624
