### ISSUE TITLE
DisableBatching causing images in scene to render incorrectly or not at all

### ISSUE THREAD

**Issue by liebeskind** [mozilla/hubs#1594]
**Description**
Images defined in custom .glb file aren't loading or are loading incorrectly.  Setting query parameter of &disableBatching=true fixes the issue.

**Screenshots**
<img width="609" alt="Screen Shot 2019-07-30 at 9 56 21 AM" src="https://user-images.githubusercontent.com/1824208/62183658-d8853280-b30f-11e9-8fe0-6ef91ab58076.png">

**Hardware**
 - Device: Desktop
 - OS: Mac
 - Browser: Both Firefox and Chrome

**Additional context**

**Comment by gfodor** [comment]
hey @liebeskind would you be willing to share your glb? would make it easier for us to track down. thanks for the report!

**Comment by brianpeiris** [comment]
This was probably fixed by https://github.com/MozillaReality/three-batch-manager/pull/19, which we just shipped in Hubs. Feel free to reopen otherwise.
