### ISSUE TITLE
Spawned emojis are scaled incorrectly in Chrome

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#1604]
**Description**
Spawned emojis appear tiny in Chrome, but are the expected size in Firefox. The hit box for the emoji is still large though. The problem still repros if you turn off batching with the `disableBatching` query param. 

**To Reproduce**
1. Use Google Chrome
1. Enter a room
2. Spawn an emoji from the chat box

**Expected behavior**
Emojis should be a reasonable size and the same size in all browsers. See screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/79419/62399138-a5b98500-b52f-11e9-944e-964ef4cd0b5a.png)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Comment by arpu** [comment]
how can i spawn a emoji from the chat box?

**Comment by brianpeiris** [comment]
Type an emoji name like ":heart:" into the chat box and then click on the magic wand button or press Ctrl+Enter

**Comment by arpu** [comment]
ah cool! thx

**Comment by brianpeiris** [comment]
This must have been fixed at some point, can't repro it anymore.
