### ISSUE TITLE
Transparent areas of images will turn black after opening in Hubs

### ISSUE THREAD

**Issue by ducile** [mozilla/hubs#1612]
When I import a text as a .png with a transparent background into Spoke it appears correctly. But after publishing to Hubs and opening the room it will turn the transparent areas black. 

![Bildschirmfoto 2019-08-06 um 12 12 15 (2)](https://user-images.githubusercontent.com/16058129/62556942-f5f05a00-b843-11e9-8c24-04b124e5c462.png)
![Bildschirmfoto 2019-08-06 um 12 13 56 (2)](https://user-images.githubusercontent.com/16058129/62556945-f852b400-b843-11e9-86a8-4cd7fd1adfc0.png)

**Comment by dastyla123** [comment]
I attached the file that I've been using.
![picturetopeople org-b871871b24be63b5586e8536f02111e8081444d81695c2cfae](https://user-images.githubusercontent.com/16058129/62564472-e6c4d880-b852-11e9-8e45-b621136a8c9c.png)

**Comment by emclaren** [comment]
We got this comment on our Youtube Channel recently - I wonder if this is a related issue

3DInteractiveSTHLMAB
1 week ago
Great video! We love hubs and actually made a room with this model six months ago. However the GIF images used in the model have started to display black borders on them after a while. Are there something you should think about or take in consideration when optimising and uploading images with transparency? Link to the room :-D 
https://hubs.mozilla.com/kX8o4dV/positive-wellmade-safari

**Comment by dpentecost** [comment]
March 2020 now, and has this PNG alpha transparency issue been addressed? Or is there a workaround?

**Comment by netpro2k** [comment]
Batching has been disabled by default. Transparency in batching was working as "intended" but was obviously not ideal. We will likely want a better solution before enabling image batching again, but more of a "feature" at that point, and already captured elsewhere, so closing this.
