### ISSUE TITLE
Meeting Room Classic Scene has broken media

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1616]
**Description**
When you select the 'Meeting Room Classic' scene, there is a broken piece of media in the room that cannot be removed.

**To Reproduce**
1. Create a new room
2. Change the room to 'Meeting room classic'
3. Enter the room and observe the broken media

**Expected behavior**
The featured scenes should not have broken media in them

**Screenshots**
![image](https://user-images.githubusercontent.com/4313320/62637020-8041c800-b8ef-11e9-8f37-dafd3401e3ff.png)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox Nightly

Scene URL: https://hubs.mozilla.com/scenes/m5CgDyA/meetingroomclassic

**Comment by joshmarinacci** [comment]
Is this still broken?

**Comment by misslivirose** [comment]
Yes

**Comment by j-conrad** [comment]
It's an image of the hubs logo from the web. I'll see if I can fix it and/or remove it.

**Comment by joshmarinacci** [comment]
how did you fix it?
