### ISSUE TITLE
Room video playback of camera videos breaks after first play

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1620]
**Description**
When you record a video with the camera tool and it plays back in the room, after the first loop, the video plays incorrectly.

**To Reproduce**
1. Spawn a camera in a room
2. Make a three second video
3. Watch the video playback in the room and compare it to the actual video

**Expected behavior**
The subsequent two loops of the video play back at the correct speed.

**Screenshots**

Video: [https://uploads-prod.reticulum.io/files/b64c302e-e3c1-4dac-a3f7-874a20905044.mov?token=a04503be43bf92364eb77d48ef0313ca](https://uploads-prod.reticulum.io/files/b64c302e-e3c1-4dac-a3f7-874a20905044.mov?token=a04503be43bf92364eb77d48ef0313ca)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox Nightly

**Additional context**
Does not repro in Firefox main release

**Comment by misslivirose** [comment]
P3 in case this is the result of a regression that ends up getting fixed in Nightly - if it repros in FF stable, revisit.

**Comment by joshmarinacci** [comment]
Seems like this would be fixed by now.

**Comment by misslivirose** [comment]
Yes, this is working now
