### ISSUE TITLE
Menu should not be able to be upside down

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1634]
**Description**
The menu can be made to be upside-down by rotating objects around.

**To Reproduce**
When pasting this model https://poly.google.com/view/bsBhfp40kQl it comes in upside down (which is expected I think since the model probably is inverted) -- but if you rotate the object properly the menu becomes hard to use since it is inverted.

**Expected behavior**
It'd be nice if the menu was smart enough to invert itself it was in a position that would read upside-down.

**Comment by misslivirose** [comment]
Is this a duplicate of #1187 ?

**Comment by gfodor** [comment]
indeed, thank you!
