### ISSUE TITLE
YouTube live stream froze on FxR for Quest

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1646]
**Description**
While watching a YouTube live stream in Firefox Reality on the Oculus Quest, the live stream froze for this client alone on a frame in the video. The pause/play buttons were still interactive, but did not actually have any impact with the video at that point. 

**To Reproduce**
1. Watch a YouTube live stream in Oculus Quest using the Firefox Reality browser

**Expected behavior**
It will work correctly and play through the duration of the live stream 

**Hardware** 
 - Device: Oculus Quest
 - OS: Android
 - Browser: Firefox Reality

**Additional context**
Reported by @larsbergstrom in the Monday Project Call (Hubs Commons room)

This may have also happened with a video played during a Spatial Assembly meetup several weeks ago and it is possible this isn't related to the Quest / FxR specifically as we've seen symptoms similar to this on other browser/device combinations. 

See also: #1559

**Comment by gfodor** [comment]
Discovered HLS playback videos on FxR, mitigated somewhat by: https://github.com/mozilla/hubs/pull/1676 but opened a bug here: https://github.com/MozillaReality/FirefoxReality/issues/1602

**Comment by gfodor** [comment]
confirmed this is fixed in FxR 1.4. closing for now, we can reopen if we see it breaking again in 1.4+
