### ISSUE TITLE
hubs crashing in firefox on windows 10

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#1654]
**Description**
Going to this room, in Firefox on Windows 10, results in hubs stuck on "Loading"
https://hubs.mozilla.com/M9m6TyU

**To Reproduce**
go to that room in Firefox

**Expected behavior**
shouldn't crash

**Screenshots**

**Hardware** 
 - Device: Razerbook 15, Windows MR display + steam VR
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
URL works on mac

A nice set of errors in the console.  Here's the full console.

Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 M9m6TyU:1:1
Request to access cookie or storage on “https://www.google-analytics.com/analytics.js” was blocked because it came from a tracker and content blocking is enabled.
M9m6TyU
A-Frame Version: https://github.com/MozillaReality/aframe index.js:80
three Version: https://github.com/MozillaReality/three.js index.js:81
core:schema:warn Default value `null` does not match type `string` in component `media-loader` 2 browser.js:111
core:schema:warn Default value `null` does not match type `string` in component `player-info` browser.js:111
core:schema:warn Default value `null` does not match type `string` in component `camera-focus-button` browser.js:111
core:schema:warn Default value `null` does not match type `string` in component `emit-scene-event-on-remove` browser.js:111
Hubs version: 1005 (435fafb4b54d1df98e3d7fbe329400363354733d) hub.js:4:8
Tracking: Sentry DSN: https://013d6a364fed43cdb0539a61d520597a@sentry.prod.mozaws.net/370 telemetry.js:10:12
Tracking: Google Analytics ID: UA-77033033-12 console.js:35
Using WebGL 2.0 context. console.js:35
THREE.WebGLRenderer 106dev console.js:35
THREE.WebGLRenderer: WEBGL_multiview extension not supported. console.js:35
THREE.WebGLRenderer: OVR_multiview extension not supported. console.js:35
Using Non-VR bindings. console.js:35
Error: WebGL warning: copyTexSubImage3D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow. 8 WebGLAtlasTexture.js:406
Hub ID: M9m6TyU console.js:35
Reticulum @ gallant-illusionist.reticulum.io: v1.0.20190807004331 on arbre console.js:35
Phoenix Socket URL: wss://gallant-illusionist.reticulum.io:443 console.js:35
THREE.GLTFLoader: Duplicating UVs to support aoMap. console.js:35
Logged into account 417198394767836015 console.js:35
Request to access cookie or storage on “https://www.google-analytics.com/r/collect?v=1&_v=j78&a=2039…d=UA-77033033-12&_gid=1144002107.1565726323&_r=1&z=472672056” was blocked because it came from a tracker and content blocking is enabled.
M9m6TyU
Janus host: admiring-rogue.reticulum.io console.js:35
Scene URL: https://uploads-prod.reticulum.io/files/8b808088-1f7b-4e5a-a874-bb31156e849d.bin console.js:35
[three-pathfinding]: Use THREE.BufferGeometry, not THREE.Geometry, to create zone. console.js:35
Releasing uncached gltf https://uploads-prod.reticulum.io/files/8b808088-1f7b-4e5a-a874-bb31156e849d.bin console.js:35
Failed to load glTF model InternalError: "too much recursion"
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
    n three-pathfinding.module.js:1
 
Object { el: a-entity
, id: undefined, attrName: "gltf-model-plus", evtDetail: {…}, initialized: true, isSingleProperty: false, isSinglePropertyObject: false, isObjectBased: true, objectPool: {…}, attrValue: {…}, … }
console.js:35
THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(215,18-93): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them console.js:35
THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(261,23-154): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(257,18-93): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them console.js:35
THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(242,23-154): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(238,18-93): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them console.js:35
THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(80,18-93): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them console.js:35
Source map error: TypeError: sketchfab-zip.worker-9ed027c28bd1d8e9e008.js.map is not a valid URL.
Resource URL: blob:https://hubs.mozilla.com/b3030947-8c65-44d6-90d8-2c0c3d56494e
Source Map URL: sketchfab-zip.worker-9ed027c28bd1d8e9e008.js.map

Source map error: TypeError: gifparsing.worker-7cba2e1c639db96ea898.js.map is not a valid URL.
Resource URL: blob:https://hubs.mozilla.com/7fd582b7-ad77-441f-a1cf-bfcd7fe8db7a
Source Map URL: gifparsing.worker-7cba2e1c639db96ea898.js.map

​

**Comment by gfodor** [comment]
this is loading for me now, did we figure this out @blairmacintyre ?

**Comment by blairmacintyre** [comment]
working for me now, too

**Comment by gfodor** [comment]
going to close for now
