### ISSUE TITLE
Spawners do not preserve their y position

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1655]
**Description**
Spawners appear to be offset by some -y value when exporting a scene from Spoke to Hubs. Test scene: https://hubs.mozilla.com/scenes/xCkGFMs 

**To Reproduce**
1. Create a scene in Spoke with a spawner at a specific location
2. Publish the scene to Hubs
3. Observe the spawner is offset

**Expected behavior**
The spawner position remains the samse

**Screenshots**

The default spawner as shown in Spoke:
![image](https://user-images.githubusercontent.com/4313320/62985424-142dfb00-bdec-11e9-9493-151b3b32944d.png)

The spawner where it appears in Hubs:
![image](https://user-images.githubusercontent.com/4313320/62985433-2019bd00-bdec-11e9-88af-21e2de763648.png)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox Nightly

**Comment by johnshaughnessy** [comment]
Fixed in https://github.com/mozilla/hubs/pull/2160
![image](https://user-images.githubusercontent.com/4072106/76809068-de4c5d00-67a6-11ea-9b7d-369d61569f10.png)
