### ISSUE TITLE
iOS safari kicking people out after a short while

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#1662]
**Description**
Had someone joining a hub from their phone on safari.  They kept getting disconnected.

**To Reproduce**
I do not know exactly what they were doing (I created a room, shared the link, they joined).  They hadn't used hubs before, didn't have an account

**Expected behavior**
They shouldn't get disconnected.

**Screenshots**
none.

**Hardware** 
 - Device: iOS phone
 - OS: ios
 - Browser: Safair

**Additional context**
If this is a new problem, I can put you in touch with the person who was having the problem for more details.

**Comment by misslivirose** [comment]
If you and/or the person who was getting disconnected can share the room/scene links, and details about the phone hardware, that can help us start to narrow down the possible source. Was it a consistent disconnection at a specific point of the entry flow, or did it happen irregularly?

**Comment by misslivirose** [comment]
We've seen similar behavior on iOS in groups of 15+ that I believe were related to memory use, I'm wondering if this could be the same root cause.

**Comment by blairmacintyre** [comment]
The disconnections happened after a few minutes, irregularly.  She always got in and could stay for a short while.

Room was a standard one I created on the fly: https://hubs.mozilla.com/zYF6ckg/decent-identical-exploration

I'll point Amber here and get her to give more details.

**Comment by brianpeiris** [comment]
Thanks for reporting these bugs @blairmacintyre!

**Comment by joshmarinacci** [comment]
Seems like something that's been fixed.

**Comment by misslivirose** [comment]
We have a lot of reports of issues with iOS that make it hard to narrow down, I think given the age of these it's fine to close and re-open if we see the same behavior now given the mediasoup changes.
