### ISSUE TITLE
Can't move pinned images on Quest

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1675]
**Description**
If you enter a room and there are pinned images or videos, you can't move them in pause mode on Quest (but works fine on PC VR)

**To Reproduce**
Create a room
Pin an image from image search
Reload
Try to move the image in paused mode on quest in oculus browser. Doesn't work.

**Hardware** 
Quest + Oculus Browser

**Additional context**
It looks like `state.held` is being set properly in the interaction system so the bug might be in setting up the constraints.

**Comment by johnshaughnessy** [comment]
I think this got fixed with https://github.com/mozilla/hubs/pull/1712 . Is that right @gfodor ?
