### ISSUE TITLE
Cannot hear avatars on iOS

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1685]
**Description**
Avatar voices are broken on iOS non-deterministically.

**To Reproduce**
1. Go to a room in Chrome
2. Go to the same room on Safari iOS
3. Enter the room on both devices
4. Check to see if you can hear the Chrome client from iOS. If so, refresh and try again. After one or two attempts, you will likely be unable to hear the chrome client.

**Expected behavior**
Voices should always work

**Hardware** 
iOS iPhone 7 + X
Chrome Windows

**Additional context**
I guess we should see if the latest version of Janus exhibits this problem or not.

**Comment by misslivirose** [comment]
#1692 - I'm ret-conning a P0 tag on this because it is almost certainly blocking iOS / Mac users and we observed it twice yesterday

**Comment by gfodor** [comment]
agree, hacky fix PRs in place, will push today. i suspect this as either always been the case, or broke with a recent safari update. the reason it may have always been the case is because for most scenarios it can either be fixed with a refresh, or it's obscured by the fact that it only affects a single avatar in a group.
