### ISSUE TITLE
Pen Erase Function

### ISSUE THREAD

**Issue by JollyGrin** [mozilla/hubs#1697]
**Why isn't there a pen erase tool?**

I've been trying to find a way to play go (ancient chinese board game) & the royal game of ur on mozilla hubs. My gameplan so far has been to use an image of a blank board and then use the pen tool to simulate stones/game pieces.

Yet the biggest obstacle is there is no erase function on the pen, meaning you can't remove stones/move pieces.

**Describe the solution you'd like**
The ability to erase with the pen tool. Not just undo (I want to delete much earlier pen strokes, while leaving the recent strokes)

**Comment by misslivirose** [comment]
#1730 implements erase menu
