### ISSUE TITLE
Non-xrCompatible context loss

### ISSUE THREAD

**Issue by avaer** [mozilla/hubs#1714]
**Description**
The main `webgl2` canvas does not appear to [set `xrCompatible` in the construction options](https://github.com/MozillaReality/aframe/blob/1d216f1e179150b5b6db53c85c93125197ccdac7/src/core/scene/a-scene.js#L589).

Therefore the context must be made `xrCompatible` at `new XRWebGLayer()` time.

This can incur context loss per [the spec](https://www.w3.org/TR/webxr/#contextcompatibility).

When context loss occurs, the rest of the rendering explodes because the code is not prepared to re-initialize:

![Capture 93](https://user-images.githubusercontent.com/6926057/64072047-f7038400-cc55-11e9-8618-e3d40434e8db.PNG)

**To Reproduce**
Run in a browser engine that causes context loss on a non-`xrCompatible` context constructing an `XRWebGLLayer` (I'm using Exokit).

Alternatively emulate this behavior by forcing context loss on `XRWebGLLayer` construction time:

```
gl.getExtension('WEBGL_lose_context').loseContext();
setTimeout(() => {
gl.getExtension('WEBGL_lose_context').restoreContext();
}, 1000);
```

The render loop will go into a THREE.js error avalanche, though it will appear to still work.

**Expected behavior**
Hubs either requests `xrCompatible` contexts, or gracefully re-initializes all resources on context loss when failing to do so.

**Screenshots**

**Hardware** 
Windows 10 / Exokit

**Additional context**

**Comment by brianpeiris** [comment]
This might be resolved now, since we've updated three.js and aframe with webxr support.

**Comment by joshmarinacci** [comment]
I'll mark as closed unless someone else can reproduce it.
