### ISSUE TITLE
Using transform controls on pinned objects doesn't persist

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1727]
**Description**
If you use the scale or rotate buttons on a pinned object, they work, but do not re-save the pinned object state when letting go.

**To Reproduce**
1. Pin an object
2. Scale or rotate it with the menu
3. Refresh
4. The rotation/scale has not been applied

**Expected behavior**
Rotate + scale should re-pin the object when completed (similar to moving it)

**Comment by misslivirose** [comment]
This is probably closer to a P1.5 (I was torn between P1/2 here) but losing media because it isn't re-pinned after changing one of these properties is definitely a broken effect and I would guess the fix is fairly straightforward?

**Comment by misslivirose** [comment]
@gfodor Did you happen to fix this already? I am not seeing this behavior right now

**Comment by gfodor** [comment]
nope, didn't try to fix this.

**Comment by johnshaughnessy** [comment]
Fixed in https://github.com/mozilla/hubs/pull/1757. Sorry for my slow.
