### ISSUE TITLE
Models from google poly fail to load from hubs.local / localhost

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1743]
**Description**
When running hubs locally, google poly models encounter a CORS error.

**To Reproduce**
Try to load poly model from the create menu from locally running hubs room.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-252)

**Comment by misslivirose** [comment]
@johnshaughnessy is this something we'd expect to have working locally (and is it still broken?), given the refactors to how we do local development / Hubs Cloud?

**Comment by joshmarinacci** [comment]
doesn't localhost stuff always break due to CORS issue? You should use a proxy server instead like ngrok.io?
