### ISSUE TITLE
Gear VR Controllers Not Working

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1746]
**Description**
User reported that Gear VR controllers were not working while using Hubs. 

**Hardware** 
 - Device: Gear VR with Samsung 7 Edge
 - Browser Samsung Internet Browser

**Comment by misslivirose** [comment]
Going to put this in P3 bucket until we can get a repo confirmation.

**Comment by misslivirose** [comment]
Going to resolve this as no-repro given the age of the bug, but we can re-open it if we get another report.
