### ISSUE TITLE
Improve Broken Media Link Appearance

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1747]
**Is your feature request related to a problem? Please describe.**
When you try to create a non-supported media type from a url (for example fbx), it creates a broken media image (see screenshot 1). This isn't very informative for users. 

**Describe the solution you'd like**
It would be nice if instead of a broken media link, when an unsupported file type is submitted via URL, if it appeared like a normal link to the page (see screenshot 2). This way, at least room members would know what media was being shared. 

**Describe alternatives you've considered**
It might be helpful to have a more informative error message saying "file type not supported" rather than displaying a broken link

**Additional context**

Screenshot 1 
<img width="1635" alt="Screen Shot 2019-09-10 at 11 53 16 AM" src="https://user-images.githubusercontent.com/6835324/64642134-816c8600-d3c2-11e9-8466-081498f55c29.png">

Screenshot 2 
<img width="1632" alt="Screen Shot 2019-09-10 at 11 57 51 AM" src="https://user-images.githubusercontent.com/6835324/64642167-90ebcf00-d3c2-11e9-8282-acd3e065e44b.png">

**Comment by misslivirose** [comment]
Suggestion from @robertlong - We can use this to surface more specific error messages about media; e.g. "cannot resolve", "unsupported format", etc.

**Comment by misslivirose** [comment]
Some other notes: 
* We don't always know why something is broken
* Some errors are recoverable
* We would like to provide more information when we _do_ know
* One way that we currently surface this is when YouTube is blocking us - we have hardcoded images in there

**Comment by misslivirose** [comment]
Tagging @mbransn as an FYI

**Comment by fernzharp** [comment]
@misslivirose @mbransn 
I've put together a few basic concepts based on what I've read here to get the ball rolling!

The text and Icons will be improved to fit the redesign and are placeholders at the moment.
I'd appreciate some feedback about what is/isn't working so far to shape this design further.
Speaking with @malqinneh about this, we also floated the idea of the image rotation always be front facing to the user to make it more noticeable/obvious.

[aahttps://hubs.mozilla.com/YQTS6Gc/nutritious-radiant-sphere](url)

![Screenshot (193).png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/64309dea-faa5-41e8-a176-19ccf47b6023)

**Comment by misslivirose** [comment]
Thanks @fernzharp! It was really cool to get to pop into that room and see them in the space itself - I think that adds a lot!

My preference at the moment is just the broken icon on its own, I think. Because we can't always tell what the object type is that has failed to download, I think the icon works best to convey any arbitrary media type (whereas the rectangular options with text imply a video or image). That would also be the quickest "v1" change, since we are already using a static image for the broken media. 

I wonder if any of the devs can chime in on whether we have statistics about media resolution failures - I'm not sure if we have a good sense of the frequency of recoverable vs. non-recoverable errors, but my suspicion is that the non-recoverable ones would be more frequent. Would having that information change whether we have the refresh button visible here?

**Comment by j-conrad** [comment]
The broken link icon is clean and clear. 👍

**Comment by fernzharp** [comment]
@j-conrad @misslivirose @mbransn @malqinneh 

Thanks for the feedback and assistance getting this up and running!

I've made a custom Broken link Icon in Figma which you can find here: 
[https://www.figma.com/file/Irqs61zk3NpTg0KIH9LXJq/Broken-media-link-appearance?node-id=0%3A1](url)

Again, please let me know if there's anything else you might like to see and I appreciate any feedback.

I made a couple of different versions, White with Black stroke and Plain Black just to see what they look like. 
I've also added them to the Hubs instance to see what they look like "in person". 
[https://hubs.mozilla.com/YQTS6Gc/nutritious-radiant-sphere](url)

![Screenshot (194).png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/3abc5c92-b41d-4d9f-aaa1-21b17a5aa97c)

**Comment by fernzharp** [comment]
Here's an Alt version with better proportions!

These images are rough png's just to help illustrate their appearance. The figma files are in the file linked above.

![BrokenLinkWhiteBlkStroke_v002(1).png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/1780763b-f805-44b7-a410-dfdd513b2a38)![BrokenLinkBlack_v002(1).png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/ffeefb66-c765-47be-a790-5ab44deb80f0)
![Screenshot (198).png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/b378d035-1625-4d67-ac51-cca64d8207c5)

**Comment by fernzharp** [comment]
Update:

I had a critique this morning of the work so far with Mustafa and Matt from the DPX-XD team.
The conversation gave me a few more things to think about and revise. 
Here is the work thus far: [Broken media link](https://www.figma.com/file/Irqs61zk3NpTg0KIH9LXJq/Broken-media-link-appearance?node-id=154%3A0)
I'm meeting with Matt again tomorrow to receive more feedback on my responses to the critique and what can be improved.
Revised icon design to be critiqued again Wednesday morning 21/11/20 PT.

**Comment by fernzharp** [comment]
@netpro2k, @misslivirose 
Hi Dom and Liv,
below is the broken media link image improvement I'm recommending. 
Please get back to me if you have any thoughts/concerns/feedback!

![Frame 8.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/55fe1e66-463d-4d65-9fa9-49c65c2d018f)![Frame 9.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/52c7686f-0cd5-4ce2-a762-b83ae4ce52b2)

**Comment by misslivirose** [comment]
Thanks @fernzharp! I think overall this looks really great. Nice job! 

The concern I have right now is that adding text to the broken image link means that we need to do one of two things: 

Option A: Ship this as an English-only image for the time being, with the text built-in to the image itself. This would be the quickest option to get this out since it would just be replacing the existing asset 

Option B: Re-work the component to include the image and text as a localized string. This would be a more complete option, but would take longer to implement

**Comment by fernzharp** [comment]
Thanks for the feedback, it's much appreciated @misslivirose!

From the explorations I've done I believe the text is important information for the user and helps to identify that it is a system message not just a piece of artwork.
Localization is definitely an important consideration and should be included so thanks for bringing that to the surface.

Would it be possible to do both options?
Shipping it now with the text built into the image would buy more time for Option B to be reworked before being implemented.
This would also allow for some community feedback.

**Comment by misslivirose** [comment]
Yes, I think that shipping this now with the text is a good short-term fix and we can include Option B work as part of other explorations into how we present in-room content!

**Comment by misslivirose** [comment]
@fernzharp - can we get a .png of the final design with the text to drop in and replace our existing image?

**Comment by mbransn** [comment]
@fernzharp making sure you've seen this. Can you get a PNG sent over?

**Comment by fernzharp** [comment]
@mbransn All sorted, sent through the image that day! Here's the link: [https://drive.google.com/file/d/1HTyxncpzqnX8cU3TOptkIC9XONKiD6Hv/view?usp=sharing](url)

**Comment by misslivirose** [comment]
Thanks Dan and Megan!

**Comment by mertakbal** [comment]
Is there a way to insert links to objects without having a preview. In that way we can upload our own preview images. the preview function is a nice thing but at the moment it is a hurdle to create otherwise would be functioning content.

**Comment by netpro2k** [comment]
Instead of creating a **Link** element, create an **Image** element and set the link href 
![image](https://user-images.githubusercontent.com/130735/115296595-00ce4980-a110-11eb-96d2-6a5ab0f4898f.png)
