### ISSUE TITLE
Pause mode 'Mute' on avatars doesn't work

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1753]
**Description**
As an administrator of a room, I was not able to mute other users in a room.

**To Reproduce**
1. In Hubs Commons today, there was a user with an open microphone
2. I am an administrator, and in pause mode, I tried to select a user and mute them, but the mute button didn't do anything

**Expected behavior**
The mute button should mute that user 

**Hardware** 
 - Device: Laptop
 - OS: Windows
 - Browser: Firefox

**Additional context**
Lars was also able to reproduce this. The workaround was to kick the user from the room, which isn't ideal.

**Comment by misslivirose** [comment]
This does not seem to repro when the person being muted it also an admin (they are muted correctly)

**Comment by johnshaughnessy** [comment]
Difficult to reproduce. I had it happen once but then accidentally kicked myself out of the room when paused in the debugger. I have not seen it happen again after several refreshes. One thing I noticed is that the button is made to be visible with the predicate `canOrWillIfCreator` whereas sending the mute action on the channel checks `can`:
`visible-if-permitted.js`:
``` 
    this.el.object3D.visible = this.el.sceneEl.systems.permissions.canOrWillIfCreator(this.data);
```
`scene-entry-manager.js`:
```
    this.scene.addEventListener("action_mute_client", ({ detail: { clientId } }) => {
      this.performConditionalSignIn(
        () => this.hubChannel.can("mute_users"),
        () => window.APP.hubChannel.mute(clientId),
        "mute-user"
      );
    });

```

The issue could of course be on the receiver's side as they verify the permissions of the sender.

**Comment by gfodor** [comment]
wrt the above -- we show the button if you canOrWillIfCreator, but the second block calls `performConditionalSignIn`, which will prompt them to sign in if they click it.

**Comment by gfodor** [comment]
i also can't reproduce. do we know anything about the device the user was on? it seems likely that this bug is one which would also prevent them from muting as well, and incidentally we noticed it because we tried to mute them remotely.

**Comment by misslivirose** [comment]
We don't have any more info - I'd be okay closing this and re-opening if we see it again
