### ISSUE TITLE
Tips are hidden by in-room chat.

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1754]
**Description**
When chat messages are in the log, tips are hidden.

**To Reproduce**
Click "Show tips" and see them pop up.
Send a chat message in the room.
Tips are now hidden by the chat message.

**Expected behavior**
Should see both.

**Hardware** 
Found this on desktop. I suspect it affects all platforms.

**Comment by misslivirose** [comment]
Going to resolve this as a subset of #1992 since we are going to move to a design that does not have the FTUE conflict with the chat messages.
