### ISSUE TITLE
Screensharing from Chrome on Linux cannot be viewed in Windows

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#1755]
Screensharing a window, desktop or tab from Chrome on Linux (Version 77) does not get displayed in Firefox on Windows. (possibly a codec issue related to #1533?).

**Comment by brianpeiris** [comment]
Sharing from Chrome on Linux to Chrome on Linux does work.

**Comment by netpro2k** [comment]
Tested in Chrome 79, this no longer seems to be an issue. Closing.
