### ISSUE TITLE
Twitch search doesn't display any results

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1759]
**Description**
Twitch doesn't show any results when searching in the media browser

**Expected behavior**
Search terms should work

**Hardware** 
Reproed 100% for everyone in standup on different devices

**Comment by gfodor** [comment]
The new API doesn't support search. The best we can do is show a list of the most active live streams. For now I'm going to disable the twitch tab.

https://dev.twitch.tv/docs/api/reference#get-streams
