### ISSUE TITLE
Improve Audio File Handling in Hubs

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1766]
**Description**
When you upload an audio file (for example, I used a .wav file) the current behavior is lacking and should be more usable in a way similar to how videos or gifs can be controlled. 

**Current Behavior**
1. Drag and drop an audio file (e.g. a wav file) into a Hubs room
2. Observe that the following behaviors occur: 
     - The 'loading object' model appears and stops animating
     - The audio plays one time
     - There is no way to replay or stop the audio
 
**Desired behavior**
1. Drag and drop an audio file into a Hubs room
2. Play and pause the audio file, which is represented in some way (a music note icon or 3D model? For a v1 I'm not too particular about this) 
3. Provide the ability to play the sound more than once when it is finished

This could also then be surfaced through Spoke as a separate asset type.

**Comment by brianpeiris** [comment]
Can we call this closed with #1887?

**Comment by misslivirose** [comment]
Yep!
