### ISSUE TITLE
Video playback broken on iOS

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1797]
**Description**
Video playback is not working when spawning youtube videos on iOS. My suspicion is it's related to iOS 13 update since I recently upgraded the device.

**To Reproduce**
Create a room and spawn a youtube video. Video spawn, but cannot be played.

**Expected behavior**
Video should play

**Hardware** 
iPhone 7, Safari, iOS 13

**Comment by gfodor** [comment]
https://github.com/mrdoob/three.js/issues/17757

**Comment by gfodor** [comment]
Root cause: https://bugs.webkit.org/show_bug.cgi?id=203435

For now, I am going to disable audio playback of videos on iOS.

**Comment by gfodor** [comment]
Actually that PR doesn't disable the audio, but stops attenuating it.

**Comment by robertlong** [comment]
@gfodor looks like the patch landed in Webkit. Maybe in Safari?

**Comment by gfodor** [comment]
yep we should test this

**Comment by InfiniteLee** [comment]
Looks like this is still broken, and was tracked/fixed in a new issue: https://bugs.webkit.org/show_bug.cgi?id=211394
Doesn't look like it will go out until 13.6 though.

blocks #2598
