### ISSUE TITLE
Can't see UI/scroll when selecting how to enter on mobile in landscape

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#180]
https://i.gyazo.com/3698b89a0987de93bb142a0ab1f6e5f3.png

On Pixel 2 (regular not XL), when loading the client this page cannot be scrolled when in landscape mode and the last option ("Enter on Daydream") cannot be seen. This also affects the following screen (can't select "ENTER NOW") without being in portrait mode.

**Comment by gfodor** [comment]
going to de-prioritize this from MVP, CSS should be augmented to support landscape phones eventually

**Comment by gfodor** [comment]
I believe Brian fixed all these issues up
