### ISSUE TITLE
Cosmos controllers not showing up

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#1800]
**Description**
Run hubs on a PC with a HTC Vive Cosmos.  The controllers do not appear.

**To Reproduce**

Run hubs on a PC with a HTC Vive Cosmos.  

**Expected behavior**

There should be controllers.

**Screenshots**

**Hardware** 
 - Device: Cosmos, GTX 1080
 - OS:  Window 10 (fully updated), Steam/Viveport, 
 - Browser: Firefox (release)

**Comment by blairmacintyre** [comment]
Ran html5gamepad.com while in spoke on Firefox.

Both controllers show up ("OpenVR Cosmos").
Both:
- grips aren't mapped
- axis 0 and 1 are the thumbstick
- displayId 1
- haptic actuators Yes
- Pose n/a (but I tried some webvr test that did get pose)
- vibration n/a
- mapping n/a

Left:  
- X and Y aren't mapped.
- press thumbstick does B1
- L1 is B2
- L2 (bigger one) is B0

Right:
- R2 (bigger one) is B0
- R1 is B4
- A is B1
- B is B2
- press thumbstick does B3

**Comment by InfiniteLee** [comment]
Just waiting to get (access to) one of these headsets and then we'll be able to sort this out.

**Comment by blairmacintyre** [comment]
@InfiniteLee hopefully one shows up ASAP;  I bought this to bring with me to UIST (flying this weekend) to demo hubs.  I don't want to rely on conference Wifi (so don't want to use Quest/Focus).  Worst case, I could bring a Samsung WindowsMR device, but (if it worked) this is so much better.

**Comment by gfodor** [comment]
@InfiniteLee this is fixed now right?

**Comment by gfodor** [comment]
confirmed fixed
