### ISSUE TITLE
Enhancement: Avoid using same icon for two different behaviors

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1802]
**Is your feature request related to a problem? Please describe.**
We should probably not have two identical icons with functionally different behavior

**Describe the solution you'd like**
One of these should be a different icon, or they should be combined into the media browser with a new tab for pasting your own link content. I think I prefer the first option.

![image](https://user-images.githubusercontent.com/4313320/66509671-5f7d2680-ea88-11e9-9a90-df6effcc2ecf.png)

See also: #1775

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-263)

**Comment by gfodor** [comment]
i agree -- the wand in the chatbox is primarily designed to be "spawn what i've typed into the chat box" -- tho probably its underused. the behavior of what to do when there was nothing in the chatbox was relatively undefined, and our v1 had that modal for the URL. I agree we should just have that pop the media browser. the media browser already has UX for pasting your own link via the button in the top right.

**Comment by gfodor** [comment]
(basically once we added the media browser I effectively forgot to wire up that event, previously the wand in the HUD showed the same modal.)
