### ISSUE TITLE
Desktop Audio Playback

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1805]
**Is your feature request related to a problem? Please describe.**
When sharing a screen or window from your computer, there is no way to enable audio sharing without use of an external program to feed output audio back in as an input.

**Describe the solution you'd like**
A way for users to toggle on if they'd like to share their desktop audio when broadcasting elements of their screen.

**Additional context**
There are two cases that this is a problem for:

When presenting a slide deck, we could work around this by ensuring that presenters are trained on a best practice that involves spawning any video or audio content as a separate piece of media. However, this is still a workaround at best, as it requires needing to pull out content that may already exist. We also need to account for the fact that any user could choose to pause the media, which could be disruptive to a structured presentation. This could be fixed with additional permission features. 

The second case is in trying to host live events that have a non-standard streaming platform. Events that are streamed on Facebook Live or a private conference website, for example, may only be possible to stream through screen sharing. However, the lack of audio makes this a difficult option to use successfully. Ideally, we would be able to enable this scenario through an audio option.

**Comment by gfodor** [comment]
I don't think there's anything we can do about this one, since my understanding is it's due to lack of browser support. We probably should have a happy path for people wrt the external program use though.

**Comment by arpu** [comment]
on windows this should work 
https://github.com/meetecho/janus-gateway/pull/1771

**Comment by gfodor** [comment]
wow, didn't know about this, we can def make this change!

**Comment by gfodor** [comment]
thanks @arpu !
