### ISSUE TITLE
Dedicated slide show support

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1806]
**Is your feature request related to a problem? Please describe.**
To present slides in Hubs, the two existing options are to screen or window share, or to put a PDF of the presentation in the room. Neither option easily allows the broadcasting of audio media from the presentation without a tool that re-broadcasts desktop audio through the microphone input. The screen share option is currently unstable due to the following bugs: 

#1788 
#1755 
#1533 

The PDF issue is that anyone in the room can change the active page of the PDF, instead of just the creator of the document. 

In both cases, presenting in VR becomes a challenge as well, because the user is likely going to need someone else to present on their behalf from a separate computer. While it may be out of scope for an initial implementation, design considerations for a VR-friendly presentation mechanic are welcomed as comments on this issue.

**Describe the solution you'd like**
Giving presentations should be easier for all users. This would include a few different strategies for making presentation-giving a better experience in Hubs, including or implementing one or more of the following components:

- Support for common web-based slide platforms. For example, if someone posts a link to a public Google Slides presentation, it could have the same pagers that are present on PDF files, but only available to the owner of the media so that they have sole control over how and when slides are advanced. 

- A controller object that a VR user could have connected to a _pagable_ media object that they own to advance slides without having to turn away from an audience

- Built-in audio support for media that is shared through a screen sharing mechanic. This is outlined as an individual consideration in #1805

- Better guidance (documentation, video) on how to use mixed-media for presentations, and encourage a "Hubs-first" approach to designing presentation content. This would likely work for power users who were willing to undergo a larger learning curve, but makes it more difficult to integrate existing content into a presentation-like environment. 

**Additional context**
This feedback has been present in the Feedback Duck survey by a few different users, as well as through Twitter. 

**Contributing**
Commentary related to design, requirements, and implementation is welcome on this issue. In particularly, we'd like to get more information about the following: 
- What are challenges that you face or observe with presenting in Hubs? 
- What kind of solution would you like to see? 

Coding contributions that relate to implementing a specific element of this issue are also welcome. Given the scope of possible fixes and improvements, we will likely ask that you create a new issue about the specific element that you'd like to work on, and we can assign it to you and work through implementation details for that specific component.

**Comment by gfodor** [comment]
wrt the PDF pager, we have a bit of a catch-22 -- sometimes you want anyone to page the object (for example, it's instructional information about a room) and sometimes you want it to be paged only by privileged users. if we wanted to support both of those use cases, i think we'd need to extend our UX fundamentally to support the ability for object creators to express per-object security policy (which seems like it could get pretty convoluted)

it *might* arguably be an improvement if we disallowed paging of non-pinned PDFs by anyone other than the creator. it's not a perfect solution (since, for example, this would mean that if you left the room, you'd need to re-spawn the PDF) but it would at least enable the use case to some degree.

**Comment by gfodor** [comment]
I guess there's an even more complex policy we could have that would be unintuitive but enable the use case a bit better:

- Unpinned PDFs can be paged by anyone
- Pinned PDFs can be paged by the creator if the creator is in the room
- If the creator is not in the room, PDFs can be paged by anyone

The tradeoff here would be a) this is unintuitive and b) in this variant, if the creator leaves accidentally, there's a window of opportunity for a malicious user to page the PDF.

**Comment by blairmacintyre** [comment]
I also just added this https://github.com/mozilla/hubs/issues/1975 while thinking about PDFs.

I would very much like to see better PDF support.  Some of the features could be set up to require "layout" by a user ahead of time, by coming into a room and setting up your presentation before others arrive.

**Comment by misslivirose** [comment]
Closing this issue in favor of improving our PDF support, which is captured in other issues
