### ISSUE TITLE
Avatar API is hit every time you enter/leave pause/freeze mode

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#1812]
Every time you enter or leave pause mode, the avatar api is hit for your current `avatarId` in order to retrieve your `avatarSrc` (the url for your current avatar). This is a side effect of `store.js` firing `statechanged` any time anything is updated, (in this case, `freeze-controller` calls `window.APP.store.update({ activity: { hasFoundFreeze: true } });` whenever pause mode is enabled. 

Expected behavior is that this API is not hit just when using pause functionality. 

Two relatively simple solutions:
* Add `avatarId` to `player-info` and check in `scene-entry-manager._setPlayerInfoFromProfile` to see if that has changed before calling `getAvatarSrc()`.
or
* Update `store.js` to include the previous state when firing `profilechanged` so that listeners can determine if the update applies to them or not.

**Comment by gfodor** [comment]
i'd also update all the call sites where we set these flags to check before updating store. i don't think we want to mess around with the `statechanged` contract, otherwise i'd suggest we do a diff before firing.
