### ISSUE TITLE
Audio on standalone HMDs is choppy and often difficult to understand

### ISSUE THREAD

**Issue by jvonitter** [mozilla/hubs#1818]
(transferring this over from https://github.com/MozillaReality/FirefoxReality/issues/1968 )

## Configuration

Firefox Reality version: 1.4.1
Firefox Reality build ID: 

Hardware: HTC Vive Focus Plus

## Steps to Reproduce

1. Enter a Hubs room with other users present and talking

## Current Behavior

The audio from the users sounds choppy/robotic.

## Expected Behavior

Smooth, clear audio.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by misslivirose** [comment]
Still happening - makes being in a Hubs room unusable so bumping up priority

**Comment by misslivirose** [comment]
This is being reported with other standalone headsets as well as the Vive Focus Plus.

**Comment by joshmarinacci** [comment]
Is this still reproducible?

**Comment by misslivirose** [comment]
Might be a duplicate of #2462, but worse on earlier hardware/versions? I think we can close this.
