### ISSUE TITLE
Clicking on Link in Windows MR freezes hubs

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#1819]
**Description**
Visiting a Hubs room (one of the UIST co-watching rooms).  Clicked on a link in a hubs room (to a twitch site, which is showing as a link(?) because the site isn't streaming, I guess?).  When Firefox opened the link, the hubs room froze, and will not start responding to motion or input (mouse or keyboard or HMD or wands) unless I reload the page. 

**To Reproduce**
1. Go to "north-ballroom-1" in the UIST discord server (https://hubs.mozilla.com/WyGunUY/north-ballroom-1?disableBatching=true)
2. Click on link to twitch stream on wall

**Expected behavior**
I would expect the room to remain working.

**Screenshots**

**Hardware** 
 - Device: Samsung Windows MR headset
 - OS: Windows 10
 - Browser:  Firefox release

**Comment by gfodor** [comment]
i think we probably need to disable opening links on non immersive browsers when using VR

**Comment by blairmacintyre** [comment]
Perhaps.  But this "the whole thing freezes" is "not good" either. 😭
