### ISSUE TITLE
Improve Audio Device Behavior

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1826]
**Is your feature request related to a problem? Please describe.**
The entry flow when joining a Hubs room requires clicking through several different modals. In many cases, clicking through does not require interaction with the modal content and it slows down the main entry flow. It is also a relatively non-standard place to surface audio behaviors, and there is no way to retroactively change devices once in a room without reloading.

**Describe the solution you'd like**
Audio device selection could be moved to a dedicated settings menu once you are in a room. We could implement logic that asks on the first time (perhaps similar to when we display an avatar / display name dialog as part of the entry flow) and only include audio device settings when we detect that the defaults have changed. 

**Additional context**
There is some design thinking that is required for this: 

* Displaying a new audio menu as part of the in-room experience instead of the lobby entry flow
* Where to move the option to mute microphone on entry 

We would also want to be cognizant that the menu is still discoverable and that this doesn't introduce new tension in getting audio working. It would be a good fix to test with community members before going live to get feedback on. 

**Contributions**
Feedback about this issue is welcome - please feel free to share your thoughts on the problem, proposed solution, or design details about the audio device flow in Hubs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-268)

**Comment by gfodor** [comment]
A common case to change your audio device is if you are changing to/from using a tethered headset, so if that happens i think we should prompt.

**Comment by keianhzo** [comment]
Related: https://github.com/mozilla/hubs/issues/828#issuecomment-788130242

**Comment by keianhzo** [comment]
@reganMoz I will need some DPX design for this task. Let me know if you need to meet for some more context.

**Comment by keianhzo** [comment]
This has been merged
