### ISSUE TITLE
Microphone is not detected in Safari

### ISSUE THREAD

**Issue by ducile** [mozilla/hubs#1830]
**Description**
When entering a Hubs room and selecting the input device, non of the devices would work (indicator would not indicate anything). Inside of the rooms the microphones are not working either. Tested on internal Macbook microphone, Bose QC 35 and AirPods. 

**To Reproduce**
1. Go to any Hubs room with Safari
2. Select one of your input devices and say something

**Expected behavior**
Microphone usage should work when selecting a suitable input device.

**Hardware** 
 - Device: Desktop
 - OS: macOS 10.14.6
 - Browser: Safari

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-270)

**Comment by gfodor** [comment]
I just tested on my macbook pro with safari 12.1.2 and macOS 10.14.6 and could not reproduce. Does your microphone look enabled in the address bar?

**Comment by ducile** [comment]
I'm on Safari 13.0.2. Not sure if that matters

**Comment by gfodor** [comment]
upgraded to safari 13, built in mic works as expected

**Comment by gfodor** [comment]
ok good to know. we'll have to investigate this further

**Comment by joshmarinacci** [comment]
Lets see if this is still an issue.
