### ISSUE TITLE
Spoke suddenly doesn't load sketchfab models

### ISSUE THREAD

**Issue by ducile** [mozilla/hubs#1831]
**Description**
The scene attached has multiple textures and models and they don't show up in the inspector anymore. 

**To Reproduce**
1. Import the attached file into Spoke.
2. View the inspector with all models and textures being black.

**Expected behavior**
Should show the models and textures correctly.

**Screenshots**
![Screenshot 2019-10-17 at 11 46 09 (2)](https://user-images.githubusercontent.com/16058129/67025274-bfe91500-f0d3-11e9-9dbb-b62073ee45ed.png)

**Hardware** 
 - Device: Desktop
 - OS: macOS 10.14.6
 - Browser: Firefox Nightly

**Additional context**
Very crucial for the upcoming conference! I can't update and republish the conference scenes if this doesn't work.

**Comment by ducile** [comment]
[north-ballroom.zip](https://github.com/mozilla/hubs/files/3740183/north-ballroom.zip)

**Comment by emclaren** [comment]
I opened on the same OS/browser, and reproduced this issue.  The following errors are in the console. 

<img width="1407" alt="Screen Shot 2019-10-17 at 9 19 27 AM" src="https://user-images.githubusercontent.com/6835324/67028261-dab18e80-f0bf-11e9-8df2-1a76cfaab794.png">
<img width="1395" alt="Screen Shot 2019-10-17 at 9 19 44 AM" src="https://user-images.githubusercontent.com/6835324/67028262-dab18e80-f0bf-11e9-98d6-91908a1cbc9d.png">
<img width="1399" alt="Screen Shot 2019-10-17 at 9 19 55 AM" src="https://user-images.githubusercontent.com/6835324/67028263-dab18e80-f0bf-11e9-9506-9f0b77b5f906.png">

**Comment by misslivirose** [comment]
We made a change that changes the rendering in the viewport a couple of days back - changing it back to 'Lit' from the default 'Unlit' fixes this. I'm going to close this and file an issue in Spoke's repo about making that more clear for folks
