### ISSUE TITLE
Reflections are incorrect in Hubs, okay in Spoke

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#1833]
Pictures:

How the reflections look in Spoke:
![Reflection_Spoke](https://user-images.githubusercontent.com/31968496/67059330-6e5d7c00-f10d-11e9-956c-68632992bbc6.PNG)

And how the reflections look in Hubs:
![Reflection_Hubs](https://user-images.githubusercontent.com/31968496/67059341-77e6e400-f10d-11e9-8d22-72f9b2c49bde.PNG)

Use this for reference:
https://sketchfab.com/3d-models/pbrchart-roughness-e608971b57314487b7b6120678502dce

**Comment by misslivirose** [comment]
Hey @j-conrad - is this still an issue? They look right to me now when I bring that model into Hubs directly, and when I publish from Spoke (on desktop at least)

**Comment by misslivirose** [comment]
Going to resolve this as no-repro and we can reopen if it happens again. Perhaps is device-specific
