### ISSUE TITLE
Live streams occasionally resolve but loading cube does not go away

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1839]
**Description**
In a room with a live stream video, occasionally the stream's loading cube will not disappear after the stream has loaded in. Instead, the video plays while the cube is in the middle of the screen. 

**To Reproduce**
Steps to reproduce the behavior (Inconsistent)
1. Go to a room with a Twitch or Youtube stream (I've seen this from both platforms)
2. Occasionally, the video will load but a loading cube will stay in the center of the video

**Expected behavior**
When the video loads, the loading cube goes away

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox Nightly

**Additional context**
I believe that @gfodor might have seen this with the YouTube video stream from last week's project call?

**Comment by misslivirose** [comment]
An additional data point for today: it turns out there may have been two videos stacked on top of one another in the scene. I will keep observing to see if this happens again, it might have just been that one loaded and one didn't

**Comment by gfodor** [comment]
hls.js was having trouble w streams, added a retry which seems to fix
