### ISSUE TITLE
Audio continues to play from a livestream after a Hubs room session ends

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1840]
**Description**
I had a Hubs room open in one tab and opened the same room in a second tab. As expected, my session ended in the first tab, and I successfully entered the room on the second tab. The scene had a Twitch live stream linked. Both tabs started playing audio from the Twitch stream, even though the first tab was an "ended" session. 

**To Reproduce**
1. Enter a room with a live stream
2. Open the room in a second tab and observe that the session in the first tab ends 
3. Observe that audio comes from both tabs

**Expected behavior**
Ended sessions no longer play audio

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox

**Comment by gfodor** [comment]
couldn't repro. this happens usually because an exception was thrown during the shutdown of the first tab, preventing the rest of the code running that cleans up the videos. mind seeing if you have any errors?

**Comment by misslivirose** [comment]
Yeah, will do! It was happening exclusively with the UIST streams so I wonder if it was possibly related to the other issue you fixed yesterday

**Comment by misslivirose** [comment]
Not reproing this and since we have #1801 tracking a similar issue I'll close this one. Can reopen if we see it again
