### ISSUE TITLE
UIST Reports of Audio working on Livestreams but no video

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1841]
**Description**
In the UIST rooms, livestreams are reported being frozen, but the audio plays.

**To Reproduce**
This doesn't repro 100% for everyone in rooms, and there are a number of stream issues that seem to be happening, but this one was reported by at least two separate users. They enter a Hubs room and the video doesn't play (it appears frozen) but audio works as expected.

**Expected behavior**
Audio and video stream both work in sync

**Hardware** 
 - Device: Desktop
 - OS: [e.g. Windows
 - Browser: Firefox

**Additional context**
At least 3 users have reported this

**Comment by gfodor** [comment]
fixed via hls retry
