### ISSUE TITLE
Users on Quest disappear before personal space bubble distance

### ISSUE THREAD

**Issue by ducile** [mozilla/hubs#1843]
**Description**
When an avatar moves towards you or you moving towards them they will disappear after reaching a certain "close" distance. Happens on the Quest.

**To Reproduce**
1. Go to Hubs with another person 
2. Move towards that person or make the person move toward you.

**Expected behavior**
The avatars should be visible up to the point where they intersect with you and go through you.

**Screenshots**
No screenshots available from the Quest.

**Hardware** 
 - Device: Oculus Quest
 - OS: -
 - Browser: Oculus Browser

**Comment by misslivirose** [comment]
Hey @ducile - are you referring to the personal space bubble? It's intentional that avatars you're too close to disappear, and I'd like to know if this is the regular instantiation of that or if it's happening in a different context.

**Comment by ducile** [comment]
Ah that makes sense to me. I was talking to Blair and we thought it might be a bug.

**Comment by blairmacintyre** [comment]
No, I don't think this is quite it:  I was dissappearing to @ducile before he did for me.  The distance was quite a bit further than the space bubble.

Perhaps the bug is that the distance is wrong on Quest.  Someone should just test.

**Comment by misslivirose** [comment]
I saw that with your specific avatar @blairmacintyre - I didn't see that with other robots. Your specific avatar had different parts that disappeared out of existence when I approached you.

**Comment by blairmacintyre** [comment]
I swtiched to the robot and I thought @ducile said it was also happening with the robot

**Comment by misslivirose** [comment]
Ah okay, good to know

**Comment by ducile** [comment]
It was happening in a similar distance, but I'm not sure if it is part of the personal space bubble.

**Comment by misslivirose** [comment]
According to @j-conrad the issue with the first case (custom meshes) is usually a result of the meshes on the avatars not being one single mesh and instead having separate pieces (it's happening on my own custom avatar mesh too)

**Comment by misslivirose** [comment]
The second one - we have some cases for the personal space bubble to improve the mechanics (Issues #1791 and #328)

**Comment by misslivirose** [comment]
Renaming this again because I realize now that there definitely are issues with Quest users specifically triggering the personal space bubble mechanic or disappearing before they should be. It's not happening with other users in VR, just Quest. Might be related to play space.

**Comment by gfodor** [comment]
I addressed a lot of issues here: https://github.com/mozilla/hubs/pull/2085

Not sure if this covers everything, so leaving this open in case we hit more issues.
