### ISSUE TITLE
Unable to create development environment

### ISSUE THREAD

**Issue by srigaurav1986** [mozilla/hubs#1861]
**Description**
I am unable to create local development environment with the details mentioned

**To Reproduce**

1. git clone https://github.com/mozilla/hubs.git
2. cd hubs
3. npm ci 

[                 .] \ extractTree: sill extract emojione@2.2.7 extracted to /home/imagine/hubs_collab/hubs/node_modules/emojione (10715ms)
npm ERR! err.code.match is not a function

**Expected behavior**
A clear and specific installation should happen as per the README instructions.

**Hardware** 
 - Device: AWS VM
 - OS:  Linux
- NPM version 6.9.0
- Node version 10.16.0

Detailed  NPM log is also attached for any further details: 
[2019-10-25T05_49_15_611Z-debug.log](https://github.com/mozilla/hubs/files/3771633/2019-10-25T05_49_15_611Z-debug.log)

Kindly suggest some solution, I want to setup locally and try. Thanks in advance!!!

**Comment by misslivirose** [comment]
We've made some fairly substantial changes to the developer setup experience - if you are still running into issues with this, we can re-open.
