### ISSUE TITLE
Squeezing the grips on Valve Index controllers doesn't grab objects

### ISSUE THREAD

**Issue by zfox23** [mozilla/hubs#1866]
**Description**
Squeezing the grips on Valve Index controllers doesn't grab objects.

**To Reproduce**
1. Enter a Hubs room in SteamVR mode.
2. Put on your Valve Index and turn on the Index controllers.
3. Verify that your hand controllers are tracked and are working from within Hubs - you should be able to move your hands and see them responding to grip grabs and trigger pulls.
4. Try to grab a grabbable object, such as the pen or a cloneable entity.
5. Notice that grabbing makes your hand animate properly and your controllers vibrate, but you can't pick up the thing from (4).

**Expected behavior**
I should be able to pick up a grabbable entity.

**Screenshots**
N/A

**Hardware** 
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox 70.0
 - SteamVR: Version 1.8.16 beta

**Additional context**
I'm not using any special/custom Index controller mappings.

**Comment by misslivirose** [comment]
Thanks for filing @zfox23! We'll take a look

**Comment by InfiniteLee** [comment]
Tested on Firefox 70 and Firefox Nightly with SteamVR 1.8.16 beta and non-beta on two different Windows 10 devices and am unable to reproduce. Can you verify your controllers are working correctly in any other VR applications?

**Comment by zfox23** [comment]
@InfiniteLee I just re-tested on Firefox 70.0 with SteamVR 1.8.17 beta and can't reproduce the issue in Hubs. Perhaps the stars were not aligned for me yesterday night. Thanks for looking into this, @misslivirose and @InfiniteLee!
