### ISSUE TITLE
Toggle to disable user interface elements & chat for non-admins in a room

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1867]
**Is your feature request related to a problem? Please describe.**
A community member requests a way of disabling the user interface elements & chat for visitors to a room.

**Describe the solution you'd like**
~~A hotkey that could turn off user interface elements & chat, or hides them behind a single icon~~.

Revised based on discussion below: A toggle that to turn off the UI for non-administrators in a room

**Comment by misslivirose** [comment]
Can you elaborate on this use case? It seems like there are two different ones here, one where the room owner wants to turn off the ability to use chat for visitors (and perhaps the HUD menu) and one where there is a hotkey that gives the _user_ the ability to hide the UI

**Comment by emclaren** [comment]
You're right - this does sound like two different use cases. This particular user wanted to disable the UI for visitors to the room, so they have no visual distractions. 

However, another community member more recently has expressed that they want a hotkey to disable/enable the UI so they can take better screencaptures (without turning on the camera).  Should I make a second issue so these are broken up into two enhancement requests?

**Comment by misslivirose** [comment]
@emclaren yes, let's make them two separate issues

**Comment by misslivirose** [comment]
I'm not convinced that we should ever have a mode that completely hides the HUD menu / UI elements. What is the use case here? Is it just to hide the elements they don't want users to have access to? Or is this scenario including the people/object lists, emojis, settings? 

There's some essential UI (e.g. sign in) behind some of those elements and the HUD has mute/unmute. I think that turning off chat could be a viable option for room admins, but hiding the rest of the UI feels like it might be something better saved for someone who wants to create their own client fork.

**Comment by misslivirose** [comment]
The ability to turn chat off is recorded in #1350 - at this time, I'm going to close this since we have #1918 to hide this on the client level. We may consider this in a design about how we handle the UI of different room permissions in the future, but I think for the time being, if someone wants to this drastically change the user experience by removing key functionality of the clients, a custom fork will be the endorsed path.
