### ISSUE TITLE
E-mail to log in never received

### ISSUE THREAD

**Issue by larsbergstrom** [mozilla/hubs#1875]
**Description**
I went to hubs.mozilla.com, entered a room, and selected to Choose a Scene. It requested that I enter an e-mail address to log in. I entered lars@lars.com, but never got an e-mail (checked Junk, too).

**Hardware** 
 - Device: Desktop
 - OS: Windows 10
 - Browser Firefox Developer Edition 71.0b5 (64-bit)

**Comment by gfodor** [comment]
confirmed. we've had at least one AWS SES outage before. will investigate

**Comment by gfodor** [comment]
actually, sorry, it is working for me when sending to gmail. is it broken for your mozilla email or just lars.com?

**Comment by larsbergstrom** [comment]
Curious - working now (@lars.com ). We can close, unless it's worth hanging onto. Are there any logs for that time? I opened the issue immediately after it happened, in case the timestamp helps.

**Comment by gfodor** [comment]
we don't have a log aggregation service, so i'd have to hop onto a few different machines to dig it up. i'll close for now, might take a closer look. i see a email send + SMTP success tick in our ops graphs at the relevant time, so I suspect this was lost on AWS's end for some reason :(

**Comment by gfodor** [comment]
thanks for reporting!
