### ISSUE TITLE
Changing scene to Hubs Room URL instead of Scene URL breaks room

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1877]
**Description**
When you change the scene using the "/scene" command, if you use a URL that links to a Hubs Room instead of a Scene by mistake, the room breaks and will no longer load. 

It throws an error that says "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**To Reproduce**
1. Go to Hubs room
2. type /scene <link to a Hubs room URL>
3. Refresh the page, it will no longer load

**Expected behaviour**
I expect the scene to not change, and when I refresh the scene it will remain as the last-used scene, or just a big empty room. I do not expect it to make the room URL break. 

**Additional context**
This error happened to Elgin while testing out scenes, but it has also been flagged by the community

**Comment by misslivirose** [comment]
Given that this fairly catastrophically impacts the room, I think it would be good to handle this in a way that doesn't break the room.

**Comment by emclaren** [comment]
Just realized as well - there is no way of removing a room that was broken like this from the list of favourites (since you need to open the room to favourite/unfavourite). My list is stuck looking like this
<img width="1587" alt="Screen Shot 2019-11-18 at 7 57 54 AM" src="https://user-images.githubusercontent.com/6835324/69068204-3a5dcb00-09d9-11ea-8732-29c650a1cc12.png">

**Comment by misslivirose** [comment]
@emclaren just opened a new issue for removing favorites (#1912 )

**Comment by misslivirose** [comment]
When we fix this, we should incorporate the suggestions in #811 as well in terms of general error messaging back to the user when a URL isn't going to work.
