### ISSUE TITLE
Investigate pinning behavior issues

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1891]
## **Pinning objects while not logged in has inconsistent behavior** 

**Description**
When not signed in, sometimes it is still possible to pin them. Other times, the object will not be pinned but the text will change from 'Pin' to 'Unpin' 

**To Reproduce**
Not 100%, but make sure you're signed out and try pinning objects, then closing out the modal dialog box. Sometimes the state of the button will change. 

**Expected behavior**
It always stays in unpinned state when a user is not logged in. 

**Screenshots**
Incoming

**Hardware** 
 - Device: observed on Quest and mobile phone 

 - Browser: observed on Oculus Browser and Firefox Preview for Android 

**Additional context**
I observed a photo that a non-logged in user "pinned" this way sticking around after they had left the room, but when I got into a similar state, the object didn't

**Comment by misslivirose** [comment]
![Screenshot_20191111-104820_Firefox Preview](https://user-images.githubusercontent.com/4313320/68605488-1a2a8b00-0472-11ea-9ce3-adc4470e3ba9.jpg)

Signed out account but I got into this state with an object after closing the modal dialogue to sign in

**Comment by brianpeiris** [comment]
Marshall did some work on improving the sign-in logic in this un-merged branch that we should probably finish and merge before digging into this pinning bug any further: https://github.com/mozilla/hubs/pull/1593

**Comment by misslivirose** [comment]
I think that this is a duplicate of #2233, so I'm going to resolve this as a duplicate and we can re-open if it turns out this behavior is different.
