### ISSUE TITLE
Make scene changes less jarring

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1894]
**Is your feature request related to a problem? Please describe.**
When you switch scenes in Hubs the room goes dark and then you are teleported to a new location. It can be very jarring when you don't expect it. Personally, I find it gives me VR sickness.

Requests for smoother scene changes have also come from the community. 

**Describe the solution you'd like**
It would be nice if the transition was a bit more gradual. For example, a chat message could say  the scene was going to be changed, and there could be a countdown like "scene changing in 3... 2... 1...."  Rather than going dark suddenly, the existing scene could fade out. 

A community member suggested the in between space could be a bit more like a "lobby" than a dark room. It could be a bit brighter, and have some sort of message while you wait that says "Scene is changing, please wait" , or "Username changed the scene, hold tight!" 

**Additional context**
We often change scenes during our meetups and I have to warn everyone when I'm about to do it. Without a warning people are interrupted mid-conversation, and if the new scene is too big or buggy, some attendees end up having to leave the room and come back. A bit of a warning would be really helpful for peoples user experience. 

Changing scenes frequently during an event is something that some members of our community are designing for.

**Comment by misslivirose** [comment]
Interstitial (maybe fade out to black) might a good intermediary, countdown

**Comment by gfodor** [comment]
scene transitions now fade to black
