### ISSUE TITLE
Open share dialog by default on newly created rooms

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1898]
**Is your feature request related to a problem? Please describe.**
When a room is created, it might improve co-presence if the 'Share' dialog is open by default. Right now, there is a prompt to open the 'Share' dialog, but it might be missed. If the share dialog was open by default, the flow of creating a room and sharing the link might be more prominent.

**Comment by gfodor** [comment]
i had considered doing this but it is a bit problematic on smaller screens, and isn't always what you want. the compromise i came up with is this tip we currently show when the room is empty:

![image](https://user-images.githubusercontent.com/220020/71853032-193b6180-308f-11ea-8812-71d25a5a74aa.png)

If we wanted to increase share discoverability at the cost of sometimes having it get in the way, we could auto-open the share dialog on empty rooms if the user has a bigger screen.

**Comment by misslivirose** [comment]
Closing this as it is now captured in the larger question of room entry and copresence
