### ISSUE TITLE
Custom logo squished in loading panel

### ISSUE THREAD

**Issue by antpb** [mozilla/hubs#1903]
**Is your feature request related to a problem? Please describe.**
I noticed that the width and height of the loading panel logo are defined. This causes issues when folks with, for instance, square logos use a custom logo. 

Here's where that is defined: https://github.com/mozilla/hubs/blob/fc21aedb5b1393aaf3aa6910df8dcf7b4255e88f/src/assets/stylesheets/loader.scss#L38-L43

**Describe the solution you'd like**
Maybe a `max-height:` here instead so various dimensions are respected.

If there is a max-height that can be agreed in this issue, I'd be happy to make a PR. :)

Here's what I'm doing it in my fork deployed at https://hubs.broken.place : 

https://github.com/antpb/hubs/blob/94778ae7fb51d5b1c84c030dce9f202cd749e4b6/src/assets/stylesheets/loader.scss#L38-L41

**Comment by antpb** [comment]
Also, not sure if this is feature request or bug so siding on feature request until I know for sure if this was intended. :)

**Comment by brianpeiris** [comment]
I'm working on related things right now and I'll include this fix. Thanks for the report!

**Comment by brianpeiris** [comment]
Fixed in #1916
