### ISSUE TITLE
Scene owned and pinned videos from Youtube don't load

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#1905]
**Description**
Scene owned and pinned videos from Youtube don't load. Pinned Youtube videos render the thumbnail, but they don't play. Scene owned videos just infinitely show the loading cube. In this example room, the scene owned Spoke landing page video plays just fine but the scene owned Firefox Reality Youtube video and the pinned Firefox Reality Youtube video do not.

**To Reproduce**
1. Open this room: https://hubs.mozilla.com/oLio9Rp/cheery-grounded-plane

**Hardware**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox 71.0b9

**Additional context**
Perhaps this is just an issue with the Firefox beta?

**Comment by robertlong** [comment]
It was that beta version. Updating to 71.0b10 did the trick

**Comment by arcdiablo** [comment]
hello , same isue is happening now ,  no videos of youtube playing on firefox or chrome
