### ISSUE TITLE
Links added to Spoke scene cannot be opened

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1906]
**Description**
When I create a room in Spoke with links to other sites, those sites cannot be opened in Hubs. 

**To Reproduce**
1. Create a room in Spoke with a link element
2. Publish the Spoke room to Hubs
3. Go to the Hubs room
4. Hover over the object, which loads correctly
Observe that there is no 'Open Link' button

**Expected behavior**
The link will show the 'Open Link' button 

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox

**Additional Information**
When I add this link directly into Hubs, the link has the button as expected.

**Comment by robertlong** [comment]
I think this is a duplicate of this issue: https://github.com/mozilla/hubs/issues/1782

**Comment by misslivirose** [comment]
Ah, indeed it is!
