### ISSUE TITLE
Move from node-sass to dart-sass

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#1913]
I think we could improve developer experience by moving from `node-sass` to `dart-sass`. `node-sass` works fine, but uses a native module using`node-gyp` that requires Python 2.7 to be installed. `node-dart` is a drop in replacement and doesn't have this dependency.

**Comment by joshmarinacci** [comment]
Has this been done?

**Comment by joshmarinacci** [comment]
Who should do this review?
