### ISSUE TITLE
Hotkey to hide/view user interface elements & chat 

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1918]
Is your feature request related to a problem? Please describe.
A community member requests a way of hiding/showing their own interface elements & chat in Hubs. They want to be able to take screen captures without the UI elements in the way (without broadcasting to the lobby).

Describe the solution you'd like
A hotkey that could turn off user interface elements & chat, or hides them behind a single icon.

Additional Info
As a community manager, I think this would be a useful feature as well. I've used camera mode for taking screenshots during our meetup, but attendees have expressed concern about chatting with me when I'm broadcasting to lobby.

**Comment by misslivirose** [comment]
@emclaren - can you elaborate on "have expressed concern about chatting with me when I'm broadcasting to lobby"?

There is always a lobby camera that shows what's in the room, regardless of whether or not someone is broadcasting - is it that they don't want to be the main focus of what is being broadcast in the lobby? Or something else?

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/2023
