### ISSUE TITLE
I could not hear Blair in the project call meeting

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1928]
**Description**
Blair joined the project call and I was not able to hear him (though I could hear everyone else in the room, and I could see his avatar)

**To Reproduce**
N/A

**Expected behavior**
I can always hear everyone in the room that I can see

**Hardware** 
 - Device: Laptop
 - OS: Windows
 - Browser: Firefox

**Additional context**
I'm on hotel-like wireless, so it's possible that I had an issue related to that.

**Comment by misslivirose** [comment]
Bumping this up to a P1 because we saw it in standup as well

**Comment by gfodor** [comment]
maybe related to https://bugzilla.mozilla.org/show_bug.cgi?id=1606886

**Comment by gfodor** [comment]
We haven't had broken avatar voices in a while now, I think my reconnect stuff mitigated some more issues. Closing for now.
