### ISSUE TITLE
Add Timeout Error if Room Fails to Load

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1933]
**Is your feature request related to a problem? Please describe.**
A community member was having trouble entering a Hubs scene, and reported waiting for a room to load for over 45 minutes. They were reluctant to refresh the page because the page still said “loading 150/152 objects”, and seemed to be increasing. It appears there were other issues preventing the scene from loading because once they refreshed it loaded quickly. When I flagged this issue to the team, Brian suggested it would be helpful to add a timeout.

**Describe the solution you'd like**
If a scene doesn't load after a certain amount of time (15 minutes?), a timeout error appears.

**Comment by gfodor** [comment]
We also don't actually properly handle errors in the environment loading.
If the environment loader throws an error, we silently wait for it forever.
(I believe other media if they fail will not block room entry.)

**Comment by misslivirose** [comment]
Fixed in #1977 and #1981
