### ISSUE TITLE
Button to clear all objects from a room

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1944]
**Is your feature request related to a problem? Please describe.**
It's somewhat time consuming to delete many objects in a room. It would be nice if there was an easier way to 
1) clear all objects in a room 
2) clear all unpinned objects in a room

**Describe the solution you'd like**
1) One solution I imagine would be if there was a button at the bottom of the object list that let you delete all the objects at once (or just the unpinned objects)

2) Alternatively,  if you hovered over the object icon in the object list it could give you the option to "unpin" an object, or to "trash" and object. This way you could go through the list removing objects much faster without having to go back and forth through between the object list & the delete button.

<img width="522" alt="Screen Shot 2019-11-26 at 1 35 45 PM" src="https://user-images.githubusercontent.com/6835324/69674638-be572900-1051-11ea-912a-f1ff41ff8dd5.png">
<img width="522" alt="Screen Shot 2019-11-26 at 1 35 45 PM" src="https://user-images.githubusercontent.com/6835324/69674885-4a695080-1052-11ea-8a22-80a49697f2aa.png">

**Additional context**
This feature was suggested by a community member. It is also one that I've thought would be handy when cleaning up the room between meetups, and when someone unknowingly brings in a large object which causes lag for everyone.

**Comment by misslivirose** [comment]
I think we had originally thought about having the pin and trash can iconography as part of the list here, which feels like it might be a good step in the right direction here. 

I'd imagine that we'd want to consider a delete button only for a room owner, and if we went that route, we probably wouldn't want to automatically delete pinned objects (or we have two separate buttons that differentiate the two cases).

**Comment by Shivansh2407** [comment]
Can you please help me to explain this so that I can solve it out

**Comment by gfodor** [comment]
I'm actually planning on jumping on this one this week, but thanks for offering to help!

**Comment by gfodor** [comment]
For reference, my suggestion for this feature is to add a next/previous button into the object viewer, and then automatically move to the next object (and wrap) if you delete the current one.

**Comment by simranaggarwal1999** [comment]
Hey! I want to work upon this issue.

**Comment by emclaren** [comment]
Hi @simranaggarwal1999 I think gfodor might already be working on this feature already.  Thanks for offering to help though

**Comment by gfodor** [comment]
New object removal UX from object menu facilitates cleanup now.
