### ISSUE TITLE
Scene page fails to load 3d scene with media

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1948]
**Description**
The scene page tries to load and show the scene in a 3d viewport. This fails if the scene has media in it.

**To Reproduce**
1. Go to https://hubs.mozilla.com/scenes/sZoPEtk
2. There's an error in the log during media loader that prevents the scene from loading.

**Expected behavior**
Scene should load

**Comment by misslivirose** [comment]
This is what I see when I view that scene (Firefox stable, desktop) 
![image](https://user-images.githubusercontent.com/4313320/69970287-fcd66300-14eb-11ea-98e2-e5c9bc0e89a9.png)

It loaded slowly, but ti did seem to load. Does this repro 100% for you? Is it a specific device/browser conversation?
