### ISSUE TITLE
Hubs / Email Address "Allow" List for Rooms

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1959]
**Is your feature request related to a problem? Please describe.**
Authentication for users right now is currently limited to Discord accounts. This option would use Hubs account / email verification and check users against a list set by the room owner before allowing them into a room, even if they have the link. 

**Describe the solution you'd like**
An easy way for room owners to set a list of Hubs accounts that are checked against before allowing users in.

**Describe alternatives you've considered**
Implementing other providers to verify / authenticate against, such as Firefox Accounts or Slack.

**Comment by gfodor** [comment]
I wrote up some thoughts about issues with using email addresses here:

https://discourse.mozilla.org/t/room-access-controls/51327/8

Invite links would mitigate the relevant concerns

**Comment by misslivirose** [comment]
Resolving this as we are going to take an invite-link approach in lieu of an email allow list. The email-specific option has been surfaced for Hubs Cloud.
