### ISSUE TITLE
Audio analyser undefined causes hubs to freeze

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1961]
**Description**

raven.js:381 Uncaught TypeError: Cannot read property 'volume' of null
    at n.tick (audio-feedback.js:185)
    at HTMLElement.value (a-scene.js:772)
    at HTMLElement.value (a-scene.js:822)
    at three.module.js:24920
    at r (three.module.js:7642)
    at a (raven.js:377)

```
const scale = getAudioFeedbackScale(this.el.object3D, this.camera, minScale, maxScale, this.analyser.volume);
````

**To Reproduce**
We saw this in our meetup when Dom became the doomatar: (link)

**Comment by brianpeiris** [comment]
I tried repro'ing with a doomatar that I created myself, but I wasn't able to. Not sure if there's something particular about @netpro2k's rendition of the avatar, but it would be good to test the fix in #1990 with that one when we get a chance.
