### ISSUE TITLE
Avatar selection button is clipped in certain cases

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1970]
**Description**
On my Razer laptop, on quackstack.net (a self hosted instance) I am unable to get through the entry flow since the avatar selection button is clipped off-screen: 

![image](https://user-images.githubusercontent.com/220020/70593986-dec7cd00-1b93-11ea-8704-c590ce606e3f.png)

It seems that whatever we are doing to set the canvas height is failing. In this scenario, there are no avatars in the system so perhaps that is a variable.

**Comment by brianpeiris** [comment]
I shipped #1969 yesterday, which should fix it if you update the stack

**Comment by misslivirose** [comment]
@gfodor - can you confirm if this was fixed with #1969 ?

**Comment by gfodor** [comment]
confirmed!
