### ISSUE TITLE
Add Edit Button to "My Scenes" in Scene Browser

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1972]
**Is your feature request related to a problem? Please describe.**
When you copy an avatar to your list of "my avatars", you can easily remix it by clicking on the edit button (pencil).

There is no equivalent button for remixing scenes. At the moment you have to go to the scene's landing page (e.g. https://hubs.mozilla.com/scenes/mD3UnWw/moz-atrium ) and click remix from there. 

**Describe the solution you'd like**
It would be great if there was a button from within the scene browser that would let you remix the scene, similar to what is available for avatars.

**Additional context**
Edit button to remix avatars in "my avatars". No corresponding button in "my scenes"

<img width="745" alt="Screen Shot 2019-12-12 at 4 00 10 PM" src="https://user-images.githubusercontent.com/6835324/70758645-8b22c400-1cf8-11ea-8750-caccac12ff46.png">
<img width="286" alt="Screen Shot 2019-12-12 at 3 59 54 PM" src="https://user-images.githubusercontent.com/6835324/70758648-8d851e00-1cf8-11ea-8b55-a97239032e0e.png">

**Comment by misslivirose** [comment]
Shipped with #1983
