### ISSUE TITLE
Quest devices show as mobile phones in user list

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1980]
**Description**
When users are in the Hubs room on Quest, the icon in the user list shows them being on mobile. 

**To Reproduce**
1. look at the user list when someone is in the room on Quest

**Screenshots**
Dan is in the  room on a Quest:
<img width="1242" alt="Screen Shot 2019-12-16 at 11 13 55 AM" src="https://user-images.githubusercontent.com/6835324/71025112-4497e580-20bb-11ea-8390-3b4fcbd1c0d9.png">

**Additional context**
Mentioned this bug in the UX channel on Discord - John responded it seems to be related to the fact that "mobile" is true in the "meta" for the user: https://github.com/mozilla/hubs//blob/feature%2Fuser-pref-screen/src/react-components/presence-list.js#L24

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/2013
