### ISSUE TITLE
Revamp room entry flow, including per-device considerations and overall user experience

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1982]
**Is your feature request related to a problem? Please describe.**
For the desktop use case, there are multiple screens that stand between the lobby experience and the Hubs room entry, including two audio screens, and for first time users, an avatar and display name screen. We should consider if there are alternative, more seamless entry options for each route in to Hubs, and make updates to the flow accordingly. 

**Describe the solution you'd like**
Fewer clicks and configurations to enter a room

**Additional context**
Needs UX design for each platform entry flow. Will incorporate #1826

**Comment by gfodor** [comment]
I'll just write a grab-bag of user flows here that need to be covered:

Desktop VR users:

- User has a desktop VR headset, but launches hubs from a non-compatible browser with WebXR. (Ideally, we onboard them to a WebXR compatible browser.)

- User has a desktop VR headset and wants to use it with this session.
  - Typically, this means that the user needs to adjust their OS audio output settings (if using steam) as well as set the microphone properly in Hubs for that session to the HMD microphone

- User has a desktop VR headset and wants to *not* use it this session, but used it in a previous session.
  - Typically this means switching their OS audio output settings + mic as above

- User wants to be sure when they enter on Desktop VR, that their audio settings are working properly before putting on the headset and getting out of their chair.

- User has a standalone HMD (Oculus Quest for example) and would like to use Hubs after loading the room on another device. (Ideally, they will not need to log in again. This is afforded by the current hub.link flow.)

- User loads Hubs on a phone, and wants to use Google Cardboard (and has the Google Cardboard app installed.)

- User loads Hubs and wants to participate in chat from the lobby for a long event.

- User loads Hubs and wants to see what is going on in the room before joining, to make sure it is something they're interested in.

- User loads Hubs and wants to be able to avoid entering the room until others have come to the page and are ready.

- User wants to be able to chat with people as they arrive, but not enter until *everyone* in their expected group arrives.

- User wants to help others diagnose basic issues before entering the room over chat.

**Comment by gfodor** [comment]
Also, my 2c is that the only way we can cover all these requirements but still reduce the entry flow steps would be to keep the general design of what we have but:

- Skip the audio step if the user is using the same mode (VR or non-VR) as last session

- Skip the audio step on Standalone VR. (This comes at a cost: it means users cannot adjust their volume properly before entering the room, and, due to a bug in Oculus Browser, will need to exit immersive mode to correct this later.)

- Add a audio setup item in the menu that lets you change your mic after you've entered the room.

Alternatively, if we wanted to make desktop VR mode much less discoverable we could remove it from the entry flow and put it somewhere else. I feel pretty strongly we should *not* do the usual thing WebXR sites do where you enter the room and *then* click an "Enter in VR" button because a) your audio settings will be all wrong and b) others in the room will have seen/heard you in the 2D context which probably wasn't your intent.

**Comment by misslivirose** [comment]
Additional consideration - should we do something more around sharing? (Copied from #1898)

>  When a room is created, it might improve co-presence if the 'Share' dialog is open by default. Right now, there is a prompt to open the 'Share' dialog, but it might be missed. If the share dialog was open by default, the flow of creating a room and sharing the link might be more prominent.

**Comment by robertlong** [comment]
I'm available to help with this

**Comment by gfodor** [comment]
Earlier versions this, the reason it was replaced:

- the new UX teaches the share button, if it automatically opened people
may be surprised/frustrated/confused that the link “disappeared” on
subsequent joins

- on small screens it takes up a lot of room

**Comment by gfodor** [comment]
*earlier versions did this

**Comment by emclaren** [comment]
Feedback on the UX a user reported related to their first time coming into Hubs that I wanted to add here. This was their feedback:

" I felt lost without my settings icon. I was lost thinking: Is my audio misconfigured? Did I miss some way to test it (ala virtual conference software's audio tests)? I don't know how often we will or will not toggle such a setting screen mid session, but I definitely missed it. "

If we do a revamp of the UI at some point, perhaps having settings more easily accessible could be helpful

**Comment by misslivirose** [comment]
Resolving this in favor of #2781 as that one is tracking the active work being done on the redesign.
