### ISSUE TITLE
Avatar selector performance

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#199]
The avatar selector spends a lot of time blocking the main thread while parsing each of the avatars. We ought to be able to re-use the bot mesh instead of re-parsing for each bot. Or perhaps use web workers to do the parsing.

**Comment by gfodor** [comment]
klee mentioned this bug too: "A bug I just remembered seeing: Avatar selector disappears after clicking on one of the arrows (like the whole little window goes black) on chrome. If I save my avatar selection and go back, it appears again, but only until I press one of the arrows again." Can file separately if you want.

**Comment by gfodor** [comment]
I would de-pri performance issues vs other must-get-done tasks for MVP (acknowledge this needs to be fixed ASAP though)

**Comment by gfodor** [comment]
New loading UX helps a bit
