### ISSUE TITLE
Colliders on duck don't scale when you resize duck

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#200]

**Comment by gfodor** [comment]
@InfiniteLee was this fixed?

**Comment by johnshaughnessy** [comment]
Will be fixed when this lands on master https://github.com/mozilla/hubs/pull/435

**Comment by robertlong** [comment]
@InfiniteLee is this fixed?

**Comment by johnshaughnessy** [comment]
We can close this because I don't think we care if the duck-bill cylinder doesn't scale, but the other colliders do.
