### ISSUE TITLE
Not able to setup backend to start contribution to hubs locally

### ISSUE THREAD

**Issue by SparshKat** [mozilla/hubs#2000]
Hi, i wanted to contribute to this repository (as i like the project and so that i could use this for GOSC '20 as well). I have started the client server locally but am unable to start Janus server correctly. Could someone point out how to do that (commands for mac would be appreciated).

**Comment by gfodor** [comment]
Hey @SparshKat thanks for offering to contribute! To work on the client code, you don't actually need to run your own janus server. (In fact, those of us who work on hubs at Mozilla rarely do so.) The only scenario where running a local janus server is necessary is if you are actually working on Janus itself, such as working on configuration or the SFU plugin. If you use `npm run start` in our client repos, then you will be connected to a shared development server run by Mozilla. Is there a reason you'd like to run Janus directly?

**Comment by SparshKat** [comment]
First of all thanks for the clarification @gfodor, and no i dont want to work on the Janus server directly. Instead i just thought working with the backend would make testing a few backend linked things fast. But it's absolutely fine ! Thank you so much for the clarification again :)
