### ISSUE TITLE
Cardboard Mode no more available

### ISSUE THREAD

**Issue by sgenou** [mozilla/hubs#2001]
**Description**
I can no more use the cardboard mode on my MotoG5S Plus, it was working some days ago.

**To Reproduce**
1. Launch a hub
2. Click "Enter Room"
3. Accept avatar
4. Click "Enter Now"
5. There was an intermediate option to choose CardBoard, no more available.

**Expected behavior**
I can enter my room in cardboard mode

**Screenshots**

**Hardware** 
 - Moto G5S PLUS
 - OS: Android 8.1.0
 - Chrome 79.0.3945...

**Additional context**
It was working some days ago, i don't understand why it stopped working...

**Comment by brianpeiris** [comment]
Thanks for the report. Chrome recently released support for WebXR and we haven't migrated yet. This should be fixed once we do.

**Comment by philtweir** [comment]
Not ideal but, in the meantime in Chrome on Android, enabling #enable-experimental-web-platform-features and temporarily disabling all WebXR flags in chrome://flags (then restarting) seems to bring back the Cardboard option in Hubs (tested with a OnePlus 5, Android 9 and Chrome 80.0)

**Comment by kwadroke** [comment]
Disabling WebXR didn't work for me.
I thought that v80 was supposed to drop WebVR?

**Comment by philtweir** [comment]
I'd had to enable WebVR also, which is disabled by default, following this comment: https://github.com/GoogleChrome/OriginTrials/issues/48 if that helps?

**Comment by kwadroke** [comment]
WebVR is not an option for in chrome://flags, even after enabling #enable-experimental-web-platform-features

**Comment by brianpeiris** [comment]
Just to update this -- we now partially support WebXR, and it looks like Chrome on Android does indeed allow you to enter with a Cardboard device without requiring any manual flag flipping. However, our cardboard support is still quite limited. The only thing you can do is teleport around.

**Comment by joshmarinacci** [comment]
Can we close this bug now that we support WebXR?

**Comment by brianpeiris** [comment]
I'd be okay with closing this bug if we open another issue for improving cardboard support.

**Comment by joshmarinacci** [comment]
https://github.com/mozilla/hubs/issues/2657
