### ISSUE TITLE
Cannot record video with sound

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2024]
**Description**
When I try to record a video with the in-game camera tool, it gets stuck with 1 second left:
![image](https://user-images.githubusercontent.com/4072106/72114606-04620680-32f9-11ea-9bdf-4901ae369697.png)

I get the following error:
```
NotSupportedError: An audio track cannot be recorded: video/webm; codecs=vp8 indicates an unsupported codec
```
And when I click the "x" button, my client freezes on the next error:
```
TypeError: this.videoRecorder._free is not a functioncamera-tool.js:475:13
    stopRecording camera-tool.js:475
    cancelSnapping camera-tool.js:320
    init camera-tool.js:223
    dispatchEvent three.module.js:172
    tick button-systems.js:21
    tick hubs-systems.js:66
    Aframe 2
    value self-hosted:869
    ko three.module.js:24920
    r three.module.js:7642
    a raven.js:377
```

**To Reproduce**
1. Spawn camera
2. Toggle the sound recording "on" (hover over the camera while in freeze mode to show the option).
3. Try to take a video.

**Expected behavior**
Create a video with sound

**Screenshots**

**Hardware** 
Error found in Firefox desktop on Linux.
Chrome works ok.

**Comment by emclaren** [comment]
Happens for me in Firefox nightly on desktop. Works fine in Chrome.

**Comment by evmorov** [comment]
For FF >= 71 you should use `video/webm;codecs=vp8,opus`
