### ISSUE TITLE
Resolution drops in Freifox when you navigate away from Hubs tab

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2025]
**Description**
I believe this commit ( https://github.com/mozilla/hubs/commit/38c32099c159df094e99ff5bab019d9fbc5ff517 ), which is meant to reduce the resolution if the FPS is too low, is also causing the resolution to drop if you look at another browser tab for too long.

**To Reproduce**
1. Open Hubs Room
2. Look at another tab
3. Wait 
4. Come back and it's blurry

**Expected behavior**
I would expect the quality to remain the same as when I left, or eventually increase again when I navigate back to the scene

**Screenshots**

<img width="768" alt="Screen Shot 2020-01-09 at 4 51 02 PM" src="https://user-images.githubusercontent.com/6835324/72117503-e0a3be00-3302-11ea-939f-baa54be93ebf.png">

**Hardware** 
Mac, Firefox. Issue does not occur on Chrome

**Additional information**
I often navigate to other tabs while using Firefox and encounter this frequently.

**Comment by brianpeiris** [comment]
Oof, nice catch. The auto-pixel-ratio mechanism is almost certainly the cause.
