### ISSUE TITLE
Hubs can share your screen when you wanted it to share your camera

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#2031]
**Description**
If you share your screen, then stop, then share your camera, you'll see your camera, but other users will see your screen (!)

Tested on Firefox Windows

**Comment by misslivirose** [comment]
I wasn't able to repro this (Windows, Firefox, using the same computer but two separate windows) - I will try again with a separate device but would also be good to know if you still see this @gfodor

**Comment by gfodor** [comment]
I can't reproduce this either. 

Scary, but lets close for now.

👻
