### ISSUE TITLE
Videos don't play on some iPads

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2035]
**Description**
A visitor to the Monday Project Meeting in Hubs reported they couldn't see the video stream. They only a still image from the video, and there was no audio (but other audio in the room works fine.)

Brian was able to repro this. He suspects the video just never started autoplaying. Tapping the video does not reveal the controls to play the video, it might be that there is detection code that thinks the iPad is a desktop (due to iPadOS) and is not doing the usual user gesture logic that we have for iOS

**To Reproduce**
Open a hubs room with a video on an iPad

**Expected behavior**
Video should play like on other devices.

**Hardware** 
Brain repro on 10.5-inch iPad Pro, running iPadOS 13.3

**Additional context**
Does not happen on an iPad mini

**Comment by Giorat** [comment]
Hey @emclaren do you have a room link as an example with a video embedded in?

**Comment by emclaren** [comment]
Hi @Giorat - the room I had a demo of this in previously is no longer available, but it was just a normal room with a youtube link that I copied and pasted in. It seems to work on small ipads (ipad mini), but not this one (10.5 inch)

**Comment by davegoopot** [comment]
I've got the same problem and have set up a demo room: https://hubs.mozilla.com/oVaYQ4D/iphone-video

The embedded video is https://vimeo.com/303878477

The video plays fine, including in just the lobby, on Firefox running on Android.

The video doesn't play at all, lobby or after entering, on all iOS Safari versions I've tried.

**Comment by takahirox** [comment]
I confirmed that on my iPad (iPadOS15) Safari, videos plays but they are very slow, and no audio.

What I did
1. Enter the same room from iPadOS15 Safari, iOS 15 Safari, and Windows Chrome
2. Spawn YouTube video and mp4 video from the Chrome
3. Videos and audios from the are fine on iOS 15 Safari and Windows Chrome. But the videos are very slow on iPadOS 15 Safari and no audio from them.
