### ISSUE TITLE
Support Pico devices

### ISSUE THREAD

**Issue by jvonitter** [mozilla/hubs#2041]
**Is your feature request related to a problem? Please describe.**
Currently when visiting Hubs on a Pico device, it looks like I'm using a Quest instead.

**Describe the solution you'd like**
Controller models and strings should show Pico versions.

**Additional context**
FxR support for Pico devices (G2, G3 and Neo 2) is planned for Feb 21 release.

**Comment by bluemarvin** [comment]
Currently we use the Oculus strings for controllers so the PicoVR version will work in hubs. The string we were planning to use were for Neo 2: `Pico Neo 2 (Right)` `Pico Neo 2 (LEFT)`
And for G2: `Pico G2 Controller`

**Comment by johnshaughnessy** [comment]
We can add support for those device ID's in hubs and interpret their inputs the same way we do for other controllers (quest controllers or 3DOF controllers, depending on what they are capable of). We will be able to add better support when we get access to those devices, so if we can get some in mountain view or at our upcoming meeting in Berlin that would help a lot!

**Comment by johnshaughnessy** [comment]
Nevermind - they work the same as the existing quest and go controllers, which means we just needed to look for the new device names.
