### ISSUE TITLE
Images in the `/link` dial in page are squished in custom Hubs instance

### ISSUE THREAD

**Issue by antpb** [mozilla/hubs#2047]
**Description**
I had a change in my fork that could be useful upstream. In the dial in panel, the logo image has a defined `height` property. This causes it to be squished if the logo is of a different aspect ratio.

**To Reproduce**
1. Go to home page of custom Hub
2. Click on "I have a room code" 
2. See logo with defined height and width.

**Expected behavior**
It should maybe lose the height property. I created a PR here: https://github.com/mozilla/hubs/pull/2046/files

**Screenshots**
![Screen Shot 2020-01-15 at 5 41 38 PM](https://user-images.githubusercontent.com/8985705/72481126-23600d00-37bf-11ea-85d1-e5a9b7258495.png)

**Comment by misslivirose** [comment]
Fixed with #2046
