### ISSUE TITLE
Preferences text fields won't accept more than one input value

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#2050]
**Description**
In the Hubs Preferences page, the text fields will not accept more than one input value. Typing a value exits the field before you can type another. So, for example, trying to type '30' into the Rotation Snap field only lets you type '3'. The only way to get a '30' in there is to paste it.

**To Reproduce**
1. Open Hubs Preferences page
2. Click on the field for Rotation Snap, for example
3. Try to type '30'
4. You can only ever type the first character and you cannot 'insert' your cursor anywhere.

**Expected behavior**
I should be able to type normally in those fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/31968496/72484034-d9bff400-37b7-11ea-993c-ac139c6c4447.png)

**Hardware** 
 - Device: Desktop or HMD
 - OS: Windows
 - Browser: Firefox or Firefox Reality

**Additional context**
The sliders probably don't need the precision of multiple decimal places, which make selecting integer values nearly impossible. Fixing that would ostensibly eliminate this bug.

**Comment by gfodor** [comment]
@johnshaughnessy mind taking this one?
