### ISSUE TITLE
When Room is embedded on my website room gets stuck on the choose device screen

### ISSUE THREAD

**Issue by Goliath3** [mozilla/hubs#2055]
I embedded a Mozilla Hub Room on my website and when trying to load the room the room got stuck on the choose input screen. I tried several times and kept having the same problem.

**Comment by gfodor** [comment]
Hey there, would you mind sharing a link to the room? You can DM me on our discord or email me at gfodor@mozilla.com if it's private.

**Comment by misslivirose** [comment]
I'm going to resolve this as a dupe of #2238 - multiple reports of this and I'm wondering if it's related to the issues with devices in general (e.g. what we see in #2240)
