### ISSUE TITLE
Spawning into some scenes cause you to float high in the air mysteriously.

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2061]
*EDIT: The initial description of this bug suggests that this is a problem related to spawn points, but this does not seem to be the case. See comment below for updated info! https://github.com/mozilla/hubs/issues/2061#issuecomment-577489805*

**Description**
When you spawn into certain scenes, you start very high above the floor and continue to float upwards. 
I think what's happening is that there is no spawn point and we do not put your character in a reasonable place
Why you float upwards after that is somewhat a mystery to me, but I suspect it's related
I suspect this fix is as simple as, "if there's no spawn points in the scene, spawn somewhere near the origin"

**To Reproduce**
The bug can be experienced in this scene: https://hubs.mozilla.com/scenes/KGMJzEN

**Expected behavior**
We should choose a "reasonable-seeming" spawn location (Either some position on the nav mesh or some place near the origin), and we should ensure your character controller state is set appropriately (e.g. put you in fly mode if there is no nav mesh).

**Screenshots**
![image](https://user-images.githubusercontent.com/4072106/72657633-7242a980-395b-11ea-917e-6161315327d2.png)

**Hardware** 
Any, as far as I can tell.

**Additional context**
It's definitely possible the bug is more complicated, but I'm pretty sure I caused this regression and we need to add a default spawn routine for when there are no spawn points in the scene.

**Comment by johnshaughnessy** [comment]
In this room:
https://hubs.mozilla.com/mkcW2H5/spirited-comfortable-plaza
there is 1 spawn point but the same bug occurs unless I turn disable `snapToNavMesh` on the waypoint. Now I think that this bug will manifest if:
- `snapToNavMesh` is enabled on the waypoint chosen as your spawn point
- there are no spawn points in the scene
- there are only occupiable spawn points in the scene, and they are all occupied.

**Comment by johnshaughnessy** [comment]
OK - I had the wrong idea about this above ^^

The problem does not have to do with waypoints/spawn points (although I still want to double-check that scenes with NO spawn points behave OK).

The problem is that we are not detecting when there is NO nav mesh in the scene. When there is NO nav mesh in the scene, we should pop you into fly mode. Instead of that, we are still trying to navigate along the (non-existent) nav mesh, and the reason you fly upwards is because we are adding the player height to the (erroneous) Y value of your position: https://github.com/mozilla/hubs/blob/d0f53221e4612e28dd95679bf43be23cea7cd326/src/systems/character-controller-system.js#L349

**Comment by emclaren** [comment]
came across this issue in another recently uploaded scene

https://hubs.mozilla.com/scenes/KZYE2b9
