### ISSUE TITLE
Physics shapes scaled incorrectly when cloned from a scaled parent.

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2063]
**Description**
See https://github.com/mozilla/hubs/pull/2053#issuecomment-576002965 for description and repro steps.

**Screenshots**
![image](https://user-images.githubusercontent.com/4072106/72681622-41a56180-3a7a-11ea-91d6-ef8cda597f3f.png)
From left to right:
A model and its hull at default size.
A clone of the model to its left, scaled down after cloning.
A clone of the model to its left. Note the hull is too small.
A clone of the left-most model, scaled up after cloning.
A clone of the model to its left. Note the hull is too big.

**Hardware** 
Desktop Chrome / Firefox

**Comment by InfiniteLee** [comment]
This should be fixed now (as of the worker update).
