### ISSUE TITLE
Fog doesn't leave a room when user changes scenes

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2073]
**Description**
Fog from a scene stays in a room when a scene is changed. You have to refresh the room for the fog to disappear

**To Reproduce**
1. Go to https://hubs.mozilla.com/scenes/x3WqmKX
2. Click on create a room with this scene
3. Change the scene

**Expected behavior**
I expect the fog to go away

**Screenshots**
![Screen Shot 2020-01-22 at 11 10 00 AM](https://user-images.githubusercontent.com/6835324/72926228-f2289500-3d08-11ea-90e4-06ebf9f9d09c.png)
![Screen Shot 2020-01-22 at 11 12 37 AM](https://user-images.githubusercontent.com/6835324/72926237-f3f25880-3d08-11ea-9ec2-c6e60b9ae166.png)

**Hardware** 
 - Device: Mac, Firefox nightly & Chrome

**Additional context**

**Comment by Utopiah** [comment]
Maybe `AFRAME.scenes[0].removeAttribute("fog")` before https://github.com/mozilla/hubs/blob/master/src/gltf-component-mappings.js#L22 could to the trick

**Comment by rawnsley** [comment]
Fixed by upstream pull request https://github.com/MozillaReality/aframe/pull/28

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 85.0.2 and Chrome 88.0.4324.182 on Windows 10 and Firefox Release 86.0 and Chrome 88.0.4324.192 on Mac OS Catalina 10.15.7.
Now, when changing the scene from Foggy Lake to another one the fog does not remain in the scene.
