### ISSUE TITLE
Youtube Videos throw CORS error

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2082]
**Description**
Some youtube videos that previously worked in Hubs now throw a CORS error

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.youtube.com/. (Reason: CORS header “Access-Control-Allow-Origin” missing)."

**To Reproduce**
1.  Visit this room https://hubs.mozilla.com/mU6dytZ/crafty-authentic-place/
2. The video  https://youtu.be/YEU_FIly708 , doesn't load as a video

**Expected behavior**
I expect it to load the video.

**Screenshots**
![Screen Shot 2020-01-23 at 1 45 30 PM](https://user-images.githubusercontent.com/6835324/73026660-afd58580-3de6-11ea-85d7-57521204c85d.png)

**Hardware** 
Mac Desktop Chrome and FireFox

**Additional context**
Also happening to several other videos, for example https://www.youtube.com/watch?v=6M1oopfKnLw&feature=youtu.be

**Comment by emclaren** [comment]
Possibly related to this: https://github.com/ytdl-org/youtube-dl/issues/23819 
Might work again soon

**Comment by gfodor** [comment]
This seems fixed, can you confirm @emclaren (the existing room still has the cached thumbnail, but if you add a query variable to make a new URL, it works)

**Comment by emclaren** [comment]
Seems to be working again! Closing issue
