### ISSUE TITLE
Camera in Chrome can sometimes fail

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#2083]
**Description**
After introducing the changes from https://github.com/mozilla/hubs/pull/2077 to fix the camera in Firefox, Chrome now occasionally fails to take a video complaining about the file data being empty.

**To Reproduce**
Try using the camera in Chrome. Seems a 3s clip usually the first time during a session can fail.

**Comment by SparshKat** [comment]
It's working perfectly for me on chrome using a mac!

**Comment by joshmarinacci** [comment]
Do we still have reports on this or can we close?

**Comment by misslivirose** [comment]
Closing due to no additional repros - we can re-open if we have more concrete repro steps available
