### ISSUE TITLE
When you grab an emoji, everything freezes for the person grabbing it

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [mozilla/hubs#2089]
**Description**
Sometimes, when you grab an emoji and play with it for a bit of time, the scene will freeze

**To Reproduce**
1. Enter any scene
2. Grab an emoji
3. Shake it until everything freezes and you have to restart the browser

**Expected behavior**
Emojis not freezing the browser

**Hardware**
 - Device: Oculus Quest, HTC Vive Pro
 - OS: Oculus (Android), Windows 10
 - Oculus Browser, Firefox

**Additional context**
Seems to happen more with some emojis than others (the face with tears and laughing is one that always breaks it)

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/commit/2a0307ad9269ae9ddc622fd9db8d4457c05e3796
