### ISSUE TITLE
specify zones that control avatar volume

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#2106]
**Is your feature request related to a problem? Please describe.**
Different social uses of hubs require different audio characteristics for avatar-avatar audio.
- Meetings would benefit from less distance falloff.
- Talks or lectures would benefit from having the speaker be loud and have their voice carry, while the audience may carry much less and be quieter.  An area for "questions" would benefit from speaker-like audio

**Describe the solution you'd like**
In Spoke, the audio characteristics of media can be controlled.  The volume range, the falloff, the maximum distance.

If regions in space could be specified (perhaps as 3D volumes, perhaps as spheres or cubes around a point), and the avatar audio characteristics of avatars in that area could be changed from the defaults, the cases above (and others) could be easily controlled.

So, a "conference room" area in a scene used for meetings could have less distance falloff within that region.
A stage in a presentation space, and some raised "question" areas, could have a larger volume and carry farther.
The audience area could carry much less and perhaps have lower default volume.

A "private chat room" could limit audio to just within that room.

**Describe alternatives you've considered**
More complex solutions, like physically based audio simulation, improve the quality of the audio, but don't solve the issues presented above.
In-hubs controls would have to be redone each time they are desired, making them error prone.  In contrast, building rooms for certain purposes may signify use, and in-world media elements can give instructions as to the setup.

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-293)

**Comment by mohoman** [comment]
I would also like to see this implemented as well.
For instance, it would be cool to set up an office with 3 separate rooms within the office. Each room is its own little zone. Only people within the room can hear each other and speak with each other. It's a "Private Room".
It wouldn't necessarily need to be walled of. It could also be a circle painted on the floor around a few chairs as well. And that would be a private zone for private conversations.
If you are familiar with Virbela, they do this and it is very effective.

**Comment by camelgod** [comment]
Isnt this implemented now?

**Comment by matthewbcool** [comment]
As @camelgod pointed our, today in Hubs we have Audio Zones which serve as a potential solution through design: https://hubs.mozilla.com/labs/creating-speaker-stages-and-manipulating-audio-in-hubs/

Audio Zones allow us to define stages for speakers, private chat areas and customize areas of the map to fit different audio needs.
