### ISSUE TITLE
Unable to spawn text into the room

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2138]
**Description**
When I type something into the text box and try to spawn the text into a room, I get a broken image instead of the text.

**To Reproduce**
1. Create and enter a room
2. Type some text into the textbox
3. Try to spawn it in the world with the magic wand

**Expected behavior**
The generated image with the text content spawns

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox

**Additional context**
Does not consistently repro - seems to only be when there is a word that ends with a colon

Examples: 
- "Test" works
- "Test : Test" works
- "test:test: does not work
- "test: test" does not work

**Comment by gfodor** [comment]
looks like this is triggering our URL detection: it thinks the text is a URL you want to spawn.
