### ISSUE TITLE
Closed Rooms that are favorited/starred still show up on main Hubs page

### ISSUE THREAD

**Issue by kwadroke** [mozilla/hubs#2148]
**Description**
Unable to unstar/unfavorate a room if closed.

**To Reproduce**
If you favorite/star a room, it will show up on the main https://hubs.mozilla.com page.
If you close the room later, it does not get removed from the main page.

**Expected behavior**
Favorited/Starred room should be removed from main page.

**Hardware** Doesn't matter the OS/Hardware
 - Device: Desktop
 - OS: Linux
 - Browser: Firefox

**Additional context**
This is more a user experience issue.

**Comment by Charlesc22** [comment]
I'm also encountering this bug.

**Comment by CrimsonZA** [comment]
I know this has been an issue for a while , I forgot to unstar a room before deleting even though I was conscious of it moments before I still closed the room 🤦‍♀️
