### ISSUE TITLE
Come up with a better way to sync state between react and aframe

### ISSUE THREAD

**Issue by netpro2k** [mozilla/hubs#215]
Currently all the toggles in the UI (mute, freeze, and space bubble) do their communication beteeen react and aframe by emitting events on the scene element and useing aframe statechange listeners and state to transfer the current state back and forth. This is pretty ugly and we should come up with a better way. This probably gets easier if/when we have react mounting the aframe scene.

**Comment by gfodor** [comment]
Created https://github.com/mozilla/hubs/issues/347 which blocks
