### ISSUE TITLE
ICE negotiation fails in Firefox nightly on Mac OS. 

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2153]
**Description**
ICE negotiation fails in Firefox nightly on Mac OS, as reported by Josh and Jofish:
```
ICE failed, add a TURN server and see about:webrtc for more details
ICE failure detected. Reconnecting in 10s. console.js:35
```

**Hardware** 
 - Device: Laptop
 - OS: Mac OS
 - Browser : Firefox Nightly

When Josh switched to the Safari web browser, his problem was fixed. (Jofish switched to a different laptop before trying this.)

**Additional context**
I have not tried reproducing the problem myself yet.

**Comment by InfiniteLee** [comment]
I appear to also be running into this but on Windows 10.

**Comment by johnshaughnessy** [comment]
Tracking https://bugzilla.mozilla.org/show_bug.cgi?id=1606886

**Comment by gfodor** [comment]
This was not reproducable for me. If one of you can reproduce it, that would be helpful to unblock the bug.

**Comment by InfiniteLee** [comment]
Fixed by https://github.com/meetecho/janus-gateway/commit/435a1e91f1661e99d7a78c7953adfeedd95b66e3
