### ISSUE TITLE
Android Firefox Webcam Feature not Working

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2162]
**Description**
If you share your webcam from an android device, it appears as a loading object on desktop computers. 

**To Reproduce**
1. Open Hubs on Android phone
2. Share your webcam
3. Open the hubs room on a desktop computer
4. See the loading object

**Expected behavior**
I expect to see the webcam, or to not have that option available on an mobile device

**Screenshots**
<img width="698" alt="Screen Shot 2020-02-26 at 11 02 34 AM" src="https://user-images.githubusercontent.com/6835324/75378667-f6584d00-5888-11ea-83cc-32565f028183.png">

**Hardware** 
Android, firefox

**Additional context**
Bug was surfaced by community member during office hours

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-310)

**Comment by takahirox** [comment]
I couldn't reproduce the problem on Android Firefox and Windows Chrome. I guess somehow the problem has been resolved?

Let me close this issue so far. Please reopen if anyone can still encounter the problem.
