### ISSUE TITLE
Can't use emoji on the Oculus Go

### ISSUE THREAD

**Issue by larsbergstrom** [mozilla/hubs#2173]
**Description**
You can bring up the emoji on the Oculus Go in Oculus Browser, but it seems impossible to actually grab and wave them.

**To Reproduce**
1. Enter a room on oculus browser on the go
2. Hold down the touchpad/directional pad to see the emoji
3. Try using the trigger to grab
4. Hand goes right through the emoji while grabbing and never grasps

**Expected behavior**
Hand grabs emoji

**Hardware** 
 - Device: Oculus Go
 - OS: [e.g. Windows, iOS, Linux]
 - Browser Oculus Browser

**Comment by InfiniteLee** [comment]
Hubs on any 3-dof device does not allow you grab objects via your "hand", only the cursor.

**Comment by larsbergstrom** [comment]
Aha! So I "laser" the emoji? Will try - thanks!
