### ISSUE TITLE
gfodor leave handoff items

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#2177]
Following is work for hubs cloud that may or may not be completed before leave - sorry for the rough doc, these should likely be captured better.

Blocking IEEEVR:
- currently we have an account POST api which handles idempotently creating accounts when passed email, name pairs. Currently, there is not a clean way to handle name changes. My intention was to create a PATCH api (which similar to the POST api allows multi-request/response, see the code) that would perform an update to the name (identity record) if the account for a specified email exists. If it doesn’t, it 404s. The use case would be for the registration list of known email, name pairs to first be submitted to the POST to create any missing accounts, then the PATCH to correct any name changes since the last sync.

Hubs cloud work:
- currently,  new aws deploys are in the SES sandbox, which limits outgoing email to verified addresses. To get out of the sandbox requires writing a message to AWS detailing the use case. Part of the requirements to get out is to have a policy around bounces and complaints. Here are the todo items:
  - already done: bounces now will be forwarded to the admin account email
  - we need to add a email blacklist in the database, and admin console tools to add/remove email addresses from the blacklist
  - then, we should add docs describing how to get out of the sandbox. Specifically, docs that include the exact form letter to send (I have a draft I will post here below) as well as an explanation on how to properly blacklist any complaint or bounced email addresses.

- in addition to the issue with the sandbox, we should provide step-by-step instructions on setting up SMTP email with gmail, send grid, and mail chimp (legal already approved this, it would not be considered an endorsement by Mozilla)

- there is a reticulum PR approved to add a cron job to keep the database alive when there are connected users. Before rolling this out to the polycosm stable channels, it’s critical a full integration test be done on the unstable channel deployed stack to ensure the database properly pauses when nobody is connected to a room, and when the room page times out. (If the code has a bug, database costs could explode.) secondarily important would be to test the positive case to ensure the database remains up when people are active in a room

**Comment by misslivirose** [comment]
Going to close this given the timing - we can re-open specific pieces as needed. I know some of this work is already done.
