### ISSUE TITLE
Spawning on quest at wrong height

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2189]
**Description**
Sometimes when we spawn on quest, the user is not at the correct height. Possibly also not in the correct place. (I ended up underground unexpectedly in the default "river" scene.)

**To Reproduce**
Unreliably - enter a scene in quest.

**Expected behavior**
Depending on the flags for the waypoint, we should either be matching the eye-height exactly or snapping to the floor underneath the waypoint using the user's reported sittingToStandingMatrix.

**Screenshots**

**Hardware** 
- Quest. Oculus Browser. (Possibly FxR - have not tested.)

**Comment by saitogroup** [comment]
Same. I'm getting spawned below the ground, even though my spawn point is at the origin.

**Comment by saitogroup** [comment]
Works fine in the broswer.
