### ISSUE TITLE
Hide all UI temporarily in client, for streaming

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#2194]
**Is your feature request related to a problem? Please describe.**
We want to stream a hubs room on Twitch.  
We don't want a bunch of UI on the stream.  This is for desktop only.
It might be good to also tie this to a "fullscreen" mode, so that we could just stream the whole display.

**Describe the solution you'd like**
A button to show/hide the UI.  Perhaps when hidden there is a tiny button in a corner of the screen to switch back to the full UI.

**Describe alternatives you've considered**
We've thought about only sharing the middle part of the window.  But that might make it hard to plan and lay out content.

**Comment by gfodor** [comment]
It exists, hit tilde :)
