### ISSUE TITLE
In Firefox (stable), loading a Hubs room stalls on a white screen for 20 seconds or so.

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#2206]
**Description**
Only on Firefox stable, loading any Hubs room (saved or newly made) stalls on a plain white screen for around 20 seconds or so. The logs don't help much.

**To Reproduce**
1. Use Firefox stable
2. go to hubs.mozilla.com
3. make a room
4. White screen hangs for quite a while before any indication of loading.

**Expected behavior**
Room should exhibit 'loading...' much sooner

**Hardware** 
 - Device: desktop
 - OS: Windows 10
 - Browser: Firefox (stable)

**Additional context**
This does not occur on Chrome or Edge browsers. At least one other developer confirmed this bug on their machine. This has been happening for the past several days (noticed on 3/6/2020), but not before that.

**Comment by brianpeiris** [comment]
Can you try this with a fresh firefox profile? Run `firefox.exe -profilemanager`

**Comment by gfodor** [comment]
this sounds like the problem where getVRDisplays in a recent firefox release now takes a long time if the VR headset is not set up right, and we delay the first UI draw until that resolves. i did a quick pass at refactoring our code to do it sooner but it was more involved than 10 minutes so i bailed.

if this is the problem, as a workaround, you can click on the vr headset icon in the address bar and deny permissions until the next session you need a headset.

**Comment by j-conrad** [comment]
Just to confirm, that suggestion works-- denying permission for VR devices.

**Comment by johnshaughnessy** [comment]
Partially fixed in https://github.com/mozilla/hubs/pull/2244

**Comment by johnshaughnessy** [comment]
Bug in Firefox tracked here : https://bugzilla.mozilla.org/show_bug.cgi?id=1623487

**Comment by johnshaughnessy** [comment]
Fixed on the hubs side in #2244
