### ISSUE TITLE
Have deleted Hubs rooms to not display in the list anymore

### ISSUE THREAD

**Issue by youngchief-btw** [mozilla/hubs#2214]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like a way to have my deleted Hubs rooms, not show on my list of rooms anymore

**Describe alternatives you've considered**
I've considered running my own client and server instances and edit the code for it

**Additional context**
N/A

**Comment by misslivirose** [comment]
Is this the 'Favorites' list? Curious if this is a dupe of #2148

**Comment by youngchief-btw** [comment]
Haven't seen if it happens with non-favs, could be the issue

**Comment by youngchief-btw** [comment]
Just confirmed it, It was a 'Favorites' only issue

**Comment by misslivirose** [comment]
Thanks for confirming! Going to resolve this as a duplicate of #2148 - we appreciate you filing this!
