### ISSUE TITLE
Disallow flying

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2215]
**Is your feature request related to a problem? Please describe.**
On certain hubs-cloud instances, it may not be appropriate to allow users to fly around the environment.

**Describe the solution you'd like**
Disallow flying on a per-server or per-room basis.

**Describe alternatives you've considered**
None

**Additional context**
Noted by tiagoperes from the IEEE-VR discord

**Comment by misslivirose** [comment]
Fixed with https://github.com/mozilla/reticulum/pull/343
