### ISSUE TITLE
Allow delayed mic permissions and configuration

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2216]
**Is your feature request related to a problem? Please describe.**
if we don't give initial browser permission to use the microphone, then once we're inside the room and try to give it, we won't be able to.

**Describe the solution you'd like**
Be able to configure audio and grant permissions after room entry

**Describe alternatives you've considered**
None

**Additional context**
 Noted by tiagoperes from the IEEE-VR discord

**Comment by misslivirose** [comment]
Consolidating audio issues - going to close this as a duplicate of #1826
