### ISSUE TITLE
Player height at spawn time is surprisingly tall

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2225]
**Description**
When spawning into the room on quest, `getCurrentPlayerHeight` reports something like 2.6 meters even though my vr devices `sittingToStandingMatrix` reports something much less than this. This means that the avatar rig and the avatar pov are unusually far apart or out of sync for reasons unknown.

**To Reproduce**
Spawn into a room on quest. 
Print `getCurrentPlayerHeight` from inside the waypoint travel code.

**Expected behavior**
The distance between the avatar rig and avatar pov node should be something like your sittingToStandingMatrix (larger in world space if your scale is not 1). 

Quest

**Additional context**
~Contributed to this bug: https://github.com/mozilla/hubs/issues/2189~
~The reason https://github.com/mozilla/hubs/pull/2226 fixes the bug above is because if the player height is at the (surprising) value of 2.6 meters, we have to use that surprising value. However, it should not be this far apart so we need to figure out why that is happening.~

Edit: This issue and https://github.com/mozilla/hubs/issues/2189 are both fixed by #2226 . We were spawning into the spawn point without taking the vr display data into account. Delaying `moveToSpawnPoint` fixes the issue.

**Comment by johnshaughnessy** [comment]
The unusually tall height seems to be related to moving the `viewing-camera` in the `scene-preview-camera-system` without also moving the `viewing-rig`. If I make sure that the `viewing-rig` always moves when the `viewing-camera` moves (as in https://github.com/mozilla/hubs/commit/120234bbf2dd0c277b55fc9e8ef5ef767d06bb20 ), then the reported height at the time we travelByWaypoint is `0`, which makes sense because there is no height offset in `hub.html` between `#viewing-rig` and `#viewing-camera`. 
This is also wrong, because by the time we are spawning we want to be using the `sittingToStandingTransform` from the vr display in some way. We need to `moveToSpawnPoint` _after_ the vr display takes over the viewing camera.

**Comment by johnshaughnessy** [comment]
Keeping the `viewing-rig` in sync with the `viewing-camera` in the `scene-preview-camera-system` is unnecessary. Delaying `moveToSpawnPoint` until after vr is enabled on the renderer seems to fix the issue altogether. Fixed in this commit: https://github.com/mozilla/hubs/pull/2226/commits/e5f6342819548435fc8998593771dd415f071b90

**Comment by brianpeiris** [comment]
Can we call this closed?

**Comment by johnshaughnessy** [comment]
Yes
