### ISSUE TITLE
Movement controls using keyboard in Macbook

### ISSUE THREAD

**Issue by BHUVAN007** [mozilla/hubs#2234]
**Description**
I have tried Mozilla hubs both in windows and Mac machines. Moving the avatar in windows works fine, but it does not work in Macbook. Is there a way to avoid it?

**Comment by misslivirose** [comment]
I don't believe that we've had a repro of this issue and we have folks who have been using Macbooks successfully with Hubs. BHUVAN007 - can you provide more information about the make of your Macbook and the browser you're using when you observe that this isn't working for you?

**Comment by vincentfretin** [comment]
May it be related to #2397?

**Comment by BHUVAN007** [comment]
Hi Liv,

I had this issue in the beginning of IEEE VR in March. It's all sorted now.
Thanks :)

Cheers,
Bhuvan
