### ISSUE TITLE
gyroscope look on android doesn't work

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#224]
On 2d android, can't look around with gyroscope.

**Comment by robertlong** [comment]
@johnshaughnessy saw this working on his phone. We need to figure out how to reproduce this.

**Comment by gfodor** [comment]
it doesn't work for me on my phone, i can maybe take a look later

**Comment by gfodor** [comment]
updated https://github.com/mozilla/hubs/issues/84

this bug is now irrelevant
