### ISSUE TITLE
Simple audio cutoff with distance

### ISSUE THREAD

**Issue by broehl** [mozilla/hubs#2259]
Currently, all the audio is sent to all the players and is spatialized locally. That uses up a lot of bandwidth (both on the server and the clients) and a lot of CPU, and limits the number of users who can be in a room at once.

On the server side, you could do a simple distance check and not send the audio beyond a certain distance. The check could be very lightweight (use the squared distance, or even just the Manhattan distance).

**Comment by misslivirose** [comment]
Avatar / media audio falloff is set by scene owners in Spoke - we've also had conversations about toggling mono/stereo as a client preference. I think there are three separate issues here, some of which are already addressed: 

1) Spatialized audio isn't always desirable 
2) Audio considerations and effects on room capacity 
3) The falloff of audio should be configurable (can currently be done in Spoke) and the default right now may not be the idea default for performance

**Comment by misslivirose** [comment]
Consolidating audio feedback under #1853 and resolving this as a separate issue - copied over text & feedback. Thank you!
