### ISSUE TITLE
Favourites remain when their room is closed

### ISSUE THREAD

**Issue by broehl** [mozilla/hubs#2270]
How to replicate:

Create a room
Mark is as a favourite
Close the room

The room is still in your favourites list, but no longer exists. There's no way to remove it from your favourites list.

**Comment by kwadroke** [comment]
Duplicate of #2148

**Comment by misslivirose** [comment]
Thanks for filing! I'm going to resolve since it's a dupe, but we appreciate the filing, @broehl!
