### ISSUE TITLE
Speaker mode for conferences

### ISSUE THREAD

**Issue by broehl** [mozilla/hubs#2272]
At conferences, it's not unusual to have someone making an announcement or giving a presentation. However, with distance attenuation, people will have trouble hearing the speaker if others are talking close by.

It would be nice if a room owner could set someone as a speaker, which would cause their audio to not be attenuated by distance. It would still be spatialized in terms of stereo panning, it would just be at a constant volume through the space. You could have multiple people set to be speakers, so you could have a panel discussion in front of an audience.

People would still be able to chat with people near them, but everyone would hear the speaker.

**Comment by gfodor** [comment]
Quick riff on this - promoted users could be given this option. To avoid hud clutter, we could slot it into the mic button, either as a third mode or as a drop down similar to screen sharing/camera sharing.

**Comment by misslivirose** [comment]
Consolidating audio feedback under #1853 and resolving this as a separate issue - copied over text & feedback. Thank you for the suggestion!
