### ISSUE TITLE
Fix issues with dead websockets

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#228]
Websocket connections can get into a state where they do not see replies to keepalive events. The result of this is that there are no join events to others in the room, and this results in no avatar spawning. To help diagnose:

- We should add an `onerror` handler for the websocket so we can get better logging
- We should consider other ways to detect failure and reconnect even if the `readystate` is open (for example, perhaps we should reconnect if a sufficient number of sequential keepalives fail)
- We should consider if a `libwebsocket` upgrade is a good idea or not (unlikely to be related but perhaps could close out other potential websocket issues that could result in the same symptoms.)

**Comment by gfodor** [comment]
Bumped libwebsocket to 2.4.2 in the hopes of increased stability 🤷‍♂️

**Comment by cvan** [comment]
I haven't dug in to the socket code, but you might find some useful patterns in a real-time library (WebRTC Data Channels w/ WebSockets upgrade + fallback) we worked on a few years back, [`socketpeer`](https://hacks.mozilla.org/2015/04/peering-through-the-webrtc-fog-with-socketpeer/).

here's the [client/browser code](https://github.com/cvan/socketpeer/blob/master/browser/index.js) and [server code](https://github.com/cvan/socketpeer/blob/master/server/index.js).

**Comment by gfodor** [comment]
I think maybe the libwebsockets upgrade fixed this issue, we have yet to see it again.
