### ISSUE TITLE
Spoke: all models suddenly return 404

### ISSUE THREAD

**Issue by MrMebelMan** [mozilla/hubs#2282]
**Description**
I've made a scene with a plenty of sketchfab & google models, but yesterday they all suddenly started returning 404, so I'm now unable to edit the scene. When I add new models, they are also broken. I also receive a different error message each time I refresh the project.

**To Reproduce**
Open any scene in Spoke. My specific project id is: 35HoeMf

**Expected behavior**
Models shoud be loading correctly.

**Screenshots**
![Selection_893](https://user-images.githubusercontent.com/15896005/77581928-dbf0ae00-6ede-11ea-81b0-0b91e438a71c.png)

![Selection_894](https://user-images.githubusercontent.com/15896005/77582523-d2b41100-6edf-11ea-97b4-af0982cee3d3.png)

 - Device: Desktop
 - OS: NixOS
 - Browser: Firefox, Chromium

**Comment by gfodor** [comment]
It looks like we are being rate limited on sketchfab's API. We're looking into it. Thanks!

**Comment by MrMebelMan** [comment]
Thanks for the fast response :heart:
