### ISSUE TITLE
pdf grows in size when navigated too quickly

### ISSUE THREAD

**Issue by clavis-magna** [mozilla/hubs#2284]
**Description**
A pdf spawned in hubs can keep increasing in size when moving between pages. As far as I can gather, there is an animation on the  pdf object that expands and then immediately shrinks back to the original size when you click forward or back. If you click too fast (or something lags), it does not have time return to its original size before the  expand animation kicks in, so it gets bigger and stays bigger (and repeat)

**To Reproduce**

1. spawn a multi page pdf in a room
2. navigate using the forward and back buttons - clicking these buttons quickly as if to get to a certain page quickly
3. pdf object will scale up with each click
4. I am located in Australia so perhaps lag is involved in reproducibility?

**Expected behavior**
pdf should not scale up, the click animation should return to the object to its original scale before allowing a new navigation click .

**Hardware** 
 - Desktop
 - windows
 - Firefox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-326)

**Comment by InfiniteLee** [comment]
Afaict, this only occurs with pinned pdfs, as only when they are pinned do they have the scaling animation.
I've seen this issue occur with other things that utilize our animation library to scale things. What is likely happening is that if you navigate very quickly, the previous animation gets cancelled/interrupted and causes the "original" scale to get messed up. 

As a workaround, you can unpin the pdf first.

The shorter/longer term fix after that is to avoid using this animation at all for pdfs, even if they are pinned. This is probably just a behavior we attach to all pinned objects when you change them in any way.

**Comment by misslivirose** [comment]
This is a common setup for presentations within events / talks - so it's probably being hit more frequently than other types of pinning behaviors

**Comment by gfodor** [comment]
The animation is an indication to the user that the object's pinned state has been changed. I agree from the other ticket disabling the animation for pagination seems right. Not clear if we should disable it on other analogous cases like when the user pauses a pinned video.

**Comment by mauriciomartinez-itesm** [comment]
I believe that in order to use this on a more professional level / as a teaching aide it should be adressed. It does only work with pinned pdfs, but can get really annoying when trying to have a class in VR and the presentations keeps growing.

**Comment by misslivirose** [comment]
Per the report in #3961, this may also happen with video media

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using the latest releases of Firefox and Chrome on Windows 10.
Now, a pinned PDF file is no longer enlarged if the next/previous page button is clicked repeatedly.
