### ISSUE TITLE
Moderated Microphone options

### ISSUE THREAD

**Issue by phillipbhan** [mozilla/hubs#2294]
Is there or can there be an option to mute the whole world's microphone all at once or automatically upon entry? I am wanting to create a live music performance without any microphones getting in the way. Another option I thought of triggering events based on entering a certain area where it is a no mic zone.

Thank you.

**Comment by misslivirose** [comment]
Consolidating audio feedback under #1853 and resolving this as a separate issue - copied over text & feedback. Thank you!

**Comment by misslivirose** [comment]
We implemented the ability for a moderator to soft mute everyone in the room via #2563 as a V1 - going to resolve this and track future work to avatar fall-off with other specific issues. Thanks for filing!
