### ISSUE TITLE
Deep link specific position/orientation in rooms

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#2296]
**Is your feature request related to a problem? Please describe.**
I would like to be able to control where a person enters a room via a link.  Could be a link in another room, or on a web page.  I don't want to just control the entry point for all users, but be able to link to different ones.  

The initial use case is for me to describe a room I've created in a blog post, and have multiple links into that room based on the thing I'm talking about in the post.

**Describe the solution you'd like**
I want someone to enter a room at a certain position and orientation, at positions other than the normal spawn points. 

**Describe alternatives you've considered**
Two alternatives seem to be
- be able to link to waypoints.  The problem here is that they must be pre-created in the scene
- be able to ask hubs for a deep link at any time, based on the current position/orientation of your avatar.  

The second seems best for this use case:  I would like to create a tour of an old room by placing text signs (type something, turn it into text, position and size it) and then locate myself appropriately, grab a link, and paste it into a blog.

**Comment by blairmacintyre** [comment]
anything happen on this?  When discussing our digital book, we want to embed links to specific parts of a hubs room within the web text;  we are considering running hubs in iframes, and would want the iframe view to go directly to specific waypoints within a space.

**Comment by emclaren** [comment]
a member of the theatre community using Hubs was saying this would be helpful for them to help users get to their seats at performances.

**Comment by JulesDoe** [comment]
if i understand you correctly your first suggestion has ben implemented in https://github.com/mozilla/hubs/pull/2918

**Comment by emclaren** [comment]
As mentioned by @JulesDoe  - this feature was just recently released! thanks for mentioning this
