### ISSUE TITLE
Hide Inspect Mode UI

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#2299]
You should be able to collapse the inspect mode UI or we should make it smaller on larger screens so that it doesn't block the media.

<img width="648" alt="Screen Shot 2020-03-30 at 12 11 57 PM" src="https://user-images.githubusercontent.com/1753624/77951979-ca612a80-727f-11ea-895e-9e21b5f165da.png">

**Comment by misslivirose** [comment]
Also to do: get focus / inspect aligned

**Comment by netpro2k** [comment]
We should consider just making some slight tweaks to the mobile UI and getting rid of the current desktop version of it.
