### ISSUE TITLE
Cant scroll in the Object List

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#2301]
**Description**
When there are a lot of items in the object list, scrolling with my trackpad doesn't work.

**To Reproduce**
Add a bunch of media to a scene in order to cause the object list to overflow. Observe that you can't scroll with your trackpad or mouse wheel.

**Expected behavior**
The object list scrolls with the trackpad / mouse wheel.

**Screenshots**
<img width="374" alt="Screen Shot 2020-03-30 at 3 12 46 PM" src="https://user-images.githubusercontent.com/1753624/77967094-3c923900-7299-11ea-9802-c1c54f06bf87.png">

**Hardware** 
 - Device: Laptop
 - OS: MacOS 10.15.3
 - Browser: Firefox 74.0

**Additional context**
Scrolling still works by dragging the scroll bar.

**Comment by brianpeiris** [comment]
Confirmed on Windows as well. Can't scroll with a mouse scroll wheel or trackpad swipe either. I think we capture and prevent default actions on all scroll wheel events somewhere in the code.
