### ISSUE TITLE
Focus mode always hides background on Edge browser

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#2309]
**Description**
Using right-click to focus on a Hubs object hides the background on Edge, whereas the background remains on other browsers.

**To Reproduce**
1. Spawn a duck
2. Right-click (hold) on it
3. Camera focuses on it, but the background is black.

**Expected behavior**
Background should remain showing like it does on other browsers.

**Hardware**
 - Device: Desktop (2d)
 - OS: Windows
 - Browser: Edge

**Comment by misslivirose** [comment]
Hey @j-conrad ! Can you add a screenshot here? I just tested and the Chromium-based Edge seems to have the same behavior as Firefox. Want to confirm if this is still an issue!

**Comment by misslivirose** [comment]
Going to resolve this, but if it's seen in Edge 79+, we can re-open
