### ISSUE TITLE
Safari mic volume indicator not working

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2346]
**Description**
When you speak while using safari the mic indicator doesn't have the blue volume indicator

**To Reproduce**

1. Go to safari
2. speak into the mic

**Expected behavior**
should indicate with a blue volume bar when you speak, but it doesn't do anything 

**Screenshots**
<img width="322" alt="Screen Shot 2020-04-08 at 12 22 55 PM" src="https://user-images.githubusercontent.com/6835324/78825147-523be880-7994-11ea-8bb8-cfff26b4cfb9.png">

**Hardware** 
safari 13.1
Macbook pro

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-358)

**Comment by takahirox** [comment]
We have updated the UI and I see the same green indicator across Windows Chrome, MacOS Safari, and iOS now.

![image](https://user-images.githubusercontent.com/7637832/135513096-4ef246af-99ca-4b24-9d51-69a2cef9953e.png)

I speculate the problem has been fixed when we updated the UI? Let's close this issue so far. Please reopen if you still encounter any mic indicator problem.
