### ISSUE TITLE
Deleting an account return "You don't have access to admin tools."

### ISSUE THREAD

**Issue by yakyouk** [mozilla/hubs#2354]
**Description**
As an admin, I select an account and click Delete, then I get a toaster "Element deleted (Undo)" and the account is removed from the list. However, a couple seconds later I get redirected and a popup shows with "You don't have access to admin tools.". Returning to the Accounts page shows the account did not get deleted.

**To Reproduce**
1. As an Admin, go to /admin#/accounts
2. Check an account or more to delete, then click Delete 
3. See error "You don't have access to admin tools." 

**Expected behavior**
Account gets deleted.

**Hardware**
 - Server deployed on AWS CloudFormation
 - Device: Desktop, Laptop
 - OS: Windows
 - Browser: Firefox, Chrome

**Comment by misslivirose** [comment]
Thanks for filing - we have this tracked on the hubs-cloud repo here: https://github.com/mozilla/hubs-cloud/issues/44 , so going to close this one as a duplicate. We appreciate the feedback!
