### ISSUE TITLE
Hubs website link not working "Take a look at the instructions in Hubs' documentation"

### ISSUE THREAD

**Issue by Githubuxer** [mozilla/hubs#2355]
**Description**
The link for 'Take a look at the instructions in Hubs' documentation' on the page https://hubs.mozilla.com/docs/intro-hubs.html just goes to a blank page -> https://hubs.mozilla.com/docs/hubs-create-join-rooms#enter-the-room.

**To Reproduce**
1. Go to https://hubs.mozilla.com/docs/intro-hubs.html
2. Scroll to 'Enter a room' section on page.
3. Click on 'instructions' link under section 'On a VR headset or mobile device?'

**Expected behavior**
Should go to a page in the documentation for instructions for VR headset or mobile device, or at very least link to this page: https://hubs.mozilla.com/docs/hubs-create-join-rooms.html#supported-devices--browsers

**Screenshots**
(attached)

**Hardware** 
 - Desktop and mobile
 - iOS iphone 6 and Mac OS X
 - Firefox desktop and ios, and Safarai

![Screenshot_2020-04-09 Getting Started with Hubs · Hubs by Mozilla](https://user-images.githubusercontent.com/62911518/78899143-f5e3d200-7a42-11ea-9a90-d7cc62edbbc6.png)

**Comment by misslivirose** [comment]
Updated this and it will be fixed when website redeploys 
https://github.com/MozillaReality/hubs-docs/commit/0983c32ebd035c9d21f4f31a95b0c6d718d4a3e4
