### ISSUE TITLE
Touching objects on iOS sends them flying

### ISSUE THREAD

**Issue by OddHouseGames** [mozilla/hubs#2360]
Touching/placing objects in iOS safari browser sends them flying.

**Comment by joshmarinacci** [comment]
Could you give us more information about what exactly is happening?

**Comment by misslivirose** [comment]
Closing issue - we can re-file a new bug if this behavior occurs but we have not gotten a clear repro of the issue.

**Comment by misslivirose** [comment]
(Likely dupe of #2348)
