### ISSUE TITLE
"box bot" avatar positioned in far distance in avatar selection and preview

### ISSUE THREAD

**Issue by clavis-magna** [mozilla/hubs#2362]
**Description**
When changing / previewing an avatar, the "box bot" avatar is not centered in the preview window. It is somewhere out in the distance and it is not possible to view it in the preview window centered. 

**To Reproduce**
* Select a box-bot based avatar. Try to view it in the preview panel
* edit am box-bot based avatar. Try to view it in the preview panel
* hav a box-bot based avatar as your default avatar. click set name and avatar. Check the avatar preview panel

**Expected behavior**
Avatar should be previewable and centered.

**Screenshots**

**Hardware** 
Checked firefox, chrome (windows/mac ) and safari (mac) 

<img width="640" alt="Screen Shot 2020-04-10 at 2 55 15 pm" src="https://user-images.githubusercontent.com/2109125/78966802-16e01c00-7b44-11ea-9e46-fb274ac143e1.png">
<img width="409" alt="Screen Shot 2020-04-10 at 2 54 29 pm" src="https://user-images.githubusercontent.com/2109125/78966805-1a73a300-7b44-11ea-895e-cd6f70994c95.png">

**Comment by misslivirose** [comment]
The screenshot is now set when you save the avatar - I think that this issue is fixed (I wasn't able to repro) but we can re-open if it's still occurring.
