### ISSUE TITLE
Hubs in VR on Pixel 2

### ISSUE THREAD

**Issue by spencercap** [mozilla/hubs#2369]
Heyo ~ loving Hubs (especially in these days of covid isolation) but I'm wondering how to get it up and running in VR on my Pixel 2 as I do not see the option to enter VR, only "Enter on Phone" from Chrome and Chrome Canary. Might I need some chrome://flags flipped? Also, am I crazy or has Firefox Reality disappeared from the Daydream store? I thought I'd try that but cant even get that on my device. Let me know how I can enjoy Hubs even more! Many thanks!

**Comment by larsbergstrom** [comment]
Hi! Unfortunately, Google was no longer handling updates to the Daydream store, and we couldn't leave an unpatched browser in there (for security reasons) and had to remove Firefox Reality. You can still currently sideload the product, for as long as we continue making builds for that platform, though!
https://github.com/MozillaReality/FirefoxReality/issues/2708

**Comment by kwadroke** [comment]
See issue #2001 for details on how to set WebXR flags to make it work on Chrome.

**Comment by spencercap** [comment]
Ah! Missed that issue, thanks for pointing me in the right direction.
