### ISSUE TITLE
Refactor when clients subscribe to voice servers to improve lobby capacity

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2377]
**Is your feature request related to a problem? Please describe.**
Currently, users subscribe to voice channels at the point when the land in the lobby. This is part of what contributes to a room cap of 30 (default value is 24) that spans between users who are actively in the room, acting as avatars, and the users who are more passively observing from the lobby.

**Describe the solution you'd like**
Participants in the lobby should not be added to voice channels until they are converted into an active room participant and expected to send voice / movement / avatar data to the rest of the users in the room.

By changing when this subscription occurs, we anticipate that we will be able to raise the room observation cap to allow for more lobby participants. This will make the "room cap" exclusive of the lobby participants. We are intentionally excluding a prediction as to the increase in lobby participants that this will be able to support.

**Describe alternatives you've considered**
The longer-term solution to address is the question of how we create an abstraction for participants who can be present in a space and represented as an avatar or some sort (perhaps instanced) and refactor how the server chooses to prioritize audio streams. However, this work is out of scope for Q2. A separate issue will be filed to track the longer-term project work required to change the current limitation of 24 avatars in a room to a greater number.

**Additional context**
This feature change is aiming to support a growing use case where an event is forced to go from 1 room to 2 rooms and set up their own streaming mechanic to relay the speakers from one room into a viewing room. While we believe that there is a greater degree of interaction needed to facilitate larger groups longer-term, we hope that a short-term project of bumping the lobby capacity will help us gain clarity about specific use cases and how to approach our longer-term scaling needs for individual rooms.

Part of #2308 work

**Comment by blairmacintyre** [comment]
This looks great.  Especially for the "100 person group that needs to be together for some things and then break out for other things" ... was just talking to folks at the university about doing class pilot experiments,  where classes would be > 50 but < 100, and where the "work" would be done in breakout groups (< 20).  But there would be the need to occasionally have the whole group together.

**Comment by misslivirose** [comment]
Implemented with #2402
