### ISSUE TITLE
Nametags look unusual on Firefox on Mac

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2388]
**Description**
Since earlier this week the nametags in Hubs on Firefox on mac look funny. Sort of like they have been chewed by a mouse.  Nametags look fine on Chrome & Safari though. 

**To Reproduce**
1. Open Hubs Room with another person
2. Look at their nametag (the edges of some of the letters. 

<img width="1459" alt="Screen Shot 2020-04-17 at 12 37 31 PM" src="https://user-images.githubusercontent.com/6835324/79623116-558b4e80-80cf-11ea-88cb-73b41b3c8cc0.png">
<img width="539" alt="Screen Shot 2020-04-14 at 3 12 48 PM" src="https://user-images.githubusercontent.com/6835324/79623149-6fc52c80-80cf-11ea-86cf-ac21e95c0143.png">

**Hardware** 
Mac, firefox nightly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-369)

**Comment by misslivirose** [comment]
@emclaren Is this still the way that nametags look on Firefox Nightly on Mac?

**Comment by keianhzo** [comment]
I guess this is updated.
