### ISSUE TITLE
Pin media objects to a wall or surface

### ISSUE THREAD

**Issue by elmau** [mozilla/hubs#2394]
**Is your feature request related to a problem? Please describe.**
Sometimes a meeting on VR can get messy when spawning videos, images and documents on a room.

**Describe the solution you'd like**
A way to pin these objects to a wall or a surface, to allow the possibility of order on a vr space.

**Describe alternatives you've considered**
1. pin directly to a surface where the object sticks like a magnet and makes it easy to put.

2. Make a single specific object that serves like a tv or an object that's capable to show video, documents or images and can be manipulated live, changing the content or passing slides. (instead of the fixed object that you can put on spoke and that can't be changed when published).

**Comment by misslivirose** [comment]
Hi @elmau - Thank you for filing! This is on our roadmap - precise placement is already supported in Spoke, but we're looking at this for Q2 under #1324 . I'm going to link this issue to the existing one for this, and close this as a duplicate.
