### ISSUE TITLE
Page indices are always '0' for Scenes and Avatar selection pages

### ISSUE THREAD

**Issue by luser** [mozilla/hubs#2396]
**Description**
In the "Choose a Scene" page, the page number at the bottom always shows 0.

**To Reproduce**
1. Create a room
2. Click the menu button, Choose a Scene
3. Scroll down to the bottom of the page
4. See the page number is 0 between the previous/next page arrows

**Expected behavior**
The page number should be displayed correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/286001/79880212-b364b280-83bd-11ea-8943-cbd00398793f.png)

**Hardware** 
 - Device: Desktop
 - OS: Tested on both Linux and macOS
 - Browser: Tested with Firefox 75 and Chrome 81

**Comment by misslivirose** [comment]
Thanks @luser! These repro steps are great.

A note for us in general - this is also happening with avatar paging as well.

**Comment by luser** [comment]
> These repro steps are great.

I didn't spent half of my professional career working at Mozilla and learn *nothing* about filing good bug reports. 😉
