### ISSUE TITLE
WASD-navigation on non-qwerty keyboards (e.g. Azerty)

### ISSUE THREAD

**Issue by eaganj** [mozilla/hubs#2397]
**Description**
The wasd/qe navigation keys are awkward to use on non-qwerty keyboards.  For example, on a French keyboard layout, the Q and A keys are swapped as are the W and Z keys.  This makes for unintuitive navigation on such keyboards.

**To Reproduce**
1. Use an AZERTY keyboard (or re-map to a virtual azerty keyboard layout).
2. Try to navigate using the wasd/qe keys.
3. See https://en.wikipedia.org/wiki/AZERTY#/media/File:KB_France.svg for why this problematic.

**Expected behavior**
Use zqsd/qe keys instead when on an Azerty keyboard (probably through a config option).

**Screenshots**
See step 3 above.

**Hardware** 
 - Device: Desktop
 - OS: yes
 - Browser: yes

**Additional context**
Azerty is the standard keyboard layout in France.  There are probably other keyboard layouts with similar problems (although QWERTZ does not seem to be one of them).

**Comment by eaganj** [comment]
As a temporary, albeit awkward and uncomfortable, workaround: it is possible to navigate with the arrow keys and rotate with the q-e keys (in the a-e position of a qwerty keyboard).

**Comment by vincentfretin** [comment]
In a simple scene created with A-Frame 1.0.4 with wasd-controls component, zqsd on a French azerty keyboard works great, as well as wasd on a qwerty keyboard . I did a quick search in hubs repo, I found `wasd-controls="enabled: false"` in `src/scene.html` so it doesn't seem to use `wasd-controls` but its own component, I guess it's in `src/systems/userinput/bindings/keyboard-mouse-user.js`.

`wasd-controls` is using key codes:
```
    KEYCODE_TO_CODE: {                                                               
    '38': 'ArrowUp',                                                               
    '37': 'ArrowLeft',                                                             
    '40': 'ArrowDown',                                                             
    '39': 'ArrowRight',                                                            
    '87': 'KeyW',                                                                  
    '65': 'KeyA',                                                                  
    '83': 'KeyS',                                                                  
    '68': 'KeyD'                                                                   
    }
```

`src/systems/userinput/bindings/keyboard-mouse-user.js` is using for example
` paths.device.keyboard.key("w")` so hard coding the letter "w" instead of using the key code.
So that's the difference it seems.

**Comment by vincentfretin** [comment]
On a French keyboard, on keydown, you get
event.code, event.keyCode, event.key
"KeyW" 90 "z"
"KeyA" 81 "q"
"KeyS" 83 "s"
"KeyD" 68 "d"
"KeyQ" 65 "a"
"KeyE" 69 "e"

wasd-controls is doing `code = event.code || KEYCODE_TO_CODE[event.keyCode];` so I guess event.code may not be implemented on some browsers, so need to be careful of that in the changes.

**Comment by djay** [comment]
This is also a problem for Thai keyboard. They use a qwerty but produces thai chars when pressed. 
https://keycode.info/ shows 
<img width="1350" alt="Screen Shot 2021-01-25 at 12 19 12 pm" src="https://user-images.githubusercontent.com/41700/105664768-13b5f100-5f08-11eb-9216-81caa3dfdda1.png">

so why isn't it working?

BTW, another alteranative might be to also allow "/" and "right-shift" as Q-E alternaitves as they are often close to arrow keys.

**Comment by pakokrew** [comment]
UP !

`event.code` is the good way!

**Comment by Slayug** [comment]
I have started something, I also have to handle other keys (P, A, E, etc.), wip
