### ISSUE TITLE
Info for running Hubs "on your own servers", isn't

### ISSUE THREAD

**Issue by mediadog** [mozilla/hubs#2418]
**Description**
Under "getting Started", the info linked for "If you would like to run Hubs on your own servers" is for running on an Amazon server, not one of my own.

**Expected behavior**
I would like to see instructions for bringing up Hubs on a private server, not just on a commercial service.  I tried copying the "dist" folder over to my server, but that results in a blank page loading when trying to access Hubs there.  (I see those instructions have since been removed and a comment added that the dev build will only work via localhost.)

The current Hubs Cloud instructions seem tremendously Amazon specific and I can't get a clue there as how to adapt those instructions for a private server.

**Additional context**
This is not just a distribution issue for me, but a development one as I need to collaborate on the development system with remote people that cannot access the system via localhost.  But of course sooner or later (hopefully sooner!) I would like to deploy on a private server too.

I understand the need to bring up Reticulum etc. as well, some docs are just needed on gluing the pieces together.  Thanks!

**Comment by gfodor** [comment]
Hey @mediadog - our goal of the Hubs Cloud project is to bring increasingly more targets where we have tooled out ease of use for deploying Hubs's services in a production-ready way. The operational tools we use for running hubs.mozilla.com can be found here, if it's helpful:

https://github.com/mozilla/hubs-ops

The current AWS offering makes it easy to add all the relevant pieces beyond the server itself to ensure quality of service, uptime, etc. (CDN, load balancer, firewall, DNS, SSL, etc.) The next target we are working on is DigitalOcean. The goal is to make it easy for anyone to run their own server, including people without any kind of technical background.

**Comment by drsounds** [comment]
but is all stuff that the infrastructure runs on free and open source? Hubs infrastructure has no propriertary dependencies to run?

**Comment by mediadog** [comment]
Yeah ditto on that - I find it odd that the only apparent route to bringing Hubs up right now is on a commercial service, and Amazon at that.  My interest at the moment is to do Hubs/Spoke experimentation and development with other folks, and having to learn (and pay!) for Amazon Web Services to do so seems too formidable an undertaking.  I was expecting to maybe have to bring up a Linux box, VM, or Apache, but frankly the stuff on the Hubs ops page is total G(r)eek to me: "Packer AMI definitions", "Habitat plans", "Terraform + terragrunt scripts", apparently stuff for cloud services.

I understand that may be the logical destination for large multi-user systems, but again it does not make sense to me for private and/or development cases.  So how is one to get into developing with Hubs in a way that allows remote collaboration without a cloud service?

I did figure out that I could bring up a "npm run dev" which other people could access if they added the correct hubs.local to their hosts file, but that's somewhat klutzy when dealing with testers that have no idea what a "hosts file" is, and doing so from multiple devices.

And hey, I'm happy to help develop/document/test a true private/local server process if the main pieces are there and it's just a matter of effort.  Thanks folks!

**Comment by gfodor** [comment]
We'd definitely welcome more resources from people to help get simpler setups working. We started with AWS for a variety of reasons, in part because that's what we use to operate hubs.mozilla.com. We'll be trying to add more targets as fast as we can, such as a DIY setup, but are a small team and Hubs Cloud is just one of several big projects we're working on (in fact Hubs Cloud ops work is only worked on by myself currently.)

**Comment by gfodor** [comment]
Closing this, since its "we're working on it"

**Comment by mediadog** [comment]
Hmmm, aren't bugs considered open until they are fixed?  Either the info in the readme needs to change to clarify "info for running Hubs on cloud servers", or the linked info needs to be what it says.  Just sayin'.

**Comment by PgLoLo** [comment]
> Hmmm, aren't bugs considered open until they are fixed? Either the info in the readme needs to change to clarify "info for running Hubs on cloud servers", or the linked info needs to be what it says. Just sayin'.

+1. Please, reopen the issue

**Comment by CheapGSean** [comment]
+1.
Yeah, I've personally come upon a situation where it would be really helpful to run hubs all on my own, we already have the hardware to do so. I've tried piecing together the install from what I can find (like the [reticulum readme](https://github.com/mozilla/reticulum#reticulum), and nothing has led to a working stack yet.)

**Comment by olavisona** [comment]
+1 yes please

**Comment by DillFrescott** [comment]
Its been so long without even an update to this. :(

**Comment by matthewbcool** [comment]
The comment above is largely still relevant today: 
> We'd definitely welcome more resources from people to help get simpler setups working. We started with AWS for a variety of reasons, in part because that's what we use to operate hubs.mozilla.com. We'll be trying to add more targets as fast as we can, such as a DIY setup, but are a small team and Hubs Cloud is just one of several big projects we're working on...

It should be possible to run hubs on your own but it would be high effort and you will need to search discord/github and put together all the pieces. There is some work underway that should hopefully make this process a bit easier next year, but it will likely be some time.
