### ISSUE TITLE
Add Scene Link to Scene Info Modal

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#2421]
**Is your feature request related to a problem? Please describe.**
I can't get the scene url for a room.

**Describe the solution you'd like**
I'd like to be able to get the scene url in the scene info modal

**Additional context**
The scene name could be the link
![Screen Shot 2020-04-24 at 12 35 17 PM](https://user-images.githubusercontent.com/1753624/80250217-3c7f2200-8628-11ea-82ff-32d133e87bb5.png)

**Comment by misslivirose** [comment]
I think that this is dependent on if the scene is remixable or can be promoted, because this is only the case for some scenes (and that's consistent with their other permissions)

**Comment by misslivirose** [comment]
I assumed that it was intentional that some of them could not be used (e.g. if the user hadn't promoted the scene and didn't want other people to find it easily)

**Comment by robertlong** [comment]
Hmm, yeah I guess it is intentional. Ok, we can close this.
