### ISSUE TITLE
Hosting Hubs on own server other than Amazon

### ISSUE THREAD

**Issue by drsounds** [mozilla/hubs#2423]
Hi,

since this is an open source project I assume it is possible to deploy hubs to any server, not just Hubs Cloud on Amazon but all docs refer to Amazon (and soon Digital Ocean). My educated guess is that this is a business reason as you get comission from the cloud usage fees that funds the open source development of this amazing system?

**Comment by gfodor** [comment]
Hi @drsounds - the code we use to deploy hubs to hubs.mozilla.com can be found here:

https://github.com/mozilla/hubs-ops

We have focused on making things easier to deploy for people on AWS, and will be working on additional targets. If you have the necessary technical expertise to deploy infrastructure, the above repo should be sufficient to set up scalable infrastructure on AWS as well, since it's what we use.

**Comment by drsounds** [comment]
I asked about setting it up on own servers not cloud like Amazon

**Comment by gfodor** [comment]
Yes, setting up a server can be understood by reviewing the code in hubs-ops. Setting up a server is only part of what is necessary to run Hubs, but the repository above shows how to not only set up a server but also the surrounding infrastructure.

**Comment by drsounds** [comment]
But it is possible to run the infrastructure not on clouds?

**Comment by youngchief-btw** [comment]
@drsounds Yes

**Comment by drsounds** [comment]
I am asking because I want to create custom components/objects with custom interactivity that can be added to room and as it is a frame based it shouldnt be so hard if we can use client with some modifications...

**Comment by classimmersevr** [comment]
We would be interested to know if it is possible to use Hubs cloud for multi cloud deploy approach like - Docker-Kubernetes

**Comment by youngchief-btw** [comment]
@classimmersevr You read my mind I also I'm looking to do Docker + Kubernetes!!

**Comment by misslivirose** [comment]
This work is now being tracked in https://github.com/mozilla/hubs-cloud/issues/135. Resolving this as a duplicate. Work to containerize or otherwise make available a cloud-agnostic provider will be tracked over on that repo.
