### ISSUE TITLE
Youtube live streams do not work

### ISSUE THREAD

**Issue by jarileon** [mozilla/hubs#2431]
**Description**
When adding an object to a room with an URL to a Youtube live stream the object appears as a broken icon and an error is printed to console:

Error adding media Error: Error resolving url "https://www.youtube.com/watch?v=5qap5aO4i9A": 
    at media-utils.js:45
    at Generator.next (<anonymous>)
    at C (HubsBasisTextureLoader.js:294)
    at o (HubsBasisTextureLoader.js:294)

Twitch streams work ok.

**To Reproduce**
1. Create a room
2. Use Create Object feature with an URL to a Youtube live stream
3. See broken icon appear
4. See error in console

**Expected behavior**
The Youtube live stream is displayed correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/28865955/80484500-7a4db480-8960-11ea-9a2e-859115a16f89.png)

**Hardware** 
 - Device: Lenovo Legion Y740
 - OS: Windows 10 
 - Browser: Chrome, Firefox

**Additional context**
Twitch streams do not have the same issue

**Comment by Utopiah** [comment]
Same bug on Firefox 75.0 (64-bit) on Linux

**Comment by prusnak** [comment]
The same is true for regular Youtube videos.

**Comment by joshmarinacci** [comment]
Is this still happening?

**Comment by prusnak** [comment]
Regular YouTube videos do work now, but the YouTube live streams are still broken.

**Comment by netpro2k** [comment]
Confirmed this is a regression in the resolver code. Looks like it was introduced when we added TTL caching for youtube videos (live videos don't have "expire" in their query so it fails. Should be a fairly easy fix.
