### ISSUE TITLE
Hubs not working at all in Oculus Quest built-in browser

### ISSUE THREAD

**Issue by jarileon** [mozilla/hubs#2439]
**Description**
When navigation to a Hubs room using Oculus Quest's buit-in browser only a white blank page is seen. With remote debugging it can be seen that there is a an error in the console: 

Uncaught TypeError: navigator.getVRDisplays is not a function
    at Object.<anonymous> (hub-e681108a1a8fad032d4e.js:1)
    at o (hub-e681108a1a8fad032d4e.js:1)
    at Module.<anonymous> (hub-e681108a1a8fad032d4e.js:1)
    at o (hub-e681108a1a8fad032d4e.js:1)
    at i (hub-e681108a1a8fad032d4e.js:1)
    at hub-e681108a1a8fad032d4e.js:1
    at hub-e681108a1a8fad032d4e.js:1

**To Reproduce**
1. Navigate to go to a Hubs room link using the built-in browser on Oculus Quest
2. See nothing appear
3. See console with remote debugging (instructions: https://developer.oculus.com/documentation/oculus-browser/browser-remote-debugging/)
4. See error in console

**Expected behavior**
Room works.

**Screenshots**

![image](https://user-images.githubusercontent.com/28865955/80593799-771efb00-8a2a-11ea-89c6-3107eacf733a.png)

**Hardware** 
 - Device: Oculus Quest
 - OS: Android
 - Browser: Built-in OculusBrowser version 9.0.0.2.38.210941660 (Chromium version 81.0.4044.117)

**Additional context**
When using Firefox Reality browser on Oculus Quest, Hubs works ok.

**Comment by Utopiah** [comment]
Same here, probably due to deprecating WebVR for WebXR

**Comment by larsbergstrom** [comment]
Yeah, the team has been doing great work on the migration to WebXR, especially while we continue to sort out some standards edge cases around AA and WebGL, but we unfortunately only had a couple of days of heads-up on the incoming deprecation.

Hopefully we'll be on WebXR soon, and until then maybe can at least change our already OB-specific path to work in 2D? cc @brianpeiris

**Comment by brianpeiris** [comment]
Fixed with #2450
