### ISSUE TITLE
Rapidly changes pages on a PDF causes it to grow!

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#2440]
**Description**
If I click rapidly on the forward or backward button, the PDF grows.

Very likely the "bounce" behavior when the slide changes is using the _current_ size as the start/end of the sizing animation, and grabbing the intermediate (larger) size from an unfinished animation.

Aside: it should be possible to disable that animation.  When using for talks, I'd (personally) prefer the image to just change, or (better) to do a quick cross fade, so that a sequence of slides with builds looks correct.  (I am the sort of personal that only ever uses a crossfade for transitions, I hate gratuitous animation in talks).

**To Reproduce**
1. put in a pdf
2. Click on forward quickly
3. watch your pdf grow!
4. it's magical

**Expected behavior**
Shouldn't change size.

**Comment by misslivirose** [comment]
Thanks Blair - we're tracking this in #2284. Agree we should take the animation out for PDFs here

**Comment by misslivirose** [comment]
But I agree, it's magical.
