### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by broehl** [mozilla/hubs#2452]
**Description**
In the Hubs documentation describing Features, the text describing the Object Menu doesn't match the figure above it.

**To Reproduce**
1. Go to https://hubs.mozilla.com/docs/hubs-features.html
2. Scroll down to the Object Menu description
3. Look at the figure
4. Read the text
5. Observe inconsistency   :-)

**Expected behavior**
Text should be consistent with the figure.

**Hardware** 
I suspect this is hardware-independent. In fact, I would be astonished if it's not.

**Additional context**
I finally got around to reading the documentation.   :-)

**Comment by misslivirose** [comment]
Fixed in: https://github.com/MozillaReality/hubs-docs/commit/3f6ae1d05439eecb817de359e6381c40c0a08ece
