### ISSUE TITLE
Hubs does not work with Firefox Reality 10 RC

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2457]
**Description**
When you attempt to enter immersive mode in a Hubs room on the Firefox Reality 10 release candidates (I tested on RC 4), the skybox doesn't render (it's solid black) and the head transform is not properly handled, making it unusable. The controls seem to indicate that Hubs is attempting to use WebXR instead of WebVR.

**To Reproduce**
1. On a standalone headset, launch Firefox Reality 10 RC 4
2. Create or enter a Hubs room
3. Go through the entry flow
4. Note that when (if) you are able to get into the Hubs room, you get strange rendering and head transformations. 

**Expected behavior**
Hubs should work (still fall back to WebVR)

**Screenshots**
![org mozilla vrbrowser-20200504-120113](https://user-images.githubusercontent.com/4313320/81003144-3c88da00-8dff-11ea-83d5-b4611ebab034.jpg)

**Hardware** 
 - Device: Standalone VR Headsets (Repros on Quest and Pico G2)
 - OS: Android
 - Browser: Firefox Reality v10 Release Candidates (at least confirmed on 2 and 4)

**Comment by daoshengmu** [comment]
@brianpeiris IIRC, we did some works two weeks ago to force the Hubs to use WebVR instead of WebXR like what you did for Oculus Browser. I am going to investigate this issue more today.

**Comment by daoshengmu** [comment]
Well, the Hubs works for me pretty well. I am using FxR v.10 778ee759

**Comment by brianpeiris** [comment]
I've also tested the latest "oculusvr" and "oculusvrStore" builds from https://community-tc.services.mozilla.com/tasks/Mfp_6nOqSNmxMHT6x7rEow#artifacts and they worked for me. Not sure if the recent WebXR push fixed it or if it was fixed on their end. 
I'll wait for someone on the FxR team to do a final verification and let them close this bug.

**Comment by daoshengmu** [comment]
It works well with my local build. We are going to have a RC build tomorrow, I will provide it to you guys to do the double check.

**Comment by daoshengmu** [comment]
Here is the newest FxR RC build (https://github.com/MozillaReality/FirefoxReality/releases/tag/release%2F10-rc5). It works for the Hubs now. So, I would like to close this issue.

**Comment by misslivirose** [comment]
Thanks all!
