### ISSUE TITLE
Reticulum doesn't care about client network conditions for HLS Adaptive Bitrate Streaming

### ISSUE THREAD

**Issue by camelgod** [mozilla/hubs#2483]
**Description**
Using an .m3u8 index in a media-video component results in Reticulum's cors proxy selecting an adaptive bitrate stream not appropriate for the user network conditions. In my case it selects a really high quality stream as both Reticulum and the HLS stream are hosted on AWS even though the client network is 500kbps down.

The video component src will be preselected - for example index_48.m3u8 instead lf index.m3u8. The client is then stuck with this quality and it will not adapt when network conditions change.

**Expected behavior**
There are two alternative ways I'd expect this to work:
- Reticulum selects a stream appropriate for the user by gathering some kind of indication of network conditions, and continously checks changes with the user and returns appropriate stream. (Hard and complicated)
OR
- When a media-video component is a HLS stream (m3u8) from an approved CSP hostname it should entirely bypass Reticulum cors-proxy in order for the client and server to figure out and adapt the stream. (Simple and how I have worked around this now)

**Hardware** 
 - Device: Any
 - OS: Windows/OSX/Linux
 - Browser Firefox/Chromium

**Additional context**
I'm currently doing a complete bypass of Reticulum remote proxy:

Line 820 in media-views.js:
`xhr.open("GET", u);`
instead of 
`xhr.open("GET", proxiedUrlFor(u));`

Line 452 in media-loader.js I set appropriate non-proxied url if it is HLS:
```
if(AFRAME.utils.material.isHLS(canonicalUrl, contentType)) {
    accessibleUrl = url;
}
```

Probably needs some conditions for:
- Checking that it's an HLS stream
- Allowed CSP and CORS hostname

**Comment by netpro2k** [comment]
youtube-dl was pulling out a particular quality level like you said. It should now as of (https://github.com/mozilla/reticulum/pull/397) return the index playlist when it is available. If you have examples of urls that still don't work with these new changes, please let us know.
