### ISSUE TITLE
WebGL not showing up on iOS

### ISSUE THREAD

**Issue by SpencerIO** [mozilla/hubs#2492]
**Description**
When I go to Hubs on my iPhone the WebGL does not show up but the rest of the UI does. WebGL works on Android and Desktop. 

If I connect an iOS client and a desktop client to the same meeting room, I can see the iOS client from the desktop client and even move the iOS Avatar around from the iOS controls.

WebGL works on iOS Safari for other websites

If I try to inspect the iOS Safari from my MacBook Pro it crashes the inspector. I can only take a quick snapshot before the inspector crashes, image below.

**To Reproduce**
Go to any hubs meeting room on iOS Safari https://hubs.mozilla.com/9YcyaR3/decent-complete-meet

**Expected behavior**
WebGL shows up like on any other platform.

**Screenshots**
iOS screenshot
![Screenshot](https://user-images.githubusercontent.com/5199953/81730892-14265e80-9443-11ea-8175-45ebb7ab8197.jpg)

2 inspector options show up in Safari
<img width="756" alt="Screen Shot 2020-05-12 at 8 18 24 AM" src="https://user-images.githubusercontent.com/5199953/81731124-5fd90800-9443-11ea-9714-f4c9d43443e4.png">

(hubs.mozilla.com)
<img width="489" alt="Screen Shot 2020-05-12 at 8 18 15 AM" src="https://user-images.githubusercontent.com/5199953/81731212-78e1b900-9443-11ea-9f17-755cfd39ed15.png">

(hubs.mozilla.com --- astonishing-passionate-camp)
<img width="647" alt="Screen Shot 2020-05-12 at 11 33 18 AM" src="https://user-images.githubusercontent.com/5199953/81731862-6ae06800-9444-11ea-8871-a1fefb8584f5.png">

**Hardware**
iPhone X
iOS 13.4.1
Safari

**Comment by SpencerIO** [comment]
This was due to the WebGL 2.0 flag being turned on

**Comment by jameskane05** [comment]
Running into the same issue - @SpencerIO did you solve it by turning that flag off or...?

**Comment by SpencerIO** [comment]
@jameskane05 That is correct. I just turned off the flag

**Comment by jameskane05** [comment]
Hm. Just tried a deploy w/ the <a-scene> attribute `renderer="webgl2: false"` but same error - the iPhone attempts a hard refresh of the page, then crashes when the same thing happens twice 🤔

**Comment by SpencerIO** [comment]
@jameskane05 I turned the flag off in the Safari Settings. Not in code. Just in case that is what you are doing

**Comment by brianpeiris** [comment]
It seems unlikely that most users will have turned the WebGL2 flag on themselves, though we could try to detect it and show a message, or fix support for WebGL2 in Safari if possible.

**Comment by takahirox** [comment]
iOS 15 has been released and Safari on it supports WebGL2 by default. I speculate the problem has been resolved?

Can anyone who faced this problem test again to check if the problem is still reproducible?
