### ISSUE TITLE
3D models as links

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2502]
**Is your feature request related to a problem? Please describe.**
We've had several community members request having objects in the room that behave as links.

For example, having a model of door that links to another hubs room, or having a 3d model of a shirt that links to an online store. 

**Describe the solution you'd like**
Allow users to add 3D objects, and specify that they point to a link in Spoke. Then when the object is opened in Hubs, when you point at it, the "open link" / "visit room" controls show.

**Additional context**
This issue should probably go into the Spoke repo, but I'm sharing it in Hubs, because the feature request has to do with how links are represented in Hubs.

**Comment by misslivirose** [comment]
One of the challenges here (I think that functionally, this is the same feature as #2357 - where you can attach room links to specific objects - albeit a bit wider in scope) is in the security consideration in immersive mode of having a user navigate to a potentially different host without knowledge before leaving the page.

**Comment by misslivirose** [comment]
I've re-titled #2358 to more widely capture the feature of linking externally from objects in a room. Going to resolve this as a duplicate.
