### ISSUE TITLE
Indication if a room visitor's mic is muted

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2504]
**Is your feature request related to a problem? Please describe.**
I meet with a lot of new Hubs users, and I find they often enter the room with their mic muted. When I speak to them, I don't get a response. It would be helpful to be able to see some sort of indication if their avatar is muted, this would speed up the triage process of whether their mic isn't working, or if they are muted. 

**Describe the solution you'd like**
This could be:

1) An icon in the dropdown room visitor list.
2) Some sort of light or icon above the person's avatar.

**Comment by misslivirose** [comment]
I did a mockup for this feature in Figma. The gist of it: 
* This list doesn't change if you are not a moderator. The new UI would only be available to room owners and moderators. 
* It adds a button to mute all of the people in the room (the downside of this is that in the case where there was a speaker, they would probably have to unmute themselves unless we restrict "mute all" to only apply to non-moderators) 
* Clicking on the audio indicator would also allow a moderator to mute someone (there is no way to unmute someone, for privacy purposes this is an action they only take themselves) 

![image](https://user-images.githubusercontent.com/4313320/83303780-87a1cd00-a1b2-11ea-91d3-bbca4c6bbcad.png)
