### ISSUE TITLE
Add a way to snap an image to a surface

### ISSUE THREAD

**Issue by luser** [mozilla/hubs#2508]
**Is your feature request related to a problem? Please describe.**
I added some images to a room to use as wall decorations, but getting them to line up with the walls is very fiddly.

**Describe the solution you'd like**
I'd like to have some way to take an image and snap it to a surface in the room, perhaps in the object menu.

**Comment by misslivirose** [comment]
Hey @luser - thanks for filing! 

This is being tracked in #1324 - it's something that we've heard quite a bit and have been planning towards!

**Comment by luser** [comment]
Thanks! I looked around for related issues but didn't see that one.
