### ISSUE TITLE
Cursor lock when dragging camera

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#251]
When you currently drag to look we do not lock the cursor. This causes your cursor to move outside the window and the user can become confused as to where their cursor went.

**Comment by gfodor** [comment]
Did we decide on the exact behavior we want?

**Comment by cvan** [comment]
(let me know if you would like me to file a separate issue as a feature request.) has the [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) been considered? it is popular for FPS games on the Web.

**Comment by johnshaughnessy** [comment]
#391 Doesn't solve this by locking the cursor on drag, but it at least allows people to toggle cursor lock on right click.

**Comment by johnshaughnessy** [comment]
Marking this as closed because we've explored the solutions and chosen one that works OK. Cursor lock when dragging camera is better than the solution we chose, except that a notification about cursor lock would appear every single time you click, and thus we only lock on right click.
