### ISSUE TITLE
Audio-only HLS streams stutter / are not supported

### ISSUE THREAD

**Issue by roddylindsay** [mozilla/hubs#2512]
**Description**
Audio-only HLS streams added as URLs (.m3u8) play, but stutter every few seconds.  Javascript console reveals that it is throwing an error when it cannot find the video

**To Reproduce**
1. Start audio-only HLS stream
2. Load HLS URL with magic wand
3. Audio plays, stutters, JS warnings thrown

**Expected behavior**
HLS audio-only streams should play normally

**Screenshots**

**Hardware** 
 - Device: Desktop
 - OS: OSX
 - Browser Chrome

**Additional context**

**Comment by netpro2k** [comment]
@roddylindsay Can you provide a link to an example of this?

**Comment by roddylindsay** [comment]
https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa-audio-only.m3u8

**Comment by camelgod** [comment]
@roddylindsay 

Might not be related, but check out https://github.com/mozilla/hubs/issues/2572

Would be interesting to see if its related to the same buffering issues I had with HLS, and if you can maybe test the workaround changing video currentTime value?

**Comment by netpro2k** [comment]
Going through cleaning up some old issues. I think this should have been resolved with the last round of HLS fixes.
