### ISSUE TITLE
Preferences Menu Refresh

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2515]
**Is your feature request related to a problem? Please describe.**
Our preferences menu has gotten long and full of levers to pull and buttons to poke for a custom Hubs experience. We should improve this so that the menu is easy to navigate so that a user can find what they're looking for. 

**Describe the solution you'd like**
The preferences menu should be broken into different categories of settings, grouped by similar properties. For this pass, I would recommend: 
* General 
* Controls
* Audio (_not present in mockups below_)
* Advanced

| **Category** | Setting           | Description |
| ------------- |-------------| -----|
| General    | Mute microphone on entry  | The default setting for whether your mic is muted when you enter a Hubs room |
| General     | Only show nametags while frozen      | If true, nametags will be hidden unless menus are open |
| General | Incoming voice volume     |   Volume of other avatars |
| General | Media volume | Volume of video or audio media in the environment | 
| General | Disable sound effects | Do not play chat bubble, spawn sounds, or other sound effects |
| Controls | Rotation per snap (in degrees) | How far your avatar turns in a single snap turn | 
| Controls | Disable movement | Prevent your avatar from moving with the joystick or WASD keys |
| Controls | Disable backwards movement | Prevent your avatar from moving backwards | 
| Controls | Disable strafing | Prevent your avatar from strafing | 
| Controls | Disable teleporter | Prevent your avatar from moving with the teleport capability | 
| Controls | Movement speed modifier | How fast you move | 
| Controls | Enable left on-screen joystick for moving around | Displays a virtual left joystick on touch screen devices when in landscape mode, used to move around | 
| Controls | Enable right on-screen joystick for looking around | Displays a virtual right joystick on touch screen devices when in landscape mode, used to look around |
| Audio | Disable microphone echo cancellation (requires restart) | Turns off the echo cancellation audio processing | 
| Audio | Disable microphone noise suppression (requires restart) | Turns off the microphone noise suppression audio processing | 
| Audio | Disable microphone automatic gain control (requires restart) | Turns off the automatic gain control audio processing | 
| Advanced | Max Resolution (width x height in pixels) | Sets the max resolution for the Hubs canvas | 
| Advanced | Material quality (requires restart) | Overrides the default material quality for a scene | 
| Advanced | Disable automatic pixel ration adjustments | ??? | 
| Advanced | Disable auto-exit when multiple Hubs instances are open | Allows you to have multiple tabs running Hubs rooms at the same time instead of automatically leaving the first room | 
| Advanced | Disable auto-exit when idle or backgrounded | Prevents you from automatically leaving a room when you change tabs or apps on a mobile device |

**Improve clarity of "restart required"**
The designs below add an additional button to reload the page on tabs if there are preferences that require reloading the room. I'm not super attached to this, we could also change the text to **(requires refresh)** to tell the user that the preference will not take effect until the page is reloaded.

**Sample desktop / VR menu mockups**
![image](https://user-images.githubusercontent.com/4313320/82240753-ccdf1880-98ef-11ea-95ad-f78671c2925a.png)

**Sample phone menu mockup**
![image](https://user-images.githubusercontent.com/4313320/82246102-f0f32780-98f8-11ea-9380-2b02e5c4e973.png)

**Comment by misslivirose** [comment]
Open question: Should volume sliders be in 'General' or 'Audio' ? I am thinking of the audio category being more about the devices, but open to discussions about the scope of that (or if these are even the right categories to use)

**Comment by netpro2k** [comment]
I would put those under "Audio" and then maybe make audio the first tab. Then maybe rename "General" to "UI", accepting that UI would basically only be the "Only show nametags while frozen" option right now

**Comment by johnshaughnessy** [comment]
I have not yet added descriptions in #2527 so if I merge that before I add them, I'll create a follow-up issue.
