### ISSUE TITLE
Hub links not clickable on iOS

### ISSUE THREAD

**Issue by awhite001** [mozilla/hubs#2523]
**Description**
Added a link element in Spoke and added a URL to the element. When viewed on mobile, the link is not clickable and will not redirect you to the page. Attempted to add a link and pin within the Hubs room, but that link was also not clickable by the mobile user.

**To Reproduce**
Links added in Spoke or within the Hubs room did not redirect the page.

**Expected behavior**
The link would redirect the user to a new page. 

**Hardware**
 - Device: iPhone 8 Plus
 - OS: iOS
 - Browser Safari

**Comment by misslivirose** [comment]
Thanks for filing - this is a known issue tracked in  #2163 so I'm going to close this as a duplicate.
