### ISSUE TITLE
support non-English languages (l10n localisation, i18n internationalisation)

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#253]
**[`l20n`](http://l20n.org)** is a solid project (supported by the L10n team and community here at Mozilla) I've used with great success. Firefox, addons.mozilla.org, and various other projects use different L10n workflows (mostly because of historical reasons), but I'd recommend `l20n` for this project.

**Comment by gfodor** [comment]
i can do a first pass on the parts of the app that are not currently localized because of the limitations of the existing plugin we use. if it works out we can use l20n going forward and try to do a burndown of the old stuff.

**Comment by gfodor** [comment]
untagging this from polish MVP, but will make a pass on this for the next bulky text-oriented UI work

**Comment by misslivirose** [comment]
We need to tag strings and an owner to help guide this along

**Comment by piercechueng** [comment]
We have deployed Hubs Cloud on AWS out of USA and found that need non-english UI. So please consider this feature to be online soon. Thanks a lot.

**Comment by misslivirose** [comment]
Going to resolve this in favor of #2373 since active discussion is happening on the newer issue
