### ISSUE TITLE
Live youtube/vimeo/twitch streams feature request

### ISSUE THREAD

**Issue by fernzharp** [mozilla/hubs#2538]
I would love the ability to be able add a live video link in Spoke so people in the scene can view live flat screen and 360 videos.
I believe this could be an asset to many use cases.

**Comment by misslivirose** [comment]
Hey @fernzharp - this is already supported. You can add the 'video' element and specify a link to a live feed, and it will pull the live feed URL in Hubs. 

View more here: https://hubs.mozilla.com/docs/spoke-adding-scene-content.html#video and here: https://hubs.mozilla.com/docs/hubs-faq.html#can-i-play-video-content-in-hubs

**Comment by fernzharp** [comment]
> 
> 
> Hey @fernzharp - this is already supported. You can add the 'video' element and specify a link to a live feed, and it will pull the live feed URL in Hubs.
> 
> View more here: https://hubs.mozilla.com/docs/spoke-adding-scene-content.html#video and here: https://hubs.mozilla.com/docs/hubs-faq.html#can-i-play-video-content-in-hubs

Ah silly me! I did already know the streaming was working for flat screen..  tunnel vision trying to get live 360 streaming up and running
