### ISSUE TITLE
Pinning is broken 

### ISSUE THREAD

**Issue by yakikki** [mozilla/hubs#2539]
**Description**
Hello! Please help. I pinned several objects yesterday, left the room by closing a browser tab, and when I came back it's no longer possible to unpin and edit them. I have this issue in all of my rooms, for example https://hub.link/fCiUMWR

**To Reproduce**
1. Create a new room
2. Choose a Scene "Hello WebXR Main Hall"
3. Add an object "Astronaut"
4. Pin the object "Astronaut"
5. Copy room link
6. Close a browser tab 
7. Open the room by URL
8. Try to unpin the object

**Expected behavior**
The object should unpin

**Hardware** 
 - Device: Desktop,
 - OS: MacOs
 - Browser Firefox, Safari

**Comment by misslivirose** [comment]
Confirmed that I've reproduced this on Firefox desktop. The 'un-pin' button is still present, but nothing happens when it is clicked.

**Comment by misslivirose** [comment]
Console error: 

`Failed to obtain ownership while trying to create constraint on networked object.`

**Comment by gfodor** [comment]
Thank you for reporting this nasty bug. Landing a fix now. Please re-open if it persists!

**Comment by yakikki** [comment]
Thank you so much!
