### ISSUE TITLE
Physics Worker Performance in Firefox

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#2549]
**Description**
The Hubs physics system runs [Ammo.js via three-ammo](https://github.com/infinitelee/three-ammo) in a WebWorker, this worker seems to run well above 100% CPU utilization in our default scene when using Firefox.

**To Reproduce**
1. Go to https://hubs.mozilla.com in Firefox
2. Create a new room with the default scene
3. Take note of the CPU usage in Task Manager or Activity Monitor
4. Do the same thing in Chrome

To narrow in on the source of the issue, you'll need to check out a branch of Hubs and run it locally:

```
git clone https://github.com/mozilla/hubs.git
cd hubs
git checkout physics-worker-performance
npm ci
npm run dev
```

Go to https://localhost:8080 and make sure you can create a room.

Test with and without the physics worker enabled in Firefox and Chrome. You can disable the physics system in this branch by appending the `disablePhysics` querystring to the room url.

https://hubs.local:8080/hub.html?hub_id=my-room-id&disablePhysics

In the Firefox Profiler you should see that the Web Content thread is doing relatively little work compared to the DOMWorker thread running the Physics Worker. However, on closer inspection it seems like the code being ran in the Physics Worker is doing relatively little work:

![screen_shot_2020-05-26_at_4 44 32_pm](https://user-images.githubusercontent.com/1753624/83903630-57f34780-a713-11ea-84d5-6e8dd3765dab.png)

In Chrome however, this is not the case. CPU utilization is much lower.

Here's what I'm observing across the browsers on my system:

FF 76 macOS w/ Physics System on: FirefoxCP Web Content process is at 151% CPU utilization, I'm maintaining a constant max frame rate (50FPS on my 100Hz monitor), FF Profiler shows the main thread doing very little work, and the DOMWorker thread doing a lot more.

FF 76 macOS w/ Physics System off: FFCP Web Content process is sitting around 23% CPU utilization, frame rate is still maxed.

Chrome w/ Physics System on: Chrome's Google Chrome Helper (Renderer) process is sitting at around 23% and the (GPU) process is sitting at 6.8%. Frame rate is fine. The main thread is doing very little work. The physics worker thread is doing around 5 really short tasks (~81 microseconds) over the course of the frame.

Chrome w/ Physics System off: Basically the same as with the physics system on. The Renderer process is hovering around 19% CPU utilization now.

**Hardware** 
 - Device: 2019 MacBook Pro 16"
 - OS: macOS 10.15.4
 - Browser: Firefox 76.0.1 and Chrome 83.0.4103.61

I do think this problem is more prevalent on a Mac and could be specific to FF on macOS. However, I haven't been able to profile Firefox Reality and Oculus Browser to see if the same thing happens on an Oculus Quest. If it is happening FxR, that could account for some of the large performance gap between the two browsers.

**Comment by larsbergstrom** [comment]
@robertlong Is this fully resolved with https://github.com/InfiniteLee/three-ammo/pull/4 ?

**Comment by robertlong** [comment]
Yes, it should be now 👍
