### ISSUE TITLE
Hub Cloud Cloudformation Status ROLLBACK_COMPLETE

### ISSUE THREAD

**Issue by caxolator** [mozilla/hubs#2553]
Hi,

I have bought the hub mozilla cloud personal service and while creating the stack at AWS webpage the status gives an error: X  ROLLBACK_COMPLETE

The domain I am using therefore is: salaschengen.eu It is from an external domain provider, not Amazon Route 53 and it has wordpress installed. Do I need to remove wordpress or make some changes? I am not able to see the Hub Cloud Personal
I am attaching a file so you can see it
![errorcloudformation](https://user-images.githubusercontent.com/64408848/84039953-47a4cc00-a9a2-11ea-8c0f-5fdb69bd4486.PNG)
 interface loading.

**Hardware** 
 - Device:Desktop, phone
 - OS: . Windows
 - Browser [e.g. Firefox Chrome]

Thank you in advance

**Comment by misslivirose** [comment]
Hi! I think that you also emailed us - if so, I've just sent this over via email as well, but I'll share the links here as well: 

The domain that you use cannot already be hosting another application unless you use a subdomain. There are instructions for various configurations with regards to using existing domains here:
https://hubs.mozilla.com/docs/hubs-cloud-aws-domain-recipes.html
https://hubs.mozilla.com/docs/hubs-cloud-aws-existing-domain.html 

 Hope this helps!

**Comment by misslivirose** [comment]
I'm going to close this out here since we can coordinate more specifically over email!
