### ISSUE TITLE
create new Chrome Origin-Trial tokens for production origin

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#256]
The current Chrome Origin-Trial token is valid for `https://reticulum.io` and `https://*.reticulum.io`

A new token will need to be made for `https://hubs.mozilla.com` (or whatever the final origin is).

<hr>

I used [this Chrome Origin Trial "Check Token" page](https://googlechrome.github.io/OriginTrials/check-token.html) by Google to test the token: `ArEZ0vY0uMo3pj+oY8Up4u4Hy8QolJwKxG4/2WRhSPnTZRrviiGhzP6/y72nBdsIhdEyoundxqg//KLbs2vGnQoAAABkeyJvcmlnaW4iOiJodHRwczovL3JldGljdWx1bS5pbzo0NDMiLCJmZWF0dXJlIjoiV2ViVlIxLjFNNjIiLCJleHBpcnkiOjE1MjYzNDg2MjEsImlzU3ViZG9tYWluIjp0cnVlfQ==`

![screenshot of Chrome Origin Trial "Check Token" page](https://user-images.githubusercontent.com/203725/39158265-dfba99fa-4713-11e8-9e26-090080a615f5.png)

**Comment by gfodor** [comment]
ah rgr that, filing an issue

On Mon, Apr 23, 2018 at 4:37 PM, C. Van Wiemeersch <notifications@github.com

**Comment by gfodor** [comment]
oh, this is an issue already :) thanks!

**Comment by gfodor** [comment]
email sent

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/284
