### ISSUE TITLE
Guide for installing HUBS locally.

### ISSUE THREAD

**Issue by DeveloperHashmi** [mozilla/hubs#2565]
**Description**
There is some certificate issue on server console and Missing index.html on the browser.

**Screenshots**
![download_20200612_101855](https://user-images.githubusercontent.com/51310612/84466083-2db30400-ac96-11ea-8352-25710118cd53.jpg)

**Hardware** 
 - Device: Desktop
 - OS: Linux
 - Browser: Chrome

**Comment by truedat101** [comment]
There is a strong cross over with the reticulum issue reported here: https://github.com/mozilla/reticulum/issues/423

I'll post my findings once I solve the mystery.

**Comment by robinkwilson** [comment]
To fix the missing index.html issue (worked for me)-> https://github.com/mozilla/reticulum/pull/425

**Comment by truedat101** [comment]
@robinkwilson oh cool.  I will try this out tonight.
