### ISSUE TITLE
Youtube links don't work

### ISSUE THREAD

**Issue by tonyschuite** [mozilla/hubs#2583]
**Description**
Since a few days I am not able to place youtube links anymore.
Vimeo links work.
**To Reproduce**
https://hubs.mozilla.com/Hq9iTTP/hku-theater-rivier-hub/
2a. Paste any youtube link
2b. paste any youtube link using the "Custom URL or File" dialog
3. shows broken link image

**Expected behavior**
It is supposed to show the video

**Screenshots**

<img width="1132" alt="Screenshot 2020-06-24 at 21 36 16" src="https://user-images.githubusercontent.com/1898121/85619600-d4b67900-b662-11ea-9ea2-27ea245cbdfa.png">

**Hardware** 
 - Device: MacBook Pro
 - OS: MacOS Also tested on windows
 - Browser Google Chrome Also tested in Safari

**Additional context**

**Comment by misslivirose** [comment]
Thanks for filing - this is a known issue with YouTube when they block access from Hubs that is documented in #2476. We either screenshot the page or it shows an error loading the media as seen in your room, but they both have the same root issue.

**Comment by truedat101** [comment]
Wow, this is disappointing.  It was working last week, and then suddenly this week it stopped working.   Why would they block access?  Is there any work around, was really counting on using a video stream in the VR for something.

**Comment by truedat101** [comment]
Also, why is this issue closed if not resolved?
