### ISSUE TITLE
Could not enter cardboard VR mode

### ISSUE THREAD

**Issue by kylebakerio** [mozilla/hubs#2586]
**Description**
There was never an interface invitation to go into 'cardboard mode'. It was always magic window mode. When opening the provided 'hubs.link' url and typing in the code, I was then right back where I was in a never ending loop.

**To Reproduce**
1. join a hubs room
2. click 'enter with vr' button
3. get the hubs.link and code
4. follow it, arrive right back where you were with no real difference.

**Expected behavior**
I expect a 'vr' button to show up like every other aframe project

**Screenshots**
can provide if needed

**Hardware** 
 - OnePlus 6T, latest Chrome

**Comment by misslivirose** [comment]
Tracking Cardboard support as a work task in #2657
