### ISSUE TITLE
Pinned objects move to the origin when visiting another room from the 'Visit Room' link

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2594]
**Description**
I went into the meetup room and added some objects (three gif files and a link to another room). I pinned them, then left the room. When I left the room to visit another room that was linked in the scene, the objects all moved to the origin (as reported by @emclaren, who stayed in the room after I left).  

**To Reproduce**
1. Go to the meetup room 
2. Add objects and pin them 
3. Leave the room by way of clicking on another room link that has been shared in the room

**Expected behavior**
The pinned objects stay in the same place 

**Screenshot**
![image](https://user-images.githubusercontent.com/4313320/85892541-fa986680-b7a5-11ea-8064-021ab093b3d7.png)

**Comment by JT-os** [comment]
Lol.  Ummmm....I was trying to click on them to get to the next room so I unpinned them and moved them back up.  I was wondering how they got halfway into the floor!  So that might have been my handy work and not a bug.  OOPSIE!

**Comment by misslivirose** [comment]
We validated this several times after the meetup - definitely happening without intervention.

**Comment by InfiniteLee** [comment]
@misslivirose @emclaren Could not reproduce just now, can you verify if this issue is still occurring?

**Comment by emclaren** [comment]
this does not appear to be happening any more
