### ISSUE TITLE
Audio playing at full volume on mobile Safari despite volume being set to 0

### ISSUE THREAD

**Issue by JacobErvin** [mozilla/hubs#2598]
**Description**
Audio is playing at full volume on Safari (iOS) despite volume being set to 0.

**To Reproduce**
1. Have a video in your Spoke project
2. Set volume to 0 
3. Test on desktop browser (works as expected)
4. Load on mobile device (iOS, Safari)
5. Audio plays at full volume

**Expected behavior**
Video sound is muted

**Hardware** 
 - Device: iPhone
 - OS: iOS 
- Browser: Safari

**Comment by InfiniteLee** [comment]
It appears that iOS volume controls for media don't function at all right now, both on media objects but also from the audio settings menu.

**Comment by InfiniteLee** [comment]
This bug is because the audio is not getting initialized correctly for iOS due to this workaround: https://github.com/mozilla/hubs/pull/1876 which was implemented because of #1797. It looks like the workaround can be reverted once iOS 13.6 goes live.

**Comment by InfiniteLee** [comment]
fixed by #2669
