### ISSUE TITLE
Memory leak when avatars leave room

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#2601]
A-frame elements for avatars are being pinned when avatars leave the room because the scheduled worked handle is mis-unregistered:

https://gist.github.com/gfodor/f1ed539ba67700db633d3ef160612ff2

**Comment by netpro2k** [comment]
Actually looks worse than that, since the thing being scheduled is missing the `if (this.avatarIsQuiet) {
` check, so it always runs.
