### ISSUE TITLE
Add a preference for selecting webcam to share

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2610]
**Is your feature request related to a problem? Please describe.**
Currently, Hubs will default to a webcam when you share from the HUD and you cannot change it after the fact.

**Describe the solution you'd like**
Like other audio conferencing applications, we should have a place to specify/change what camera we are sharing

**Additional context**
Sometimes the prompt from the browser asks (on other sites) which camera to use - it might also be worth figuring out whether that is an avenue through which we could request a specific camera to use at share time. 

Further note - it seems like in particular, Hubs has issues displaying cameras that are being routed through a capture card device.

**Comment by netpro2k** [comment]
This is already available in preferences 
![image](https://user-images.githubusercontent.com/130735/86724093-57352600-bfdd-11ea-9463-1a981016d9a8.png) as of #2603

**Comment by misslivirose** [comment]
:tada:
