### ISSUE TITLE
Avatars don't load in browsers that don't use ImageBitmapLoader

### ISSUE THREAD

**Issue by jdm** [mozilla/hubs#2616]
**Description**

Avatars show up as a black texture in Servo, because the images are classified as cross-origin and aren't made as a CORS request. This causes a security error when they're used as a WebGL texture.

**To Reproduce**
Force the HubsTextureLoader to take the THREE.ImageLoader path instead of THREE.ImageBitmapLoader. When entering a room, the default avatar appears black instead of whatever was expected.

**Expected behavior**
The avatars should load regardless of whether ImageLoader or ImageBitmapLoader are used.

**Screenshots**
<img width="342" alt="Screen Shot 2020-07-09 at 3 04 17 PM" src="https://user-images.githubusercontent.com/27658/87080331-7a3a2280-c1f5-11ea-9160-a89d82b78eb8.png">

**Hardware** 
 - Device: Desktop
 - OS: macOS
 - Browser: Firefox Nightly, Chrome

**Additional context**
The actual reason that a CORS request is not performed for the image request is surprising. [The crossOrigin property](https://github.com/mozilla/hubs/blob/7ca52e63085a8cb8f2234abac1f842a88d2a85ad/src/loaders/HubsTextureLoader.js#L6) for the loader is a static property, and adding a `console.log` to loadTextureAsync that shows the values of `this.crossOrigin` and `HubsTextureLoader.crossOrigin` are `undefined` and `anonymous` respectively. I don't know enough about JS and static properties to declare whether this is caused by a transpiler bug or is incorrect as written.

In any case, one quick fix for this particular issue would be changing uses of `this.crossOrigin` to `HubsTextureLoader.crossOrigin`.

**Comment by jdm** [comment]
This also prevents a Servo client from entering a room where there are already other clients present.

**Comment by arpu** [comment]
how can i use a servo based client? ( on linux)

**Comment by jdm** [comment]
Download tomorrow's nightly from http://download.servo.org/. Run Servo with `./servo [url] --pref dom.webrtc.enabled --pref dom.svg.enabled --pref dom.gamepad.enabled --pref dom.canvas_capture.enabled --pref dom.webrtc.transceiver.enabled`.

**Comment by arpu** [comment]
ohh cool to know thx!
