### ISSUE TITLE
(Design and Exploration) Delete thing in the admin panel

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2647]
Design changes to admin panel to help make logical deletions better without needing real deletion yet

My office hours increasingly have people asking about deleting things in the db by themselves. I’m afraid someone is going to get themselves in a bad state.

See also https://github.com/mozilla/hubs/issues/2314

**Comment by misslivirose** [comment]
Linked: https://github.com/mozilla/hubs-cloud/issues/44
Linked: https://github.com/mozilla/hubs-cloud/issues/79

**Comment by misslivirose** [comment]
Design document for this is now ready for review.

**Comment by misslivirose** [comment]
Discussed on 9/21 meeting - we are still going to need to discuss design on this. Less of a significant need now that the delete button is hidden from the admin panel.

**Comment by ConstantChange** [comment]
The problem comes when we need to reset for a new season and have 25 pages of 25 records each that need to get disabled. Very important for admins

**Comment by misslivirose** [comment]
Going to close this since we are now tracking it in the Hubs Cloud repo with issue #79: https://github.com/mozilla/hubs-cloud/issues/79
