### ISSUE TITLE
Experiment with a Medium Quality Mode

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#2652]
Figure out what a medium quality mode looks like and what features to enable/disable on each quality mode.

I think medium quality could use a Phong shaded material or possibly Cel Shaded. Realtime lighting and static shadow maps will likely work well.

**Comment by joshmarinacci** [comment]
How will this mode be triggered?

**Comment by misslivirose** [comment]
https://github.com/mozilla/hubs/pull/2760
