### ISSUE TITLE
Some links show broken link image instead of screenshot

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2678]
A community member wrote to me about link screenshots that aren't resolving in Hubs (they show as a broken link) - for example, this link (https://nhmu.utah.edu/) - gives a broken link image on hubs.mozilla.com and throws this error in the console:

`Error adding media Error: Error resolving url "https://nhmu.utah.edu/": Not Found`

This one fails in the same way  (http://www.borlandrivermedia.com/)

Other links she added seem to be working fine

**Comment by emclaren** [comment]
this one is also not working https://www.amazon.jobs/en/landing_pages/principal-engineer-hiring

**Comment by JulesDoe** [comment]
We could fix that in oure case by adding the `og:image` meta tag to the target Website.

**Comment by emclaren** [comment]
thank you for sharing this tip @JulesDoe

**Comment by andrewadams32** [comment]
Is anyone else still facing this issue? 

We have two websites that we would like to have links to in Hubs, but neither of them work. One is a Wordpress site, and the other is just static HTML hosted with Nginx. We noticed that for the Nginx site, the links would show up fine if the protocol was set to http, but as soon as we added the ssl certificate to Nginx and forced https, all of the links broke. As for the wordpress site, we haven't had any luck with getting links to show up correctly in Hubs. 

Has anyone else successfully hosted their own website and made links to it in Hubs? Any tips or advice would be greatly appreciated

**Comment by davegoopot** [comment]
Yes lots of these problems. 

Worse case had to make a static page with some link text that with wait 3 seconds (JavaScript) and then redirect to the target page.

**Comment by andrewadams32** [comment]
Yes, we have a setup like that currently that uses http-equiv refresh to redirect to another link. However, even this intermediate page doesn't display correctly when it is served on https for some reason.

**Comment by davegoopot** [comment]
@andrewadams32 I had that problem with http-equiv refresh. JavaScript <body> onload with settimeout to 3 seconds allowed the image of the redirect page to load a preview in the Hub and the redirect to the real page.

**Comment by andrewadams32** [comment]
@davegoopot I will definitely try that, thanks for the tip!

**Comment by mx6363** [comment]
i am also facing this issue.
i am linking webpages in the hubs.  the webpages resolved fine for a few days and then after awhile, it just shows broken links.
trying to 'magic wand insert' the same link still throws a broken link icon/image.

btw, not sure how long i will keep that room alive

https://sixtrees.studio/j2qDfFM/escapetest

**Comment by misslivirose** [comment]
I'm going to propose bumping the priority of investigating this, but am resolving this issue here since we're tracking it in the other repo. https://github.com/mozilla/reticulum/issues/435

**Comment by sea922** [comment]
> We could fix that in oure case by adding the `og:image` meta tag to the target Website.

I tried but it doesn't work, do you have any solution that works
