### ISSUE TITLE
'Browser unsupported' message should only appear for rooms, not hubs.mozilla.com generally

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2692]
**Description**
When accessing a room on iOS on an unsupported browser, the message should appear when a user tries to enter a room on a non-Safari browser. This is desired. However, this message appears when arriving on hubs.mozilla.com, which shouldn't require specific permissions to be visible. By blocking access to hubs.mozilla.com with an 'unsupported browser' message, users on mobile aren't able to access documentation, the community links, what's new, or other pages related to Hubs. 

**To Reproduce**
1. Go to hubs.mozilla.com on Chrome or Firefox on iOS
2. Observe that the unsupported browser message appears

**Expected behavior**
The unsupported browser message only appears when I attempt to enter a room on the devices. Perhaps the 'Create Room' button is inactive on unsupported browsers, and replaced with a message about needing to use Safari. 

**Hardware** 
 - Device: iPhone 11 Pro
 - OS: iOS 13.6
 - Browser: Firefox, Chrome

**Comment by takahirox** [comment]
Now Hubs works on iOS Chrome and Firefox. I think we can close this issue.
