### ISSUE TITLE
Importing a legacy .spoke project on Spoke wipes out current project.

### ISSUE THREAD

**Issue by yuriaru** [mozilla/hubs#2697]
**Description**
Updating an existing Spoke project by importing a legacy .spoke project from another instance, creates a new project and also a different scene and scene id.  This is problematic because it should only be an update and not a new project.

**To Reproduce**
1. Go to an existing Spoke project.
2. File >Import legacy .spoke project to import an update.
3. When saving the project and/or publishing the scene, Spoke will create a new project from scratch and therefore a new scene. This can be seen on the new URL generated.

**Expected behavior**
Updating with an import, should keep existing project info and scene.

**Hardware** 
 - Device: Desktop
 - OS: [e.g. OS
 - Browser Firefox

**Comment by misslivirose** [comment]
This should be fixed with https://github.com/mozilla/Spoke/pull/1000 and https://github.com/mozilla/Spoke/pull/1005. Thanks for filing!
