### ISSUE TITLE
Move 'Favorites' button to the Settings menu and use that UI for an 'Emote' button

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2707]
**Is your feature request related to a problem? Please describe.**
Room favorites are a relatively little-used feature, and the action of favoriting or unfavoriting a room is likely to happen with less frequency than emoting, which tends to happen regularly throughout conversations in a room. This feature proposal is to move the 'Add to Favorites' star icon from the bottom left corner of the UI, and replace it with an emote button that will replace having the emote menu open with the space bar. Users would then be able to add or remove a room from their favorites from the Settings menu in the top-left corner. 

Mockup: 
![image](https://user-images.githubusercontent.com/4313320/88441337-a93fbf00-cdc5-11ea-9ed8-2f27db30f494.png)

This would allow users to toggle emotes independently from the other object menus.

**Comment by gfodor** [comment]
Might want to check the stats, fyi the favorite feature seemed used quite a
bit

**Comment by misslivirose** [comment]
We could also move the ? icon content (it just triggers the FTUE tutorial and point to docs) into settings, and then use emote on that space instead.

**Comment by misslivirose** [comment]
No longer applicable to new UI design
