### ISSUE TITLE
Screen share disappeared on iPhone

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2723]
**Description**
While in the Monday Project Call, the screen share being used to play back the video disappeared only for me. I could still hear the audio and see the avatar of the user who was screen sharing, but the screen share itself was gone.
 
**To Reproduce**
Unknown 

**Expected behavior**
The screen share does not disappear, and in the event of a network issue or disruption, Hubs attempts to reconnect to the screen share during the recover process. 

**Hardware** 
 - Device: iPhone 11 Pro
 - OS: iOS 13.6
 - Browser: Safari 

**Additional context**
The screen share was still visible to other users in the room

**Comment by netpro2k** [comment]
Just to clarify. So you were seeing it for some period of time, and then all of a sudden it went away? Did it still have menus in pause mode?

**Comment by misslivirose** [comment]
I was seeing it previously, yes. I didn't check to see if it still had menus when in pause mode. I'm going to close this given the age of the bug but will file a new one if I hit it again.
