### ISSUE TITLE
Hubs wirelessly on Quest from Virtual desktop

### ISSUE THREAD

**Issue by PauGuardiolaNet** [mozilla/hubs#2728]
Is it possible to get into Hubs in VR with the Oculus Quest using a PC wirelessly with the app Virtual Desktop on Firefox? I can with the link cable but what about wirelessly? This will open a whole new world of possibilities!

**Comment by brianpeiris** [comment]
Closing, since this is quite old, and is better suited as a discussion if it still doesn't work with Quest 2.
