### ISSUE TITLE
Turn off chat bridging for hubs cloud discord bot

### ISSUE THREAD

**Issue by camelgod** [mozilla/hubs#2731]
**Is your feature request related to a problem? Please describe.**
I understand that the chat bridge is core functionality of the bot, but bridging all messages in a room feels a bit invasive for user privacy in some cases. 

**Describe the solution you'd like**
 I'd only like images, join/leave and stats to be posted in discord. An option to turn off the chat bridge, while keeping only the join/leave announcements and the stat announcement. Also being able to only allow image posts would be ideal in my case. Basically some options for the bot.

**Describe alternatives you've considered**
I've checked the docs but cant seem to find anything on this. I've tried to restrict certain permissions but it behaves basically the same.

I ended up just commenting out the sendmessage stuff in the habitat package for hubs-discord-bot, but would be nice to manually configure this somewhere.

**Comment by misslivirose** [comment]
Hey @camelgod - This feature request is being tracked in https://github.com/MozillaReality/hubs-discord-bot/issues/83 - I'm going to resolve this one but am linking your message to the issue tracking on the bot repo itself. 

Thanks for the feedback!
