### ISSUE TITLE
create a W3C Web-App Manifest

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#274]
In order for Chrome + Firefox for Android to detect a web page as a Progressive Web App (PWA), it needs a Web-App Manifest, a Service Worker (it can be empty to start), and served over HTTPS.

Here's an example of a typical manifest: https://w3c.github.io/manifest/#example-manifests

I can open a PR for this; I just wanted to see if there are vector favicons to use first. Also, if you have screenshots, you can send them to me or attach them to this issue.

**Comment by misslivirose** [comment]
@gfodor can this be closed per #1380?

**Comment by brianpeiris** [comment]
Yup, I think we can call this closed now.
