### ISSUE TITLE
Buffering Issue with Twitch Livestream

### ISSUE THREAD

**Issue by gregorourke** [mozilla/hubs#2752]
**Description**
Very choppy unreliable video (audio and/or video pausing) with dropouts when streaming live video from Twitch into Hubs room with Twitch video placed in scene with Spoke. Tested with 30 people (about 15 people each across 2 duplicate rooms) and 80% of participants experienced occasional to severe dropouts during event. 

Got users during event to leave Hubs room and switch to watching the stream to a simple webpage using Twitch video embed. Users reported no issues with stream on the webapge, only in the Hubs room. 

**To Reproduce**
Subsequent extensive testing today I could replicate error even with just myself only in the room (using Firefox on Mac):

- I first setup a test stream using my very fast broadband connection, streaming into room with Twitch video embedded in scene using Spoke. Result: slight dropouts when first entering Hubs room which then resolves to no issues. No issues on video embed on the simple webpage on my site when I viewed the video there.

- Then repeated the process but using 3G mobile connection for internet connection instead. Result: Very choppy video in Hubs room that did not go away. BUT there were no issues on video embed on the simple webpage on my site when I closed the Hubs room and switched over to that.

**Expected behavior**
Expected Twitch live video stream to be of same quality regardless of whether the video was embedded on a webpage or embedded in a Hubs room.

**Hardware** 
 - Device: Users during concert were using Apple or PC desktop and laptops - no one used a mobile device.
 - OS: All
 - Browser: All (Out of all browsers, Chrome seemed to perform the best)

**Additional context**
Could the bufferSize property in the Twitch API you are using might be set too low in Hubs code? (Sorry I'm not a developer so don't know how to inspect the code) - https://dev.twitch.tv/docs/extensions/reference

Because the user experience in this event was poor for so many users I think that if the bufferSize property is the issue, the buffer should be set higher (or have a 'Buffer Size' property in Spoke for Twitch livestreams that room designers could set themselves) so as to ensure the same playback quality as when watching the video on the standard embed on a webpage.  I know that might put more of a delay on the stream but I think it's much better if it takes a little while for the stream to load on room entry and then play smoothly rather than have choppy video throughout stream (currently the performance in Hubs as it is would render Hubs unusable for my application unless this is resolved).

**Comment by vjFred** [comment]
Same issues and users have to relaunch the hub continuosly for audio/video issues
