### ISSUE TITLE
Easier way to access 'Only Show Nametags When Frozen'

### ISSUE THREAD

**Issue by gregorourke** [mozilla/hubs#2753]
Recently held an online event where attendees complained the nametags were getting in the way of watching a video screen. Could there be a hotkey to hide the nametags (e.g. 'N' key), or otherwise listed in the main menu under the hamburger 'E.g. Hamburger>People>Hide Nametags ? Many users reported this issue.

Also the wording 'Only Show Nametags When Frozen' is hard for new users to understand. Simply the menu option saying 'Hide Nametags' is easier to understand.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-230)

**Comment by keianhzo** [comment]
After the latest name tag work this is now available as long as other name tag visibility options in the settings.
