### ISSUE TITLE
add an empty Service Worker file (for browsers to detect as a PWA)

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#276]
1. create a file at the web root called `sw.js` (and just leave it blank)
2. add code in [`src/index.js`](https://github.com/mozilla/hubs/blob/58e8e508/src/index.js#L10) to just call the Service Worker: `navigator.serviceWorker.register('./sw.js')` (you can borrow some code from [here](https://github.com/mozilla/unity-webvr-export/blob/e08ad53/Assets/WebGLTemplates/WebVR/webvr.js#L29-L41)

I can open a PR for this, if it's cool with y'all

**Comment by gfodor** [comment]
we have a service worker now for Web Push
