### ISSUE TITLE
Sign In Modal color contrast, difficult to read on dark mode

### ISSUE THREAD

**Issue by yuriaru** [mozilla/hubs#2773]
**Description**
Hub instance is set with Dark Mode on Theme settings. Clicking on the "Sign In" link on the landing page, pops up the Sign-In modal, in which the text is not readable.

**To Reproduce**
1. Go to Admin and enable Dark Mode on Theme settings.
2. In a different browser session, on the landing page click the "Sign in " link.
3. Modal will appear but text is not readable.

**Expected behavior**
Text should be readable on modal as is in the case once you create a room and try to change the scene or room settings. At that point modal shows fine and text is readable, but when you try to click "Sign In" directly from the home page, the modal shows with white background and very light gray that makes the text unreadable.

**Screenshots**
Landing Page, after clicking "Sign In"
<img width="598" alt="Screen Shot 2020-08-03 at 11 06 26 AM" src="https://user-images.githubusercontent.com/49990079/89208666-c9703a80-d58a-11ea-89b7-83af4841fbc9.png">

Other pages, once you created a room
![Screen Shot 2020-07-31 at 12 49 46 PM](https://user-images.githubusercontent.com/49990079/89208953-5d420680-d58b-11ea-9d29-39172397e218.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-391)

**Comment by Namanl2001** [comment]
Hey, can I work on this issue?

**Comment by yuriaru** [comment]
Yes sure

Sent from my iPhone

On Oct 4, 2020, at 7:07 AM, Naman Lakhwani <notifications@github.com> wrote:

﻿

Hey, can I work on this issue?

**Comment by Namanl2001** [comment]
@yuriaru Thanks. As I am new to this project, can you please guide me, how to proceed further? Which particular files to look into?

**Comment by Yashs911** [comment]
Hi @yuriaru I would like to work on this issue. Can you please guide me on what all changes do I need to make and in which file?
