### ISSUE TITLE
How to distinguish waypoints in javascript code?

### ISSUE THREAD

**Issue by zhaozj89** [mozilla/hubs#2783]
I would like to control the character along several waypoints pre-set in spoke. I use the following code to get all waypoints:

    let s = document.querySelector("a-scene");
    let objects = s.sceneEl.object3D.children;
    for(let i=0; i<objects.length; ++i){
        let obj = objects[i];
        if(obj.hasOwnProperty("el")){
            let el = obj.el;
            if(el.classList.contains("teleport-waypoint-icon")){
                // collect waypoints
            }
        }
    }

But I do not know the order of the waypoints. `obj`'s name property is empty. 

So I would like to ask if there is a way to distinguish waypoint objects? Or the way I used to collect waypoints is correct? Thanks.

**Comment by johnshaughnessy** [comment]
You will probably want the associated `object3D`'s so you can look at the name and its position/orientation in the world:
```
{
  // Collect waypoint data
  const elements = [];
  const components = [];
  const object3Ds = [];
  const names = [];
  document.querySelectorAll("[waypoint]").forEach((element)=>{
    elements.push(element);
    components.push(element.components.waypoint);
    object3Ds.push(element.object3D);
    names.push(element.object3D.name);
  });
  console.log(elements);
  console.log(components);
  console.log(object3Ds);
  console.log(names);
}
```

**Comment by zhaozj89** [comment]
Solved. Thank you!
