### ISSUE TITLE
Add preference to change audio/microphone devices that are used by Hubs

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2799]
**Is your feature request related to a problem? Please describe.**
Right now, the only way to change the microphone and audio output devices that I am using with Hubs is to refresh the page and change them as part of the room entry flow. We should have a section in the preferences panel that allows us to change our microphone and audio out so that we can narrow down issues with devices being mis-selected without needing to refresh, reload, and re-enter the room, or allow us to change devices without disconnecting entirely.

**Describe the solution you'd like**
A section in the preferences menu where I can see which devices I am currently using, and change them. This will likely need a new browser permission prompt, but that seems acceptable to me if I don't need to refresh the page, especially since refreshing the page doesn't always fix my issue. This could also live in the mute/unmute section of the UI to make it more discoverable.

**Additional context**
I was playing with https://janus.conf.meetecho.com/devicetest.html which seems to indicate that this is technically possible without a page reload.

I am not totally clear on whether this would be needed at this time with VR headsets or mobile phones, since those feel less likely to have as many potential audio in/output settings as a desktop PC would.

**Comment by keianhzo** [comment]
@misslivirose I've added support for this in Preferences.

**Comment by reganMoz** [comment]
For what I understand these are mostly UX issues at this point after mic selection has landed. I see a few things that we should do to improve the overall audio selection experience:

    Improve the Mic selection discoverability. We currently expose the mic selection menu in the audio preferences but that's not really easy accessible by the user and needs to go through a few hops. Most of the apps expose it in a builtin menu in the Mic button.
    Expose output selection where available. As commented above mostly only Chrome has a mechanism to select the output device right now so we should expose a conditional way to select that too. Most of the apps expose it in the same menu as the mic input selection.
    Better audio issues recovery. Right now when the mic gets disconnected (ie. the bluetooth headset runs out of battery) we just mute the mic. We should either switch to the next available mic and warn the user that the mic input has changed or open the mic selection menu so they can choose another mic.

**Comment by keianhzo** [comment]
Closing this in favor of https://github.com/mozilla/hubs/issues/1826 as it's already landed
