### ISSUE TITLE
"Report Issue" link in room menu is broken

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#2821]
**Description**
Looks like we lost the UI for the report dialog on the main page during the react refactor (#2460). The [ReportDialog component](https://github.com/mozilla/hubs/blob/master/src/react-components/report-dialog.js) still exists, but it is not used anywhere. The report dialog was also accessible from a link on the front page, but that has been removed as well. Not sure if that was intentional.

**To Reproduce**
1. Go to any room.
2. Open the room menu
3. Click on "Report Issue"
4. That takes you to the front page, but no report dialog is shown.

**Expected behavior**
We should reintroduce some equivalent UI for info about reporting issues, or maybe just link to https://hubs.mozilla.com/docs/help.html

**Comment by aychtang** [comment]
Hey @brianpeiris, I can try to take a look at this if you like. My team started using hubs for standups so would be happy to help out a bit.

**Comment by brianpeiris** [comment]
@aychtang Sorry for the delayed reply. I'm actually not sure what we want to do with this link. But I'll find out and fix it today.
