### ISSUE TITLE
Vimeo videos with sound won't load or stream

### ISSUE THREAD

**Issue by brunomartelli** [mozilla/hubs#2865]
![90070900-8d587a80-dcec-11ea-820d-4397f8cfa623](https://user-images.githubusercontent.com/4471896/90311820-18a55c00-def7-11ea-98bc-ae8a7a8d2743.png)
**Description**

**_Vimeo videos with sound won't stream_**. Vimeo videos without sound will

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'vimeo.com' choose   a video with sound, that has permissions enabled to be embedded and downloaded
2. Add the video link in Spoke
3. video shows broken link
4. Next load of the project in Spoke throws up 'FFMpeg Demuxer' or 'Failed to Init Decoder' error.
5. Video does not show up in Hubs.

Then try with a video with no audio, and the video will load then you can watch it in Hubs.

**Expected behavior**
Expected video with sound to load in Spoke and Play in Hub

**Screenshots**

**Hardware** 
 - Device: PC
 - OS: Windows
 - Browser: Firefox

**Additional context**
Have tried various format videos with AAC or MP3 sound etc. No luck. Also not possible to load Vimeo video URLS directly into a Hub room as a 'user'

**Comment by InfiniteLee** [comment]
Thank you for your report. We will be tracking this issue in the spoke repo via https://github.com/mozilla/Spoke/issues/964
