### ISSUE TITLE
Support waypoint anchor short-hand links with 'Go To' button

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2898]
**Is your feature request related to a problem? Please describe.**
It's possible to use the new waypoint anchor feature (#2837) to create a teleporter link that can jump you into a new waypoint without clicking on it as seen in the attached gif. However, right now it uses the full qualified URL for the room, so the button on the link image says "Visit Room", which implies navigating to a new room entirely. 

**Describe the solution you'd like**
This is a two-part feature request, but the first part would still help significantly though I'm not entirely sure how feasible it is. It would be awesome to have a different string on the button when it is a teleport link instead of a new room (for example, saying something like 'Go To' or 'Teleport' or 'Go' or even just dropping to 'Visit' instead of 'Visit Room') so that when a user hovered, it would be more clear that it wouldn't necessarily open a new room. 

The second part is presumably more complex, but it would be great to just be able to specify the desired anchor point (e.g. `#WayPointName` ) in a link element (or other custom element) that had the correct button associated with it. I'm not sure it's entirely necessary at this point, but it would great to have this for scenes so the teleport functionality would work even without having to change it for individual rooms. This way, if a link element (or new, custom element) detected that the link was just the waypoint anchor, it would automatically navigate to the waypoint for that specific room if it existed. 

**Additional context**
![Teleport-Small](https://user-images.githubusercontent.com/4313320/90837788-e71dfd80-e307-11ea-9b88-93e13fc4952c.gif)

**Comment by Charlesc22** [comment]
Love this idea Liv!
I just made a room with anchors from your video. Worked great. This opens up lots of possibilities!
