### ISSUE TITLE
Hubs has audio issues on Oculus Quest using Oculus Browser. Suggest adding message: "Works best in Firefox Reality""

### ISSUE THREAD

**Issue by markvandenbergen** [mozilla/hubs#2905]
The hardware button to adjust audio the volume of the Quest headset does not work when within a Hub VR scene. So if you enter the scene with the headset volume down, there is no way to turn it up. You have to exit the hubs scene - turn up your headset volume, then re-enter the hubs scene. But it is not an obvious fix, so most people will just think it's a Hubs bug.

**Comment by blairmacintyre** [comment]
One problem is that Oculus browser is faster, so it supports more complex rooms, more avatars, etc.  so, it's a tradeoff.

**Comment by christianprison** [comment]
We are organizinig a bigger event (Virtual Germany #4) on April 28th. Maybe one of the contributors would like to join us and see for him/herself what is the problem with the Quest? I dont remember it exactly but if I'm not totally wrong, the problem persisted even after switching to Firefox Reality. And I was on Quest 2 at least!

**Comment by goatchurchprime** [comment]
I've encountered this problem too.  It could be related to an issue with Parties.  

If you set up a Party with other people on the Quest and enter Hubs, Hubs does not capture the audio and turn off the Party audio, and you get an echo -- you hear the other person's voice twice.  

Usually when you join a multiplayer networked game on the Quest with a Party set up, there's a message that says your Party audio has been turned off on account of the audio between players being done by the game (as it is with Hubs).  Whatever this setting is, it should be turned on for Hubs (if it is accessible to a web-app like it is for a native app).  

It is possible that there is a confusion in the system and the volume button is controlling the external Party audio and not the in-game audio.   Same thing can happen on phones, where it can get confused as to whether the volume buttons control the speaker audio, the ringtone, or the music that was playing before you picked up the phone.
