### ISSUE TITLE
Preference list checkboxes don't update visuals

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2922]
**Description**
Clicking on preference checkboxes should immediately update the visuals and the underlying preference in local storage. It appears that clicking the buttons DO update the local storage, but the visuals do not update.

**To Reproduce**
1. Go to preferences page
2. Click on a checkbox
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/4072106/91209134-1d6ccb80-e6c0-11ea-8eb0-f33cc91b091b.png)

**Hardware**
 - Device: Desktop
 - OS: Linux
 - Browser: Firefox

**Comment by InfiniteLee** [comment]
Seems to have been caused by this commit: https://github.com/mozilla/hubs/commit/40a355f69794bb3da2317714320385a535c1bcbe
