### ISSUE TITLE
Set quality setting with query string parameters (again)

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2937]
**Is your feature request related to a problem? Please describe.**
We used to set the quality setting with a query string parameter. I removed this feature when adding the preference screen, thinking that it was best left as an end-user feature, and didn't want there to be confusion on the part of the end user in cases where the query string parameter did not match the user pref.

**Describe the solution you'd like**
Re-enable the ability to set quality via query string parameter. If end user has a specific preference saved, I think the user pref should take priority, but if the user does not have any preferences, the query string parameter should take precedence.

**Describe alternatives you've considered**

**Additional context**
Crimson's team ran into this problem because they wanted people's default quality setting to be "low" instead of "high" but couldn't do this with the query string parameter.

Also update the docs when doing this : https://hubs.mozilla.com/docs/hubs-query-string-parameters.html

**Comment by lue** [comment]
Hi, @johnshaughnessy

Sorry, I am a bit confused. Should ?default_material_quality=low string parameter work right now on hubs.mozilla.com ? I tried and it does not seem to force low settings.
