### ISSUE TITLE
Link to outside URLs

### ISSUE THREAD

**Issue by emilianodelau** [mozilla/hubs#2987]
Currently when you import a URL into a Hub the rendered image is a preview of the page. This can be pretty ugly, as seen in the attached screenshot. I would like to upload any image or 3D model and associate a URL to it so that when clicked it opens that Web page in a separate tab. It would be nice to choose between opening in a separate tab the same tab, or separate window.

<img width="971" alt="Hubs URL Issue" src="https://user-images.githubusercontent.com/5191664/92513410-402dd280-f1de-11ea-992a-15c1d0430d07.png">

**Comment by davegoopot** [comment]
See discussion at #2979

**Comment by misslivirose** [comment]
This feature request is being tracked in #2933. I’m going to resolve this as a duplicate but it will be linked in the other issue. Thanks for filing!
