### ISSUE TITLE
in prod: should FPS counter be hidden (by default)?

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#299]
https://hubs.mozilla.com/0erc6knwehp/sophisticated-exhausted-safari

![image](https://user-images.githubusercontent.com/203725/39281988-5d8a4ad4-48bc-11e8-92fa-d2cf250c7567.png)

**Comment by cvan** [comment]
upon click, it shows the A-Frame counter which is a tad ugly. perhaps adding a **Debug Mode** toggle from the Help (?) modal? (and just flip a value in `localStorage`?)

**Comment by brianpeiris** [comment]
I felt it was important for us to keep an eye on performance and keep us honest about it as well. It's also useful for users to report actual FPS numbers when performance degrades.

**Comment by cvan** [comment]
totally. makes sense. it's also a nice performance "dog whistle" - to folks who know FPS, they'll be impressed (in ideal scenarios :smile:). what about `https://hubs.mozilla.com/0erc6knwehp/sophisticated-exhausted-safari?debug`?

**Comment by gfodor** [comment]
feeling like scope of this ticket has creeped -- if we want to enable a "developer mode" I think that deserves a dedicated ticket since it adds a lot of incidental complexity to the whole app. the nice thing about the way it works now is its easy to tell people what to do if we would like to have them give us more diagnostic info. mind closing?

**Comment by cvan** [comment]
to me (admittedly a user of the Web for two decades), it seems like an oversight (debug pushed to prod). but I can totally see how it's also a nice dog whistle for those who understand perf/diagnostics (gamers, devs, and humans alike).

my biggest question would be still, why is it shown in 2D only but not in VR? (that is, how will people identify the framerate/etc. with standalone headsets?)

personally, I'd hide it behind a `#debug` or `?debug` flag. but totally understood, closing given the consensus here. filed issue #357 for a possible Developer/Debug Mode. :+1:
