### ISSUE TITLE
Avatar audio should be decoupled from the loading of the GLTF model / head node

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#3004]
**Description**
If an issue causes an avatar not to load on the page, the user cannot be heard. We should decouple the audio from being dependent on the avatar loading, so that the client is more resilient to server loading 502/504 errors.

**Comment by misslivirose** [comment]
An additional thought - can we have a placeholder in the client (similar to the broken media image) that we use if an avatar fails to load that would work to indicate someone is there while still getting their audio?

**Comment by johnshaughnessy** [comment]
Oops -- I did not mean to add this to Hubs 2020-Q3. I clicked that on accident

**Comment by keianhzo** [comment]
What would be the right avatar to be used as a place holder?

**Comment by misslivirose** [comment]
Great question! I would love to get some design thoughts on that. I would imagine that something like a default robot would be good, potentially with imagery tied into #1747 - so that we have consistent messaging about "failed to load" resources. Maybe something like this, but with any updated media iconography that results from 1747.
![image](https://user-images.githubusercontent.com/4313320/93916749-d96ce680-fcbe-11ea-9813-811e2ae663c5.png)
