### ISSUE TITLE
Mail server failed to start (?) on Enterprise stack

### ISSUE THREAD

**Issue by MegaMotion** [mozilla/hubs#3024]
The backstory: I started a Personal stack on my AWS account, then realized that it did not allow multiple servers, which I potentially want to have, so I deleted this stack and added a new Enterprise Multi-Server stack. Everything went smashingly until I tried to sign in to my new stack, but I waited and waited and the email never came, when previously it only took a few seconds. I don't recall my exact timing but I *may* have started creating the enterprise stack before the personal stack had finished deleting, and they are using the same URL and credentials - is there any chance the first one failed to let go of a resource by the time the second one needed to have it, or something? 
Thanks!

**Comment by robin-k-wilson** [comment]
It's certainly possible you had collisions with dependencies on the Personal deleting stack + Enterprise spinning up stack is possible. AFAIK, the resources aren't locked down while one is using it or the other is adding to it. 

In a perfect world, I'd suggest you delete the Personal stack first. Check your domain's Hosted Zones for left over CNAMES + MX records from the old Personal Stack, delete those mentioned in [Solution 4 here](https://hubs.mozilla.com/docs/hubs-cloud-aws-troubleshooting.html#potential-solutions). Then spin up the Enterprise stack.

**Quick checks for you:**
1. Check that your admin email address is verified with amazon: https://hubs.mozilla.com/docs/hubs-cloud-aws-troubleshooting.html#in-my-hubs-admin-panel-i-see-networkerror-or-not-found-page-or-no-data-populates-in-any-of-the-admin-menus

2. In aws console SES, can you double check that an email is being sent when you try to login?

3. Add email addresses manually (Solution 1) so SES will send the email to them: https://hubs.mozilla.com/docs/hubs-cloud-aws-troubleshooting.html#solution-options

**Comment by robin-k-wilson** [comment]
Should be in discussions, see https://github.com/mozilla/hubs/discussions/3025
