### ISSUE TITLE
RFE: Scene change should have some default scene loading with a horizon in between scene changes

### ISSUE THREAD

**Issue by truedat101** [mozilla/hubs#3059]
**Is your feature request related to a problem? Please describe.**

When changing a scene, if users are in the room, they experience darkness and an experience of  being in black space with no sense of horizon.

**Describe the solution you'd like**
I propose a minimal default scene change scene that includes a horizon of some short.  This is to prevent the abrupt and somewhat frightening experience of being in VR and tossed into darkness for sometimes several minutes depending on the next scene loading.

A simple "grid horizon" without texture should be fine and would load quickly.  I'd recommend each session have this "default" scene pre-loaded so it is possible to switch.

**Describe alternatives you've considered**

Alternative that I think would work would be to snapshot the existing view, and slowly fade it out as the new assets load, and have some form of progress bar indicating "New Scene is loading"

**Additional context**
Some people get vertigo.  The experience of the darkness is very similar to being on a deep dive in the ocean and shutting off the lights.  It is easy to get disoriented.

**Comment by misslivirose** [comment]
Thanks for filing this - I'm copying the information that you shared in the bug that we have tracking proposed changes to the scene change interstitial and resolving this as a duplicate.
