### ISSUE TITLE
vertical scrollbar should not appear in "Get Updates" modal

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#306]
1. load https://hubs.mozilla.com/
2. scroll to the footer of the page
3. click the "Get Updates" link
4. when the modal appears, notice the vertical scrollbars (though there is adequate vertical space on desktop/non-mobile)

<img width="1270" alt="screen shot 2018-04-25 at 8 52 44 pm" src="https://user-images.githubusercontent.com/203725/39284940-a9cbb438-48ca-11e8-936d-8ba4aa7867fe.png">
<img width="1464" alt="screen shot 2018-04-25 at 8 52 54 pm" src="https://user-images.githubusercontent.com/203725/39284947-ad897f2e-48ca-11e8-926e-2d33bb3797b2.png">

**Comment by brianpeiris** [comment]
Fixed in #319
