### ISSUE TITLE
Links don't work on mobile phones

### ISSUE THREAD

**Issue by jessicasymons** [mozilla/hubs#3066]
We are currently developing a community arts festival using Mozilla Hubs where users jump from one hub to another via links.

However, the linking process does not work on mobile phones.

This is a really big issue as the majority of our users will access the community festival via their phones.

Is there a workaround?

I have tried the following:
- Made a URL link using the hub link element
- Inserted an image and put the URL link in the Image url box

Both of these work fine on a computer, they do not work at all on
- Safari IOS (even with popups enabled)
- Samsung Internet

**Comment by misslivirose** [comment]
Hi @jessicasymons - can you try the popup workaround noted in https://github.com/mozilla/hubs/issues/2163 and see if that resolves the issue you're seeing?

**Comment by misslivirose** [comment]
Resolving as a duplicate to be addressed with #3294
