### ISSUE TITLE
Edge Dev and Chrome Canary support full WebXR:  should work with Hubs

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#3076]
**Description**
Hubs must support WebXR, since it runs on Oculus browser on Quest.  But on desktop, any attempt to enter via connected VR headset directs to Firefox.

Chrome Canary and Edge Dev now support WebXR, and it works well.  If you have a Windows MR display, it's actually the cleanest and least friction solution.

**To Reproduce**
1. try to use "connected vr headset" on hubs
2. won't enter vr

**Hardware** 
 - Device: desktop
 - OS: windows 10
 - Browser: Edge Dev or Chrome Canary

**Comment by brianpeiris** [comment]
Closed with #3785. WebXR is actually enabled by default in the stable versions of Chrome and Edge, but only for Windows Mixed Reality devices. 
Note that in the new design, you need to click on the "Enter on Device" button, and then "Enter in VR".
