### ISSUE TITLE
background video is confusing when viewed at mobile width

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#309]
especially the movement of avatar names ("Do" and "Bri") is confusing because of the size of the video (or, rather, what's not shown in the background `<video>` because of the screen viewport).

1. load https://hubs.mozilla.com on an iPhone 7 (or smaller)
2. notice the background video is truncated/hidden/clipped to show the leftmost content: the windmill moving, with the text `Do` shaking at the top and then `Bri` popping out the right every 15 seconds or so 😄

![capture at 320×480](https://user-images.githubusercontent.com/203725/39285488-7cdc4c28-48cd-11e8-8b88-54475ae45b3e.gif)

**Comment by gfodor** [comment]
suggestions? I think we're going to be rotating this video out semi-regularly -- I did notice that on smaller screens we end up stuck in the top left corner like that, but wasn't sure if there was a better CSS method that preserved aspect ratio, etc.

**Comment by cvan** [comment]
I'd recommend the video be played at only `(min-width: 800px)`. anything narrower, and I'd recommend:

1. ideally: swap the video out with a static/still image of the video. (and change `home-root.js` to load it conditionally with `window.matchMedia`.) added-bonus side effect: it would improve load times on mobile.
2. for a quick fix: freeze `videoEl.currentTime` to a reasonable time.

![a decent still](https://user-images.githubusercontent.com/203725/39552204-1410e488-4e1d-11e8-8ba7-45d912b951ba.png)

**Comment by robertlong** [comment]
I agree with @cvan we probably want to show a static image below a certain width. Also we haven't swapped out the video yet 🙂

**Comment by brianpeiris** [comment]
Looks like we changed the layout at some point so that the video is no longer cropped in a confusing way, so I'm going to call this one closed.
