### ISSUE TITLE
Name Tag Update

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#3110]
**Background**
In Hubs, there is often information that we want to understand about other visitors in a room. Currently, we display the following information in a panel above each avatar’s head as part of their “name tag”:

- Display name - all users
- Identity - if set in Hubs Cloud, only in pause mode
- Discord ID - if bridged to a Discord room, only in pause mode
- A star icon if the user is a moderator or the room owner
- A recording icon if the user is broadcasting their perspective to the lobby  

By default, name tags are always visible, but there is a preference that can be turned on so that individual users can set their client to only display name tags when they are paused (via the spacebar or tab menu).

**Status**
In addition to states that are visible in the name tag, the ‘user list’ also shows whether or not users in the room have their microphones muted or not. If a user is speaking, they have a volume indicator present in the user list. 

**Feature Update**
We have had a number of requests filed based on community feedback and want to consider an update to the way that we display important information about other room attendees. These range from stylistic choices (for example, the ability to customize the appearance of name tags, or change the size of the name tags) to wanting additional information surfaced (for example, an ‘Away from Keyboard’ tag if the user is tabbed away from the Hubs room, or to have the muted indicator more visible in the space). 

Story | Priority | Exists in-client today?
-- | -- | --
As a visitor to a room, I want to know the display name that is linked to different avatars so I can tell who is who. | P0 | Yes, in the user list and in name tags
As a visitor to a room, I want to know who is talking | P0 | Yes, dependent on the avatar that the user is wearing, and in the user list
As a room moderator, I want to easily be able to see whether or not someone in the room is muted. This allows me to help them troubleshoot their own audio if they are talking and others cannot hear them. | P1 | Yes, in the user list
As a room visitor, I want to know who in the room is an owner / moderator | P1 | Yes, in the name tag and user list
As a room visitor, I want to know if someone is recording from their POV to the lobby | P1 | Yes, as an icon above the name tag
As a room visitor, if there is additional information associated with a user (e.g. an identity or account name) I may want to see that information | P2 | Yes, in pause mode in the name tags
As a room visitor, I may want to know if another user is AFK or otherwise not fully present in the room | P2 | No

**Considerations**
Information surfaced in the name tag or elsewhere in the client about another user should respect the privacy of the other user. In some cases, it may be desirable to allow a user to opt in or out of having certain types of information shared in their name tag. 

**Related issues**
General suggestions for name tags: #79
Add AFK / auto-AFK information: #2253
Surface ability to hide name tags more easily: #2753
Add voice or mute indicator to name tag: #2665
Add non-avatar based indication for speaking users: #2533
Bug: Name tags look unusual with artifacts on Mac #2388

**Existing Designs**
The following designs show what name tags currently look like in the Hubs client by default. Left: the default name tag indicator with a moderator star. Center: the default name tag indicator in pause mode. Right: The mute information and information about the device a user is on as it appears in the user list. There are also moderator stars on the user list.

![image](https://user-images.githubusercontent.com/4313320/94844620-5ee54a80-03d3-11eb-9de8-6ca3a095489e.png)

**Next Steps**

1. Identify the best way to associate a non-avatar based indicator for speaking/mute, and resolve #2665 and #2533 as a single issue with the design we have landed on. 
2. Produce a unified design for new name tags, either a single design or a set of several that users can choose from in a preferences menu that also improves how we surface the ability to hide name tags altogether.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-422)

**Comment by misslivirose** [comment]
@mbransn & team - 

This is a "work to do at some point" update that we will need to do in the future, but not one with an immediate/urgent priority. If it would be helpful to have a dedicated meeting to discuss this and how we surface information about users in Hubs, I can schedule something but also fine with skipping if this is enough detail and we can work async on it. Still learning our new processes! 🙂

**Comment by mbransn** [comment]
Thanks @misslivirose this is a great summary brief to work from. Agreed re: priority and I'm inclined to potentially triage this as part of experience strategy work that will touch onboarding and avatars. Let me work with @malqinneh on some prioritization on the DPX zenhub side. It may be that we phase this and break it out into multiple issues, will get back to you. In the meantime if this becomes higher priority just shout.

**Comment by netpro2k** [comment]
One other thing that came up recently is that we might want to be able to right click on the nametags to inspect. Right clicking on the avatars themselves to do this is problematic sine skinning makes determining avatar bounding boxes difficult, and also avatars can easily get in the way of other objects. Using the nametag (or part of it) would make this easier.

**Comment by camelgod** [comment]
Maybe consider this related if you are going to rework the design: https://github.com/mozilla/hubs/issues/2672

**Comment by misslivirose** [comment]
#2672 is part of the design for the avatar / user menu, rather than the name tags, so I think that it's a separate design rather than the elements that will specifically be displayed over a user's head the whole time. That said, we do have a desire to update that flow as well.

**Comment by netpro2k** [comment]
It is worth noting that the current awkward spacing of the nametag is to accommodate the in-world volume controls. There is not any sort of hard technical reason the nametag couldn't be positioned differently in pause mode to accommodate them, but just worth thinking about.

**Comment by mcroud** [comment]
Name Tag ideation work shared with the team yesterday.
The Figma work is available [here](https://www.figma.com/file/2IEPYkghXGvVsCJc3rFOgt/Name-Tag-Update?node-id=162%3A0) for further comments and feedback.

**Comment by keianhzo** [comment]
This feature request might have evolved over time and the recent implementation diverges from the original requirements. I think we can probably close this and open new issues with new feature requests based on what we currently have.
