### ISSUE TITLE
Inspect yourself: I have no head!

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#3115]
Some avatars are fine: 
![image](https://user-images.githubusercontent.com/4072106/94976238-29bb2400-04c9-11eb-91c5-d5498fab09ac.png)

But some avatars are headless:
![image](https://user-images.githubusercontent.com/4072106/94976227-1dcf6200-04c9-11eb-884a-1343b84fad9c.png)

What gives?

**Comment by yakyouk** [comment]
Looks like the head is always visible as long as we don't change avatars after loading the page, but always disappears after changing avatars.
