### ISSUE TITLE
The members list is not dismissed by clicking outside its borders after the first attempt

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#3139]
**[Affected Versions]:**
- Firefox Release 81.0.1.
- Chrome 86.0.4240.75

**[Affected Platforms]:** 
- Windows 10x64

**[Prerequisites]:**
- The https://hubs.mozilla.com/ website is opened. 
- You are logged in your hubs account and a room is opened.

**[Steps to reproduce]:**
1. Click the "Members" button from the top right
2. Click outside the list borders to dismiss it.
3. Click again on the "Members" button.
4. Click outside the list borders to dismiss it again.
5. Observe the behavior.

**[Expected results]:**
- The list is dismissed every time.

**[Actual results]:**
- The list is not dismissed in the second attempts.

**[Notes]:**
- This issue is not reproducible when dismissing the list by clicking the "Members" button again.
- I was not able to test this issue on MacOS, Linux or mobile devices.
- Attached is a screen recording of the issue:
![DismissMembersMenu](https://user-images.githubusercontent.com/40061643/95567603-d6e2ee80-0a2b-11eb-9973-5d45727d2fa7.gif)

**Comment by misslivirose** [comment]
Thanks for filing! 

Since we are redesigning this UI (#3148) I'm going to resolve this 'won't fix' in the current UI, but it will be addressed in the new one.
