### ISSUE TITLE
add text tooltip text for HUD/UI buttons (improving `title` attribute text)

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#314]
improving upon PR #279 which added labels to the HUD icons via `title` attributes… (which was a great addition :+1:)

when a Hub scene loads, it'd be nice if text labels appear below the icon (just like they do in the _Help_ graphic). they could then fade out after a few seconds when the page is interacted with. have the text labels re-appear if the user taps (on mobile) or hovers on desktop/non-touch devices in, say, the top `25vh` of the page.

relying on browsers' `title` attributes IMO isn't an obvious-enough method. they take a long time to show up, they're small, they work on only desktop (i.e., devices with a mouse pointer to hover, or screen readers), and so on.

an alternative to what I suggested in the first paragraph, something off the shelf could be used, such as [`tippy.js`](https://atomiks.github.io/tippyjs/) or [this van11y one](https://van11y.net/downloads/simple-tooltip/demo/), to get the desired effect.

<img width="1386" alt="screen shot 2018-04-25 at 9 52 53 pm" src="https://user-images.githubusercontent.com/203725/39286515-3b8b6f3c-48d3-11e8-8a51-160cb30dfa6f.png">

<img width="1386" alt="screen shot 2018-04-25 at 9 52 56 pm" src="https://user-images.githubusercontent.com/203725/39286518-4069a410-48d3-11e8-8bf1-22323df3a43d.png">

**Comment by joshmarinacci** [comment]
Don't we do this now?

**Comment by misslivirose** [comment]
Closing this as UI redesign will address this
