### ISSUE TITLE
Add Privacy Notice + ToS to bottom of Help dialog

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#315]
1. load https://hubs.mozilla.com/
2. notice the _Mozilla_, _Mozilla Mixed Reality_, and _View Source_ links in the header
    <img width="1270" alt="screen shot 2018-04-25 at 10 09 27 pm" src="https://user-images.githubusercontent.com/203725/39286899-5fd43e44-48d5-11e8-8f75-2f8b91143407.png">
3. scroll down to the footer to notice the following: _Terms of Use_, _Privacy Notice_, and the _made with 🦆by Mozilla_
    <img width="1270" alt="screen shot 2018-04-25 at 10 09 29 pm" src="https://user-images.githubusercontent.com/203725/39286898-5fa7e1a0-48d5-11e8-9490-1589e375b0ea.png">

<hr>

1. load https://hubs.mozilla.com/0h6bsjd7ofz/snoopy-soft-festivity
2. notice there is no Mozilla branding (nor _Terms of Use_, _Privacy Notice_, and _View Source_ links; I could be missing them somewhere though)
    <img width="1270" alt="screen shot 2018-04-25 at 10 10 44 pm" src="https://user-images.githubusercontent.com/203725/39287007-2382d0bc-48d6-11e8-858b-7334f1028707.png">
    <img width="1270" alt="screen shot 2018-04-25 at 10 10 39 pm" src="https://user-images.githubusercontent.com/203725/39287008-2399c038-48d6-11e8-8b2d-5aaba2877cd6.png">
    <img width="1270" alt="screen shot 2018-04-25 at 10 10 37 pm" src="https://user-images.githubusercontent.com/203725/39287009-23b33702-48d6-11e8-83a3-0a05232153fa.png">
3. is that intentional? (if so, apologies for filing this issue!)

notice the interstitial avatar-selection screen does though show the _Terms of Use_ and _Privacy Notice_:
<img width="1270" alt="screen shot 2018-04-25 at 10 01 43 pm" src="https://user-images.githubusercontent.com/203725/39286961-d112daa2-48d5-11e8-93aa-2cbb5bf83e24.png">

**Comment by gfodor** [comment]
I've updated the title to reflect the actionable item for this
