### ISSUE TITLE
3rd party avatars are not becoming transparent when another avatar is passing through them

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#3163]
**[Affected Versions]:**
- Firefox Release 81.0.1
- Chrome 86.0.4240.75

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- The https://hubs.mozilla.com/ website is open.
- A room with at least 2 avatars is opened.
- One of the avatars is created by a 3rd party. (e.g. https://readyplayer.me)

**[Steps to reproduce]:**
1. Create an avatar on a 3rd party website e.g. https://readyplayer.me
2. On one of the avatars use the 3rd party skin.
3. Using the default avatar pass through the 3rd party avatar.
4. Observe the avatar.

**[Expected results]:**
- The 3rd party avatar becomes transparent.

**[Actual results]:**
- The 3rd party avatar does NOT become transparent.

**[Notes]:**
- The glasses of the avatar become transparent.
- I was not able to test this issue on MacOS, Linux or mobile devices.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1eJX3jDTkGSK3sRsuoruXuGnAj6_Lphf8/view?usp=sharing).

**Comment by misslivirose** [comment]
Does this only happen with Ready Player Me avatars, or with other third party avatars as well?

**Comment by Softvision-GeluHaiduc** [comment]
I tried it using Ready Player Me avatars, I didn’t find any other reliable free 3D avatar creator, if you could recommend other websites I would be happy to try them out.

**Comment by Softvision-GeluHaiduc** [comment]
This issue appears to be fixed by #3951
I have verified this issue using Firefox and Chrome on Windows 10.
Now, the 3rd party avatar has become transparent when getting close enough.
