### ISSUE TITLE
player randomly spawned positions sometimes feel awkward in "Medieval Fantasy Book" Environment 

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#318]
examples:
<img width="1386" alt="screen shot 2018-04-25 at 9 52 53 pm" src="https://user-images.githubusercontent.com/203725/39288283-4512132c-48dc-11e8-8c3a-e0978178d4c3.png">
<img width="1270" alt="screen shot 2018-04-25 at 10 02 06 pm" src="https://user-images.githubusercontent.com/203725/39288303-4e554684-48dc-11e8-9e13-bf3afc84625a.png">

**Comment by netpro2k** [comment]
The spawn points are not random anymore, they are randomly selected from the points the artist puts into the environment. Anytnig in particular you find awkward about them? Hard to tell from the screenshots.

**Comment by cvan** [comment]
this seems fixed / different now. it was mainly the position in the first screen that caught me by surprise (with pages folded and what not, it looked jarring when it first loaded). I am unable to reproduce any "unusual" positions. closing this. thanks for updating with this info. and updates :+1:

**Comment by cvan** [comment]
actually, with [some more testing](https://hubs.mozilla.com/0mxlh6ae2iu/acrobatic-proud-camp/), I did find myself spawned in – what I considered to be – random/awkward positions:

<img width="1464" alt="screen shot 2018-05-01 at 9 02 42 pm" src="https://user-images.githubusercontent.com/203725/39504824-373e0cfa-4d83-11e8-9308-0049c762ac70.png">
<img width="1270" alt="screen shot 2018-05-01 at 9 02 37 pm" src="https://user-images.githubusercontent.com/203725/39504825-376de808-4d83-11e8-979e-338d0a329ad8.png">

if I know the controls and how to interact (on desktop), it's not _super_ confusing. but I will admit that the starting positions were _unexpected_, and felt initially confusing, to me.
