### ISSUE TITLE
Req Individual one on one chat 

### ISSUE THREAD

**Issue by doreai** [mozilla/hubs#3182]
How to implement one on one private chat? is that any code integration is available for an individual private chat inside the room

**Comment by camelgod** [comment]
You can follow discussion here: duplicate of https://github.com/mozilla/hubs/issues/2961
No good way to do this yet afaik.

**Comment by truedat101** [comment]
For the op, is this voice chat or text chat?  Both are desirable features.

**Comment by misslivirose** [comment]
Closing this as a duplicate of #2961. We also have a number of other issues that speak to a desire for a feature that would allow for private voice chat / "Whisper" type functionality.
