### ISSUE TITLE
Halloween scenes - Dark Forrest

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla/hubs#3185]
**Description**
 
In the middle of the Dark Forrest is what looks like a bonfire of "!" icons.  Please see attached screenshot.

**To Reproduce**
1. Go to the Dark Forrest Hubs scene
2. Look towards the centre of the scene from any angle

**Expected behavior**

Not sure what to expect, but this looks odd.

**Screenshots**
![filename](https://user-images.githubusercontent.com/31939113/96304350-db8f4000-0ff3-11eb-840e-c0407b17f642.jpg)

**Hardware** 
 - Device: Pico Neo 2
 - OS: Pico Android
 - Browser: FxR 12

**Additional context**

**Comment by Softvision-GeluHaiduc** [comment]
This issue is also reproducible on Firefox Release 81.0.1 and Chrome 86.0.4240.75 on both Windows 10x64 and Ubuntu 18.04.2.
I have seen this behavior when creating emojis fast one after the other but wasn't able to reproduce the issue last week.

**Comment by SeburoSUMO** [comment]
It is worth mentioning that I was not creating emoji - the animation seemed to be a feature of the scene.

**Comment by emclaren** [comment]
fixed this scene by removing the particle system, it worked on some devices, but not on others. Happens when a sprite for a particle system fails to load

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 81.0.1 and Chrome 86.0.4240.75 on both Windows 10x64 and Ubuntu 18.04.2.
Now, the odd behavior that was present in the scene is not visible anymore.
