### ISSUE TITLE
Improve `/audiomode` command documentation

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#3191]
The `/audiomode` command is frequently misunderstood. When you toggle it (or see it in the command tip box), it says "positional audio disabled/enabled". This leads people to think it should make all audio sound the same, but it does something different:

It does not disable distance-based attenuation. It disables panner-nodes, so that left/right forward/back directionality will be removed. It replaces the distance-based attenuation from `THREE.PositionalAudio`s with a different falloff curve ( https://github.com/mozilla/hubs/blob/master/src/components/avatar-volume-controls.js#L60 )

I don't know the best way to explain this in a few words ( maybe "toggle left/right panning" ), but it would be good if this feature was explained more clearly in the client and in the docs https://github.com/MozillaReality/hubs-docs/blob/c50f02cece06f70b23d91bcd87f36c16637005e9/docs/hubs-features.md

**Comment by matthewbcool** [comment]
Would it be more accurate to say "sound output set to mono" or do we still get two channels of output with that?

**Comment by Varen8** [comment]
Hi, I would like to work on this.

**Comment by Varen8** [comment]
@johnshaughnessy . I submitted a PR.

**Comment by Varen8** [comment]
Review ping?

**Comment by brianpeiris** [comment]
Closed with https://github.com/MozillaReality/hubs-docs/pull/84
Thanks @Varen8, sorry it took so long to merge.

**Comment by johnshaughnessy** [comment]
Sorry, I lost track of this issue. Thanks for your patience Varen and for picking it up again Brian
