### ISSUE TITLE
Update Origin-Trial for WebVR

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#320]

**Comment by cvan** [comment]
through the [`check-token` page](https://googlechrome.github.io/OriginTrials/check-token.html), I was able to verify the current Origin-Trial token expires on June 5, 2018.

there are extended WebVR trials too (sigh) and now _WebXR_ trials as well (both filed under issue #365).

**Comment by gfodor** [comment]
Updated this because this is expiring soon so we need to bump it.
