### ISSUE TITLE
Crash client for everyone in the room by importing GLTF file with uv-scroll and only emissive map

### ISSUE THREAD

**Issue by zach-capalbo** [mozilla/hubs#3219]
**Description**

If you import a glb file containing a mesh with the Hubs uv-scroll extension set, and an emissive map rather than a diffuse map, it will crash the hubs client for everyone in the room.

This is an easy situation to get into by exporting a common unlit shader setup from Blender:

![image](https://user-images.githubusercontent.com/1325621/97083609-1dfde180-15df-11eb-9394-09c0c9beace0.png)

Here is a glb file which reproduces the behavior:

[scroll-crash.zip](https://github.com/mozilla/hubs/files/5432982/scroll-crash.zip)

**To Reproduce**

1. Drag and drop `scroll-crash.glb` from the attached zip file into any hubs room
2. Client will freeze for everyone in room

**Expected behavior**

The client shouldn't freeze. The imported model should display a blinking smiley face

**Screenshots**

![image](https://user-images.githubusercontent.com/1325621/97083733-27d41480-15e0-11eb-915a-8d5915075f05.png)

**Hardware**
 - Device: Desktop, VR, Smartphone
 - OS: Tested on Windows. Presumably affects Linux, too
 - Browser: Confirmed on Chromium and Firefox

**Additional context**

I've already submitted a fix for this issue here: https://github.com/mozilla/hubs/pull/3202

**Comment by hollyhudson** [comment]
This is also causing a problem for me.  I'm adding a model in Spoke that has UV scroll and only an emission node for the shader nodes (with an image texture plugged into it), and if I create a room with the scene the room never loads.  I've tried adding it to other scenes, and they stop loading as well.  Here's a screenshot of the error from the web console:
<img width="553" alt="Screenshot 2020-11-04 at 13 51 07" src="https://user-images.githubusercontent.com/2358145/98114307-5afe8980-1ea5-11eb-8aec-37076bc4e5dd.png">

And the nodes in Blender:
<img width="1174" alt="Screenshot 2020-11-04 at 12 49 56" src="https://user-images.githubusercontent.com/2358145/98114402-83868380-1ea5-11eb-94b4-5ec8497b37b1.png">

**Comment by hollyhudson** [comment]
In case anyone else with this problem ends up here -- there is an easy fix:  just add a Principled BSDF shader and mix it with the Emission shader via a Mix Shader.  I have the Image texture plugged into both shaders and that's working fine.

**Comment by misslivirose** [comment]
Appears resolved with the fix in #3202 (for the provided .glb) - thank you! 

@hollyhudson - thanks for the additional information. It sounds like you're still experiencing this is the model is included through Spoke? I'll file that in the Spoke repo.
