### ISSUE TITLE
Support for KHR_texture_basisu texture compression

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#3225]
The [KHR_texture_basisu](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_texture_basisu/README.md) extension appears to be stable now [and is supported by three.js](https://threejs.org/docs/#examples/en/loaders/GLTFLoader).

gltfpack supports the required texture compression ([-tc option](https://github.com/zeux/meshoptimizer/blob/e264c06e5b317be5b3f51fca1a2e354397350f60/gltf/README.md#options)) so the workflow could just be: export from Blender and compress `gltfpack -i Duck.gltf -o Duck.glb -tc`

The only thing that appears to be stopping this working is that the version of GLTFLoader currently in Hubs isn't up-to-date so you get an _Unknown extension "KHR_texture_basisu"_ error in the console when the load fails.

[Here is an archive](https://github.com/mozilla/hubs/files/5438914/Duck.zip) with the Duck model converted to use KHR_texture_basisu and saved as a GLB (there aren't any examples in GLB format that I could find online). I've also included the uncompressed GLTF files for reference.

Obviously supporting this extension would mean you could deprecate MOZ_HUBS_texture_basis.

**Comment by netpro2k** [comment]
Wow I missed this, but this is very good news. Will definitely try and dive more into this soon.

**Comment by netpro2k** [comment]
This has now been landed, and marks official deprecation of the `MOZ_HUBS_texture_basis` extension. Both will continue to function for now since some people are already using it, and its fairly minimal code overhead to retain, but people should now prefer using the official extension.
