### ISSUE TITLE
Youtube video element created in Spoke does not work 

### ISSUE THREAD

**Issue by i3games** [mozilla/hubs#3240]
**Description**
A video element created in Spoke pointing to a Youtube video does not work and gives a misleading error message.

**To Reproduce**

1. Create a video element in Spoke
2. Set the URL to a Youtube video. I have tried my own videos - both public and unlisted videos and both shortened and expanded URLs
3. Publish to Hubs and create a room
4. See error message below. 

5. Refresh doesn't do anything
6. The linked video opens normally in a new tab

**Expected behavior**
Video plays

**Screenshots**
attached

**Hardware** 
 - Device: Macbook Pro
 - OS: macOS Catalina
 - Browser: Firefox 82

**Additional context**
The video is the first video linked from Youtube, therefore exceeding a quota is unlikely.    

![Screenshot 2020-10-28 at 09 40 22](https://user-images.githubusercontent.com/830492/97415311-549c6a80-1905-11eb-9695-008fbcf824e5.jpg)

**Comment by misslivirose** [comment]
The image message is explaining what is happening - there is a quota that the service reaches with YouTube videos, and when that is reached, the video can't be played in Hubs until it's reset. You can read more about this here: #2929

**Comment by i3games** [comment]
Suggestion: the wording could be a bit more clear. Consider adding "This is a global quota for all rooms hosted with Mozilla." or the like.
