### ISSUE TITLE
clarify in Privacy Notice the "third-party services" used

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#326]
In the [_Privacy Notice_](https://github.com/mozilla/hubs/blob/master/PRIVACY.md#things-you-should-know), in the **`Interaction data:`** section:

> Mozilla uses third party services to store and analyze these operational messages.

can this contain a list (with links) to which third-party services are used?

also, a few more details would be nice. this comes to mind:

- links to Privacy Policies and ToS for the services
- links to the GitHub repos, project URLs, or paths/folders in this repo where they're used

**Comment by gfodor** [comment]
these are q's for legal, I am not sure how to properly escalate out of GitHub. any precedent?

**Comment by cvan** [comment]
my old colleague, @mattbasta, helped the Legal + Privacy folks start using GitHub for maintaining their docs in Markdown (version control is really helpful for them!)

**https://github.com/mozilla/legal-docs**

I'd check with @mikaland2, [et. al.](https://github.com/mozilla/legal-docs/graphs/contributors) to see if it's cool: it'd be awesome to get Hubs' docs in there :+1: (I should do the same for the Unity WebVR Assets.)

**Comment by mikaland2** [comment]
Yes! It would be good to get the hubs and unity docs in there

**Comment by cvan** [comment]
@gfodor are you saying that we should track all Privacy Policy changes as issues filed in [`mozilla/legal-docs`](https://github.com/mozilla/legal-docs/issues)? I think that makes sense. just wanted to confirm that's what you're suggesting?

**Comment by cvan** [comment]
TBH, I'm not sure across the board. in past projects, we filed Bugzilla issues and then opened PRs in [`mozilla/legal-docs`](https://github.com/mozilla/legal-docs). as long as there are issues on file (or protocols in place) to sync (or link to) the versions in `mozilla/legal-docs`, it's probably fine to keep the issues in that repo. probably err on the side of duplicated issues, but yeah this is likely a question for @mikaland2 to answer.

**Comment by misslivirose** [comment]
Resolving this due to age and changes to the privacy policy that have since happened - we've got a new internal practice for privacy policy changes.
