### ISSUE TITLE
Oculus QUEST does not instantly teleport  in breakout panels 

### ISSUE THREAD

**Issue by salahzar** [mozilla/hubs#3286]
**Description**
Just use the Hubs School v1.0 (one of the  

**To Reproduce**
1) Just create a scene from  the Hubs School v1.0 and
2) just after entering go in the hall towards the first door on the left
3) and click the panel to go to the breakout room

**Expected behavior**
an instant teleport inside as it happens with Oculus GO (very strangely it works correctly with go), or PC version. Instead on Oculus Quest it leaves VR and the room and tries to reenter in the room, an operation that can take minutes or forever.
If really used in a Conference with children it will totally destroy the sense of presence and educational usage

**Screenshots**

**Hardware** 
Tried with Oculus Quest and firefox reality

**Additional context**

**Comment by misslivirose** [comment]
I don't have Oculus devices to test on, but I wonder if this has to do with whether or not the browsers are using WebVR vs. WebXR APIs in their implementations and if those handle the waypoints differently as a reload/load. If it's possible to check the browser versions on the different devices, that might help pinpoint the different behaviors.

**Comment by salahzar** [comment]
Hi @misslivirose , thanks for the answer.
I tried again today. Since it seems you are not fluent with Oculus I can start telling you that there are basically two browsers available so far as I know with Oculus Quest. The first is named Oculus Browser https://developer.oculus.com/documentation/oculus-browser/ and it is automatically installed on the headset when you buy it.
And the second browser is Firefox reality: https://www.oculus.com/experiences/quest/2180252408763702/?locale=en_US
When I initially bought Oculus Quest in February I started entering Mozilla Hubs using Oculus Browser, but then had some major problems and reading on the web they suggested to use Firefox Reality instead, so I permanently switched to it until ... now.

The way it works with these devices is that you are forced to have the last version of each application installed. For instance using firefox reality now it is version 12, and I havent' any other particular information about it.

Today I extensively tried to reproduce the problem with either of the two browsers:
1) Oculus Browser "almost" worked as I wanted (see after for the concern I still have)
2) Firefox reality is NOT working since at each "instant" teleport it keeps in "logging you out" and then you have to repeat ALL needed to enter a room including avatar choosing, mic choosing and muting etc. So Firefox reality is definitely unusable in this context.
To be sure at least ONE time, the same Firefox reality version behaved similarly to the "almost" part of Oculus Browser, but when I restarted it, it just fell back to the improper behavior.

Regarding the "almost" part with Oculus Browser. When you click on the teleport you expect to be teleported inside the room. Instead, what it happens is that you quite the VR for a moment and a 2D screen is shown offering you to Resume VR experience.
Honestly now it becomes a not urgent fix, but I would expect Mozilla Hubs stays in VR not exiting and reentering asking me to resume vr.

**Comment by misslivirose** [comment]
I am aware of the different browsers available on Oculus. My comment refers to whether or not Oculus Go and Oculus Quest are running the same version of the Oculus Browser, hence my comment "on the different _devices_. You mentioned that this teleportation works fine on the Oculus Go, not the Oculus Quest, but since Oculus has since said that they are no longer supporting Go, it is not clear whether or not they are still updating the browser there. You did not mention whether or not the Oculus Browser on Go is the same version as Oculus Browser on Quest, which was the question I posed earlier.

**Comment by misslivirose** [comment]
This is likely a more general issue not specific to Oculus Quest. Closing in favor of a more general issue for us to investigate with other headsets as well.

**Comment by salahzar** [comment]
I understand now that you wanted to investigate on the different behaviors of teleport on various headsets. This particular issue however was on Oculus Quest and not on Oculus Go, so it was a strange question  at least for me. Sorry for having sounded rude in my previous answer.
Anyway since using the other Oculus Browser it seems the problem can be fixed, no problem for me in closing this bug.
