### ISSUE TITLE
add expunge/expiry times (TTLs) for unused/stale hubs

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#329]
it seems like session data is already set to expire at some – unknown to me – point.

(filed issue #327 to track the _Privacy Notice_ clarification.)

**Comment by gfodor** [comment]
I'm actually not sure of the best way to do this -- we want to avoid breaking URLs that are active. We could start storing a "last accessed time" on the hub database, but I believe that impacts privacy. (For example, it would allow us to know what are the popular rooms over time, which we currently have no way to ascertain.)

I think we will definitely introduce a "ownership" concept to a room, so the owner could close the room.

**Comment by misslivirose** [comment]
Closing this as the new design is that rooms will never close unless explicitly closed by the room owner. If we see otherwise with session data expiry, we will file this as a new issue.
