### ISSUE TITLE
3D objects do not fit media frame scales

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#3298]
**Description**
- 3D objects are not scaled to correctly fit into the frame. The bounding box should be calculated given the object's scale, and then set to match the frame boundaries.

**Additional context**
The [media frames PR](https://github.com/mozilla/hubs/pull/2967) notes this, but I wanted to capture it separately here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-463)

**Comment by sardug10** [comment]
Hey, I am a beginner in open-source. Is this issue good to start with?

**Comment by matthewbcool** [comment]
fixed with https://github.com/mozilla/hubs/pull/4655 and other updates
