### ISSUE TITLE
Ability to change from "spectate" to "join"

### ISSUE THREAD

**Issue by heaversm** [mozilla/hubs#3314]
**Is your feature request related to a problem? Please describe.**

In the new UI, if I choose "Spectate", it doesn't appear that I can change to "Join Room" afterward unless I refresh my browser.

**Describe the solution you'd like**

Ability to change from the spectator of a room to a participant in the room.

**Additional context**

![spectate](https://user-images.githubusercontent.com/520541/98844856-c98d9b00-2401-11eb-96c1-b15a5f52bfa4.gif)

@mbransn

**Comment by heaversm** [comment]
Closing to surface within DPX first.

**Comment by misslivirose** [comment]
We should add visual UI for this - you can return to the main lobby panel by hitting the 'Escape' key when spectating

**Comment by mbransn** [comment]
@misslivirose I don't have a way to add labels, can you add the dpx label for zenhub integration and we'll work to resource this UI?

**Comment by fernzharp** [comment]
This has been solved by the Hubs team
![Screenshot (446) 1.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/7fe3cfbf-ed60-45fe-bec2-a4b4fa382556)
