### ISSUE TITLE
Cardboard VR detection incorrect

### ISSUE THREAD

**Issue by mikebolt** [mozilla/hubs#333]
I tried to use a Pixel (1) phone. It worked fine in non-vr mode, but when I selected "Gear VR" I was taken to a black page with white text that said my session had ended. Reloading the page did not fix it, and restarting my browser (Chrome) did not fix it either.

Also, I was expecting an "Enter VR" button. I was planning on using a cardboard viewer, so "Gear VR" mode was not intuitively named.

Good work though, I look forward to trying Hubs in VR!

**Comment by brianpeiris** [comment]
Thanks for the report @mikebolt! You're right, we should give you the option to enter in Cardboard. Looks like the code for cardboard-capable phones is not doing the right thing here.

**Comment by gfodor** [comment]
Can this issue be closed or is there something actionable to be done here?

**Comment by InfiniteLee** [comment]
Cardboard for iOS is a different issue, though this issue doesn't really specify iOS vs android. So this is related to #358

**Comment by InfiniteLee** [comment]
I'm going to close this issue since the only real outstanding problem is with iOS, and carboard mode on there doesn't work correctly right now anyways.
