### ISSUE TITLE
Gaze cursor does not work in Cardboard mode

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#334]
Tested with a Nexus 5. You enter Cardboard mode correctly, but there is no cursor and tapping the cardboard button does nothing. Interestingly, the in-vr-hud buttons do change hover states, as if there were a cursor, but tapping the Cardboard button does not click the hub buttons.

**Comment by kwadroke** [comment]
I have seen this earlier on a Note 3 & Chromium using Cardboard mode. Thought it might have just been me/my device.

**Comment by InfiniteLee** [comment]
#343 was merged but this functionality is still disabled as the approach I was taking had some bad side effects for non-cardboard devices. Going to write a `cardboard-controls` component to solve this problem instead.

**Comment by brianpeiris** [comment]
This is just blocked by #358 now
