### ISSUE TITLE
[New UI] The create object button from chat is not always actionable

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#3361]
**[Affected Versions]:**
- Chrome 86.0.4240.198

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Have a new room created and entered.

**[Steps to reproduce]:**
1. Click the “Chat” button from the bottom menu.
2. Write a text message.
3. Click the create object button from the chat box.
4. Observe the behavior.

**[Expected results]:**
- The object is created from the text in the chat box.

**[Actual results]:**
- The attach button is wrongly clicked and the window to attach is opened.

**[Notes]:**
- The issue is not reproducible on Firefox.
- In the right position the button can still be clicked, but it is hard to find that position.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1Tb5vVkvqsQx6vnYKRbvO5fmo01XAP7Kd/view?usp=sharing).

**Comment by robertlong** [comment]
@Softvision-GeluHaiduc could you check to see if this is still happening for you? I switched the behavior of the attach file button and cant reproduce the hidden file picker button on my end.

**Comment by Softvision-GeluHaiduc** [comment]
@robertlong I managed to reproduce the issue on Chrome 87.0.4280.88 but it has slightly different behaviour.
Now, if the chat field is empty the create object button is not actionable and the file picker is clicked instead if there is text in the chat field the button is actionable and works as expected.
![chat object](https://user-images.githubusercontent.com/51400741/101602914-82e28f00-3a07-11eb-83ee-35c7f17ffcd3.gif)

**Comment by robertlong** [comment]
There was also a report of the file input button expanding past it's bounds in the custom object modal
![image 2](https://user-images.githubusercontent.com/1753624/101695609-b7674280-3a29-11eb-8da0-a23b675782f0.png)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 83.0 and Chrome 87.0.4280.88 on Windows 10x64.
The original issue is not reproducible anymore, unfortunately, a regression appeared. When the file picker from the chat is clicked on chrome the file picker and object creation button are moved to the middle of the text field of the chat.
![chat filepcker](https://user-images.githubusercontent.com/51400741/101746876-344ef680-3ad4-11eb-9529-4ded6a9ae8f0.gif)

**Comment by robertlong** [comment]
Ok, I clicked the button in all browsers while testing and I think I've finally fixed it.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Chrome 87.0.4280.88 on Windows 10x64.
Now, when the file picker from the chat is clicked the buttons are not moved and the window to select the file is open.
