### ISSUE TITLE
[New UI] Nothing happens when the “Change Scene” button is clicked

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#3368]
**[Affected Versions]:**
- Firefox Release 82.0.3
- Chrome 86.0.4240.198

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Make sure to be logged in to an account.
- Have a new room created and entered.

**[Steps to reproduce]:**
1. Click the “More” button from the bottom menu.
2. Go to “Room Info and Settings” and click the “Edit” button.
3. Click the “Change Scene” button.
4. Observe the behavior.

**[Expected results]:**
- The scene can be changed.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- Attached a screen recording of the issue below.
![change_scene](https://user-images.githubusercontent.com/51400741/99509873-0839cd00-298f-11eb-962b-2578a708bdc2.gif)

**Comment by robertlong** [comment]
Fixed in https://github.com/mozilla/hubs/pull/3006/commits/4abbe456486f6b52cd64f1497b91aaf34254ced3

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 83.0 and Chrome 87.0.4280.88 on Windows 10x64.
Now, the scene can be changed when the “Change Scene” button is clicked.
