### ISSUE TITLE
preserve paths for https://hubs.mozilla.org/* redirects

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#337]
we should use 302 (not 301 Permanent) redirects, just in case we decide to change the domain in the future

```
302 https://hubs.mozilla.org/* https://hubs.mozilla.org/$1
```

```nginx
server {
  server_name hubs.mozilla.org;
  if ( $host != $server_name ) {
    rewrite 302 ^(.*)$ https://hubs.mozilla.org$request_uri;
  }
}
```

@gfodor: I'm not sure where the redirects are handled (likely with Mozilla Ops w/ Cloudfront, so let me know if you want me to file a Bugzilla ops ticket for this).

<hr>

**blocks issue #336**

**Comment by cvan** [comment]
@gfodor: are you cool with me to file a Bugzilla Ops ticket for this?

**Comment by gfodor** [comment]
closing, we can revisit if something comes up that makes us care more about `org` URLs beyond "lol nope"
