### ISSUE TITLE
[New UI] The tour messages are displayed over the menus and objects

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#3370]
**[Affected Versions]:**
- Firefox Release 82.0.3
- Chrome 86.0.4240.198

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Have a new room created and entered.
- Make sure to have at least 2 objects created.

**[Steps to reproduce]:**
1. Click the “More” button from the bottom menu.
2. Click the “Start Tour” option.
3. Click the “Place” or “React” button from the bottom menu.
4. Observe the tour messages.
5. Click the “Objects” button from the top-right of the screen.
6. Click on one of the objects from the list.
7. Observe the tour messages.

**[Expected results]:**
Step 4 - The tour messages should be hidden/dismissed when a menu is displayed.
Step 7 - The tour messages should be hidden/dismissed when an object is viewed.

**[Actual results]:**
Step 4 - The tour messages are displayed over the menus.
Step 7 - The tour messages are displayed over the objects when viewed separately.

**[Notes]:**
- Attached screenshots of the issue below.
![tour messages over menu](https://user-images.githubusercontent.com/51400741/99517563-2c4ddc00-2998-11eb-9c7b-bfbe1d5a8fdd.png)
![tour messages over menu 3](https://user-images.githubusercontent.com/51400741/99517568-2e179f80-2998-11eb-92c3-5b408ac5152c.png)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 83.0 and Chrome 87.0.4280.88 on Windows 10x64.
Unfortunately part of the issue is still reproducible. When an object is viewed separately the tour messages are still displayed over the object menu.

**Comment by robertlong** [comment]
@Softvision-GeluHaiduc it should be fixed now. Thanks!

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 83.0 and Chrome 87.0.4280.88 on Windows 10x64.
Now, the tour messages are not displayed over the menus and objects.
