### ISSUE TITLE
Leave Room doesn't actually disconnect from the room

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#3381]
**Description**
@misslivirose found that leaving a room on mobile still played the audio from the room. We need to make sure that we are completely disconnected from the room after leaving and all media stops playing.

**Comment by emclaren** [comment]
Added p1 label to this because even though this doesn't break Hubs this would be confusing to users who press leave and the music is still playing. It could cause users to worry that their mic is still connected.

**Comment by robertlong** [comment]
@misslivirose I'm looking at this code and when you get kicked out to the "Exit Room" screen, I'm pretty sure all voice connections are disconnected, so you shouldn't hear other users and they shouldn't hear you. However, media in the room will continue playing. This isn't the easiest thing to fix right now and seems unrelated to the redesign. Would a good compromise be to make the "Leave Room" button take you back to the home page?

**Comment by misslivirose** [comment]
I think that compromise is fine (return to the home page) - I'll re-test but I'm fairly certain I was still hearing Christian talking when I tried this out last time.

**Comment by misslivirose** [comment]
It's very possible I had something mixed up too.

**Comment by robertlong** [comment]
Ok, I'll mark this as needs-repro for now and we can try to look for it in our testing session tomorrow.

**Comment by misslivirose** [comment]
When I leave the room now it goes to the home page so I'm comfortable calling this resolved. The original issue no longer happens for me.

**Comment by robertlong** [comment]
Ok, thanks! We'll keep a look out for any voice activity happening on the exited screen.
