### ISSUE TITLE
n.components.networked.data is undefined

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#3383]
**Description**
This error came up in our most recent test of the redesign and was spammed quite frequently, causing my dev tools to slow down.

![image](https://user-images.githubusercontent.com/1753624/99580348-3b328f80-2994-11eb-9585-388fb92f9ec7.png)

**Comment by emclaren** [comment]
added p1  - as this seems like a high priority to address to make it easier to find other console errors when debugging

**Comment by robertlong** [comment]
This is confirmed to be a duplicate of: https://github.com/mozilla/hubs/issues/3452
