### ISSUE TITLE
After favoriting room and signing in, the sign in modal is not closable

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#3386]
**Description**
After favoriting room and signing in, the sign in modal is not closable. The continue and close buttons don't work.

**To Reproduce**
Reported by @emclaren. Needs reproduction steps

**Expected behavior**
The continue and close buttons should close the sign in modal

**Hardware**
- Mobile
- Android
- Chrome?

**Comment by emclaren** [comment]
This bug is no longer happening for me on Android with either Chrome or Firefox. Does not repro anymore
