### ISSUE TITLE
[New UI] Part of the “Room Settings” menu disappears when a “Room Member Permissions” is changed

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#3393]
**[Affected Versions]:**
- Firefox Release 83.0

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Make sure to be logged in into an account.
- Have a new room created and entered.

**[Steps to reproduce]:**
1. Click the “More” button from the bottom menu.
2. Go to “Room Info and Settings” and click the “Edit” button.
3. Click one of the switches from the “Room Member Permissions”.
4. Observe the behaviour.

**[Expected results]:**
- The setting is switched.

**[Actual results]:**
- The view is shifted up and the menu can no longer be dismissed.

**[Notes]:**
- The issue is not reproducible on Chrome.
- If you resize the window the menu can be dismissed.
- The issue is reproducible in the room setting from the lobby as well.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1WeqgVJmxJvYsp0K9U1_UdDr0U3-N5HUV/view?usp=sharing).

**Comment by robertlong** [comment]
Hmm, this looks to be a really nasty Firefox CSS bug. Removing `position: relative` from the sidebar `div` element temporarily fixes the problem, however on a refresh it completely breaks the CSS grid for the room layout...

None of this behavior happens in Chrome.

**Comment by robertlong** [comment]
@Softvision-GeluHaiduc this should be fixed now.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 83.0 on Windows 10x64.
Now, the “Room Settings” menu does not change when a “Room Member Permissions” is changed.
