### ISSUE TITLE
[New UI] Emojis can still be created by members if the setting is off in room settings

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#3394]
**[Affected Versions]:**
- Firefox Release 83.0
- Chrome 87.0.4280.66

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Have a new room created and where emojis are not allowed to be created.

**[Steps to reproduce]:**
1. Enter the room from prerequisites without being logged in. 
2. Click the “React” button from the bottom menu.
3. Click one of the emojis and observe the behavior.

**[Expected results]:**
- The react emoji is not created.
OR
- The “React” button is not available to other users.

**[Actual results]:**
- The react emojis can be created.

**[Notes]:**
- Sometimes the emojis are not rendered to the other users in the room.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1y4-BQyXdhAm5Z_HKKXGIaKo7-P5-P36e/view?usp=sharing).

**Comment by johnshaughnessy** [comment]
I was not able to reproduce this bug. I believe it may have been fixed in https://github.com/mozilla/hubs/pull/3484/commits/fe9caf698641dcc4be64c88d509e54597b16d61f
 
@Softvision-GeluHaiduc are you still seeing this or should we close this issue?

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 84.0.1 and Chrome 87.0.4280.88 on Windows 10.
Now, emojis can not be created by other members if the setting is off in the room settings.
