### ISSUE TITLE
add Privacy Notice and Terms of Use to `mozilla/legal-docs` repo (for historical versioning and localisation)

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#341]
see discussion here: https://github.com/mozilla/hubs/issues/326#issuecomment-385098482

**Comment by cvan** [comment]
see comment here: https://github.com/mozilla/legal-docs/pull/1021#issuecomment-494346514

**Comment by misslivirose** [comment]
Now tracked in [mozilla/legal-docs#1289](https://github.com/mozilla/legal-docs/pull/1289/)
