### ISSUE TITLE
Correct a line in the Spanish translation.

### ISSUE THREAD

**Issue by elmau** [mozilla/hubs#3446]
Hi, we noticed we made a mistake with the spanish translation in this line:

https://github.com/mozilla/hubs/blob/b9a8797277cacc7f31bb35cebb349817e3b1c79f/src/assets/locales/es.json#L418

The line says:   "hide-ui.prompt": "Ocultar a todos",
It should say:   "hide-ui.prompt": "Ocultar interfaz",

Sorry
:)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-500)

**Comment by natastro** [comment]
Hello! I'd love to help fix this and send a PR if possible. Thank you 😊

**Comment by brianpeiris** [comment]
Looks like this particular line is no longer in our list of translations.
