### ISSUE TITLE
Add environment preview image <meta> tags for non Spoke environments

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#345]
currently, the social images (for Twitter/FB) all use the same [`hub-preview.png` image](https://github.com/mozilla/hubs/blob/master/src/assets/images/hub-preview.png).

it would be nice to have each Hub page use its environment's screenshot as the card. the [`<meta>` tags are defined in `mozilla/reticulum` here](https://github.com/mozilla/reticulum/blob/master/lib/ret_web/templates/page/hub-meta.html.eex).

it would be nice to have a social (Twitter/FB) card for each [environment](https://github.com/mozilla/hubs/blob/master/src/assets/environments/environments.js), incorporating the [`Mozilla by Hubs` logo](https://github.com/mozilla/hubs/blob/master/src/assets/images/hub-preview.png) either in a corner or as a layer atop the environment's screenshot.

**Comment by gfodor** [comment]
yep, we'd like to do this -- it will require crawling/parsing the gltf bundle file and caching it within the OTP cluster so that's why it wasn't in scope for MVP.

**Comment by robertlong** [comment]
It looks like this is finished now. We show an image for all environments created in Spoke. Perhaps we should do the same for our own environments? I'll change the issue.

**Comment by gfodor** [comment]
we just need to migrate the existing scenes into spoke, and then nuke all
the old bundle code
