### ISSUE TITLE
[iOS/iPhone] Not having a 'send' button in chat may be confusing

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#3454]
**Description**
When I open the chat modal and try typing a message, it is not clear to me that hitting 'return' on the keyboard will be send the message and there is no visual button for sending the message that I have typed. 

**Expected behavior**
There is a clear option that visibly tells me that I can send my message. Return sometimes adds a new line for text editing and sometimes sends a message, so specifically adding a clarification would be helpful so I know when my message will be sent to the others in the room.

**Comment by emclaren** [comment]
on Android, hitting the return key once put the cursor onto a new line, pressing it a second time made it send. This is a bit confusing. The suggestion Liv makes would be helpful.
