### ISSUE TITLE
"Attach" button in chat does not upload file

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#3456]
**Description**
The "Attach" button with the paperclip icon in the Chat window does not work.

**To Reproduce**
1. Open the chat panel
2. Click on the attach button (the paperclip icon)
3. Select an image file from the file picker
4. See that the file does not get uploaded or added to the room.
5. An error appears in the console:
```
Uncaught TypeError: t is not a function
    onChange ChatSidebarContainer.js:182
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
ChatSidebarContainer.js:182:19
```

**Expected behavior**
The attach button should immediately upload the file and insert it into the room.

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 83.0 and Chrome 87.0.4280.88 on Windows 10x64.
Now, the "Attach" button in chat uploads the file in the room.
