### ISSUE TITLE
Missing button to hide interface when spectating (and ~ doesn't work)

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#3460]
Its not possible at the moment to hide the interface when you watch from the lobby. There is no button and ~ doesn't work. It would be nice to have one or both of these options available

**Comment by emclaren** [comment]
Added P2 label because it would be nice to have since it exists in the current UI, but it does not break the experience. 

Note that there is not currently a way to take a full screen recording without the interface (since ~ has a bug in world at the moment  https://github.com/mozilla/hubs/issues/3467)

**Comment by robertlong** [comment]
Fixed in https://github.com/mozilla/hubs/pull/3006/commits/51925670128304b53819118486128d94cd1cdf3c
