### ISSUE TITLE
In Google Chrome, the "create" button in the chat panel is covered by an invisible file input field

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#3464]
**Description**
The "Create" (wand) button in the Chat panel cannot be clicked in Google Chrome since it is covered by the file input element that's associated with the "Attach" (paperclip) button.

**To Reproduce**
1. Use Google Chrome
2. Open the chat panel
3. Type some text in
4. Try to click the create button
1. See that it opens a file picker instead.

**Expected behavior**
You should be able to click on the create button.

**Screenshots**
![notepad++_SIKmyeo9fF](https://user-images.githubusercontent.com/79419/100931063-dc463d80-349e-11eb-9657-9b1b93305989.png)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Comment by Softvision-GeluHaiduc** [comment]
This issue appears to be a duplicate of #3361

**Comment by brianpeiris** [comment]
Ah, yup, it is. Closing this one.
