### ISSUE TITLE
Hide button (~) leaves a white bar at the bottom of the screen 

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#3467]
The ~ button leaves behind the toolbar at the bottom (see screenshot) 

<img width="1661" alt="Screen Shot 2020-12-02 at 1 37 11 PM" src="https://user-images.githubusercontent.com/6835324/100935132-92f8ec80-34a4-11eb-9206-026a05eb5cf2.png">

Firefox on Mac

**Comment by emclaren** [comment]
added a p2 label because it would be really nice to get this fixed (particularly for folks doing screencapturing), it doesn't break the experience for anyone

**Comment by robertlong** [comment]
Fixed in https://github.com/mozilla/hubs/pull/3006/commits/51925670128304b53819118486128d94cd1cdf3c
