### ISSUE TITLE
Hubs client does not load (blank white screen) on iOS 10

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#348]
Loading https://hubs.mozilla.com/0fncia46zw5/tasty-spectacular-meetup on an iPhone 7 running iOS 10.3.2 results in a blank screen (in both Safari and Chrome):

![image](https://user-images.githubusercontent.com/203725/39500862-601a325a-4d6c-11e8-88a2-aa950d564bd1.png)

I assume it fails on `navigator.mediaDevices.getUserMedia` or invoking WebRTC. I don't see any errors in Sentry. Any idea what's up?

**Comment by InfiniteLee** [comment]
@cvan Loads fine for me on iPhoneX iOS 11. Have you tried updating to 11?

**Comment by cvan** [comment]
> @cvan Loads fine for me on iPhoneX iOS 11. Have you tried updating to 11?

this from a friend's phone. he refuses to update to iOS 11, in fear of slowing down his iPhone 7. do we have any stats of `User-Agent`s? usage numbers of Safari on iOS, Chrome/Firefox on Android? if I understood correctly, the telemetry @gfodor has added does not include this level of granularity. any ideas?

**Comment by InfiniteLee** [comment]
Reproduced on an iPad running iOS 10.0.2. Saw this error in console: 
```
[Error] TypeError: Object.values is not a function. (In 'Object.values(h.dialogTypes)', 'Object.values' is undefined)
```
<img width="995" alt="screen shot 2018-05-11 at 2 49 26 pm" src="https://user-images.githubusercontent.com/1821537/39948398-a961b382-552a-11e8-884d-d900b7fa2bc6.png">

**Comment by robertlong** [comment]
WebRTC is not supported on iOS 10. Unfortunately I'm not sure we can support it.
