### ISSUE TITLE
can't load a video

### ISSUE THREAD

**Issue by turbogaming** [mozilla/hubs#3497]
**Description**
when i try to spawn a youtube video i it wont load it i refresh the video but it wont load. 

**To Reproduce**

**Expected behavior**
i thought that i would put a vid down and so i got a vid from youtube and chill and watch it with my friends. 

**Screenshots**

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]    deaktop
 - OS: [e.g. Windows, iOS, Linux]    linux
 - Browser: [e.g. Firefox]      google

**Additional context**

**Comment by misslivirose** [comment]
The issue with YouTube is that their service blocks traffic per this discussion: https://github.com/mozilla/hubs/discussions/2681
