### ISSUE TITLE
phone Camera does not work on Iphone or Android

### ISSUE THREAD

**Issue by Charlesc22** [mozilla/hubs#3501]
When a phone user (Iphone and Android) turns on their camera view, they can view themselves in their room view, but others in the room do not see the Camera feed.
On the Iphone, it just shows a blank square and on the Android, it just shows the colored cube with the arrows wrapping around it, but never resolves

![image](https://user-images.githubusercontent.com/21025989/101299121-c958a380-37e5-11eb-8060-5a0740f7d166.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-510)

**Comment by takahirox** [comment]
Hi, thanks for the report.

I couldn't reproduce the problem although I tested on my Android Chrome - Windows Chrome and iPhone Safari - WIndows Chrome. Do you mind if testing again to check if the problem is still reproducible?
