### ISSUE TITLE
Ask users to download Firefox if they want to use WebVR on desktop

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#351]
On desktop, the reality today is that if you want to use WebVR with Hubs and are using any browser other than Firefox you will either:

- Not have data channel support (Edge)
- Have unstable WebVR support that has known issues (Chrome)
- Not have WebVR support (anything else)

As such, we should always enable the "Enter in VR" button on Desktop, but if you are not in Firefox, direct you to download it. Once other browsers ship stable WebVR support or data channels then obviously this can change.

I don't think just linking to webvr.rocks, as we're doing now, is a humane UX for the average person: that page, while very useful for technical types, fails to convey the information a user needs who just wants to get things working quickly, which for desktop users reduces down at the time of this writing to "Install Firefox."

Most users, even VR savvy ones, are not going to understand the WebVR ecosystem and the various stages of support by the browser vendors at any given moment -- it's our job to make this simple for them so they don't have to think about it.

**Comment by cvan** [comment]
for Windows…

WebVR (and WebXR) are officially in Chrome 67 (currently Beta) with an Origin Trial. which means on desktop, with Hubs' Origin Trial, the APIs will work in Chrome Beta / Canary.

I wish the day never came, but, especially in my last few several weeks of testing, I have encountered more issues with WebVR in Firefox release channel and Firefox Nightly than I have encountered in Chrome Canary.

<hr>

for macOS…

should we be promoting Firefox for Windows, even if they don't have that? perhaps ask if they have a Windows PC or mobile headset? (this is where I think the ease of sharing shorter URLs becomes useful: issue #336.)

Firefox doesn't work here (well _barely_, if like @blairmacintyre you have a swanky new iMac and Steam VR Beta macOS drivers).

**Comment by cvan** [comment]
these are very valid good points I agree with. Firefox’s stability in the Vive, I have been experiencing a plethora of bugs that don’t seem to appear in Oculus. I thought it was my 3 different Vive setups, but testing in desktop Chrome and native VR content, it was clear that there are bugs specific to  Firefox + OpenVR. (coincidentally or not, Chrome has a few of the same OpenVR bugs; it could be from a shared implementation, the drivers, or the design of the OpenVR or WebVR APIs.)

thanks for writing this all up. this will be useful to point folks to if/when the topic comes up. much appreciated :+1:

so, what is the action item here? quick mock or PR of the change you had in mind?

**Comment by gfodor** [comment]
can try to do a mock soon, but I think the main changes are:

- On Chrome, we always show the Enter in VR button on desktop. But when you click it, we show a message saying "WebVR support for Chrome is coming soon, For now, please download Firefox to use Hubs in VR on your Oculus Rift, Vive, or Windows Mixed Reality headset. "

- On Edge, we currently say "your browser doesn't have data channels" and we link them to a MDN page with the compat table. I feel we should continue to do that, but should have a primary CTA to download Firefox. The reason being that if they want to use WebVR, if they decide to install Chrome first, we'll then ask them to install Firefox (as per the previous bullet), so by the end they've installed *two* new browsers just to try Hubs in VR. Once Edge has data channel support, we'll need to work on the Enter in VR flow again, prompting them to download Firefox (or Chrome, if WebVR has stabilized) if they do not have a Windows Mixed Reality headset.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/383
