### ISSUE TITLE
MP4 Videos have double bugged audio sources (non-positional and positional)

### ISSUE THREAD

**Issue by camelgod** [mozilla/hubs#3516]
**Description**
After uploading a mp4 video in Hubs, you get two audio sources: One positional (the normal expected one) and another non-positional audio source that is very loud.
Seems like it creates two audio elements, one positional and one just generally in the browser.

**To Reproduce**
1. Join a room 
2. Upload Mp4 video manually
3. Get blasted with loud audio after your video loads
4. Turn the video volume up to hear double audio (they are not 100% synced, so you can make out two tracks playing. Reloading the video will only reload the positional audio, leaving you with two unsynced audio tracks).  

**Expected behavior**
One positional audio attached to ingame video.

**Hardware** 
 - Device: Desktop, Laptop
 - OS: Mac OS Catalina 10.15.7
 - Browser: Firefox, Chrome, Safari

**Additional context**
- A clone of the video will not have the issue. This is our temporary workaround for now.
- Pinning and reloading the page will make the video audio normal again.
- Pausing and skipping still works, and will update both audio sources.
**- Global Media Volume only affects the normal positional audio source.**

Video specs:
MPEG-4
14,8MB
Stereo audio, AAC, H.264
640x360
Duration: 01:30

Also happens with all other mp4 videos I try. Smaller and larger filesize.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-512)

**Comment by camelgod** [comment]
Straight up commenting out the entire block that creates audio element in media-views seems to solve the issue in Safari, Firefox and Chrome:

https://github.com/mozilla/hubs/blob/584e48ad0ccc0da1fc9781e7686d19431a2340cd/src/components/media-views.js#L821

Also seems to have fixed another bug I had with adjusting volume in Safari.

Not sure how it affects other types of media. Will do more testnig.

**Comment by takahirox** [comment]
Hi, thanks for the bug report.

We recently applied bunch of patches for audio issues. Would you mind if testing again to check if the problem is still reproducible?
