### ISSUE TITLE
Long chat messages are cut off

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#3520]
**Description**
The presence log messages can get cut off if they are really long, this also happens for single-line chat messages.

**To Reproduce**
1. Send a long multi-line message
2. Close chat sidebar and see that the message is cut off

1. Send a long single-line message
2. See that the message is cut off in the chat sidebar

**Expected behavior**
They shouldn't be cut off

**Screenshots**
![image](https://user-images.githubusercontent.com/1753624/101672058-3a78a080-3a0a-11eb-8e0d-ab9a0f912800.png)

![image](https://user-images.githubusercontent.com/1753624/101672360-a0fdbe80-3a0a-11eb-971a-440cbd34bb82.png)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 83.0 and Chrome 87.0.4280.88 on Windows 10x64.
Now, long chat messages are NOT cut off, they are correctly displayed in the chat bubbles.
