### ISSUE TITLE
Add a CTA to microphone permission dialog

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#353]
Came up in async discussions, the CTA for the mic permission prompt should be more obvious.

**Comment by cvan** [comment]
I like how [Opera's Download page](https://www.opera.com/computer/thanks?ni=stable&os=mac) detects the browser + OS and guides the user of where to look:

<img width="1464" alt="screen shot 2018-05-02 at 2 58 27 pm" src="https://user-images.githubusercontent.com/203725/39551314-6ab8c20a-4e19-11e8-9043-1ce4b411f182.png">

@gfodor: you got this 💯

**Comment by gfodor** [comment]
Turned on the "next" button in https://github.com/mozilla/hubs/pull/383/files -- does the job
