### ISSUE TITLE
[New-UI] Switch the mic during the meeting

### ISSUE THREAD

**Issue by vincentfretin** [mozilla/hubs#3548]
**Is your feature request related to a problem? Please describe.**
I want to be able to switch to another mic during the meeting.

I may want to test easily the different microphones I have with another participant so I can keep the mic where my voice is clearer.

If when I started the meeting I selected a USB mic, then during the meeting this mic failed for a reason (your cat unplugged it), like disconnected after 10s and the mic changed to internal mic after that (see https://github.com/mozilla/hubs/pull/3543 for context), then I want to be able to switch back to my USB mic easily.

If I was using my internal mic on Chrome and my dock station disconnected and reconnected, the mic stop working. If I can switch to some other mic and back to Internal mic this solves my issue described in the second paragraph of my comment  https://github.com/mozilla/hubs/issues/2643#issuecomment-742750908)

**Describe the solution you'd like**
We should at least add the mic list next to "Preferred camera" in Preferences/Misc, with a mic volume indicator. But I think it should really be accessible right from the menu. Don't forget a "refresh list" button to refresh the list after you connected an USB mic.

**Describe alternatives you've considered**
The alternative is to refresh the page, but that takes time to go back to the room.

**Comment by misslivirose** [comment]
Thanks for filing @vincentfretin - This isn't specific to the new UI; this is a new feature request that we are tracking in #2799 for the platform as a whole. Agree that we should be able to do this without reloading the room.
