### ISSUE TITLE
[New UI] The RTC panel is positioned too far to the right and not fully displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#3567]
**[Affected Versions]:**
- Chrome 87.0.4280.88
- Firefox Release 83.0

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Have a room with the new UI created and opened.

**[Steps to reproduce]:**
1. Click the "Preference" button from the "More" menu.
2. Click the "Misc" button from the top of the page.
3. Click the "Show RTC Panel" checkbox.
4. Close the page and observe the RTC Panel.

**[Expected results]:**
- The panel is correctly positioned and fully displayed.

**[Actual results]:**
- The panel is positioned too far to the right and not fully visible.

**[Notes]:**
- The visibility of the panel is also affected if the Chat box for example, is opened or closed.
- This issue also depends on the screen resolution used, making the panel more or less visible.
- Attached is a screen recording:
![RTCpanel](https://user-images.githubusercontent.com/40061643/102352906-0f192700-3fb1-11eb-97b7-0be3e99a6331.gif)

**Comment by keianhzo** [comment]
@Softvision-RemusDranca I believe this has been fixed and it's available in myhubscloud.com

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using App version: 1.0.0.20210108173817. The RTC panel is now positioned on the entire screen and fully visible.
Tested on Windows 10x64 using Firefox Release 84.0.2 and Chrome 87.0.4280.141.

Considering this I'll close this issue as verified fixed.
