### ISSUE TITLE
Objects menu remains open when you view an object on mobile

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#3572]
**Description**
When you click on the "View" button when inspecting an object in mobile browsers, the inspect view disappears, but the object menu remains open.

**To Reproduce**
1. Open the object menu
2. Inspect an object
3. Tap on "View"
4. See that the inspect view disappears, but the objects menu still remains open

**Expected behavior**
The objects menu should close when you view an object on mobile browsers.

**Hardware** 
 - Device: Phone
 - OS: Android
 - Browser: Chrome

**Comment by robertlong** [comment]
I think #3693 fixed this

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on "https://hubs.mozilla.com/" using App version: 1.0.0.20210224235145. The object menu is closed after tapping "View" while inspecting an element.

Tested on Iphone SE (iOS 14.3) with Safari and Google Pixel 4a (Android 11) with Chrome (88.0.4324.182).
