### ISSUE TITLE
Link icon does not do anything in new hubs UI

### ISSUE THREAD

**Issue by heaversm** [mozilla/hubs#3575]
**Description**
If I click on objects, then choose a model and click "link" it is not grayed out, but it doesn't do anything. Note that if, instead, you raycast to the object in the scene and hold spacebar and click "open link", it will open the sketchfab model. There may be an issue with popup blocking(?). When I used the raycast method, I got a warning asking for permission to open new window (but nothing when trying to access from the "objects" menu

**To Reproduce**
See above.

**Expected behavior**
I get a link to the model URL, or if there is no link, the button should be grayed out.

**Screenshots**

<img width="805" alt="Screen Shot 2020-12-16 at 1 22 58 PM" src="https://user-images.githubusercontent.com/520541/102407998-d6258600-3fa1-11eb-983e-e7cc5cdbe30a.png">

**Hardware** 
Mac OSX Catalina, FF 83

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox Release 84.0.1 and Chrome 87.0.4280.88 on Windows 10.
Now, clicking the “Link” button opens up the URL of the object in a new browser tab.
