### ISSUE TITLE
Rename 'Copy Avatar' to 'Save Avatar'

### ISSUE THREAD

**Issue by heaversm** [mozilla/hubs#3583]
**Description**

If you click on place > avatar, then spacebar on the avatar in the scene and click "copy avatar", you get a "copied" message, but it is unclear what this does. If it is supposed to duplicate the avatar, it does not. If it does something else, I'm not sure what.

**To Reproduce**

**Expected behavior**

Some method of pasting the avatar? Or remove this button?

**Screenshots**

https://share.getcloudapp.com/12uK0ORX

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox 89.0 and Chrome 90.0.4430.212 on Windows 10.
Now, the “copy avatar” button is changed to “save avatar”. Logged issue #4312 but it is unrelated to this fix.
