### ISSUE TITLE
How to add own javascript code to a Mozilla Hubs room (live server, without "npm run deploy")?

### ISSUE THREAD

**Issue by vhelin** [mozilla/hubs#3595]
NOTE: This is actually a question. I was forwarded here from https://support.mozilla.org/en-US/questions/1318383 ...

Hi!

We are trying to use Mozilla Hubs in a customer case, but we need to add functionality (javascript logic that manages some objects) to the rooms. How can this be done? I've tried:

- ... to search for an injection point in the Hubs server running in AWS, but cannot find it (how the room web page is created and from which templates, and where the templates are?)
- ... to deploy our custom Hubs server using "npm run deploy", but the server gets broken and cannot load rooms any more...

Ideally I'd just mod an existing, running, live server without deploying it again as the customer might not allow redeploying...

PS. We cannot create a browser plugin as the customer uses Oculus Quests to run Hubs, and on Quest you cannot use your own browser plugins...

Thanks!

PS. I'm not trying to mod hubs.mozilla.com, but our own (or the customer's) instance of Hubs running on AWS.

**Comment by emclaren** [comment]
transferring to this discussion so the dev team will see it : https://github.com/mozilla/hubs/discussions/3601
