### ISSUE TITLE
Set initial player position using named waypoints

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#3616]
Named waypoints allow the player to move to specific positions once a room is loaded, but if you join a new room using the waypoint fragment syntax you start from the default position rather than the named waypoint.

Consider [this example scene](https://hubs.mozilla.com/scenes/RjWMtwk) with two named waypoints: **red** and **blue**. If create [a room](https://hubs.mozilla.com/LLmN62m/nautical-modern-room) using this scene I would expect to be able to join the room and jump straight to the [blue](https://hubs.mozilla.com/LLmN62m/nautical-modern-room#blue) or [red](https://hubs.mozilla.com/LLmN62m/nautical-modern-room#red) waypoints using the fragment syntax.

<img width="1144" alt="waypoints-redblue" src="https://user-images.githubusercontent.com/303516/102899434-c8b94180-4462-11eb-9223-c4c4e0af1c05.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-134)

**Comment by strangerattractor** [comment]
same problem here. Would love having this feature working!

**Comment by blairmacintyre** [comment]
Ditto.  Still broken.

**Comment by dezigns333** [comment]
You have to make the Way Point 'clickable' from the menu.
Then when you publish the scene and press 'space bar' or 'tab' you will see
the white icons for the Way Points.
When you click on the icons, you will be teleported to the Way Point.

**Comment by dezigns333** [comment]
https://hubs.mozilla.com/scenes/rpfDnLo

**Comment by blairmacintyre** [comment]
> You have to make the Way Point 'clickable' from the menu. Then when you publish the scene and press 'space bar' or 'tab' you will see the white icons for the Way Points. When you click on the icons, you will be teleported to the Way Point.

These two things are orthogonal.  Yes, waypoints work as designed when you are inside a hubs room.  As near as I tested, the various waypoint features work within a room (clickable, orientation, etc).   You can even go to the URL bar and manually append "#waypointname" to the room URL and when you hit return it will teleport you there.

This issue is about using waypoint names on room URLs when you **first enter the room**, so you can link directly to waypoints from outside of hubs.

**Comment by yakyouk** [comment]
Seems to me that the url hash is lost in routing during entry. One quick fix would be to store it and apply it upon entry.

**Comment by rawnsley** [comment]
> Seems to me that the url hash is lost in routing during entry. One quick fix would be to store it and apply it upon entry.

That would work.

It's probably related, but I think the same problem is causing a problem with the back button. Basically you have to press twice to get back because the first time you press it takes you to the #waypoint-name point in the history.

**Comment by blairmacintyre** [comment]
@yakyouk  I came to that conclusion too.  I was leaving it for now, if the team doesn't fix it before I need to launch my project, I'll hack it into mine.

@rawnsley there's some interesting rewriting of the history going on, perhaps that's broken too

**Comment by yakyouk** [comment]
Not a proper fix as it doesn't address history not carrying the hash, but a workaround storing the hash early on and restoring it upon entry: https://github.com/yakyouk/hubs/tree/f/waypoint-spawn-wa

Side notes: I noticed that the hash isn't destroyed during entry when in local mode. My other fix https://github.com/yakyouk/hubs/tree/f/waypoint-reload-bug incidentally allows waypoint links to work in local mode as well.

**Comment by rawnsley** [comment]
Potential fix here https://github.com/mozilla/hubs/pull/4328

**Comment by yakyouk** [comment]
> Going to "bump" this again. I'm using the newest hubs-cloud client, and the fix in #4328 is in there, and this allows me to enter at a waypoint.
> 
> However, if I then refresh the browser, it loses the hash and goes to the default spawn location.
> 
> I think the "correct" behavior would be to have the client go to the entry point that was used when the room was entered, not the URL with the hash stripped. I'm not sure how to fix this.

I don't see a way of handling this with the hash since it's destroyed when moving to a waypoint. An alternative that I used before is to add an extra query param with a waypoint name that is to be used only on spawn or fast-switch.
