### ISSUE TITLE
sign up and use WebXR Chrome Origin Trials

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#365]
from https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/available-trials.md:

> WebXR (For Chrome M67+) | Allows web sites to use virtual reality and applications that your audience can access on AR or VR enabled mobile devices or VR enabled headsets like Google's Daydream, Oculus Rift, Samsung Gear VR, HTC Vive, and Windows Mixed Reality Headsets. This is a new trial that requires registering separately from the existing WebVR trial. | First available in Chrome M67. Trial ends on September 17, 2018.
> -- | -- | --
> WebVR (For Chrome M62+) | Allows web sites to make use of any VR headset and a VR-capable device to create fully immersive 3D experiences. This is a new trial to continue experimenting with WebVR.Intent to Experiment | First available in Chrome M62. Trial ends on July 24, 2018.

here's the [Sign-Up page](https://docs.google.com/forms/d/e/1FAIpQLSfO0_ptFl8r8G0UFhT0xhV17eabG-erUWBDiKSRDTqEZ_9ULQ/viewform)

**Comment by misslivirose** [comment]
It looks like this was addressed so I'm going to close this - we can create a new issue to track future work that needs to be done around this.
