### ISSUE TITLE
Paste Twitter URL into room or in Spoke result in a broken url

### ISSUE THREAD

**Issue by robinkwilson** [mozilla/hubs#3654]
**Description**
Paste a twitter URL into a Hubs room and it will result in a broken link. 
https://github.com/mozilla/hubs/discussions/3625

**To Reproduce**
1. Open hubs room
2. Paste https://twitter.com/home in the window (not the chat)
4. See error in console and broken link in room

**Expected behavior**
Webpage screenshot for twitter links.

**Screenshots**
See https://github.com/mozilla/hubs/discussions/3625

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**
Twitter video links work.

**Comment by VelocityDesign** [comment]
I don't know if this is helpful, but twitter statuses don't work either. It is most likely that it detects it as a video and not a web page.
System:

Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-bit)
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 20H2 (Build 19042.685)
JavaScript | V8 8.7.220.29
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36

**Comment by VelocityDesign** [comment]
I can confirm that it has to do with the domain twitter.com.
Strangely, the same thing doesn't happen to youtube.com.
One more thing: Statuses are also affected by this.

**Comment by tttigo** [comment]
Instagram URL not working well too.

**Comment by misslivirose** [comment]
Thanks for the additional detail - we have an issue filed in the server repository where the media resolver lives to track this (https://github.com/mozilla/reticulum/issues/435) so I'm going to resolve this as a duplicate, but it's good to know that we can use Twitter and Instagram links as a base case for sites that should be resolving properly but aren't!

**Comment by misslivirose** [comment]
(I added the corresponding reticulum bug to our kanban board to bump up the priority - I think that it will go a long way in improving the in-room experience for media)
