### ISSUE TITLE
Uploaded music files in a room continue to play at the same volume even when muted

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#3658]
**[Affected Versions]:**
- Firefox Release 84.0.1
- Chrome 87.0.4280.88

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Have a new room created and entered.

**[Steps to reproduce]:**
1. Drag and drop a music file in the room or upload the file.
2. Click the “-” volume down button from the object until it is muted.
3. Observe the volume of the music.

**[Expected results]:**
- The volume is set to a lower and lower level until it is muted and no longer can be heard.

**[Actual results]:**
- The volume remains the same, the text displayed in the volume bar is “MUTE”

**[Notes]:**
- The volume remains the same when the “+” volume up button is clicked as well.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1ZSvbXESTDFtG6YVKRyIWnxYcFCOfWwVC/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-145)

**Comment by johnshaughnessy** [comment]
This should block release until we understand what is happening here. (Should I add the [QA]:Blocker issue label?)

**Comment by takahirox** [comment]
Probably this problem will be fixed by #4445 for Hubs Cloud, and already solved in hubs.mozilla.com.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using the latest releases of Firefox and Chrome on Windows 10.
Now, uploaded music files do not play at the same volume when muted.
