### ISSUE TITLE
Invert look controls

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#369]
When using a mouse or trackpad, some users expect to look up when dragging down, and to look down when dragging up. Provide a way for them to invert the default direction of look controls.

**Comment by gfodor** [comment]
This is probably gated on a Wall-O-Checkboxes dialog and the infamous Gear Icon. I think we should do it, but I don't know where, exactly, to bury it in the UI right now.

**Comment by misslivirose** [comment]
Implemented with #2555
