### ISSUE TITLE
Ability to jump over things

### ISSUE THREAD

**Issue by djay** [mozilla/hubs#3721]
**Is your feature request related to a problem? Please describe.**
Chairs, railings and other obstacles can be confusing for new users. in particular the chairs in the outdoor meetup scene.
Having to walk around this is 

**Describe the solution you'd like**
Have a jump short cut. For anyone familiar with first person games this is a very instinctive way of dealing with obstacles.
Normally this is the space bar but that is already in use so another would have to be found.

**Describe alternatives you've considered**
- fly mode so you can go through anything. but this is less intuitive

**Additional context**
I could provide additional emotion expressing. like jumping instead of clapping.

**Comment by misslivirose** [comment]
Hey djay, thanks for filing. This is one of the features that is captured and supported by #2302 so I'm going to resolve this as a duplicate. The work in 2302 will allow us to update the character controller to support jumping, which is included as one of the things that we'd add if we switch to that type of system.
