### ISSUE TITLE
Re-implement the ability to hide the lobby UI 

### ISSUE THREAD

**Issue by hbollaert** [mozilla/hubs#3765]
the lobby feature is a great alternative to having more viewers able to attend in case the room is full.
but since the new user interface the "enter room" pop up is blocking the view.
in the previous UI one could close that pop-up

**Comment by misslivirose** [comment]
We will temporarily overload the spectate button to fix this and hide the main middle modal in the lobby. We will also add the ~ key behavior back into the lobby to toggle everything showing or hiding. The bottom bar will stay in place for the first pass, but we'll do a full design pass on this in a couple of weeks.

**Comment by misslivirose** [comment]
Fixed by #3776
