### ISSUE TITLE
Can't load video

### ISSUE THREAD

**Issue by VelocityDesign** [mozilla/hubs#3817]
**Description**
Ok, so whenever I paste a video link (say, for example, https://www.youtube.com/watch?v=MfRhNluOVeI) Hubs says that it cannot load the video and that it has exceeded its quota on resolving videos from 'This Provider'. I just wanted to report it because even though it is likely just youtube's limit, it could be an error with hubs itself.
**To Reproduce**
1. Copy a link (https://www.youtube.com/watch?v=MfRhNluOVeI)
2. Paste it into a room
3. See error

**Expected behavior**
YouTube video should paste into the room and start playing.

**Screenshots**

**Hardware** 
- Laptop
- Browser: Brave Browser
CHROME VERSION |   | 88.1.19.88 (Developer Build 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784} Windows)
-- | -- | --
OS VERSION |   | Windows NT: 10.0.19042

**Additional context**
Nothing else

**Comment by misslivirose** [comment]
Thanks for the bug report - this is an issue specific with YouTube due to limiting on video fetches. More information is documented here :https://github.com/mozilla/hubs/discussions/2681. We generally recommend uploading videos directly or using an alternate provider when possible.
