### ISSUE TITLE
Enter on GearVR is totally hosed

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#382]
This, apparently, never worked, unless you were like me and had an esoteric app called "Launch in Oculus Browser" installed on your phone :/

**Comment by InfiniteLee** [comment]
What is broken exactly? We can enter on GearVR on oculus go fine.

**Comment by cvan** [comment]
I think @gfodor means deep-linking from the `Enter in Gear VR` button from Chrome/Firefox

**Comment by InfiniteLee** [comment]
Ah yea I just saw the convo on slack.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/383
