### ISSUE TITLE
The "g" character from strings inside the drop-down fields in Preferences is slightly cut

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#3825]
**[Affected Versions]:**
- Google Chrome - Version 88.0.4324.104
- Firefox Release - Version 85.0

**[Affected Platforms]:**
- Windows 10 x64.

**[Prerequisites]:**
- A room is opened on the "https://hubs.mozilla.com/" website.

**[Steps to reproduce]:**
1. Open the Preference menu from the More menu.
2. Open for example the "Misc" section.
3. Click the "Material quality" drop down-menu.
4. Select the "High" option.
5. Observe "g" character.

**[Expected results]:**
- The character is correctly displayed.

**[Actual results]:**
- The character is slightly cut at the bottom.

**[Notes]:**
- This issue is reproducible with all strings that include the "g" character inside Preferences in all drop-down fields..
- Attached is a screenshot of the issue: 
![GString](https://user-images.githubusercontent.com/40061643/106483158-e5f81b80-64b6-11eb-8d30-c28e2290c10e.PNG)

**Comment by csnktms** [comment]
https://github.com/mozilla/hubs/pull/3860

**Comment by robertlong** [comment]
Fixed in https://github.com/mozilla/hubs/pull/3860

Thanks again @csnktms!

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on "https://hubs.mozilla.com/" using App version: 1.0.0.20210220005842. The "g" character is no longer cut in "Preferences"
- Tested on:
	- Windows 10 using Firefox Release (85.0.2) and Chrome (88.0.4324.182).
	- Iphone SE using Safari 14 and Chrome (87.0.4280.77).
