### ISSUE TITLE
Potential Action Required: Lambda Botocore Deprecation

### ISSUE THREAD

**Issue by jasoncks** [mozilla/hubs#3844]
**Description**
We have a mail from AWS that reported about "Potential Action Required: Lambda Botocore Deprecation"

> 
> Below is the part of the mail: 
> We are contacting you regarding actions needed on your account(s) to prevent disruption to your CloudFormation stacks. Starting on April 01, 2021, AWS Lambda will no longer support the botocore.requests library in Python runtimes [1][2]. If you are using the cfn-response module for a Lambda-backed custom resource, you must modify your Lambda function resource’s Code or Runtime property and update your stack(s) in order to get the latest version of the cfn-response module which removed its dependency on botocore.requests. If you do not update your Lambda function by April 01, 2021, you will no longer be able to create, update or delete your custom resource. If you are updating the Runtime property, please include the lambda:UpdateFunctionCode action in your IAM policy.
> 
> If you are hosting your Lambda function code from an S3 bucket, you can refer to the updated cfn-response module’s source code in our documentation [3]. For more information on how to update lambda function can be found in knowledge center [4].
> 
> Please contact AWS Support if you have any questions or concerns [5].
> 
> [1] https://aws.amazon.com/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/
> [2] https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/
> [3] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html
> [4] https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-cfn-response-lambda/
> [5] https://aws.amazon.com/support/

**To Reproduce**
I have not check all Lambda functions that done by HubsCloud
But I found that at least in "EmptyBucketFunction", botocore.requests is import in the python script.
1. Login to AWS Account
2. Go to Lambda panel
3. Select the "EmptyBucketFunction"

**Expected behavior**
Update the related functions to prevent disruption of CloudFormation.

Please let me know should this problem need to be fixed by ourselves.
If so, we would like to know the steps also.

As ours HC instance is now in service and we do not want the services to be disrupt after April 01, 2021.

Thank you

**Comment by jasoncks** [comment]
With help from AWS support, I get the list of function that related to this problem.

- CustomAcmCertificateLambda
- EmptyBucketFunction
- SESDomainApplication-N-SESDomainFunction
- ses-password

Here is also, part of the reply from AWS

> Using our internal tools I went ahead and checked the lambda functions in your account. I found the following list of functions which might be potentially affected. These functions are using python 2.7 or python 3.6 or python 3.7 in ap-northeast-1 region.
> 
> Please note that this change affects the Python 2.7, Python 3.6 and Python 3.7 Runtime. The Python 3.8 runtime is not affected.
> 
> If any of the above lambda functions rely on requests module, you need to review them and take action appropriately.
> 
> In order to fix this for any function that can be affected, you have 2 options
> 
> 1. Bundling the 'requests' module within the deployment package and to make appropriate code change for import statement.
> 2. Using AWS Lambda layers with AWS SDK which includes 'requests' module.
> 
> Both options are explained in detailed steps here (1)
> 
> Kindly note that if you are using AWS Cloud Formation templates that include the cfn-response module, this module’s dependency on botocore.requests has been also removed. You can follow the steps described in this blog (2) to help you with updating the AWS Cloud Formation cfn-response module for AWS Lambda functions running on Python 2.7/3.6/3.7
> 
> I hope you find the above information useful. Please feel free to reach out to me if you have any other questions and I would be glad to help.
> 
> (1) https://aws.amazon.com/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/
> (2) https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-cfn-response-lambda/

Please let me know if any additional information is needed.

**Comment by misslivirose** [comment]
This is tracked in https://github.com/mozilla/hubs-cloud/issues/183 - thank you for filing!
