### ISSUE TITLE
[VR] The mobile icon is wrongly displayed in front of the name in the "People" section

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#3848]
**[Affected Versions]:**
- Firefox Reality - Version 12
- Oculus Browser

**[Affected Platforms]:**
- Oculus Quest
- Pico Neo2

**[Prerequisites]:**
- The "https://hubs.mozilla.com/" website is opened.

**[Steps to reproduce]:**
1. Open or create a room.
2. Click the "People" button from the top-right corner.
3. Observe the icon displayed in front of the name.

**[Expected results]:**
- The VR icon is displayed.

**[Actual results]:**
- The mobile icon is displayed.

**[Notes]:**
- This issue was not reproducible with the previous UI.
- Attached is a screenshot of the issue: 
![org mozilla vrbrowser-20210202-180329](https://user-images.githubusercontent.com/40061643/106630207-4ef99500-6584-11eb-8efb-d78a18ccd23a.jpg)

**Comment by csnktms** [comment]
https://github.com/mozilla/hubs/pull/3859

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on "https://hubs.mozilla.com/" using App version: 1.0.0.20210222221102. The VR icon is now displayed for user that use VR headsets.
Tested on Pico Neo 2 using Firefox Reality v12.

Considering this I will close this issue as verified fixed.
