### ISSUE TITLE
suddenly stopped loading the assets (vimeo links)

### ISSUE THREAD

**Issue by kurtmalonnek** [mozilla/hubs#3889]
Hi, I'm working on an online electronic art exhibition in hubs, one of the rooms suddenly stopped loading the assets and this musical note icon appears, only some audios are heard, most are links to videos hosted on vimeo

https://hub.link/MCPspwc

![image](https://user-images.githubusercontent.com/30682511/107395590-b7dc9200-6adb-11eb-833a-15dd95eff538.png)

**Comment by brianpeiris** [comment]
Thanks for reporting this, @kurtmalonnek. It is a known issue and we're working on a fix.

**Comment by brianpeiris** [comment]
We've released a fix for this. Apologies for the delay.
