### ISSUE TITLE
[Iphone SE] The room codes entered are cut off

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#3915]
**[Affected Versions]:**
- Safari - Version 14
- Chrome - Version 87.0.4280.77

**[Affected Platforms]:**
- Iphone SE (iOS 14.3)

**[Prerequisites]:**
- Have the browser opened.

**[Steps to reproduce]:**
1. Navigate to the "https://hubs.mozilla.com/link" page.
2. Tap on a number/letter from the page displayed.
3. Observe the inserted number/letter.

**[Expected results]:**
- The number/letter is correctly displayed.

**[Actual results]:**
- The number/letter is cut at the bottom.

**[Notes]:**
- The issue is also reproducible on landscape view mode.
- I was not able to reproduce this issue on mobile devices with bigger screens, for example with the Google Pixel 4a.
- Attached is a screenshot of the issue: 
![IphoneSE](https://user-images.githubusercontent.com/40061643/108074950-749d9880-7072-11eb-99f3-a4d0bb1c3946.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-542)

**Comment by CodingAlbert** [comment]
> **[Affected Versions]:**
> 
> * Safari - Version 14
> * Chrome - Version 87.0.4280.77
> 
> **[Affected Platforms]:**
> 
> * Iphone SE (iOS 14.3)

I am adding more affected platforms.

**[Affected Platforms]:**
iPad Air 2 (iOS 14.4)

**Comment by Softvision-RemusDranca** [comment]
This issue is no longer reproducible for me using on Iphone SE2 (iOS 15.0.1) using Safari and Chrome 94.

@CodingAlbert can you also please check on your iPad Air 2 with the latest iOS (15.0.1) update?

**Comment by matthewbcool** [comment]
room codes are no longer in use
