### ISSUE TITLE
Cardboard support in Firefox for Android

### ISSUE THREAD

**Issue by rugk** [mozilla/hubs#392]
Some time ago I tried this in Firefox for Android, Android 7/LineageOs 14.1.

So I have the option to select "Phone" (which is just some touch navigation) and "GearVR". As it seems "GearVR" can be used with professional headsets, but not with a simple cardboard.

AFAIK when "GearVR" has been selected this does not work. IMHO there should be an option "Cardboard", which just splits the screen as cardboard stuff just usually does it.

**Comment by InfiniteLee** [comment]
We currently don’t enable cardboard on Android Firefox due to some rendering issues. It should work on Chrome, however.

**Comment by rugk** [comment]
Huh, that's bad. Is there a Firefox bug where this is tracked? Or is there a Firefox version where this is already fixed?

**Comment by InfiniteLee** [comment]
It is not an issue with Firefox. Hubs specifically has a bug with cardboard on both iOS and Android/Firefox. See #352

**Comment by rugk** [comment]
I have not used it yet, but I thought this would be a nice project.

And hey, this is a Mozilla project, so I would really assume you should support Firefox, at least. I mean, if there are technical problems as you said, you should have the connection to address them… :stuck_out_tongue_winking_eye: (Or are these Android limitations?)

And if you say there is this lag problem then the previous statement is no longer true:
> It is not an issue with Firefox.

So let's open a Firefox bug if there is not yet one and try to bring that thing here to more browsers…

**Comment by brianpeiris** [comment]
Looks like there is already a [Firefox bug for this](https://bugzilla.mozilla.org/show_bug.cgi?id=1310657), but the [latest update](https://bugzilla.mozilla.org/show_bug.cgi?id=1340876#c12) is that WebVR on Android will be supported through the [Firefox Reality browser](https://blog.mozilla.org/blog/2018/04/03/mozilla-brings-firefox-augmented-virtual-reality/) which is in active development.

**Comment by rugk** [comment]
Hu… first time I heard about this. But kinda strange, do not really feel the need for another browse just to use one web standard/feature – it's all about the web, not yet another browser.

**Comment by rugk** [comment]
Ah… wait…  Firefox Reality browser was the thing of a browser _for_ VR devices if I understood it correctly. So you could surf "usual" websites on such headsets.

If it will be cross-device then maybe you can use it on Android, too, ~but I have not seen this mentioned anywhere explicitly (only skimmed the post though).~ Saw your link, okay…

So basically this is still something else, I think. Maybe you can also use VR demos, but I just want to use my "usual" browser for that. E.g. to go to the website itself, I may not really want to do that in VR mode, I can just type the website as usual with an on-screen keyboard.
And AFAIK some WebVR support is already implemented in Firefox (for Android), so it needs bugfixing anyway (or removing of this feature, but that would be removing a web standard just to push a different browser.).

**Comment by brianpeiris** [comment]
Yeah, it's all still in a state of flux, especially considering the WebVR spec will be replaced with the WebXR spec in the near future. For the most part we (the Hubs team) will target what ever browser will target as many browsers and platforms as feasible, as long as there is some decent baseline of performance. Unfortunately the Firefox for Android performance (specifically regarding the gyroscope lag) does not meet that baseline at the moment. We will certainly be targeting Firefox Reality.

I'm going to go ahead and close this bug (for Hubs at least). Feel free to continue a conversation on the Firefox Bugzilla if you feel that's a better venue.

Thanks for giving Hubs a try and for taking the time to submit an issue!

**Comment by rugk** [comment]
Okay, thanks. I did so.
