### ISSUE TITLE
'addTrack' is broken on Chrome, Firefox and Edge when sharing screens

### ISSUE THREAD

**Issue by dezigns333** [mozilla/hubs#3920]
When attempting to share a screen from a local computer in a browser from an application like Hubs  nothing happens after pressing the share icon. On further inspection using the developers tools "scene-entry-manager.js:421 Uncaught (in promise) TypeError: Cannot read property 'addTrack' of null shows up in the errors.

**Comment by misslivirose** [comment]
Hey @dezigns333 - can you add more information about the system that you're testing this on? I'm unable to reproduce this.

**Comment by dezigns333** [comment]
I'll close it. it's working again it seems. It was very strange.  It happened after a Chrome update I think.
