### ISSUE TITLE
The webcam can not be shared

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#3952]
**[Affected Versions]:**
- Firefox Release 86.0
- Chrome 88.0.4324.182
- Safari 14

**[Affected Platforms]:**
- Windows 10x64
- Android 10
- iOS 14.3

**[Prerequisites]:**
- Have a new room created and entered.
- Make sure a user is signed in.

**[Steps to reproduce]:**
1. Click the “Share” button from the bottom menu.
2. Click the “Camera” button from the Share menu.
3. Observe the behavior.

**[Expected results]:**
- Permissions are asked for the webcam or the webcam feed appears in the room.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- The issue is reproducible on the mobile Chrome browser and Safari on the iPhone as well.
- The issue is not reproducible on the mobile Firefox browser.
- The issue is not reproducible on Hubs Cloud.
- This seems to be a regression.
- Attached a screen recording of the issue below
![share camera](https://user-images.githubusercontent.com/51400741/108965359-6c9eb380-7685-11eb-82b8-d654a3a68aee.gif)

**Comment by misslivirose** [comment]
Looks like the following error shows up: 

`Uncaught TypeError: e.detail is null
    _setupMedia scene-entry-manager.js:466
    a raven.js:377
    value Aframe
    u SharePopoverContainer.js:74
    onClick ButtonGridPopover.js:19
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    a raven.js:377
`

**Comment by robertlong** [comment]
This should be fixed now https://github.com/mozilla/hubs/pull/3957

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox and Chrome on Windows 10 and Android 10, I also verified using Safari 14 on iOS 14.3 and Mac OS Catalina 10.15.7.
Now, the webcam can be shared.
