### ISSUE TITLE
Waypoints don't work on mobile

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [mozilla/hubs#4004]
**Description**
Waypoints don't work when you click them on mobile

**To Reproduce**
1. Go to a scene with waypoints: https://hubs.mozilla.com/rnq8pf2/good-clear-nation/#
2. Tap on a waypoint
3. You can't go to it on mobile

**Expected behavior**
Going to the waypoint you clicked

**Hardware**
 - Device: Phone
 - OS: Android
 - Browser: Chrome & Firefox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-565)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using the latest mobile releases of Firefox and Chrome on an Android 11 device.
Now, waypoints work in the room from the above steps and in newly created rooms. Waypoints on mobile don’t work if the “Create and move objects” setting from room settings is disabled.
