### ISSUE TITLE
"Change name and avatar" breaks experience on Safari Mac Desktop

### ISSUE THREAD

**Issue by rogerkenny** [mozilla/hubs#4011]
**Description**
While viewing a room from the lobby on Safari Mac Desktop, clicking on the 'More' button and then 'Change name and avatar' item puts the user in a broken state. The room is active but all UI disappears. The avatar and name panel does not show up and there are no UI buttons visible. Only option is to go back or close the window.

**To Reproduce**
1. Enter the lobby of a room.
2. Click on the 'more' button at the bottom right of the screen.
3. Click on the 'Change name and avatar' item from the list.
4. Notice that all UI has disappeared with no way to recover.

**Expected behavior**
On other browsers a panel will appear on the right side of the window which allows the user to change their username and choose an avatar. 

**Screenshots**
<img width="1438" alt="Screen Shot 2021-03-12 at 3 01 55 AM" src="https://user-images.githubusercontent.com/12489309/110910443-5593ce80-82df-11eb-9df3-1ce693b9fd14.png">

**Hardware** 
 - MacBook Pro 
 - macOS Big Sur 11.2.2
 - Safari

**Additional context**
Seems to occur when joining a room on Safari as well, but I noticed it as soon as I went to set my name and avatar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-569)

**Comment by matthewbcool** [comment]
I believe this one has been fixed. Was not able to repro on safari desktop.
