### ISSUE TITLE
[iOS][MacOS] The Attach button from the Upload prompt is displayed to the left and the text is not visible

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4031]
**[Affected Versions]:**
- Safari 14 (iOS and MacOS)
- Chrome 89 (iOS)

**[Affected Platforms]:**
- MacOS 10.15.7
- Iphone SE 14.4

**[Prerequisites]:**
- Have a room opened on "https://hubs.mozilla.com/" website.

**[Steps to reproduce]:**
1. Click the "Place" button from the menu bar.
2. Click the "Upload" button from the prompt displayed.
3. Observe the input field from the "Custom Object" prompt.

**[Expected results]:**
- The Attach button is displayed to the right and the placeholder is visible.

**[Actual results]:**
- The Attach button is displayed to the left and only a few or one letter is displayed from the placeholder.

**[Notes]:**
- The names of the attached files are not visible.
- After inserting a string in the input field, the "x" dismiss button replaces the Attach button, in the same position.
- I was able to reproduce the issue on Chrome and Safari using an iOS device.
- I was only able to reproduce the issue on Safari while using the MacOS device.
- I was not able to reproduce the issue using Windows 10 or Android devices.
- The functionality is not affected, the objects can still be created/uploaded.
- Attached is a screenshot of the issue:
![iOSupload](https://user-images.githubusercontent.com/40061643/111498450-a295fb80-874a-11eb-9143-a035febaab1b.jpeg)
![MacUpload](https://user-images.githubusercontent.com/40061643/111498469-a6c21900-874a-11eb-88c2-5374e8dec10a.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-575)

**Comment by takahirox** [comment]
I confirmed that this problem is still reproducible on iOS 15 and MacOS BigSur 11.6.

I guess this is a CSS stuff? Wondering who knows CSS well in the team. @matthewbcool ?

**Comment by SV-AndreiC** [comment]
I have verified this issue and it's no longer reproducible. The Attach button from the Upload prompt is correctly displayed to the right and the text is visible. 
Tested this on iOS 15.1 and macOS BigSur v11.6.1 using Safari v15.1.
