### ISSUE TITLE
[iOS][Intermittent] The video controls are hard to toggle with or are not responsive

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4032]
**[Affected Versions]:**
- Safari 14 

**[Affected Platforms]:**
- Iphone SE 14.4

**[Prerequisites]:**
- Have a room opened on "https://hubs.mozilla.com/" website.
- Have a video spawned into the room.

**[Steps to reproduce]:**
1. Tap on the video from prerequisites to display video controls.
2. Tap on the video controls.
3. Observe the behavior.

**[Expected results]:**
- The control buttons are responsive.

**[Actual results]:**
- The control buttons are not always responsive.

**[Notes]:**
- This issue is also reproducible for GIF formats.
- In some attempts the buttons seem to remain in a click state when tapped.
- Attached is a screen recording of the issue: [link](https://drive.google.com/file/d/1E6GEDBHSYVihWnQ_S2ejLeG2UU74UGaW/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-576)

**Comment by takahirox** [comment]
Maybe this issue is very related to #4036 ?

**Comment by Softvision-RemusDranca** [comment]
@takahirox  They could be related, the difference is that in this issue the video controls can be tapped but they aren't responsive and in the other issue the object itself is "thrown" away and it involves all types of objects with the condition that they are not pinned.

**Comment by takahirox** [comment]
@Softvision-RemusDranca

Thanks for explaining. Yeah this issue sounds different from the other.

I know tapping controls including response from tapping objects on mobiles in Hubs is unstable and we should improve it at some point. If we improve tapping controls, I speculate this problem will be resolved too.

**Comment by Softvision-RemusDranca** [comment]
@takahirox  I was not able to reproduce this issue on Iphone SE2 (iOS 15) with Safari and on Google Pixel 4a using Chrome 92.
Now, the media buttons are actionable from different positions.
Considering this I will close this issue as verified fixed.
