### ISSUE TITLE
[iOS][Intermittent] A shadow remains displayed after importing a GIF file 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4033]
**[Affected Versions]:**
- Safari 14 

**[Affected Platforms]:**
- Iphone SE 14.4

**[Prerequisites]:**
- Hubs Cloud services are set up.
- Have a room opened.

**[Steps to reproduce]:**
1. Tap on the "Place" button from the menu bar.
2. Tap the "Upload" button from the prompt displayed.
3. Tap on the GIF button.
4. Select a GIF from the list and observe the behavior.

**[Expected results]:**
- The Hubs room is redisplayed and the file is spawned into the room.

**[Actual results]:**
- A shadow is also visible in the room along with the spawned file.

**[Notes]:**
- The shadow is dismissed after tapping inside the room.
- Attached is a screen recording of the issue: [link](https://drive.google.com/file/d/1nl4lnS0pQzw1QscIHyUBH-ny77iH8bHn/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-577)

**Comment by takahirox** [comment]
I couldn't reproduce the problem on my iPhoneX iOS 15 + Safari. Would you mind if testing again to check if it's still reproducible on your iOS 15 device?

**Comment by Softvision-RemusDranca** [comment]
@takahirox  I was not able to reproduce this issue on Iphone SE2 (iOS 15) with Safari in multiple attempts.
Considering this I will close this issue as verified fixed.
