### ISSUE TITLE
[Mobile][Intermittent] The objects are "thrown" away when trying to tap on them

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4036]
**[Affected Versions]:**

* Safari 14 

**[Affected Platforms]:**

* Iphone SE 14.4

**[Prerequisites]:**

* Have a room opened on "https://hubs.mozilla.com/" website.

**[Steps to reproduce]:**

1. Spawn an object/video into the room.
1. Tap on the object/video.
1. Observe the behavior.

**[Expected results]:**

* The object/videos controls are displayed.

**[Actual results]:**

* The object/videos are "thrown" away.

**[Notes]:**

* I was not able to reproduce the issue with pinned objects/videos.
* Attached is a screen recording of the issue: [link](https://drive.google.com/file/d/146ePMv-HqQRnSroCpAh6ErqOYH5vcrGZ/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-579)

**Comment by Softvision-GeluHaiduc** [comment]
Unfortunately, this issue is still reproducible using the latest mobile releases of Firefox and Chrome on an Android 11 device.

**Comment by Softvision-RemusDranca** [comment]
I was also able to reproduce the issue on Iphone SE2 (iOS 15) using Safari.
