### ISSUE TITLE
[Mobile] The buttons from the objects/drawings/media don't work in first attempts or they remain in a click state

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4048]
**[Affected Versions]:**
- Safari 14 
- Chrome 89

**[Affected Platforms]:**
- Iphone SE 14.4
- Google Pixel 4a

**[Prerequisites]:**
- Have a room opened on "https://hubs.mozilla.com/" website.

**[Steps to reproduce]:**
1. Spawn an object into the room.
2. Tap on the screen using two fingers to display the object menu.
3. Tap on the objects from the menu.

**[Expected results]:**
- The buttons perform they designed functionality.

**[Actual results]:**
- The buttons are not performing their functionality in first attempts or they remain in a click state.

**[Notes]:**
- Usually a tap needs to be performed outside the menu's area and than try to tap on the buttons.
- Sometimes it takes more than two attempts to trigger the buttons functionality.
- I will log separate issues for the buttons that I could not trigger their functionality at all.
- Attached are screen recordings of the issue: 
	- iOS: [link](https://drive.google.com/file/d/1lUW3U1wpcc_v7zJcvy3dDVGBYpQTFtMI/view?usp=sharing).
	- Android: [link](https://drive.google.com/file/d/1-tBezWuil-Zb8-s_NV-pBeT_hLbIx8zl/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-582)

**Comment by takahirox** [comment]
@Softvision-RemusDranca

Sounds like there is a chance that #4397 can resolve the problem? Do you mind if testing again to check if the problem is still reproducible?

**Comment by Softvision-RemusDranca** [comment]
@takahirox  I was not able to reproduce this issue on Iphone SE2 (iOS 15) with Safari and on Google Pixel 4a using Chrome 92.
Now, the buttons from the object menu are actionable.
Considering this I will close this issue as verified fixed.
