### ISSUE TITLE
A pinned PDF file is enlarged if the next/previous page button is clicked repeatedly

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#4059]
**[Affected Versions]:**
- Firefox Release 86.0.1
- Chrome 89.0.4389.82

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Make sure to have a room created and entered.

**[Steps to reproduce]:**
1. Click the "Place" button.
2. Click the "Upload" button from the menu and attach a PDF file.
3. Click the "Create Object" button.
4. Pin the PDF file in the room.
5. Click the next/previous page button and observe the behavior.
    
**[Expected results]:**
- The next/previous page of the PDF file is displayed.

**[Actual results]:**
-  The next/previous page of the PDF file is displayed but the PDF file is also enlarged.

**[Notes]:**
- The issue is not reproducible if the PDF file is not pinned.
- Attached a screen recording of the issue below
![pdf file](https://user-images.githubusercontent.com/51400741/111789757-2cb89e00-88ca-11eb-8272-dc5465f61dc0.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-585)

**Comment by mauriciomartinez-itesm** [comment]
This issue has already been reported in #2284

**Comment by matthewbcool** [comment]
Seems to be fixed, can we confirm?

**Comment by mauriciomartinez-itesm** [comment]
> Seems to be fixed, can we confirm? Never mind! was able to reproduce after moving the pdf, resizing it and re-pinning.

This issue has not been fixed in the production build yet, I just tested it... remember to pin the PDF before clicking right and left rapidly

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using the latest releases of Firefox and Chrome on Windows 10.
Now, a pinned PDF file is no longer enlarged if the next/previous page button is clicked repeatedly.
While verifying this issue I encountered another issue that is logged here #4696.
