### ISSUE TITLE
Need a way to include cube map reflections for any and all models that are using PBR shader.

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#406]
Any models that use the PBR shader and have roughness that is anything less than 100% need something to reflect. Without reflection maps, any shiny objects will appear way too dark. Typically, this is done by having a cubic or spherical reflections. Ideally, this would be generated by placing nodes within the environment and having part of the build process generate reflection maps at those locations. You'd also want to be able to specify the distance (a depth defined by x, y, z--a box, essentially) that the reflection maps would render. Then, those reflection maps would get applied to any and all PBR materials in your scene. See Unity's documentation on Reflection Probes for what I'm describing here. https://docs.unity3d.com/Manual/class-ReflectionProbe.html
In lieu of this auto-generation, I would settle for the ability to set one reflection map for a given scene that would get applied to all meshes with a PBR material on them.

**Comment by robertlong** [comment]
Closing in favor of https://github.com/MozillaReality/Spoke/issues/350 and https://github.com/mozilla/hubs/issues/637
