### ISSUE TITLE
[Mobile] The track, focus and Pin/Unpin buttons are only working from certain positions

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4061]
**[Affected Versions]:**
- Safari 14 
- Chrome 89

**[Affected Platforms]:**
- Iphone SE 
- Google Pixel 4a

**[Prerequisites]:**
- Have a room opened on "https://hubs.mozilla.com/" website.
- Have an object spawned into the room.

**[Steps to reproduce]:**
1. Open the "Camera" from the "Place" menu.
2. Tap on the screen using two fingers to display the object menu.
3. Tap on the track/focus buttons and observe the behavior.
4. Tap the Pin/Unpin buttons from the menu and observe the behavior.

**[Expected results]:**
Step3: The camera is focused on the object every time.
Step4: The object is pinned/unpinned every time.

**[Actual results]:**
Step3: The camera is focused on the object only after moving the avatar or moving the object.
Step4: The object is pinned/unpinned only after moving the avatar or moving the object.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/file/d/1EmVnuBqfP2W2ZN1aUeP2yJK8I2xbtd4Q/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-587)

**Comment by takahirox** [comment]
@Softvision-RemusDranca 

Sounds like there is a chance that #4397 can resolve the problem. Do you mind if testing again to check if the problem is still reproducible?

**Comment by Softvision-RemusDranca** [comment]
@takahirox  I was not able to reproduce this issue on Iphone SE2 (iOS 15) with Safari and on Google Pixel 4a using Chrome 92.
Now, the track, focus and Pin/Unpin buttons are actionable from different positions.
Considering this I will close this issue as verified fixed.
