### ISSUE TITLE
[iOS] The "Browse" button from the attach menu is not visible if opened while the keyboard is on

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4063]
**[Affected Versions]:**
- Safari 14 

**[Affected Platforms]:**
- Iphone SE 

**[Prerequisites]:**
- Have a room opened on "https://hubs.mozilla.com/" website.

**[Steps to reproduce]:**
1. Tap on the "Chat" button from the menu bar while having the phone in portrait mode.
2. Tap inside the Chat input field to display the keyboard.
3. Tap the "Attach" button and observe the behavior.

**[Expected results]:**
- The attach menu is fully displayed.

**[Actual results]:**
- The "Browse" button from the attach menu is not displayed.

**[Notes]:**
- The issue is not reproducible when performing the steps while the device is in landscape mode.
- Attached is a screen recording of the issue: [link](https://drive.google.com/file/d/1Gq6E_Mz_K20xeIOFGRlJeiXsGoxWghnd/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-589)

**Comment by takahirox** [comment]
I couldn't reproduce the problem on my iPhoneX(iOS 15) Safari. Do you mind if testing again on iOS15 to check if it's still reproducible?

**Comment by Softvision-RemusDranca** [comment]
@takahirox  I was not able to reproduce this issue on Iphone SE2 (iOS 15) with Safari.
Now, all three options from the attach menu are displayed.
Considering this I will close this issue as verified fixed.
