### ISSUE TITLE
The invite only link can not be revoked

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#4070]
**[Affected Versions]:**
- Firefox Release 86.0.1
- Chrome 89.0.4389.82

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Make sure to have a room created and entered as an admin.

**[Steps to reproduce]:**
1. Click the "More" button from the menu bar.
2. Click the "Room Info and Settings" button.
3. Click the "Edit" button.
4. Click the "Invite only" radio button and open the link in PB.
5. Click the "Revoke" button (click “yes”).
6. In the PB window with the invite link refresh the page.
7. Observe the behavior.
           
**[Expected results]:**
- The room can not be entered anymore.

**[Actual results]:**
- The room can still be entered, the link is still valid.

**[Notes]:**
- Attached a screen recording of the issue below
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1C_qJYkkQ-mwo7R-78ooJ5oBIvrgWm9k5/view?usp=sharing).

**Comment by sagefreeman** [comment]
This seems to be working as expected for me. Your steps to reproduce should include the following:

5. Click the "Revoke" button (click “yes”).
6. Click the **Apply** button
6. In the PB window with the invite link refresh the page.
7. Observe the behavior: The room can not be entered

**Comment by Softvision-GeluHaiduc** [comment]
Yes, clicking the “Apply” button solidifies the revoke action and the room is no longer available using that invite link.
I will mark the issue accordingly and close it.
Thank you
