### ISSUE TITLE
[Mobile] Button on object is not work when avatar is far from the object

### ISSUE THREAD

**Issue by jasoncks** [mozilla/hubs#4075]
**Description**
In mobile, button on link/image object is not work when avatar is far from the object, but when the avatar get close to object/button, the buttons function properly.
This problem occur in mobile only.

**To Reproduce**
1. Create a new room
2. Turn on the freeze mode
3. Move the avatar in front of the object and click the button, the button function normally
4. Move the avatar apart from the object, the button not work

**Expected behavior**
- The button should work properly whenever user can click on the button

**Screenshots**
[Screenshot Far](https://drive.google.com/file/d/1zWlEpJP-J4T4VOqVPF3vWyEXve1Mz1t9/view?usp=sharing)
[Screenshot Near](https://drive.google.com/file/d/1kVPXJLA8CwJW-Sf3HhvVq_KYP3CRK9i6/view?usp=sharing)

**Hardware** 
 - Device: iPhone X, iPhone X Max
 - OS: iOS
 - Browser: Safari

 - Device: Google Pixel 4 XL
 - OS: Android
 - Browser: Chrome

**Additional context**
Not sure if is the same problem(#4048, #4052), since it does not mention about the distance

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-593)

**Comment by yakyouk** [comment]
[this pull request](https://github.com/mozilla/hubs/pull/4397) should fix this

**Comment by takahirox** [comment]
Hi @jasoncks, thanks for the bug report.

Do you mind if testing again to check if the problem is still reproducible?

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using the latest mobile releases of Firefox and Chrome on an Android 11 device.
Now, the buttons on objects are working even when the avatar is far from the object.
