### ISSUE TITLE
Hubs cloud is offline (as usual)

### ISSUE THREAD

**Issue by BonzoMartini** [mozilla/hubs#4097]
**Description**
I try to look at my Hubs or use Spoke. I have Mozilla Hubs Cloud. About 60-70% of the time I get the Hubs Cloud is offline message and/or I use it for 20 mins then I get Hubs Cloud is offline. We don't have  a lot of traffic either. I would like to use Hubs but with the AWS it just so unreliable....

Steps to reproduce the behaviour:
1. Pay for AWS Hosting
2. Host a Hub
3 Attempt to use it.

...what you expected to happen.

I would have assumed the paid service would be more reliable than the unpaid version and have more uptime than downtime....

**Screenshots**
here's a pic of my hubs

![Screenshot 2021-03-30 120407](https://user-images.githubusercontent.com/66266175/112978942-d9f3a780-914f-11eb-80f6-91722963fc56.png)

**Hardware** 
Desktop, Windows, Firefox

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-610)

**Comment by dezigns333** [comment]
AWS may very well be the problem.
I have another site hosted by them that was offline for 6 hours last night but the server said it was fine.

**Comment by netpro2k** [comment]
Also possible you may have "database pausing" enabled, this will take the database offline if it not has been used for some time, but comes with the tradeoff that it will take a few minutes to spin back up when you go to use it again. Keeping it always on will be more expensive, but also more responsive. See https://hubs.mozilla.com/docs/hubs-cloud-aws-costs.html#database-pausing---automatic

**Comment by BonzoMartini** [comment]
Hi @netpro2k  - I wondered if it was that, however, the pattern is I get onto my Hubs and Spoke, do a bit of editing in Spoke, then it goes offline when I'm using it.

**Comment by BonzoMartini** [comment]
Like for example today, I updated the stack yesterday. It was fine yesterday and this morning for 30 mins then the usual 'Hubs Cloud is offline '

**Comment by BonzoMartini** [comment]
We can look at it for 10 mins today then once again Hubs Cloud is offline

**Comment by johnshaughnessy** [comment]
We've had other people see "Hubs Cloud is currently offline" when they run out of memory on the server (https://github.com/mozilla/hubs/discussions/3792) or (apparently) when they are using a bunch of 4k textures (https://github.com/mozilla/hubs/discussions/3892). 

See also
https://github.com/mozilla/hubs/discussions/3071
https://github.com/mozilla/hubs/discussions/3429

Do any of these previous discussions have a solution that work for you? If not, can you please add more details about your configuration and usage that would help us diagnose the problem?

**Comment by BonzoMartini** [comment]
Well its pretty much only me on the server developing, apart from when we had one event last year and of course the server **_"Hubs Cloud is Offline"_**  in the middle of the event. So how does one check for memory usage on the server? 
I had it t3 medium but a few days ago, when I went to t3small because why pay for t3 medium when it's so totally unreliable. I will look at the 4k texture thing but I don't think I have many of those and they are all quite small. I have updated the stack, enabled the cloudflare etc.

**Comment by BonzoMartini** [comment]
Also now I have the cloudflare, I get this new class of error loading the project in Spoke - this is about a youtube video + oh I apologise, its not possible to copy text from hubs error messages, so here's a pic 
![image](https://user-images.githubusercontent.com/66266175/113913620-74995980-97d4-11eb-8e67-604c72db7bae.png)

**Comment by BonzoMartini** [comment]
So I've followed the steps above, no textures over 4k, made assets lower poly all green lights, when I build apart from yellow on the lights. Now my published scene will only load on Firefox on my develop pc, wont load in any other browser on that pc and won't load on any other computer or device. So no steps forward many steps back...now what? delete half the content and see if it loads??

**Comment by johnshaughnessy** [comment]
@BonzoMartini I'm sorry that you are running into so many issues trying to use Hubs Cloud. We want you to be successful with the software and clearly that isn't happening now. I understand that can be frustrating, but the increasing hostility of your messages here and on Discord are not helping to diagnose the problems.

In my earlier message, I linked four discussions where people encountered similar "Hubs Cloud is offline" issues. In those discussions, our developers asked followup questions and recommended remediation steps that may be applicable to your situation. I'd recommend trying the steps in those discussions, answering the questions about your configuration, and volunteering as much detail as you feel comfortable doing about your configuration and how you're using the software.

Regarding your most recent messages:
- [we recommend not using youtube for your video content](https://hubs.mozilla.com/docs/hubs-faq.html#can-i-play-video-content-in-hubs), 
- you can copy detailed error messages from the [devtools console](https://developer.mozilla.org/en-US/docs/Tools) of your browser, 
- we are aware of [several related issues related to video playback on certain devices](https://github.com/mozilla/hubs/issues?q=is%3Aissue+is%3Aopen+video+safari), so if you have details you can add to an existing issue to help someone debug it, that would help. In this case, it looks more like an issue with the cors proxy.
- regarding `delete half the content and see if it loads??`, I would recommend starting even more basic than this. Do empty scenes work? What about empty scenes with a few objects? When does the experience break down? What are the error messages?
- re `So how does one check for memory usage on the server?` There are a variety of ways. We don't provide a hubs-specific way to do this. [AWS has some tools to monitor EC2 health](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html), and there are [general health check mechanisms you can use with ubuntu](https://duckduckgo.com/?t=ffab&q=ubuntu+check+memory+usage&ia=web).

We are a small team with no dedicated support staff at this time (though it is [a role we are actively looking to hire](https://careers.mozilla.org/position/gh/2535502/)). As you encounter specific issues, you will unfortunately have to debug many of them yourself. I recognize that this is asking a lot on your part for consumer software -- we may not have reached the point of polish, stability and user-friendliness yet for you to use it as desired. If by solving a problem for you we improve the code or leave behind a helpful tip for the next person, we will get closer to that goal.
