### ISSUE TITLE
Latest MozillaReality/three.js commit breaks hubs-cloud version of Hubs

### ISSUE THREAD

**Issue by traviskaufman** [mozilla/hubs#4101]
**Description**
[The removal of setBasisTextureLoader](https://github.com/MozillaReality/three.js/commit/af08f523ef36c7fa30e0f32b6380a71cbca5a7ca#diff-f00aa7342f399843d87be1c6bb85d7fc671034bb5a1f5d37829ddcf3a2b2a99dL59) in a recent commit for MozillaReality/Three.js's GLTFLoader causes [code in gltf-model-plus](https://github.com/mozilla/hubs/blob/hubs-cloud/src/components/gltf-model-plus.js#L335) to error out, causing a `scene failed to load` UI when running Hubs cloud. 

I believe this has to do with the fact that `mozilla/hubs` has [a dependency](https://github.com/mozilla/hubs/blob/hubs-cloud/package.json#L120) on `MozillaReality/three.js#master` and thus running `npm i` post-merge of that PR breaks the app.

**To Reproduce**
1. Switch to the `hubs-cloud` branch of `hubs`
1. Run `npm install`
1. Run `npm start`
1. Spin up a hub, and make note of the hub ID
1. In Firefox, navigate to https://localhost:8080/hub.html?hub_id=<hub_id>, replacing `<hub_id>` with the spun up hub's ID

**Expected behavior**
The room entry modal should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/1185269/113062823-5b642d80-9182-11eb-994a-d746394a51aa.png)

**Hardware** 
 - Device: Desktop
 - OS: Mac
 - Browser: Firefox

**Comment by traviskaufman** [comment]
To clarify I believe the exact commit that breaks it is https://github.com/MozillaReality/three.js/commit/c1e252f0b4787b84da317352d12452cbc9607983

**Comment by netpro2k** [comment]
Yep. I am actually in the middle of testing and deploying these changes now. The associated Hubs client PR is here https://github.com/mozilla/hubs/pull/4047 it will be required to work with this new version of Three. How did you end up running into this? The package lock file should not have updated to point at these changes unless you also pulled in the Hubs client update.

**Comment by netpro2k** [comment]
Finished deploying this so master is up to date. the `hubs-cloud` branch won't get this until these changes are deployed to hubs cloud instances which could be awhile since we already have a pending release rolling out very soon, so it wont be until the next one after that.

**Comment by traviskaufman** [comment]
Got it; thank you!
