### ISSUE TITLE
Running Hubs In Amazon Cloud9 IDE

### ISSUE THREAD

**Issue by jeffrobernard** [mozilla/hubs#411]
Hello, 
I'm a little unclear as to how to run hubs in Cloud 9 IDE. It could be an issue with Cloud 9, still sorting it out. The project compiles with a 'successfully compiled' message after running $yarn start. It gives me a ip address and says application running on ports 8080. I would assume that would be enough to view the application in a browser and start making my edits in the IDE. When I command $ yarn build I get the following terminal message. What more is required to view the running application. Also, I people are using various IDEs, but the process in my mind should be the same to get it running. What am I not doing or doing incorrectly? 
ec2-user:~/environment/hubs (master) $ yarn start
yarn run v1.7.0
$ cross-env NODE_ENV=development webpack-dev-server
/home/ec2-user/environment/hubs/webpack.config.js:69
      compilation.plugin("html-webpack-plugin-before-html-processing", async data => {
                                                                       ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at WEBPACK_OPTIONS (/home/ec2-user/environment/hubs/node_modules/webpack-cli/bin/convert-argv.js:133:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ec2-user:~/environment/hubs (master) $

**Comment by brianpeiris** [comment]
Hey Jeff. I was able to get Hubs running in AWS Cloud9 with the following steps:
- Create a new environment. You'll probably need an m3.medium instance at least, since yarn can consume a lot of memory at times.
- Upgrade nodejs: `$ nvm install 9`
- [Install yarn](https://yarnpkg.com/en/docs/install#centos-stable)
- Run `$ git clone https://github.com/mozilla/hubs`
- Setup Hubs:
  - `$ cd hubs`
  - `$ yarn install`
- Configure Hubs for Cloud9 by editing `webpack.config.js`
  - Set `https` to `false` under `devServer`
  - Add `disableHostCheck: true` under `devServer`
- Run `$ yarn start`
- Preview the running app by clicking on the "Preview" menu item and then "Preview Running Application"

Note that the room creation dialog on the Hubs landing page will not work because it attempts to communicate with our servers, which are not accessible from the AWS domain. Instead, you have to access a Hubs room directly:

`https://ENVIRONMENT_ID.vfs.cloud9.REGION_ID.amazonaws.com/hub.html?allow_multi&room=test-cloud9`

Also keep in mind that your Cloud9 instance will be using our WebRTC server for voice and data transfer by default, unless you setup and configure your own.

**Comment by jeffrobernard** [comment]
Brian,
Thank you so much for the thorough explanation! I will test it out and report back. This hubs project is amazing.

**Comment by gfodor** [comment]
I've converted this issue into a wiki page, thanks for digging @brianpeiris !

https://github.com/mozilla/hubs/wiki/Running-Hubs-on-Cloud-9

**Comment by hulnglei** [comment]
hello， I test install in aliyun.  I follow the guide, but fall in the step " yarn start" @brianpeiris 
[https://scontent-sin2-2.xx.fbcdn.net/v/t1.0-9/46789735_2132905286760748_3810752932157063168_n.jpg?_nc_cat=106&_nc_ht=scontent-sin2-2.xx&oh=37169191ececcd7dfad1f771554be5fc&oe=5C761409](url)
[https://scontent-sin2-2.xx.fbcdn.net/v/t1.0-9/46654501_2132905470094063_4743766008060182528_n.jpg?_nc_cat=103&_nc_ht=scontent-sin2-2.xx&oh=8507abea4bebb7da80152de02080d2fd&oe=5CAE2419](url)

**Comment by hulnglei** [comment]
new error report when run "yarn install" in aliyun
 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅
   three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
狻 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
猗 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅?three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅
   three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
狻 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
猗 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅?three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅
   three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
狻 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
猗 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅?three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅
   three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
狻 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
猗 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅?three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅
   three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
狻 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
猗 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅?three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅
   three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
狻 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
猗 three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db7
鉅?three@github:mozillareality/three.js#8b1886c384371c3e6305b757d1db
error Couldn't find match for "8b1886c384371c3e6305b757d1db7577c5201a9b" in "refs/heads/GLTFExporter/gltfExtensions,refs/heads/GLTFExporter/parseChunks,refs/heads/GLTFLoader/MOZ_alt_materials,refs/heads/GLTFLoader/lazy,refs/heads/GLTFLoader/texture-spec,refs/heads/bug/box-helper-cloning,refs/heads/dev,refs/heads/feature/ecs,refs/heads/gh-pages,refs/heads/hubs-editor/dev,refs/heads/hubs-editor/editor-controls,refs/heads/hubs-editor/gltf-additions,refs/heads/hubs/dev,refs/heads/hubs/dev-v2,refs/heads/master,refs/heads/spoke/dev-ecs,refs/tags/r1,refs/tags/r10,refs/tags/r11,refs/tags/r12,refs/tags/r13,refs/tags/r14,refs/tags/r15,refs/tags/r16,refs/tags/r17,refs/tags/r18,refs/tags/r2,refs/tags/r25,refs/tags/r28,refs/tags/r29,refs/tags/r3,refs/tags/r30,refs/tags/r31,refs/tags/r32,refs/tags/r33,refs/tags/r34,refs/tags/r35,refs/tags/r36,refs/tags/r37,refs/tags/r38,refs/tags/r39,refs/tags/r4,refs/tags/r40,refs/tags/r41/ROME,refs/tags/r42,refs/tags/r43,refs/tags/r44,refs/tags/r45,refs/tags/r46,refs/tags/r47,refs/tags/r48,refs/tags/r49,refs/tags/r5,refs/tags/r50,refs/tags/r51,refs/tags/r52,refs/tags/r53,refs/tags/r54,refs/tags/r55,refs/tags/r56,refs/tags/r57,refs/tags/r58,refs/tags/r59,refs/tags/r6,refs/tags/r60,refs/tags/r61,refs/tags/r62,refs/tags/r63,refs/tags/r64,refs/tags/r65,refs/tags/r66,refs/tags/r67,refs/tags/r68,refs/tags/r69,refs/tags/r7,refs/tags/r70,refs/tags/r71,refs/tags/r72,refs/tags/r73,refs/tags/r74,refs/tags/r75,refs/tags/r76,refs/tags/r77,refs/tags/r78,refs/tags/r79,refs/tags/r8,refs/tags/r80,refs/tags/r81,refs/tags/r82,refs/tags/r83,refs/tags/r84,refs/tags/r85,refs/tags/r86,refs/tags/r87,refs/tags/r88,refs/tags/r89,refs/tags/r9,refs/tags/r90,refs/tags/r91,refs/tags/r92,refs/tags/r93" for "https://github.com/mozillareality/three.js.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
