### ISSUE TITLE
Spectate button not visible when room is full

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#4116]
With the current hubs (screenshot from hubs.mozilla.com today), opening a full room just shows an entry panel with no options and no explanation. Is this intended?

![image](https://user-images.githubusercontent.com/10034859/113420954-da7a8100-938f-11eb-8396-7b18408f1242.png)

_Originally posted by @wmurphyrd in https://github.com/mozilla/hubs/discussions/4110_

I believe the issue is that `entryDisallowed` takes room occupancy / capacity into account. Spectate should be available even when the room is full.

https://github.com/mozilla/hubs/blob/41373e0078ce55eb09b6034fe2c621871c88ce96/src/react-components/ui-root.js#L806

**Comment by wmurphyrd** [comment]
@johnshaughnessy in the Immers Space fork we just dropped the `entryDisallowed` and made `showSpectate` only dependent on on `waitingOnAudio` - is that right? If there's nothing else that the spectate button should depend on, then I'll happily send a PR

https://github.com/immers-space/hubs/pull/33/files#diff-258d97e06f65f1694919ac9f757081b8fe2f50593464c4d166faf5d0cfeadfc5L821-R823

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible. The "Spectate" button is now displayed when the room is full.

Tested on Windows 10 using Firefox 89 and Chrome, and also on Oculus Quest using the Oculus Browser.
