### ISSUE TITLE
Hubs will become unresponsive in Oculus Browser after selecting a 3D model to place it on a created room

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#4119]
**Description**

The following javascript error occurs: "Uncaught DOMException: Failed to execute 'getPose' on 'XRFrame': XRSpace and XRFrame sessions do not match."
The code might be calling getPose with a space from a previous session.

**To Reproduce**
1. Open Hubs in Oculus Browser on the Quest
1. Create and enter a room
1. Press the Create button
1. Select a 3D model

**Expected behavior**
Spawning a 3D model should not break the VR experience.

**Hardware** 
 - Device: Quest
 - Browser: Oculus Browser

**Comment by cstfan** [comment]
Hi Brian,
I also have this problem, so I changed the permissions of my rooms to block its access but now I have this problem:  VR - Impossible to grab pen #4141
Best regards,
Stephan

**Comment by DougReeder** [comment]
I can confirm this happens, with those steps, in the Quest at the meetup on April 22.

**Comment by brianpeiris** [comment]
This might have been fixed with #4206. We'll need to confirm.

**Comment by brianpeiris** [comment]
Confirmed this is no longer an issue.
