### ISSUE TITLE
VR + WebGL2 not working on Oculus Quest 1 and 2

### ISSUE THREAD

**Issue by camelgod** [mozilla/hubs#4134]
**Description**
Clicking the "Enter VR" green button on the bottom will result in a WebXR session with black screen, making the VR experience unavailable. It works when first entering the room (hubs wants to start xr session, click allow), but using the button will not work.

The Invite button inside the initial WebXR session is also completely broken and does nothing.
Clicking the Create button will show a prompt "Continue" but will break the website by going out and then back into WebXR session but this time with a black screen.

**To Reproduce**
1. Go to hubs.mozilla.com on Oculus Browser
2. Enter the room, exit webxr session, click "Enter VR" button
3. See black screen

**Expected behavior**
Clicking "Enter VR" should start a WebXR session without pitch black darkness.

**Hardware** 
 - Device: Oculus Quest 2
 - Browser: Oculus Browser.

**Additional context**
Seems to have started after the UI update.
Avatar Head rotation and movement still works fine if you look at the avatar through another browser.

Here is the log from Chrome debugging / OQBrowser:
![image](https://user-images.githubusercontent.com/28685654/114212177-d0451d80-9961-11eb-8c8b-e9940da9b08d.png)

Here is another log from Chrome/OQBrowser on my hubscloud
![image](https://user-images.githubusercontent.com/28685654/114215218-a0981480-9965-11eb-8049-8936b72dc8e4.png)

**Comment by camelgod** [comment]
I was able to reproduce the same issue on hubs.mozilla.com using Firefox Reality. Seems like it is hitting the physics system?

Mozilla Nightly (81.0a1) Quest

![image](https://user-images.githubusercontent.com/28685654/114207189-65451800-995c-11eb-9bff-9124f2302f04.png)

**Comment by bekojang** [comment]
Running into the same issue. 

![Screen Shot 2021-04-12 at 1 26 37 PM](https://user-images.githubusercontent.com/20364018/114457496-f4d40c00-9b92-11eb-8d34-7a5a48940b2c.png)

**Comment by camelgod** [comment]
Update: I managed to get it working seting webgl2: false in hub.html

**Comment by camelgod** [comment]
So my hypothesis is that previously there was some kind of bug that made the client fall back to WebGL1. This is not the case anymore after the UI update, and it now loads WebGL2 successfully, but there is some kind of bug with Hubs + WebGL2 and Oculus Browser.

**Comment by dvdsmthdvd** [comment]
I'm still having this issue. Has anyone found a solution?
