### ISSUE TITLE
Controller disappears on the Go if you don't interact with things enough

### ISSUE THREAD

**Issue by larsbergstrom** [mozilla/hubs#414]
If you're sitting around chatting in Hubs on the Go without playing with things/moving, eventually the controller will turn off and you'll be stuck in gaze mode. If you go to turn the controller back on, you have to hold the back or home buttons, which will then kick you out of immersive mode and back into the 2D browser experience. From there, there's no way to get back into VR mode without refreshing the page and disappearing/reappearing to others in the room.

**Comment by cvan** [comment]
I've noticed this but haven't investigated if it's an Oculus Go (Bluetooth), Oculus Browser, A-Frame, or `super-hands` issue. Will need to do some investigating / remote debugging.

**Comment by misslivirose** [comment]
I tried to reproduce this today by taking the batteries out of the controller and putting them back in. I was able to reproduce it once, though the battery was low on the controller and didn't end up working at all to get to the step where I could reload the page. After I replaced the battery, I went through the repro steps again and never got forced into gaze mode, so this wasn't reproduceable. I'm going to close this but if it is observed again, please let me know and we can re-open.
