### ISSUE TITLE
Hubs Discord bot is down

### ISSUE THREAD

**Issue by JT-os** [mozilla/hubs#4143]
**Description**
Hubs Discord bot has been offline for several days.

**To Reproduce**
Look @ the Hubs bot in Discord user list and it is offline.

**Expected behavior**
Hoping for bot to be back online and responsive to commands.

**Screenshots**
Hubs Discord server shows current status.

**Hardware** 
 - Browser: all

**Additional context**
Projects my groups are working on are hoping to use the bot as part of hour moderation setup with the Discord bridge.

**Comment by johnshaughnessy** [comment]
The bot was causing db usage issues on our side. We shut it down last week. It's back up again now.
