### ISSUE TITLE
Rotate camera

### ISSUE THREAD

**Issue by CubeOfCheese** [mozilla/hubs#4145]
When I try to take a picture of something I open the camera, then remember I can't turn the camera so I close the camera, walk in front of the subject of the picture, turn around, open the camera, then walk back around the camera to finally take the picture.

**Describe the solution you'd like**
I want to be able to rotate objects with a key or mouse movement or something.

**Describe alternatives you've considered**
A 180 degree flip button for the camera would help a lot but doesn't solve the more general problem of rotating objects. I would like to rotate other objects as well but the camera was the most annoying.

**Additional context**
For clarification, I want to be able to rotate an object without rotating myself.

**Comment by netpro2k** [comment]
Hold spacebar or press Tab to show object menus. From there you can click and drag on the rotate button to rotate any object. See https://hubs.mozilla.com/docs/hubs-controls.html for controls on other platforms.
