### ISSUE TITLE
Fly mode cannot be disabled 

### ISSUE THREAD

**Issue by dezigns333** [mozilla/hubs#4154]
**Description**
After disabling fly mode /fly Hubs responds with 'Fly mode disabled.0 seconds ago'
After moving the mouse up and the control keys forward flying is still capable.

**To Reproduce**

Disable fly /fly
Try flying

**Expected behavior**
No flying

**Screenshots**

**Hardware** 
Windows 10, Chrome

**Comment by netpro2k** [comment]
This likely means the scene you are using does not have a navmesh, so we have no choice but to let you fly. If the scene is created in Spoke, make sure it has a floorplan. If it's made in blender make sure to add the `nav-mesh` component to a mesh node.

**Comment by dezigns333** [comment]
Great thanks.

**Comment by dezigns333** [comment]
solved
