### ISSUE TITLE
Can't link to Hubs rooms using named target

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#4173]
If you have a link that looks like this:

```
<a href="https://hubs.mozilla.com/uipqcCJ/buttery-energetic-shindig" target="sometarget">
    Click to open in a new browser window
</a>
```
The Hubs room load can fail with the following error message in console:

`Uncaught DOMException: Blocked a frame with origin "https://hubs.mozilla.com" from accessing a cross-origin frame.
`

The offender [is some code](https://github.com/mozilla/hubs/blob/master/src/hub.js#L235) that's part of the OAuth project and probably temporary:

```
// OAuth popup handler
// TODO: Replace with a new oauth callback route that has this postMessage script.
if (window.opener && window.opener.doingTwitterOAuth) {
  window.opener.postMessage("oauth-successful");
  isOAuthModal = true;
}
```

Basically you are not supposed to reference `window.opener` unless you have CORS permission from the parent server.

Kind of obscure, but I happen to link to Hubs in exactly this way. [Here is an example page](https://alpha.avncloud.com/dev/cross-window-hubs-bug.html) with the two types of links, the first will work and the second will not.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-627)

**Comment by oneWaveAdrian** [comment]
Experiencing the same issue. Only happens when linking with `target="_blank"` otherwise works fine. I will use intermediate solution as suggested by poster

**Comment by matthewbcool** [comment]
I wasn't able to repro using `<a href={hubsroomurl} target="_blank">`

**Comment by brianpeiris** [comment]
Just wanted to note something I realized about this bug -- when linking to Hubs rooms, users may not always have control of the particular HTML used in the link tag, for example when using a third-party site or CMS, so the `noopener` workaround may not always be usable. That bumps the priority of this issue, in my mind.
