### ISSUE TITLE
Compressed textures broken on mobile browser

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#4179]
Models using extension _KHR_texture_basisu_ or legacy _MOZ_HUBS_texture_basis_ do not display properly on Chrome Chrome 90.0.4430.82 on Android:

<img width="460" alt="Screenshot 2021-04-22 at 12 49 44" src="https://user-images.githubusercontent.com/303516/115709555-42a5fc80-a369-11eb-963f-de88ba4d23d0.png">

Console warning **WebGL: INVALID_ENUM: compressedTexImage2D: invalid format** appears to be relevant and tracing through function `patchThreeAllocations` I can see that `null` is being passed as the _internalformat_ parameter. Presumably the basisu translation is failing silently somehow.

Here is [a sample scene](https://hubs.mozilla.com/y3sqGsB/fantastic-this-spot) with two compressed objects. The example models were taken from Discord discussions and work fine on desktop browsers: [compressed-models.zip](https://github.com/mozilla/hubs/files/6357985/compressed-models.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-629)

**Comment by rawnsley** [comment]
Fixed by https://github.com/MozillaReality/three.js/pull/58

**Comment by takahirox** [comment]
Hi, thanks for the report.

> Here is a sample scene with two compressed objects.

I confirmed that they are rendered correctly on my Android Chrome. The problem seems to have been resolved by Three.js upgrade. Let's close this issue, thanks!
