### ISSUE TITLE
Fail to load image/video on custom instance

### ISSUE THREAD

**Issue by jasoncks** [mozilla/hubs#4204]
**Description**
Suddenly , custom HC instance cannot load image/video in the rooms.
No setting is changed on AWS or in the admin panel of HC.

**To Reproduce**
1. Create a soke project with image and video on custom HC instance
2. Publish the  project and create room
3. Enter the room

**Expected behavior**
Image and video should be shown properly.

**Screenshots**
[Screenshot](https://drive.google.com/file/d/1ej8vOQfQ7l-elPkofF20Jlg5C2G8i1f2/view?usp=sharing)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Additional context**
Problem only occurred when the URL is extended with the proxy link.
Following error message are shown in console (Error code: undefined; Response: undefined).
If we enter the image link to browser directly, image can be shown properly.
That means this problem is not caused because of dead link of image/video.

Failed: 
https://pai-dev-livexr-cors-proxy.dev-hubs-premiumartsinc.com/https://images.wallpapersden.com/image/download/windows-10-hero-logo_a2hsammUmZqaraWkpJRmZWdprWxrbQ.jpg

Success: 
https://images.wallpapersden.com/image/download/windows-10-hero-logo_a2hsammUmZqaraWkpJRmZWdprWxrbQ.jpg

**Comment by brianpeiris** [comment]
This should be fixed now. Thanks for the report.
