### ISSUE TITLE
Perf: Don't use aframe Line component in cursor-controller

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#421]
We call `setAttribute` every frame in the `cursor-controller` in order to update the start and end of the aframe `line` component. We will see a performance benefit by not using the aframe `line` component and manipulating the underlying threejs line directly.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/757

**Comment by myeshiamorgan** [comment]
u all will get in trouble for identification theft an fraud also privacy
violations theives..

M.Morgan
