### ISSUE TITLE
How to install Mozilla Hubs on localhost ?

### ISSUE THREAD

**Issue by Seikida** [mozilla/hubs#4263]
**Description**
Hello and thank you for you great works.

**To Reproduce**
Steps to reproduce the behavior: (just follow the "Quick Start" section)

1. Run: git clone https://github.com/mozilla/hubs.git
2. Run: cd hubs
3. Run: npm ci
4. Run: npm run dev
5. Go on: https://hubs.local:8080/webpack-dev-server/
6. Go on: https://localhost:8080/

**Screenvideos**

→ I uploaded video on Youtube:

[![Mozilla Hubs - Installation](https://img.youtube.com/vi/V8-H98NIIkk/0.jpg)](https://www.youtube.com/watch?v=V8-H98NIIkk)

URL: https://www.youtube.com/watch?v=V8-H98NIIkk

**Screenshots**

URL 1 :https://hubs.local:8080/webpack-dev-server/

![alt text](https://firebasestorage.googleapis.com/v0/b/idols-community.appspot.com/o/tmp%2FScreen%20Shot%202021-05-16%20at%2014.03.42.png?alt=media&token=7e365815-a90f-4f6f-a9a9-f37ef3f9a1a7)

URL 2: https://localhost:8080/

![alt text](https://firebasestorage.googleapis.com/v0/b/idols-community.appspot.com/o/tmp%2FScreen%20Shot%202021-05-16%20at%2014.04.21.png?alt=media&token=bc7398d9-8b22-414b-9a31-7417c9bb3503)

**Hardware** 
 - Device: Desktop
 - OS: Mac OS
 - Browser: Chrome
 - Node version: 12.18.0

Thank you so much

**Comment by rawnsley** [comment]
You can either enable [the bypass flag](https://security.stackexchange.com/questions/241387/chrome-allow-insecure-localhost) or you can use the temporary [thisisunsafe](https://medium.com/@idomo/chrome-bypassing-ssl-certificate-check-2-f8eb6c2be68a) cheat code.

**Comment by Seikida** [comment]
Hello @rawnsley and thank you for your fast reply.
It's works now. Thank you so much.

If you got the same error as me, please follow:

1. Go to: chrome://flags/#allow-insecure-localhost
2. Enabled: "Allow invalid certificates for resources loaded from localhost."

![alt text](https://firebasestorage.googleapis.com/v0/b/idols-community.appspot.com/o/tmp%2FScreen%20Shot%202021-05-16%20at%2017.43.46.png?alt=media&token=4a744d3b-2f36-4b4c-8497-c2f82a512704)

3. Restart chrome
4. Go to: https://localhost:8080/

![alt text](https://firebasestorage.googleapis.com/v0/b/idols-community.appspot.com/o/tmp%2FScreen%20Shot%202021-05-16%20at%2017.49.22.png?alt=media&token=97cc7576-8a1a-4bb4-9be0-a8b19ee1b751)
