### ISSUE TITLE
"Scene Editor" does not appear in non-English languages on Hubs Cloud

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#4268]
**Description**
When users set their preferred locale to something other than English, the link to the scene editor does not appear on the home page. 

I suspect the same might be true for some of the other translations that are not part of the default translation files:

https://github.com/mozilla/hubs/blob/5f204a029b1f451031cc18a9eb9f0f85a1b5e8f8/src/schema.toml#L3-L13

**To Reproduce**
1. Go to Hubs Cloud home page
2. Enable scene editor in admin panel
3. Enter room
4. Go to preferences
5. Select non-English language preference
6. Go to Hubs Cloud home page
7. There is no link to the Scene Editor

**Expected behavior**
A link to Spoke with a translated version of "Scene Editor" should appear on the home page. If there is no available translation in the target language, then the English words "Scene Editor" should appear instead. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4072106/118751086-8f201300-b815-11eb-91c9-67d0d39bfdd3.png)

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**
```js
./src/schema.toml:13:translations.en."editor-name" = { category = "translations", type = "string", internal = "true" }
./src/react-components/room/SceneUrlModalContainer.js:30:      editorName={configs.translation("editor-name")}
./src/react-components/layout/PageContainer.js:17:      editorName={configs.translation("editor-name")}
./src/react-components/scene-ui.js:250:                    values={{ editorName: configs.translation("editor-name") }}
./src/react-components/scene-ui.js:265:                      values={{ editorName: configs.translation("editor-name") }}
./src/react-components/media-browser.js:428:                    {configs.translation("editor-name")}
./src/react-components/media-browser.js:525:                      values={{ editorName: configs.translation("editor-name") }}
./src/utils/i18n.js:7:  "editor-name": "Scene Editor",
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBSOLD-651)

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. But i dont know how to fix it

**Comment by ArneKossmann** [comment]
Hi, I run into the same issue with the german translation.
Somehow `configs.translation("editor-name")` returns a empty string for Non-Englisch languages.
But `configs.translation()` also search the current translation.
You can fix this by adding a `"editor-name"` entry to the translation files.
e.g. `./assets/locales/de.json`
`"editor-name": "Szenen Editor"`
