### ISSUE TITLE
Transparant Walls

### ISSUE THREAD

**Issue by kurtmalonnek** [mozilla/hubs#4269]
**Description**
this scene did not have any problem, suddenly some shaders look transparent, check other scenes that have some elements of this scene and now they have the same problem, before they were ok

https://hubs.mozilla.com/tDYsMSP/playful-famous-territory

**To Reproduce**
I did not do anything special

**Expected behavior**
it should look smooth as it was before

**Screenshots**
![image](https://user-images.githubusercontent.com/30682511/118770928-e347e900-b84f-11eb-89b1-3ed6f9a78986.png)

**Hardware** 
 - Device: Notebook hp omen gp rtx 2070 i7 16gb ram ssd 512
 - OS: win
 - Browser: firefox and chrome

**Comment by matthewbcool** [comment]
Did a quick test in chrome, was not able to repro.
https://i.gyazo.com/37abab3c4a87ec1b4e3a812229b821b9.mp4

**Comment by kurtmalonnek** [comment]
Hello, someone from the mozilla hubs team helped me to find the problem, when i'm exporting from maya to blender the transparency mode is changed, it leaves it in "blend alpha" and then I change it by hand to "opaque" in all the shaders
