### ISSUE TITLE
Hub Compilation Errors 

### ISSUE THREAD

**Issue by jeffrobernard** [mozilla/hubs#427]
Hi @mquander @brianpeiris @gfodor 
Really close to getting hubs running. We need some advice to solve the following issue. 
 During the compilation, we get following errors:

ret_1 | == Compilation error in file lib/ret_web/controllers/page_controller.ex ==
ret_1 | ** (File.Error) could not read file "/ret/_build/prod/lib/ret/priv/static/hub.html": no such file or directory
ret_1 | (elixir) lib/file.ex:272: File.read!/1
ret_1 | lib/ret_web/controllers/page_controller.ex:8: (module)
ret_1 | (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

ret_1 | == Compilation error in file lib/ret_web/controllers/page_controller.ex ==
ret_1 | ** (File.Error) could not read file "/ret/_build/prod/lib/ret/priv/static/smoke-hub.html": no such file or directory
ret_1 | (elixir) lib/file.ex:272: File.read!/1
ret_1 | lib/ret_web/controllers/page_controller.ex:14: (module)
ret_1 | (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

The reason is that static/hub.html and static/smoke-hub.html are missing in the repository. https://github.com/mozilla/reticulum/blob/master/scripts/build.sh#L42 which isn't included in the "compose up" process indicates they might be able to be created with simple empty files. I also tried to copy hub.html from compiled hubs. Both methods were not successful. 

Here are the steps to reproduce the issue:
1. git clone https://github.com/mozilla/reticulum.git
2. add MIX environment variable to docker-compose.yaml
    ret:
        build: .
        environment:
            - MIX_ENV=prod
3. build & run:
docker-compose up

What might be the way to solve this issue?

**Comment by gfodor** [comment]
Hopefully this was resolved, closing.
