### ISSUE TITLE
Audio Source Components Do Not Move With Objects

### ISSUE THREAD

**Issue by Exairnous** [mozilla/hubs#4276]
**Description**
When adding a GLB with an audio source component the component stays at it's initial coordinates regardless of where the object is moved to in a scene/room.

**To Reproduce**
1. Export a GLB with mic + audio source component and speaker + audio target component. ([Mic_Speaker_test.zip](https://github.com/mozilla/hubs/files/6518138/Mic_Speaker_test.zip))
  Note: make sure to remove Mute self in the audio source and enable debug in both the audio source and audio target (done in test file).
2. Add it to a Spoke scene or drop it into a Hubs room.
3. Move it somewhere away from the world origin.
4. Go to the mic in the room and try to talk (you won't be amplified)
5. Go to the initial location of the audio source in the GLB file (0.9811 m on the blender Y axis from world origin) and try to talk (you will be amplified)

**Expected behavior**
To be amplified from the new position in the scene/room that the audio source has been moved to.

**Hardware**
 - Device: Laptop
 - OS: Linux
 - Browser: Chromium

**Additional context**
The audio target component appears to work correctly and move with the object.

**Comment by netpro2k** [comment]
Nice find, looks like we are incorrectly assuming zone audio sources are in world space. Should be an easy fix

**Comment by Exairnous** [comment]
Thanks :)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox 89.0 and Chrome 90.0.4430.212 on Windows 10 using the Mic_Speaker_test object.
Now, when the user goes up to the microphone the voice is amplified regardless of where the object is put.

**Comment by Exairnous** [comment]
Thanks @Softvision-GeluHaiduc.  I tested in Chromium 91.0.4472.77 and Firefox 89.0 in Linux and they work for me as well.
