### ISSUE TITLE
Line breaks not visible in room description.

### ISSUE THREAD

**Issue by matthewbcool** [mozilla/hubs#4284]
**Description**
Line breaks not respected in the RoomSideBar room description.

**To Reproduce**
1. Edit room description and insert breaks
2. apply the changes

**Expected behavior**
I think the line breaks would be nice. Is there a reason for not respecting string line breaks in the room description? I had trouble figuring out why it is this way but it can be fixed with a single line of CSS.

**Screenshots**
Current:
![nobreaks](https://user-images.githubusercontent.com/4493657/119246751-ef29f880-bb38-11eb-8e03-540896aa4b01.png)
Expected:
![breaks](https://user-images.githubusercontent.com/4493657/119246756-f94bf700-bb38-11eb-8f38-3a8c6066766c.png)

**Hardware** 
 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue and it's no longer reproducible. Tested this on Win 10 using the latest releases for Firefox and Chrome browsers.
While testing I also encountered another issue that I logged here #4645
