### ISSUE TITLE
Can not login into Hubs Cloud Personal

### ISSUE THREAD

**Issue by romadon** [mozilla/hubs#4289]
**Description**
When I write the email address to login into Hubs Cloud Personal, the email never arrives and browser console show me a websocket error:

phoenix-utils.js:149 Socket error, changed endpoint to wss://gallant-werewolf.altalandia.com/socket/websocket
phoenix.js:844 WebSocket connection to 'wss://gallant-werewolf.altalandia.com/socket/websocket?vsn=2.0.0' failed: 
connect @ phoenix.js:844
(anonymous) @ phoenix.js:794
teardown @ phoenix.js:925
(anonymous) @ phoenix.js:794
(anonymous) @ phoenix.js:1434

**To Reproduce**
1. Go to Admin page -> Scenes
2. Try to delete one or more scenes
3. HUBS show the Screenshot and jumps to login page, after that I can not load /admin page
4. Logout from HUBS
5. Try to login writing email address and clicking Next
6. Open console window and see the error
7. Email magic-link never arrives

**Expected behavior**
I want to do login

**Screenshots**
![image](https://user-images.githubusercontent.com/5645917/119514726-8c717080-bd75-11eb-8576-c32d160adf9f.png)

**Hardware** 
 - Device: Desktop (LENOVO Thinkpad, i7-6700HQ , 16GB RAM)
 - OS: Windows 10
 - Browser: Chrome 90.0.4430.212 (64 bits), Firefox 88.0.1 (64-bit), Edge 90.0.818.66 (64 bits)

**Additional context**

**Comment by romadon** [comment]
Database restored, deleted some parameters from "Parameter Store" (AWS) with bad values, restarted the machine and working again, the only thing, JSon error when I try from Chrome, but works from Firefox and Edge.

Thanks to @chriscalef :-)

**Comment by heaversm** [comment]
I am having the same issue in Hubs Cloud - how were you able to restore? Can we reopen this?

**Comment by nupur711** [comment]
How to resolve this issue? Any idea
