### ISSUE TITLE
Firefox doesn't correctly gather WebRTC candidates when using TURN

### ISSUE THREAD

**Issue by keianhzo** [mozilla/hubs#4296]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1713161

**Description**
Firefox doesn't correctly gather WebRTC candidates when using TURN so the WebRTC connection cannot be established  and the comms are broken.

**To Reproduce**
- Open any HMC room with query params: `?force_turn=true` That forces using a TURN
- Open about:webrtc (or in Hubs. Preferences->Misc->RTC Panel))
- See that the candidates cannot be gathered (see attached about:webrtc report)

Alternatively you can also use https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Expected behavior**
Candidates should be correctly gathered when using TURN

**Additional context**
It doesn't happen in FF Nightly or Chrome.

**Comment by vincentfretin** [comment]
If you didn't saw it, I wrote about the same issue in #4187

**Comment by keianhzo** [comment]
This has already been fixed in latest FF stable, closing.
https://bugzilla.mozilla.org/show_bug.cgi?id=1713161

**Comment by keianhzo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1713161
