### ISSUE TITLE
e is not iterable

### ISSUE THREAD

**Issue by Andrei-Mamal** [mozilla/hubs#4299]
Hi everyone. 

When I try to post a scene from spoke, it tells me that "e is not iterable."
Can someone explain to me what this error is related to? How can I solve it? My scene contains only a 360 jpeg. 

Thanks,
Andrei

**Comment by Exairnous** [comment]
I believe it's because you have no models/GLBs in your scene.  See also https://github.com/mozilla/Spoke/issues/1137

**Comment by Andrei-Mamal** [comment]
Issue solved. 

Thank you, Exairnous.
