### ISSUE TITLE
Thousands of emojis freezes your browser 🧊🧊🧊

### ISSUE THREAD

**Issue by guillecro** [mozilla/hubs#4346]
**Description**
Sending thousands and thousand of emoji freezes Mozilla Hubs client  

**To Reproduce**
1. Go with a friend to any scene (Or join the same lobby with the same 
2. One comments thousands of emojis. Send for example 120K 🍆 emojis. Try sending 300K 🍆
3. Everyone should notice that everything freezes

**Expected behavior**
Shall we add a character limit to the chat? 😅

**Screenshots**
![image](https://user-images.githubusercontent.com/8771166/122840837-41de0800-d2d1-11eb-90f4-288e3f0867e2.png)

**Hardware** 
 - Device: Desktop
 - OS: [e.g. Windows 10
 - Browser: Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Additional context**
We were with [@thatrainbowbear](https://github.com/thatrainbowbear) testing stuff and he came up with the amazing idea of sending thousands and thoudsands of emojis. And yeah, we found out there is no character limits and he was able to freeze my client. Even while being spectator. Maybe for now a character limit in the text input might be a nice fix :)

NOTE: 
You can use this to repeat an emoji how many thousands times you want!
[https://www.browserling.com/tools/text-repeat](https://www.browserling.com/tools/text-repeat)

**Comment by robinkwilson** [comment]
Fix via https://github.com/mozilla/hubs/pull/4354

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue and it's no longer reproducible. Tested this on Windows 10 using the latest releases of Firefox and Chrome browsers.
