### ISSUE TITLE
[iOS] The Email Sent prompt is not fully visible

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4368]
**[Affected Versions]:**
- Chrome 87
- Safari 14

**[Affected Platforms]:**
- Iphone SE 2

**[Prerequisites]:**
- Hubs Cloud services are set up.
- Have a room opened.
- You are not logged into Hubs.

**[Steps to reproduce]:**
1. Tap on the "Sign In" button from the "More" menu.
2. Insert a valid email and tap "Next".
3. Observe the Email Sent prompt

**[Expected results]:**
- The prompt is fully visible.

**[Actual results]:**
- The bottom side of the prompt is cut off.

**[Notes]:**
- The issue depends on the set language and browser used.
- The issue is also reproducible on "https://hubs.mozilla.com/" website.
- Attached is a screenshot of the issue: 
![EmailSent](https://user-images.githubusercontent.com/40061643/123278963-172dc280-d510-11eb-86f3-5da3ec9ae31f.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-91)

**Comment by takahirox** [comment]
I couldn't reproduce the problem on my iPhoneX iOS15 + Safari. Do you mind if testing again on iOS15?

If you can still reproduce, the problem might be model (or screens size) or language specific?

**Comment by Softvision-RemusDranca** [comment]
@takahirox  I was not able to reproduce this issue on Iphone SE2 (iOS 15) with Safari 15 and Chrome94.
Considering this I will close this issue as verified fixed.
