### ISSUE TITLE
Unable to access ANY hubs rooms

### ISSUE THREAD

**Issue by carlagnyu** [mozilla/hubs#4369]
I am based in Brooklyn, NY and I cannot access any hubs spaces right now. 

I go to this page, for example, https://hubs.mozilla.com/VCBH2rP/recollecting-futures (I was just there last week for several hours) and I get:
"Unable to connect to this room, please try again later. You can try connecting via TCP, which may work better on some networks.  You can also create a new room.  Refresh Page"

When I refresh page, I get "The scene failed to load"

I expect to be able to enter the room. There is an event going on there right now and other people are inside but I can't get in. 

**Hardware** 
 - Desktop, laptop, smartphone
 - Windows + iPhone
 - Chrome, Firefox

![HubsIssue](https://user-images.githubusercontent.com/55764072/123314673-de362380-d4f8-11eb-9908-55b65c149d98.PNG)

**Comment by brianpeiris** [comment]
We just released a fix that should resolve this. Please try now and let us know if you still have issues.

**Comment by brianpeiris** [comment]
I believe we've resolved this issue, but feel free to comment or reopen if you're still encountering it.
