### ISSUE TITLE
[Safari] The window freezes when uploading video, GIF and audio files

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4405]
**[Affected Versions]:**
- Safari 14.0.2

**[Affected Platforms]:**
- macOS Catalina 10.15.7
- IphoneSE

**[Prerequisites]:**
- Have a room opened on "https://hubs.mozilla.com/".

**[Steps to reproduce]:**
1. Open the Chat box.
2. Insert a link for a video in the Chat input field.
3. Click the Create button.
4. Observe the behavior.

**[Expected results]:**
- The video is spawned into the room and played.

**[Actual results]:**
- The window freezes.

**[Notes]:**
- The issue is reproducible when uploading the files from the Place menu.
- The issue is also reproducible when the files are attached.
- The audio can still be heard in the background after the window freezes.
- Attached is a screen recording of the issue: [link](https://drive.google.com/file/d/1xUMnqKA4fZ0r1HoWhsbFK4swuKAd4X0l/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-73)

**Comment by takahirox** [comment]
Thanks for the report.

Any console errors?

> IphoneSE

I couldn't reproduce the error on iPhone X + iOS 14.6 + Safari 14.1.1.

**Comment by Softvision-RemusDranca** [comment]
@takahirox [Here](https://drive.google.com/file/d/1exRNZpW91auZUx8nrPxPkDRXthCOGlSO/view?usp=sharing) are the console logs received while reproducing the issue on MacOS using Safari 14.0.2.

**Comment by takahirox** [comment]
Thanks for the console logs.

This seems the error causing the problem.

> [Error] TypeError: undefined is not an object (evaluating 'e.panner.positionX.value') (frontend-1b3139bed401fce92cce.js:123:6827)

**Comment by brianpeiris** [comment]
Was not able to reproduce this in Safari 14.1.1, on MacOS 11.4, on a Macbook Air (M1, 2020). I uploaded this video from the chat sidebar: https://github.com/brianpeiris/test-media/blob/main/big-buck-bunny-360p-short.mp4 and I also tried the vimeo video you used in your screen recording and I used the same Outdoor Workshop scene.
The video uploaded correctly without freezing the app, and it played correctly with audio.
The last error in the log you posted would definitely cause an issue though, so I think we'd have to figure out how to reproduce the behavior you're seeing. If you can't repro in the latest version of Safari, it could have just been a Safari bug that was fixed in the browser.

**Comment by Softvision-RemusDranca** [comment]
This issue seems to be only reproducible on Safari 14.0.2, I've updated MacOS and Safari to the latest version 14.1.1 (15611.2.7.1.6, 15611) and ran into a different issue where the audio is broken, more details in #4411. I'll leave this issue open, not sure how many users still use this version, but we could set a lower severity if you want.

**Comment by keianhzo** [comment]
I can't reproduce this freeze on Safari 14.1.2 but I see this log:

`Error loading video – "https://cors-proxy-dev.reticulum.io/https://github.com/brianpeiris/test-media/blob/main/big-buck-bunny-360p-short.mp4?raw=true"`

and the video is displayed as an audio element.

<img width="486" alt="Screen Shot 2021-08-13 at 18 27 38" src="https://user-images.githubusercontent.com/837184/129390412-ac7912ae-d708-4de8-a9bb-7388c60af292.png">

**Comment by takahirox** [comment]
@keianhzo Looks like the same issue #4516

**Comment by johnshaughnessy** [comment]
@takahirox , I see that you have found a work-around for #4516 . Does that also fix this issue?

**Comment by takahirox** [comment]
> @takahirox , I see that you have found a work-around for #4516 . Does that also fix this issue?

Maybe no. Because I have never seen a frozen window problem in #4516, and the error log looks different.

https://github.com/mozilla/hubs/issues/4405#issuecomment-878505921

**Comment by takahirox** [comment]
@Softvision-RemusDranca Do you mind if testing to check if the problem is still reproducible on the latest iOS and MacOS Safari?

**Comment by Softvision-RemusDranca** [comment]
@takahirox I have verified this issue and it's no longer reproducible. The window is no longer freezing when uploading media files.
Tested on Iphone SE2 (iOS15) and macOS Big Sur 11.6 using Safari 15.
Considering this I will close this issue as verified fixed.
