### ISSUE TITLE
The around of the circled buttons in object menu can be weird

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#4417]
**Description**

The around of the circled buttons in object menu can be weird.

**To Reproduce**

1. Go to hubs.mozilla.com
2. Place a thin object
3. Make an angle and move it to a certain position
4. Point the object and press space to open an object menu
5. Observe that the around of the circled buttons in object menu can be weird

I'm really not sure the exact factor which causes this problem. If you can't reproduce the problem, please further try to move or rotate the object, or try another object.

**Expected behavior**

They are rendered correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/7637832/125868854-d05807f2-8221-4338-b37c-ea3db6497c4a.png)

![image](https://user-images.githubusercontent.com/7637832/125869044-48b9c1fa-b687-4e89-8c93-7a74d0fe369a.png)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Additional context**

Could be render order issue?

**Comment by johnshaughnessy** [comment]
This happens because both the button and the avatar images are transparent and sorted by the distance from the camera along its forward ray. With spector js you can see how if the button is drawn first, it will "cut out" of the avatar image, but buttons drawn afterwards will render correctly:

![image](https://user-images.githubusercontent.com/4072106/126692967-6cec31ff-1135-45d7-9bbc-baea79ed5b4f.png)

To fix this problem in general, I believe we'd have to do per-pixel transparency or adopt some other similar technique.

**Comment by johnshaughnessy** [comment]
I believe these all share the same underlying problem:

https://github.com/mozilla/hubs/issues/3431
https://github.com/mozilla/hubs/issues/1979
https://github.com/mozilla/hubs/issues/4416
https://github.com/mozilla/hubs/issues/4417

**Comment by takahirox** [comment]
If that's the case, probably it may be easily resolved by letting writeDepth false. It is the same approach the new Three.js glTF loader does. Let me try.

**Comment by takahirox** [comment]
Note to self:
* Button background is rendered with [aframe-slice9-component](https://github.com/fernandojsg/aframe-slice9-component)
* Avatar image is rendered with our `media-views` component
* Text content in the buttons are rendered with our `hubs-text` component
* Icons are rendered with our `sprites` system

**Comment by takahirox** [comment]
I realized that I misunderstood one thing.

The involved components are transparent but the transparency seems for alpha clipping. The contents them selves (e.g. texts, icons) are opaque (alpha=1).

The `depthWrite=false` approach doesn't work. We need to think of other workarounds.

**Comment by takahirox** [comment]
I may have came up with an easier solution. Introducing `alphaTest` to slice9 can resolve this problem. 

The screenshot of `alphaTest: 0.1` for `rounded-text-button`. See that the clone button doesn't have problem.

![image](https://user-images.githubusercontent.com/7637832/128064795-9cbea98a-c1ac-46f2-ac6b-e9b59606b1db.png)

But it doesn't resolve #4416.
