### ISSUE TITLE
Hubs rooms are black, in Chrome and Firefox and Edge

### ISSUE THREAD

**Issue by ElieDDD** [mozilla/hubs#4428]
**Description**
Hubs rooms are black, in Chrome and Firefox and Edge, I have tried a number of different rooms including the empty project on two  different (Dell and Lenovo) Windows 10 laptops, my class of 7 students on a range of different laptops also had black rooms, they tried the ideation room and other templates, they were all black on Hubs in a range of browsers

**To Reproduce**
1. Go to '.any hubs room on any browser'
2. Click on '..enter room..'

**Expected behavior**
I expected to see a room with walls and objects etc

**Screenshots**

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset] Laptops , Dell and Lenovo, updated and restarted, Chrome, Edge and Firefox, Windows 10
 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**

**Comment by Softvision-RemusDranca** [comment]
@ElieDDD thanks for reporting the issue. It should be fixed now, please let us know if you still encounter it.

**Comment by ElieDDD** [comment]
Yes, great, seems to be back to normal, many thanks !

**Comment by keianhzo** [comment]
II rolled back that and I just  just pushed a fix with audio zones and that issue fixed. It t should be working fine now.
