### ISSUE TITLE
Sketchfab search and filters have incorrect effect on results

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#4452]
**Description**
In Hubs, using the Sketchfab search box or category filters has no effect (or the incorrect effect) on the resulting models listed.

**To Reproduce**
1. Go to any room in Hubs
2. Click on Place-->3d Model
3. In the Sketchfab section, try searching or using the category filters
4. Result:  Categories have no effect on results. Search box seems to give incorrect results.

**Expected behavior**
Search and category filters should give correct results

**Screenshots**
Searching for **'car'**:

![image](https://user-images.githubusercontent.com/31968496/127239535-c396b5e3-0a4c-40e7-903e-3eb95b7b6592.png)

Searching for **'spider'**:

![image](https://user-images.githubusercontent.com/31968496/127239595-9ee7c58e-1824-4e3e-b3c5-f1ec3f17b95b.png)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox

**Additional context**
Seems like something is wrong with the Sketchfab API

**Comment by robinkwilson** [comment]
Fixed! https://github.com/mozilla/reticulum/pull/516

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using the latest releases of Firefox and Chrome on Windows 10.
Now, the Sketchfab search works as expected.
