### ISSUE TITLE
Spacebar options not working (pop up dissapears)

### ISSUE THREAD

**Issue by juanbazan** [mozilla/hubs#4464]
**Description**
Whenever I upload a video or image in my room and I want to edit it in size and position using the spacebar, the pop up disappears when I use the key, preventing me to do anything in the room. 

**To Reproduce**
1. Go to "place"
2. Click on upload or paste a URL from any vid or img. 
3. Press space bar
4. See how the option pops up and then it disappears restricting the possibility to reshape object

**Expected behavior**
That the pop up options for resizing, etc. stay there and are functional 

**Hardware** 
 - Device: [e.g. Desktop, and web browser
 - OS: [e.g. Windows, 
 - Browser: [e.g. Firefox, Chrome and Edge

https://user-images.githubusercontent.com/88348062/127919863-6716a108-4639-40c2-ac94-e5a99d51bc35.MOV

]

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBSOLD-60)

**Comment by johnshaughnessy** [comment]
I'm not sure if I am understanding the report correctly but this might help:
The space bar has to be held down to keep the pop-up menus visible. If you want to _toggle_ freeze mode (which is what allows pop-up menus to appear on hover), you can use the tab key instead. 

Does that resolve the issue or did I misinterpret the bug report?

**Comment by matthewbcool** [comment]
@juanbazan Thanks for very much for the report. Could you clarify the issue? 

> The space bar has to be held down to keep the pop-up menus visible. If you want to toggle freeze mode (which is what allows pop-up menus to appear on hover), you can use the tab key instead.
> 
> Does that resolve the issue or did I misinterpret the bug report?
