### ISSUE TITLE
Videos and GIFs objects appear broken when using the Magnify feature

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4472]
**[Affected Versions]:**
- Safari 14.6
- Chrome 92
- Firefox 90.0.2

**[Affected Platforms]:**
- Windows 10
- Iphone SE 2

**[Prerequisites]:**
- Have a room opened on "https://hubs.mozilla.com/".
- Have a video or a GIF file spawned into the room.

**[Steps to reproduce]:**
1. Hover over the video or GIF object.
2. Press the Space key to display the object's menu.
3. Click the Magnify button from the menu.
4. Observe the low view of the object displayed.

**[Expected results]:**
- The view of the object is correctly displayed.

**[Actual results]:**
- A black view of the object is displayed.

**[Notes]:**
- The issue is not reproducible with images and PDF objects.
- The issue is not reproducible on Hubs Cloud production or beta.
- Attached is a screen recording of the issue: [link](https://drive.google.com/file/d/1KfRt4liiqHGh1moFXZE8DTKexxVYVj0T/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-58)

**Comment by takahirox** [comment]
I can reproduce the problem, left: `master`, right : `qa-test`.

![image](https://user-images.githubusercontent.com/7637832/128235808-30525a74-6e8b-4a7e-9ee9-bb5cb5c67fb8.png)

**Comment by takahirox** [comment]
The console error is

![image](https://user-images.githubusercontent.com/7637832/128244363-bc8e8602-737c-4c6e-a391-be9cb81c23f0.png)

And the line causes the error is

![image](https://user-images.githubusercontent.com/7637832/128244857-c6fb91ab-8c5d-4cdd-8722-04fa9483464c.png)

It looks `audio-params` component data issue. I think @keianhzo recently fixed it but this problem was overlooked? Any clues, Manuel?

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible on https://hubs.mozilla.com/ using App version: 1.0.0.20210810133537. Now, the Videos and GIFs objects are correctly displayed when using the Magnify feature.

Tested on Windows 10 - Firefox 90.0.2; Chrome 92 and on Iphone SE 2 - Safari 14.6.
