### ISSUE TITLE
The media objects volume bar is wrongly displayed at 100% when created

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4477]
**[Affected Versions]:**
- Safari 14.6
- Chrome 92
- Firefox 90.0.22

**[Affected Platforms]:**
- Windows 10
- IphoneSE 2

**[Prerequisites]:**
- Have a room opened on "https://hubs.mozilla.com/".

**[Steps to reproduce]:**
1. Spawn a video or GIF file inside the room.
2. Hover over the object.
3. Observe the volume bar.

**[Expected results]:**
- The volume bar is displayed at 50%.

**[Actual results]:**
- The volume bar is displayed at 100%.

**[Notes]:**
- If the "+" or "-" buttons are clicked the volume bar jumps back to 50%.
- This issue is not reproducible on Hubs Cloud.
- Attached is a screen recording of the issue:
![VolumeBar](https://user-images.githubusercontent.com/40061643/128226049-0560caa7-07ff-4c87-84dd-31049489fcbb.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-43)

**Comment by takahirox** [comment]
This problem seems the same problem I encountered in the smoke test and internally reported.
