### ISSUE TITLE
master branch VS hubs-cloud branch

### ISSUE THREAD

**Issue by Seikida** [mozilla/hubs#4490]
**Description**
Do you plan to update the hubs-cloud branch?
Indeed, It's very hard to deploying my work on AWS.

The master branch and hubs-cloud branch are using different version of three:
The master branch using the 0.128.0 version of three while the hubs-cloud branch uses the 0.111.0 version of three.

**version: 0.128.0**

```
"devDependencies": {
    "@babel/core": "^7.13.15",
    "@babel/eslint-parser": "^7.13.14",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/preset-env": "^7.13.15",
    "@rollup/plugin-babel": "^5.3.0",
    "@rollup/plugin-node-resolve": "^11.2.1",
    "chalk": "^4.1.0",
    "concurrently": "^6.0.2",
    "eslint": "^7.24.0",
    "eslint-config-mdcs": "^5.0.0",
    "eslint-plugin-html": "^6.1.2",
    "glob": "^7.1.6",
    "rollup": "^2.45.2",
    "rollup-plugin-filesize": "^9.1.1",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-visualizer": "^5.3.6",
    "servez": "^1.11.0"
  }
```

**version: 0.111.0**

```
"devDependencies": {
    "@types/webgl2": "^0.0.5",
    "@typescript-eslint/eslint-plugin": "^2.9.0",
    "@typescript-eslint/parser": "^2.9.0",
    "concurrently": "^5.0.0",
    "eslint": "^6.7.1",
    "eslint-config-mdcs": "^4.2.3",
    "eslint-plugin-html": "^6.0.0",
    "failonlyreporter": "^1.0.0",
    "google-closure-compiler": "20190929.0.0",
    "http-server": "^0.12.0",
    "qunit": "^2.9.3",
    "rollup": "^1.27.5",
    "rollup-plugin-buble": "^0.19.8",
    "typescript": "^3.7.2"
  }
```

---> to be exactly, the hubs-cloud branch using this version of three: mozillareality/three.js#hubs/master
https://github.com/mozillareality/three.js
It's a fork of old three.js version

Can you upgrade this version?

Thank you

**Comment by Seikida** [comment]
I found this issue: https://github.com/mozilla/hubs/issues/4108
→ Replace our Three.js fork to the official one #4108

**Comment by matthewbcool** [comment]
Hi @Seikida, master branch is going to be ahead of hubs cloud with updates and version upgrades. Generally hubs cloud releases come later but there is not a specific release schedule at the moment.
