### ISSUE TITLE
[VR]Mute State Reversed in VR mode UI

### ISSUE THREAD

**Issue by matthewbcool** [mozilla/hubs#4504]
**Description**
vr-mode-ui displays mic muted when mic is live and mic on when mic is muted. 

**To Reproduce**
1. Join a hubs room in immersive mode with your headset.
2. Talk while the ui appears muted. 
3. audio should be heard by room participants while vr-ui indicates mic muted (note 2d ui is still correctly indicating proper mute status)

**Expected behavior**
When the vr-mode-ui displays a muted mic, the participant should expect to be muted.

**Screenshots**

https://user-images.githubusercontent.com/4493657/128947432-80e0b16e-7054-4922-b371-bcd07455d57e.mp4

**Hardware**
 - Device: Oculus 2
 - Browser: FF Reality and Oculus Browser

**Comment by johnshaughnessy** [comment]
I'm guessing this broke here:
https://github.com/mozilla/hubs//commit/94625cce3#diff-c99a3911292f8ce088bcb9afaed09a4f4af9ccd38ecb9abbb01c8a0436dee63fR250

That too-clever statement has an `!active` where there should be an `active`. It should be:

```js
   const spriteNames =
      SPRITE_NAMES[active ? (hovering ? "MIC_HOVER" : "MIC") : hovering ? "MIC_OFF_HOVER" : "MIC_OFF"];
```
or
```js
    const spriteNames =
      active && hovering ? "MIC_HOVER" : active ? "MIC" : !active && hovering ? "MIC_OFF_HOVER" : "MIC_OFF";
```
or 
```js
    let spriteNames;
    if (active && hovering) {
      spriteNames = "MIC_HOVER";
    } else if (active && !hovering) {
      spriteNames = "MIC";
    } else if (!active && hovering) {
      spriteNames = "MIC_OFF_HOVER";
    } else {
      spriteNames = "MIC_OFF";
    }
```

**Comment by keianhzo** [comment]
I believe this might have originated here:
https://github.com/mozilla/hubs/commit/5770fcb05acb3c72a145ff8b4364b11ef88735e7#diff-41e4a162abee096fd8e0ad392f7996269045a2cea8cd5ef800d78a526f25c951L17-R22

```
- this.mic.setAttribute("mic-button", "active", this.el.sceneEl.is("muted"));
+ this.mic.setAttribute("mic-button", "active", APP.dialog.isMicEnabled);
```

We went from passing a disabled state to an enabled state. Pushing fix.
