### ISSUE TITLE
Additional content sharing features

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#451]
Grab bag of fixes + features for content sharing

Frontend Bugs:
- [x] Google Poly does not load due to failed HEAD request
- [x] Animated GIFs hitting CEF security issue
- [x] Positional audio on videos
- [ ] Mobile perf dropping off at 6 ppl
- [x] Maybe kill videos if they get thrown away/far away
- [x] Some objects were not getting destroyed
- [x] When user pastes a URL in the modal for a UGC site we use the API for, add a "Powered by X" attribution on screen in the modal.
- [x] Fix offsets
- [x] Loading indicator while resolving media
- [x] Rework spawners so they can load any asset
- [x] Support inflation of spawner spawned objects
- [ ] Bizarre shadow map bug when viewing gifs or videos on Oculus Go
- [x] Switching between hands while holding an interactable stops rotation from happening
- [ ] Error images for things that were originally 3d models show delete buttons on all 4 sides insted of just front and back

Backend Bugs:
- [x] Reticulum media api sometimes returns farspark urls for error strings (see comments below)
- [x] Fix 302 redirects
- [ ] Apply for prod giphy API key
- [x] Media API should return "assumed content type" for poly
- [x] Media API should return raw origin URL
- [x] Proxy OPTIONS requests
- [ ] Google drive video fail to return HEAD request so we need to return `expected_content_type` for them

Feature requests:
- [x] Video sync, video pause
- [x] Video volume control
- [x] PDF/slides paging (ok nobody asked for this yet but me :))
- [x] Rotate object at the end of my cursor
- [ ] Snap onto wall surface
- [x] Snap rotate object

**Comment by netpro2k** [comment]
This url:

https://r4---sn-n4v7knls.googlevideo.com/videoplayback?fvip=4&ms=au%2Conr&mv=u&mt=1531187234&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&pl=48&id=o-AHUbC6cW1MAJN1ZV0Xso7vyxKrPDVCDtc-7JTJKLnUQG&mime=audio%2Fwebm&gir=yes&mn=sn-n4v7knls%2Csn-a5meknsd&ip=2620%3A101%3A80fc%3A224%3A9d66%3A4006%3Aa053%3A40c4&key=yt6&expire=1531209165&ei=bRFEW4OGIYLi-gOq-K_YCA&itag=251&keepalive=yes&mm=31%2C26&requiressl=yes&source=youtube&dur=242.001&clen=3970912&fexp=23709359&ipbits=0&c=WEB&lmt=1526501621884570&signature=064F44DD585DDF7D4604BC43B74D43836A701BFA.4152ABBA8EF19703B91B860DEDC05D29494C9CD5&ratebypass=yes 

Resolves to:
https://farspark-dev.reticulum.io/vXcB2VzGcQYYVdZ7dt69RGIvMrNhk1yk9ouowC51K9U/raw/0/0/0/0/ZnVuY3Rpb24gOmVycm9yLmJvZHkvMCBpcyB1bmRlZmluZWQgKG1vZHVsZSA6ZXJyb3IgaXMgbm90IGF2YWlsYWJsZSk

Which is a farspark URL for ""function :error.body/0 is undefined (module :error is not available)"

**Comment by gfodor** [comment]
A few more follow up things:

[ ] Loading object (instead of white cube :))
[ ] Portrait photo uploads from phone are rotated
