### ISSUE TITLE
Avatar Cam Texture Transparency Bugs

### ISSUE THREAD

**Issue by matthewbcool** [mozilla/hubs#4557]
**Description**
the avatar cam material appears transparent and functions unexpectedly. When inspecting your own avatar, the avatar cam works as expected in material and 

**To Reproduce**

1. Change into an avatar camera enabled avatar 
1. Observe your avatar with the camera
1. enable cam and view results in self inspect mode and through the camera/other player

**Expected behavior**
expect to see the camera output in the designated texture

**Screenshots**
![Screen Shot 2021-08-20 at 11 28 13 AM](https://user-images.githubusercontent.com/4493657/130283261-ea58b5e5-44c0-4416-b83a-eba92788fb97.png)

![](https://cdn.discordapp.com/attachments/878252407409246259/878324639896600606/unknown.png)

![](https://cdn.discordapp.com/attachments/878252407409246259/878295318037426207/unknown.png)

![](https://cdn.discordapp.com/attachments/878252407409246259/878323854592839710/unknown.png)

**Hardware** 

* Device: macbook pro
* OS: Windows, MacOs
* Browser: Chrome, FF, Safari

**Additional context**

possibly related to https://github.com/mozilla/hubs/issues/4553

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-720)

**Comment by Softvision-GeluHaiduc** [comment]
There are other 2 issues that could possibly be related to this one, #4273 and #4010, but I'm not sure.

**Comment by keianhzo** [comment]
Closed by https://github.com/mozilla/hubs/pull/4598
