### ISSUE TITLE
Very tiny URL input form in Upload menu on Safari

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#4591]
**Description**

URL input form in Upload menu on Safari is very tiny. Or the attach button is too long.

**To Reproduce**

1. Go to hubs.mozilla.com on Safari
2. Enter a room
3. Click "Place" - "Upload"
4. Confirm the problem

**Expected behavior**

The URL input form looks long enough like the one you see on Chrome

![image](https://user-images.githubusercontent.com/7637832/131572026-27ceb2e2-085a-421a-91f7-6cbe6b440c8d.png)

**Screenshots**

![image0](https://user-images.githubusercontent.com/7637832/131571473-b2620313-48e3-4e10-9a16-cdd200f00c5e.jpg)

**Hardware** 
 - Device: Desktop, mobile
 - OS: MacOS, iOS
 - Browser: Safari

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-849)

**Comment by j-conrad** [comment]
Note: This layout looks identical in portrait and landscape modes.

**Comment by Softvision-RemusDranca** [comment]
I think this is a duplicate of #4031.

**Comment by takahirox** [comment]
Oh, thanks
