### ISSUE TITLE
Can not create room - Websocket connection fail

### ISSUE THREAD

**Issue by baohiep83** [mozilla/hubs#4605]
I install hubs and reticulum locally. After run hubs.local:8080, the screen display, but when I press button "Create Zoom", system can not create because of websocket connection fail as belows:
browser.js:25 WebSocket connection to 'wss://hubs.local/?roomId=AJihiK9&peerId=80de6e62-03ce-4030-9fe9-13bcec733674' failed: 
Please help me to fix this issue.
![image](https://user-images.githubusercontent.com/42344684/131884063-d566680c-b11d-4beb-81d5-fb042ca30f5d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-857)

**Comment by rawnsley** [comment]
There should be a corresponding error message in the Network tab that may give you more information.

**Comment by baohiep83** [comment]
@rawnsley I found no error message in the network tabs. Only hub.service.js is pending as the attached picture
![image](https://user-images.githubusercontent.com/42344684/131946292-f59385c0-fc7c-439e-90fc-4a2ab28257f1.png)

**Comment by baohiep83** [comment]
I fixed this error. The error happen when I configured port of Dialog is 4443. I modified port of dialog into 443.
