### ISSUE TITLE
Pinned objects causing owned-object-limiter issues after stack upgrade

### ISSUE THREAD

**Issue by camelgod** [mozilla/hubs#4607]
I did the following:

1. Created a room on HC
2. Spawned some 3D objects, pinned an image, put something into a media frame.
3. Left the room
4. Did a stack upgrade on AWS from t3.micro to t3.small
5. Terminated the old instance (single server hc personal)
6. Joined the room on new instance
7. Clicking any object, both new and old, that anyone has spawned (tested with Pellinore and he clicked my image and it was also removed) will remove it from the room. The removal is triggered by the owned-object-limiter.js even though the object I am clicking has a networked-counter limit of 100 (even when logging the data for the component it is 100). 

Observations:
- `_destroy` and `_destroyOldest` from networked-counter are not triggered
- Creating a new room does not have this issue
- Drag-and-drop an image and it appears in the room. If I click on it (I assume its the isHeld that gets triggered), it is removed again instantly.
- The objects data has a max value of 100, so it makes no sense why it is deregistered immediatley on click / drag / hold.
- I have left and entered the room multiple times, happens with new users too.

_syncCounterRegistration is being called on each tick in owned-object-limiter. Failing to be isMine on any element touches calls deregister on it immediately. I think maybe the stack upgrade made the previous pinned objects in the room lose its original owner.

Here is me logging the NAF.utils.isMine in owned-object-limiter.js. It goes off every tick (even before entering the room):
![image](https://user-images.githubusercontent.com/28685654/131967227-99e1afe2-6c31-4f54-88b7-f519abdc7681.png)

Deleting two of the items in the object lists that were pinned before stack upgrade made the issue go away.  I had to manually takeOwnership, setAttribute("pinnable", { pinned: false }); and then remove the object. After the two broken objects were removed, the room works as normal and I can spawn stuff again.

I dont know if the stack upgrade is related to this object limiter / media frame system breaking.

Here is what I think happened:

- I added an object into a media frame, and something broke scaling the object to 700x. Then it was automatically pinned (logic I added myself)
- After the stack upgrade something went wrong with the ownership of the item, causing owned-object-limiter to freak out
- The scale issue made it so i didn't see the problem objects as they were so large

**Comment by johnshaughnessy** [comment]
@camelgod I am having a difficult time understanding the bug. Have you reproduced the issue on a vanilla hubs cloud instance (without a custom client)? I am hesitant to look into this issue (with complicated repro steps) if the root cause has something to do with the modifications you made to your custom client.

**Comment by camelgod** [comment]
> @camelgod I am having a difficult time understanding the bug. Have you reproduced the issue on a vanilla hubs cloud instance (without a custom client)? I am hesitant to look into this issue (with complicated repro steps) if the root cause has something to do with the modifications you made to your custom client.

Sorry, i should have updated this issue. Here is what happened:

The room had a media zone that took an object of 0.3 scale, glitched out so it covered the entire world and turned invisible, then pinned it (i put the pinning logic on release into media zone). 

This invisible object triggered the owned object limiter inside the room after a stack upgrade, then though the room didnt have close to the limit of objects.

I still dont know what caused the object limiter to behave in this way, but this issue has become outdated.

**Comment by camelgod** [comment]
I will open a new issue if there are more episodes of glitched pinned objects that somehow lose ownership and occupy limit after stack upgrade again. Due to the rare circumstances i cannot repro this and I was able to work around it by simply deleting the problem object.
