### ISSUE TITLE
Test Issue Syncing update 1035

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#4621]
**Description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-886)

**Comment by data-sync-user** [comment]
➤ Elgin-Skye McLaren commented:

im commenting on this in jira

**Comment by emclaren** [comment]
closing this test issue
