### ISSUE TITLE
Environment settings doesn't support non-HDR texture for background

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#4635]
If you set the **Environment Settings** _Background Image_ property to be a non-HDR texture it is not displayed in Hubs. In [this example scene](https://hubs.mozilla.com/scenes/KaUPL2M/ldr-env-texture-test) the image was set to another scene texture:

<img width="419" alt="Screenshot 2021-09-13 at 08 50 13" src="https://user-images.githubusercontent.com/303516/133045224-1cca411b-809a-4442-999e-6c0380fcfc96.png">

When the scene is loaded only the background color is shown:

<img width="738" alt="Screenshot 2021-09-13 at 08 51 21" src="https://user-images.githubusercontent.com/303516/133045349-98cd3282-d565-4a96-8354-f7478f76245a.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-894)

**Comment by netpro2k** [comment]
Thanks for reporting this. This is actually an exporter issue (I literally just didn't implement it yet), the hubs client should be able to handle both HDR and non HDR images for everything.

**Comment by netpro2k** [comment]
Fixed this in the exporter, but it turns out SDR background images end up being flipped, so this turns out to need a hubs change after all
