### ISSUE TITLE
The people counter has the wrong format in the “People” side menu if the language is set to french

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#4647]
**[Affected Versions]:**
- Firefox Release 92.0
- Chrome 93.0.4577.82

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Have a new room created.
- Have the room entered.

**[Steps to reproduce]:**
1. Open Preferences from the More menu on the "Misc" page.
2. Click the drop-down menu from the Language section.
3. Select the French language from the dropdown menu.
4. Dismiss the “Preferences” menu
5. Click the “Personnes” button from the top right of the screen
6. Observe the top of the opened panel

**[Expected results]:**
- The string “Personnes” followed by a space and a counter between brackets is displayed

**[Actual results]:**
- The counter is displayed first followed by the string “Personnes” and both the counter and string is in between brackets

**[Notes]:**
- Attached is a screenshot of the issue below:
![image](https://user-images.githubusercontent.com/51400741/133620852-d5099356-8f1c-4374-bde5-de01d9c1ee84.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-908)

**Comment by SV-AndreiC** [comment]
"I have verified this issue and it's no longer reproducible. The people counter has the correct format in the “People” side menu when the language is set to French: ""Personnes"" followed by a space, followed by the number of people in the room inbtween brackets. 
Tested this on Win 10 using Firefox 94.0.2 and Chrome 96.0.4664.45 browsers. "
