### ISSUE TITLE
Background Is Always Black Without Skybox

### ISSUE THREAD

**Issue by Exairnous** [mozilla/hubs#4648]
**Description**
When using a scene with a singular color as the background and no skybox, the background is always rendered as black instead of the color set with the Background Color property of the scene.

**To Reproduce**
1. Create a scene in Spoke with no skybox and the background color set to something other than black.
2. Publish the scene and note that everything in spoke looks as it should.
3. Enter a room with that scene.
4. See that the background or "sky" is pure black.

Here's a link to a test scene: https://hubs.mozilla.com/scenes/BErFYHQ/testbackgroundcolor

**Expected behavior**
For the background to be rendered with the color that was set in Spoke.

**Hardware**
 - Device: Laptop
 - OS: Linux (Archlinux, KDE)
 - Browser: Chrome, Firefox

**Workaround**
You should be able to work around this bug by creating a cube (1000 m, in blender you can scale the default cube by 500 to achieve this) with an unlit material the color you want your background and adding that to your scene at the origin (disable walkable and collidable).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-910)

**Comment by j-conrad** [comment]
I can confirm this bug. 
One thing to note: The background color shows correctly in the Lobby view. This tells me it might have something to do with the user camera's clipping values--perhaps the far clip is set too close?
Another scene for testing:
https://hubs.mozilla.com/scenes/SzjM45o

**Comment by Exairnous** [comment]
Interesting, for me the background color shows up black in the lobby, it does show up correctly in the scene preview image and it shows correctly when just viewing the scene link you posted, but not if the scene is in a room.
And thanks for the confirm :)

**Comment by netpro2k** [comment]
This was a regression with the new environment settings system. It needs to account for scenes that already have a background setting and don't have environment settings component.
