### ISSUE TITLE
Impossible to join Hubs Cloud room in Oculus Browser because button is offscreen

### ISSUE THREAD

**Issue by wmurphyrd** [mozilla/hubs#4672]
**Description**
When going through the room entry flow as a new user on Oculus Browser / Quest2, I cannot proceed past the name & avatar selection because the button to continue is hidden offscreen. 

This applies to the current hubs-cloud release (52f293ed7f65329386adc50cbd192807166c83a5), but it does not apply to hubs.mozilla.com

**To Reproduce**
1. Visit a Hubs Cloud or checkout `hubs-cloud` branch to run against one or observe on https://hub.vreign.space (this hub is still on the previous release of hubs cloud, but the issue appears on both)
2. Use private mode or clear local storage force first-time join flow
3. Try to proceed through flow from Oculus Browser

**Expected behavior**
Can click the button and finish room entry flow

**Screenshots**

![image](https://user-images.githubusercontent.com/10034859/134776268-5a2450ca-af9b-441f-9714-20d9cbd28df0.png)

**Hardware** 
 - Device: Quest2
 - OS: Oculus
 - Browser: Oculus

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-916)

**Comment by matthewbcool** [comment]
additional context here: https://github.com/mozilla/hubs/pull/4616

**Comment by wmurphyrd** [comment]
Thanks for the link @matthewbcool ! Now I can cherry pick that fix into my builds
