### ISSUE TITLE
Unable to connect to this room, please try again later.

### ISSUE THREAD

**Issue by tomoya8177** [mozilla/hubs#4717]
**Description**
Hubs system seems to be working with no problem, but when a user tries to enter a room, it shows "Unable to connect to this room, please try again later.
" error.

**To Reproduce**
1. Go to 'https://vosproduction.com/BMRbutY/aoike-high-school'

**Expected behavior**
you enter into a room.

**Screenshots**
https://www.dropbox.com/s/6ldwz7oq6c65ju3/Screen%20Shot%202021-10-07%20at%208.39.50.png?dl=0
[https://www.dropbox.com/s/6ldwz7oq6c65ju3/Screen%20Shot%202021-10-07%20at%208.39.50.png?dl=0](url)

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1088)

**Comment by matthewbcool** [comment]
@tomoya8177 are you still experiencing this issue and can it be reproduced on hubs.mozilla.com? Closing for now as I could not repro.
