### ISSUE TITLE
Websocket problem for all users, all rooms: "Unable to connect to this room, please try again later."

### ISSUE THREAD

**Issue by hnu-janfiedler** [mozilla/hubs#4734]
**Description**
We cannot create/enter any rooms on our AWS hosted Hubs instance (Hubs Cloud Personal version 1.1.2). We have tried different browser, university-VPN on and off, even using a mobile cell data connection, the problem is still the same. I terminated the instance, too, to see if it was just the instance being stuck, but that didn't help either.
When looking at the browser console and network analysis (see attached screenshots), you can see it's a websocket connection issue, but how can we fix this?
I have also attached the "journalctl -f" logs from the server. Connecting via SSH works fine and all services seem to be running.
![firefox-console](https://user-images.githubusercontent.com/92423605/137081206-7803ed31-d4b3-4a53-8a13-3f57fc4532f6.png)

![firefox-networkanalysis](https://user-images.githubusercontent.com/92423605/137081226-06666dd9-cc5d-40c9-8c02-cebeb70ab9b7.png)

[journalctl-f.txt](https://github.com/mozilla/hubs/files/7335577/journalctl-f.txt)

**To Reproduce**
1. Go to 'virtual-hnu.de'
2. Click on 'Create Room'
3. After loading all the objects and seeing "Entering room", you get the error "Unable to connect to this room, please try again later."

**Expected behavior**
User should enter the room.

**Screenshots**

**Hardware** 
 - Device: Desktop, iPad, iPhone (haven't tested Mac yet)
 - OS: Windows, iOS
 - Browser: Chrome, Firefox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1100)

**Comment by hnu-janfiedler** [comment]
And I just saw in the Discord chat that the v1.1.2 template has been fixed, so updating or setting up a new stack with it is now again possible!

**Comment by gdmtech** [comment]
Lets try the update and share result here

**Comment by hnu-janfiedler** [comment]
> 
> 
> Lets try the update and share result here

Worked for me!
