### ISSUE TITLE
Local dev "npm start" does not work

### ISSUE THREAD

**Issue by illusorr** [mozilla/hubs#4749]
**Description**
App Home page don't work.
Firstly it was appear for 0.1 sec only once by F5 refresh page, but it is disappear and screen is white blank.

**To Reproduce**
`git checkout hubs-cloud`
`npm ci`
`npm run login`
`npm start`
goto https://localhost:8080/webpack-dev-server/

**Expected behavior**
landing page should be appear.

**Screenshots**
![Screenshot from 2021-10-18 08-29-33](https://user-images.githubusercontent.com/92729925/137730940-65b014b7-e076-48cb-9328-f59fe4fcabb4.png)

**Hardware** 
 - Device: Desktop
 - OS: Ubuntu 18
 - Browser: Chrome 94.0.4606.61 (Official Build) (64-bit)

**Additional context**
backend version: Hubs Cloud Personal 1.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1108)

**Comment by JINDBS** [comment]
Having the same issue did you find the solution?
