### ISSUE TITLE
Can't create and enter a room on iOS Firefox

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#4768]
**Description**

Currently I can't enter and create a room on iOS Firefox

**To Reproduce**
1. Go to https://hubs.mozilla.com
2. Click on "Create Room Button"
3. See error

**Expected behavior**

Can create and enter a room on iOS Firefox

**Screenshots**

![image0](https://user-images.githubusercontent.com/7637832/138348181-6762f92d-79d4-4d25-8566-62bd0e1211b4.jpg)

**Hardware** 
 - Device: Phone
 - OS: iOS
 - Browser: Firefox

**Additional context**

I can do them on iOS Chrome and Android Firefox. So the problem seems as iOS Firefox specific.

I googled, but remote debugging with iOS Firefox is impossible?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBSOLD-1122)

**Comment by brianpeiris** [comment]
I did not have any issues with the latest version of Firefox on iOS. FxiOS/99, iPhone 11, iOS 15.4

**Comment by takahirox** [comment]
I couldn't reproduce on the latest Firefox + iOS 15.4.1 iPhoneX. I guess the old Firefox or iOS issue?

Closing for now. Please reopen if someone still faces the problem.
