### ISSUE TITLE
The room is black on iOS in the old smoke test room

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#4771]
**Description**

The room is black on iOS in the old smoke test room.

**To Reproduce**

1. Go to the old smoke test room on iOS (Internally ask the team for the URL)
2. See the room is rendered as black

**Expected behavior**

The room is rendered correctly.

**Screenshots**

![df718560-10f5-4c4c-ad97-4ae76eae0772](https://user-images.githubusercontent.com/7637832/138536488-6af08032-3e6d-4a7b-af38-fd65ac7e38bd.png)

**Hardware** 
 - Device: iPhoneX
 - OS: iOS 15.0.2
 - Browser: Safari, Chrome

**Additional context**

I couldn't reproduce on Android. So maybe this is an iOS specific problem.
I couldn't reproduce in other scenes (yet). So maybe this issue is a scene specific problem.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBSOLD-1123)

**Comment by takahirox** [comment]
Thank for the test. Hm, so the problem might be old or low-end model specific or latest iOS specific. Would you mind if upgrading your iOS and test again?

**Comment by brianpeiris** [comment]
I cannot reproduce this anymore on my iPhone 11 with iOS 15.4.1 and Safari 15.4

**Comment by takahirox** [comment]
I can no longer reproduce it neither on my iPhoneX iOS 15.4.1 Safari and Chrome 101.0.4951.44. I guess the problem has been fixed on iOS end?

Let's close this issue. Please reopen if someone still faces the problem.
