### ISSUE TITLE
The audio is broken on iOS Safari in the smoke test rooms

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#4772]
**Description**

After being in the smoke test room for a few minutes, I don't hear anything on iOS Safari.

**To Reproduce**
1. Go to the old smoke test room ~~or the new smoke test room # 2 (media test room)~~
2. Confirm that you don't hear anything after being in the room for a few minutes

**Expected behavior**

Audio is fine.

**Hardware** 
 - Device: iPhoneX
 - OS: iOS 15.0.2
 - Browser: Safari

**Additional context**

Audio is fine in the following conditions.
* https://hubs.mozilla.com
* Enter a room from iOS Safari and Windows Chrome

I have no idea why the problem is reproducible only in the smoke test rooms. Many audio sources can break the audio?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1124)

**Comment by brianpeiris** [comment]
I could not reproduce this on my iPhone 11 with iOS 14.7.1 and Safari 14.1.2. In the old smoke room, with bots, I waited ~10 minutes and the bot audio kept playing.
In the second smoke room, with the media tests, the mp4 video continued to play with sound, but I could not get the mp3 test to work at all, though that might be a separate bug.

**Comment by takahirox** [comment]
I can no longer reproduce the problem on my iPhoneX iOS 15.4.1 Safari. I guess the root issue is same as #4771 and it has been resolved on iOS end.

Let's close this issue. Please reopen if anyone still faces this problem on the latest iOS.
