### ISSUE TITLE
I want like this endpoint on my local machine. 'https://dev.reticulum.io/api/v1/media'

### ISSUE THREAD

**Issue by Aaryan9898** [mozilla/hubs#4789]
Hello There !

I want to have this endpoint on my local machine.
What and which repository i have to install to get started ?
And please state me How to install those repositories. ?
It would be very much helpful.

https://dev.reticulum.io/api/v1/media

Thank You.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1129)

**Comment by matthewbcool** [comment]
Welcome you to join the hubs community discord where I encourage you to discuss this issue further in the community dev channel #dev-self-hosting. https://discord.gg/sBMqSjCndj

closing this issue because it's outside the scope of a client bug/feature request.
