### ISSUE TITLE
Embedd hub room without cookies

### ISSUE THREAD

**Issue by ngmiduc** [mozilla/hubs#4793]
Is there a way to embedd a Room on a website without Mozilla setting a cookie ?
When I embedd a room, it puts a GA cookie from hub.mozilla.com on my webpage. 

The problem is that it might be problematic for the European Data Protection Law.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBSOLD-1133)

**Comment by tokyoronin** [comment]
Google Analytics
