### ISSUE TITLE
Tracking bug with VR headset, navigating in hubs room not possible

### ISSUE THREAD

**Issue by LExit89** [mozilla/hubs#4799]
**Description**

Tracking with VR headset doesn't work. It's not possible to move in spaces, you cannot navigate correctly. While navigating in Hubs rooms the head/the hands have a distance to the avatars body. Top menue is not tracked correctly.

**To Reproduce**
1. Go to a hubs room using VR headset. (doesn't matter which)
2. Navigate, try to move
3. Find your avatars body at another place than your head
4. moving around doesn't work

**Expected behavior**
Yesterday it worked perfectly - the bug exists since today

**Screenshots**
[grafik](https://user-images.githubusercontent.com/93397719/139916011-01cf1f06-c580-4ee1-92f1-0df599bc16d6.png)
you see the hands of the avatar in the foreground and the body in the background. 

**Hardware** 
 - Device: VR headset (Oculus Quest 2/Valve Index/htc vive pro 2)
 - OS: Windows 10
 - Browser: Firefox and chrome

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1134)

**Comment by TJG-RR** [comment]
https://support.mozilla.org/de/questions/1356270

**Comment by netpro2k** [comment]
Thanks for the report. This was a regression with the last threejs update. It should now be fixed!

**Comment by teamVRtjg** [comment]
Bug is there again. https://github.com/mozilla/hubs/issues/5373#issue-1210712700
