### ISSUE TITLE
Personal space bubble has stopped working

### ISSUE THREAD

**Issue by keianhzo** [mozilla/hubs#4801]
**Description**
The avatar personal space bubble is not working

**To Reproduce**
1. Enter a Hubs room
2. Make sure that there are two avatars in the room
3. Get inside the personal space of the other avatar
4. The avatar doesn't become transparent

**Expected behavior**
When an avatar enter another avatar's personal space bubble it should become transparent.

**Screenshot**
<img width="1137" alt="Screen Shot 2021-11-03 at 09 07 07" src="https://user-images.githubusercontent.com/837184/140026636-bd2c57d8-47d0-4a9d-aa4d-281329bc211b.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1136)

**Comment by SV-AndreiC** [comment]
I have verified this issue and it's no longer reproducible. Now, the avatars become transparent when entering the personal space bubble.
Tested on Windows 10 using Firefox 94.0.1 and Chrome 95 browsers.
