### ISSUE TITLE
Tweet Sharing not working

### ISSUE THREAD

**Issue by tokyoronin** [mozilla/hubs#4807]
1. I set up the Twitter API Tokens and entered in the backend Settings   (Mozilla Hubs Enterprise Install)
2. I made a Selfie inside a room with the camera
3. When the picture pops up, I selected TWEET
4. A window opens and says CONNECT TO TWITTER    --- here is the problem,  no connection to twitter is happening to allow app access

![Bildschirmfoto 2021-11-04 um 10 19 12](https://user-images.githubusercontent.com/92306028/140288623-d6ea5017-7543-4039-8b32-deffa68e75c2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1138)

**Comment by Charlesc22** [comment]
We also get the same experience. The Tweet from Selfie does not work, but the Tweet button in the Invite menu does work.

**Comment by robinkwilson** [comment]
You'll need to add the proper `Callback URL` to your application in the Twitter developer menu. I added more instructions here: https://hubs.mozilla.com/docs/hubs-cloud-enable-media-browser.html#twitter

If you are still having issues, can you send a screenshot of errors in your Console and comment on this issue?

**Comment by tokyoronin** [comment]
@robinkwilson I added the call back urls. But it is still not working. I refreshed the browser. When I hit connect to twitter, it kicks me out to the lobby. You can try it yourself under https://tmvr.io

Can you explain me where I can find the **console** that you mentioned please.

**Comment by tokyoronin** [comment]
![Bildschirmfoto 2021-11-06 um 11 37 04](https://user-images.githubusercontent.com/92306028/140606701-553203fa-43fc-4b77-a9ee-7697517496d6.png)

**Comment by tokyoronin** [comment]
Here is what my Console says when I click "Connect to Twitter":

<img width="558" alt="Bildschirmfoto 2021-11-08 um 16 50 23" src="https://user-images.githubusercontent.com/92306028/140773775-ac02abae-ea9d-4508-af60-10197e0a00fe.png">

**Comment by tokyoronin** [comment]
Somehow it is working now. I believe I needed some approval from Twitter. When I regenerated all tokens it worked. I also set "request user email" to on.
