### ISSUE TITLE
Scene failed to load custom client localhost

### ISSUE THREAD

**Issue by jinspe** [mozilla/hubs#4813]
**Description**
I have a working cloud instance, everything is working as expected on the website, the issue is getting a development environment.
Following the doc: 
https://hubs.mozilla.com/docs/hubs-cloud-custom-clients.html

**To Reproduce**
1. Follow this tutorial https://hubs.mozilla.com/docs/hubs-cloud-custom-clients.html
2. After npm start visit :  https://localhost:8080/
3. Click create room
4. Get The scene failed to load.
5. Console first error: Failed to load resource: the server responded with a status of 404 (Not Found)

**Expected behavior**
Getting a room as on the live website with localhost and be able to develop on it

**Screenshots**
![image](https://user-images.githubusercontent.com/93541183/140411464-a7e59f63-250b-4c66-bc88-9d80e9f9ff31.png)

**Hardware** 
 - Device: [Desktop]
 - OS: [ Windows 10]
 - Browser: [Chrome]

**Console**
GET https://localhost:8080/manifest.webmanifest 404 (Not Found)
manifest.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
An SSL certificate error occurred when fetching the script.
hub.js:954 Reticulum @ determined-cleric.minikosm.com: v1.0.20210618144438 on minikosm-01
phoenix-utils.js:125 Phoenix Socket URL: wss://determined-cleric.minikosm.com
hub.js:1086 Logged into account 1092072784852418562
hub.js:505 Dialog host: determined-cleric.minikosm.com:8443
hub.js:379 Scene URL: https://192.168.1.127:8080/cors-proxy/https://minikosm-01-assets.minikosm.com/files/27453223-f86a-422d-b128-93e19fa845ac.bin
gltf-model-plus.js:42 Releasing uncached gltf https://192.168.1.127:8080/cors-proxy/https://minikosm-01-assets.minikosm.com/files/27453223-f86a-422d-b128-93e19fa845ac.bin

**Additionally**
The quick start on github doesn t work for me.

Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1141)

**Comment by ErikOrjehag** [comment]
I have the same issue
