### ISSUE TITLE
"Enter in VR" prompts to download Firefox in the case that vr hardware is not found

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#482]
https://i.gyazo.com/72f9beace96c965f2a13c6ae8e4917d4.png
When using Firefox, if you try to click "Enter in VR" when you don't have any VR devices installed (e.g. `navigator.getVRDisplays()`) finds nothing), the message that pops up prompts to download Firefox. 

This should probably be a different message in this case, or we should not show this button at all if no vr device is found.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/483
