### ISSUE TITLE
DigitalOcean / Hubs Cloud user can't join any rooms.

### ISSUE THREAD

**Issue by safuyield** [mozilla/hubs#4844]
Hi,

I've tested out the marketplace template at: https://marketplace.digitalocean.com/apps/hubs-cloud-personal
I've succesfully created a room and I am able to join the room as admin:

However if I try to join the room as a logged in user or anonymous user I just get an error -> The scene failed to load..

**I am seeing the user joining the lobby and then it just hangs and it's connecting forever.**

I saw similar bug reports for the AWS marketplace so wondering if it's related to the older template DigitalOcean uses..

Nov 18 14:55:44 meta.safu.net bash[999]: reticulum.default@polycosm(O): 14:55:44.147 [info] JOINED ret in 149µs
Nov 18 14:55:44 meta.safu.net bash[999]: reticulum.default@polycosm(O):   Parameters: %{"hub_id" => "gh9tdFp"}
Nov 18 14:55:44 meta.safu.net bash[999]: reticulum.default@polycosm(O): 14:55:44.181 [info] JOINED hub:gh9tdFp in 33ms
Nov 18 14:55:44 meta.safu.net bash[999]: reticulum.default@polycosm(O):   Parameters: %{"auth_token" => nil, "context" => %{"embed" => false, "mobile" => false}, "hub_invite_id" => nil, "perms_token" => nil, "profile" => %{"avatarId" => "XDDBcxa", "displayName" => "Merganser-15778"}, "push_subscription_endpoint" => nil}

Could you please confirm if this issue is because of the specific template DigitalOcean Marketplace uses?
If yes, could you please provide steps how could we manually update the installation to a newer version of Hub Cloud?

You can check my created room here: https://meta.safu.net/

Thanks
<img width="1670" alt="Screenshot 2021-11-18 at 17 06 47" src="https://user-images.githubusercontent.com/84081868/142462974-29066864-4200-4a99-9b94-8f1a23f00cb1.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1161)

**Comment by safuyield** [comment]
I think the issue started after I've rebooted my server.
Where can I find/check if all my services are running OK?

**Comment by markusTraber** [comment]
I think that this is the same issue as #4404.

**Comment by safuyield** [comment]
Thanks for checking @markusTraber, could be indeed the filesize as I was able to load a smaller .glb file just now.
Is there any workaround for this? Maybe the VM can be tuned manually?

**Comment by markusTraber** [comment]
Lets continue in the other issue in future to avoid spreading information. But as of now, I only know about compressing the scenery, as described in my latest comment: https://github.com/mozilla/hubs/issues/4404#issuecomment-980237191

**Comment by matthewbcool** [comment]
closing as customizing glb file size should be a separate discussion
