### ISSUE TITLE
Putting the half body "Ready Player Me" avatar into Hubs.Mozilla, we found the avatar facial expression very vivid. However, it's NOT easy to find who is speaking in VR environment. We wonder if Mozilla can provide animation for the Ready Player Me avatar in highlighting the speaking avatar.

### ISSUE THREAD

**Issue by larrydnlee** [mozilla/hubs#4847]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1164)

**Comment by matthewbcool** [comment]
Closing this request for lack of specificity.

scale-audio-feedback/morph-audio-feedback can be used to create solutions.  This is a cross post from discord: https://discord.com/channels/498741086295031808/819203020604047380/912899100247224351

> 
> Maybe these will serve you better: https://mozilla.github.io/hackweek-avatar-maker/
>  
> You can customize avatars with the scale audio feedback component and get the effect you would like: https://youtu.be/A51eHOkR0IY?t=754
> also you can use morph-audio-feedback if you would like to add morphs (although this is more complex).
> More in the docs here: https://hubs.mozilla.com/docs/creators-advanced-avatar-customization.html

**Comment by Exairnous** [comment]
In addition to what @matthewbcool said, here are some links to discussions about visual audio feedback on name tags.

https://github.com/mozilla/hubs/issues/3110
https://github.com/mozilla/hubs/issues/2533
https://discord.com/channels/498741086295031808/819596227271852082/822160725723578377
