### ISSUE TITLE
URL fragments that deep-link to named waypoints don’t work when fast switching is enabled.

### ISSUE THREAD

**Issue by SV-AndreiC** [mozilla/hubs#4877]
**[Affected Versions]:**
- Firefox Release 94.02
- Chrome 96.0.4664.45

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- The Hubs Cloud stack is set up.
- Have https://hubs.mozilla.com/scenes/CQC6oC7 and https://hubs.mozilla.com/scenes/RjWMtwk/namedwaypointtest scenes imported in Hubs Cloud.
- Have a room created and opened with the first scene.

**[Steps to reproduce]:**
1. Go to preferences from the “More” button.
2. From “Misc” enable “Fast room switching” and dismiss .
3. Hover over the object on the left and click "Visit Room".

**[Expected results]:**
- The user should appear in the new room on the blue pad.

**[Actual results]:**
- The user lands between the 2 colored pads in the room.

**[Notes]:**
- When the “Fast room switching” option is disabled the user lands on the correct waypoint.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1179)

**Comment by Dayk0** [comment]
Hello, the bug still persists. Indeed, it would be interesting to solve this problem...
