### ISSUE TITLE
The Avatar is wrongly changed when logging out

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4901]
**[Affected Versions]:**
- Firefox Release 94.02
- Chrome 96
- Safari v15.1

**[Affected Platforms]:**
- Windows 10x64
- macOS BigSur v11.6.1
- Android 8

**[Prerequisites]:**
- Your Hubs Cloud stack is set up.
- Have a room created and opened.
- You are logged in into Hubs.

**[Steps to reproduce]:**
1. Click the 3 dot button to display the More Menu.
2. Click the "Log Out" button from the menu.
3. Observe if the avatar set is changed.

**[Expected results]:**
- The avatar is not changed.

**[Actual results]:**
- The avatar is changed.

**[Notes]:**
- The avatar is changed when logging out regardless if it was previously selected from the the Featured, My avatars or the Newest section.
- Attached is a screen recording of the issue:
![LogOutAvatar](https://user-images.githubusercontent.com/40061643/145213491-ba79c4cb-7a66-44fd-bfdd-58720577b1ab.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBSOLD-1190)

**Comment by emclaren** [comment]
I think this is working as expected, if you sign out you would  no longer have access to the information tied to your account (e.g. avatars)
