### ISSUE TITLE
Can't Render Texture on Mobile Device

### ISSUE THREAD

**Issue by AlbertWijaya1** [mozilla/hubs#4937]
**Description**
Cant view texture on mobile devices. It can only be viewed on PC

**Expected behavior**
Expected to see the texture.

**Screenshots**
![image](https://user-images.githubusercontent.com/40056466/145947970-287369e3-e0a9-496d-a36f-e63c3c771190.png)
Figure 1: Parameters of my scene showing all are optimized.

![image](https://user-images.githubusercontent.com/40056466/145948252-b95b9d2a-15fb-49a0-a66e-2fac614ce0ac.png)
Figure 2: Shows Black Texture.

![image](https://user-images.githubusercontent.com/40056466/145948156-e046086f-0cfb-4e85-986d-7726d8eaded3.png)
Figure 3: How it Suppose to Look Like.

**Hardware** 
 - Device: [Phone]
 - OS: [Android Verision 11]
 - Browser: [Chrome]

**Additional context**
My phone can view the the build-in scene made by hubs with larger size but can't view mine with low size on every aspect.
![image](https://user-images.githubusercontent.com/40056466/145948634-5e61af18-a702-49be-aee7-330cab0666a5.png)
Figure 4: The built-in scene made in hubs that can be viewed in my phone

![image](https://user-images.githubusercontent.com/40056466/145949193-e12cdf44-454b-40d4-ac72-0d485680ce90.png)
Figure 5: Live view opened on PC

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1213)

**Comment by Charlesc22** [comment]
Yes, we are also seeing this with certain scenes and trying to figure out what is causing it. For us, it seems to happen only on iPhones, and specifically, iPhones that have been upgraded to IOS 15, the scenes seem to work better on IOS 14 ironically. It still happens even if we Set Preferences > Misc. > Material Quality = High on the iPhone.

**Comment by AlbertWijaya1** [comment]
Hi! Thanks a lot for the response. So was it a bug? Is there nothing we can do about it?  Regards,Albert Wijaya Sent from Mail for Windows From: Charlesc22Sent: Wednesday, 15 December, 2021 1:55 AMTo: mozilla/hubsCc: AlbertWijaya1; AuthorSubject: Re: [mozilla/hubs] Can't Render Texture on Mobile Device (Issue #4937) Yes, we are also seeing this with certain scenes and trying to figure out what is causing it. For us, it seems to happen only on iPhones, and specifically, iPhones that have been upgraded to IOS 15, the scenes seem to work better on IOS 14 ironically. It still happens even if we Set Preferences > Misc. > Material Quality = High on the iPhone.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by gitvirtualmente** [comment]
> Yes, we are also seeing this with certain scenes and trying to figure out what is causing it. For us, it seems to happen only on iPhones, and specifically, iPhones that have been upgraded to IOS 15, the scenes seem to work better on IOS 14 ironically. It still happens even if we Set Preferences > Misc. > Material Quality = High on the iPhone.



Any information about this issue? I have the same problem. I tried everything and still sometimes (not everytime) textures show black on mobile. Thanks

**Comment by takahirox** [comment]
Looks like duplicated with #4954? Let's close this issue and move there because there are more many comments. Sorry for closing the issue made earlier.
