### ISSUE TITLE
[iOS] Audio got noisy after several minutes

### ISSUE THREAD

**Issue by jasoncks** [mozilla/hubs#4948]
**Description**
Audio from avatar produce noise after entered the room for a few minutes in iOS 15

**To Reproduce**
1. Create a new room
2. Enter the room with at least 2 users
3. Enable voice chat of one person
4. Wait for several minutes to observe the noise problem happened.

**Expected behavior**
No noise is heard even runing for several minutes

**Screenshots**
Video capture:
[Click To See](https://drive.google.com/file/d/1wponMhldoXyR3lGgFqCRoy2FUfoJATxX/view?usp=sharing)

**Hardware** 
 - Device: iPhoneX
 - OS: iOS 15.1
 - Browser: Safari

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1220)

**Comment by jasoncks** [comment]
Addition information:
Below device also have the same problem.
It just take a minute and noise occurred.

**Hardware**
- Device: iPhone 7Plus
- OS: iOS 15.2
- Browser: Safari

**Comment by takahirox** [comment]
Hi, thanks for the problem report.

Probably duplicated with #4411, so let's close this issue and move there. Please reopen if the problem looks different from #4411.

Regarding the distorted audio noise problem on iOS, it seems to happen on relatively old iOS devices. There seems to be no workaround what we can do on our ends. We already reported the problem to webkit devs. What we can advice so far may be wait until they fix or try with newer iOS devices.
