### ISSUE TITLE
Video objets don't show play button

### ISSUE THREAD

**Issue by tardiskun** [mozilla/hubs#4952]
**Description**
The video objets don't show a play button, even if the are from youtube or uploaded to hubs

**To Reproduce**
1. Go to  room with video objets
2. Try to play the video (without autoplay, of course)

**Expected behavior**
Video objets must show a play button.

**Hardware** 
 - Device: [Desktop, iPad]
 - OS: [Windows 10, Windows 11 and iPadOS]
 - Browser: [Firefox, Chrome and Safari]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1223)

**Comment by matthewbcool** [comment]
Can you confirm the video has controls enabled? 

I tried importing an mp4 and controls appeared as expected in Chrome.

**Comment by tardiskun** [comment]
> Can you confirm the video has controls enabled?
> 
> I tried importing an mp4 and controls appeared as expected in Chrome.

Yes, the video has controls enabled. 

I found was wrong. Too many objets in the room. 
When you have 20 3d objets and 1.000 (less or more) images with billboard activated, the controls in videos don't show. 

I think this is not a bug really, only a limitation from the hubs itself. 
Sorry if you lost time with this. 

The ticket can close if you wish.

**Comment by matthewbcool** [comment]
Thank you for your help documenting this.
