### ISSUE TITLE
Lose connection of the hubs room when taking off quest2 headset

### ISSUE THREAD

**Issue by JapanRain** [mozilla/hubs#4964]
I entered a room in hubs with my quest2 headset.
Sometimes I just lift my headset or take it off. Then I lost connection of the room and had to enter the room again....
(This is not because of the sleep mode of quest2, since I set the time to 4 hours, long enough.)
Anyway to solve this problem?
When grabbing a tea or going to toilet, I want my avatar still in the room so I don't need to enter the room all the time...
Thank you!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1226)

**Comment by matthewbcool** [comment]
Currently, if you exit immersive mode and put the headset to sleep with disable auto-exit enabled: 
![image](https://user-images.githubusercontent.com/4493657/168169619-31a8160a-4129-41db-9cf4-91656d5cde85.png)
You should remain in the room when you return to your headset (you would then still re-enter immersive mode but you won't need to rejoin the room)

Thank you for your report and please feel free to make another issue or feature request if you find this issue persists.
