### ISSUE TITLE
Users Permissions per room 

### ISSUE THREAD

**Issue by Pattersonbl2** [mozilla/hubs#5004]
### Discussed in https://github.com/mozilla/hubs/discussions/4956
The community is requesting that a feature be added to control user permission at the room level. This would prevent people from entering rooms that are not allowed to them. 
<div type='discussions-op-text'>

<sup>Originally posted by **stealink** December 18, 2021</sup>
Hello, 
I want to allow access to a room to certain users but not to others . 
EX : 
I have room A with user 1 and I don't want user 1 have access to room B but the user need to login before .
thx for your reply 

</div>

**Comment by matthewbcool** [comment]
Closing this as a hubs cloud feature request (since this feature is for admins on hubs cloud as I understand it but welcome @stealink to give us more information details about what they expect). Will follow up with @stealink and request more information.
