### ISSUE TITLE
As a room Owner, Mute/MuteAll no longer mutes participants.

### ISSUE THREAD

**Issue by matthewbcool** [mozilla/hubs#5062]
**Description**
Selecting a person from the people menu and muting them does not mute participant. (Chrome) 

**To Reproduce**
1. Open people menu with multiple participants in room
2. Click on person name
3. Select 'Mute'

**Expected behavior**
participant should be muted

**Hardware**
 - Device: [Desktop]
 - OS: [MacOs]
 - Browser: [Chrome]

**Additional context**
Regression, previously these features have worked for me.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1258)

**Comment by Dayk0** [comment]
I tried again today and the "mute microphone" button doesn't work. Unable to mute participants' microphones.

**Comment by matthewbcool** [comment]
This issue has been resolved: https://github.com/mozilla/hubs/commit/a185073540da114dba73469e579e1b6d586d9d69

Confirmed room owners can once again mute participants.
