### ISSUE TITLE
The camera object does not have a record button on Safari

### ISSUE THREAD

**Issue by SV-AndreiC** [mozilla/hubs#5065]
**[Affected Versions]:**
- Safari 15.2

**[Affected Platforms]:**
- iOS 15.2
- macOS BigSur v11.6.2

**[Prerequisites]:**
- The Hubs Cloud stack is set up.
- Have a room created and opened

**[Steps to reproduce]:**
1. Spawn a camera object from the Place button.
2. Observe the buttons on the camera.

**[Expected results]:**
- A record button is present on the camera. 

**[Actual results]:**
- No record button is present on the camera.

**[Notes]:**
- Attached is a screenshot of the issue:
![camera](https://user-images.githubusercontent.com/93765706/151777883-3973ef19-ebf7-4432-8524-8718f7a18bf9.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1262)

**Comment by brianpeiris** [comment]
This is expected behavior. Safari does not support the APIs we use for the video capture feature.
