### ISSUE TITLE
Video texture target does not work in Chrome

### ISSUE THREAD

**Issue by keianhzo** [mozilla/hubs#5069]
**Description**
Video texture target does not work in Chrome only. There no errors in the console.

**To Reproduce**
1. Go to a scene with a video texture target or use the attached glb
4. The video texture doesn't show

**Expected behavior**
The video texture should be visible

**Screenshots**
<img width="611" alt="Screen Shot 2022-01-31 at 22 36 25" src="https://user-images.githubusercontent.com/837184/151877337-5aed6483-a2c0-4f03-a29a-1b9ead49596a.png">

**Hardware** 
 - Device: Desktop
 - OS: MacOs
 - Browser: Chrome

**Additional context**
You can use this GLB to reproduce the issue: [SimpleMIrror.glb.zip](https://github.com/mozilla/hubs/files/7974418/SimpleMIrror.glb.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1263)

**Comment by matthewbcool** [comment]
duplicate and confirmed here https://github.com/mozilla/hubs/issues/5061

**Comment by netpro2k** [comment]
closing as duplicate
