### ISSUE TITLE
Object manipulation improvements for 3dof + mouse + touch

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#509]
Idea ticket for improving obj manipulation (no idea how hard these are to implement, just writing ideas.)

For 3dof:

- For object rotation, use the controller roll. (The yaw and pitch I'm assuming are driving the cursor)

- For scaling, extend the "move object far and away" interaction so that if you drag up on the touchpad the object moves away, but at a max distance it begins scaling up. (And dragging down will move the object towards you again.) Opposite for scaling down, drag the object towards you and once its within a certain distance further dragging scales it down (and dragging away moves it away from you.)

For mouse:

- For rotation, consider either a right click-drag to rotate the object around the screen-space Z-axis, or if that's hard input-wise, a click-drag to begin manipulation and then depress the RMB to activate/deactivate rotation mode when you drag left right.

- For scaling, same as 3dof except using the mouse wheel.

For touch:

This might be hard to do, but basically once I start dragging an object with my finger, if I touch down with another finger that can be used to pinch/unpinch to scale, and two-finger rotate to rotate.

**Comment by j-conrad** [comment]
> drag up on the touchpad the object moves away, but at a max distance it begins scaling up.

My concern with this design is that it might need some sort of feedback to show the user where the threshold is-- especially because the object will appear smaller as it moves away from you so knowing it's now actually scaling up will be difficult to discern. This is even more difficult on a 2d screen.
Also, users may use the mouse wheel as a way to pass objects to other users. So now if the other user is located just beyond that threshold, the object will scale up when that was never the owner's intention.

**Comment by gfodor** [comment]
interesting, I guess i'm not sure how it will feel in both 2d or 3d. on 2d it will visually get smaller as you move it away and then get bigger as you continue to scroll upwards (as it scales up.) I think visually it might work out OK because its position in screen space will stay the same as it gets bigger. It may appear like you are moving it towards your face though -- I think we won't know for sure until we try it. I suspect it will work fine in stereo.

**Comment by gfodor** [comment]
also if it wasn't clear, once you hit the distance cap it will fix the object in place as it scales up. so it won't be getting smaller or take up the area, it will visually increase in size at that point. this, coupled with the fact that you are dragging upwards may be enough cues to drive home that you're *increasing* distance, and then *increasing* size.

**Comment by gfodor** [comment]
main thing still missing is scaling on 3dof. horizontal swipe seems like the best option

**Comment by gfodor** [comment]
all done!
