### ISSUE TITLE
How user can see its own Avatar

### ISSUE THREAD

**Issue by jayvs6341** [mozilla/hubs#5097]
**Is your feature request related to a problem? Please describe.**
I am as a user, feel that, I should see my own avatar. That will help me to navigate the Met averse more live.

**Describe the solution you'd like**
I am as a user, feel that, I should see my own avatar. That will help me to navigate the Met averse more live.

**Describe alternatives you've considered**
I am as a user, feel that, I should see my own avatar. That will help me to navigate the Met averse more live.

**Additional context**
I am as a user, feel that, I should see my own avatar. That will help me to navigate the Met averse more live.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1271)

**Comment by matthewbcool** [comment]
Thank you for submitting your request. Closing for now since this requests ignores current solutions (inspect, in-room camera). Feel free to make a more specific request in the future with these features in mind.
