### ISSUE TITLE
[hubs cloud]Avatar camera no longer works

### ISSUE THREAD

**Issue by Dayk0** [mozilla/hubs#5130]
Hello,

Trying the avatar camera on my hubs cloud server, it doesn't work. My colleagues don't see me while on mozilla hubs it works.

Cordially.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBSOLD-1274)

**Comment by matthewbcool** [comment]
Will need more information to investigate... Which camera avatar are you referring to? Steps to repro?

**Comment by Dayk0** [comment]
@matthewbcool, I just tried again with mozilla hubs and I have the same problem. Here are screenshots.

So, precisely, here is the problem:

-User A uses the camera avatar, he activates it.
-User B connects to the room and he sees the activated camera avatar but it is black. It does not work.
-User A refreshes the page then re-enters the room and activates the camera. It works.
-If user B refreshes the page and user A remains in the room with the camera avatar activated, user B will see the camera avatar in black again.

In short, the camera avatar does not work when the user using it is present in the room first. The user using the camera will need to re-enter the room to operate it.

![camera-1](https://user-images.githubusercontent.com/72855344/154024301-2176f37a-76ae-4677-8501-53c0a5c9ffa8.png)

![camera-2](https://user-images.githubusercontent.com/72855344/154024299-4942ca6d-dd5a-4e9c-9dee-215d379f124b.png)

![camera-3](https://user-images.githubusercontent.com/72855344/154024292-62484237-eb7c-4075-87a6-d99b2717e415.png)

![camera-4-deconnected](https://user-images.githubusercontent.com/72855344/154024286-696bacad-83e9-426b-857e-40c4d1eda267.png)

![camera-5-reload-camera-user](https://user-images.githubusercontent.com/72855344/154024277-547ae63c-4f2c-4c1e-ad3e-e6e80d964309.png)

**Comment by SV-AndreiC** [comment]
@Dayk0 are you still experiencing this behavior? 
I tested avatar cameras on Windows Firefox(97.0), Android Chrome(98.0.4758.87) and iOS Safari 15.3 and could not reproduce the behavior.

**Comment by SV-AndreiC** [comment]
@Dayk0 I was able to reproduce the issue using the scenario you described above, however for me the camera is sometimes transparent not black and even if user A refreshes the page, the feed will sometimes not work
![avatar](https://user-images.githubusercontent.com/93765706/154028857-d194a5b3-1891-4ed2-ba94-b185e0772392.jpeg)
.
