### ISSUE TITLE
Server Not Found

### ISSUE THREAD

**Issue by Dayton2028** [mozilla/hubs#5131]
**Description**
Can't find any server

**To Reproduce**
I started up Reticulum/Hubs/Hubs admin/Dialog/Spoke locally, and when I navigate to https://hubs.local:4000/admin#/server-setup, it will show Not Found, just as below image.

**Expected behavior**
Since I have started Recticulum server locally, shouldn't it display the server I've startup locally? Or anything wrong with me? Here just shows the servers of Amozon or DOs?
May anyone give me any tips for setup server locally here? Very appreciated.

**Screenshots**
Please see screenshot here
![screenshot-no server](https://user-images.githubusercontent.com/98076577/153908045-45b34d51-efff-481d-98ee-376e57ce8fa9.png)

**Hardware** 
 - Device: PC/4CPU/8GMem/100G HD
 - OS: Ubuntu 20
 - Browser: Firefox
 - 
Thank you very much.

**Comment by cherry-fan** [comment]
> **Description** Can't find any server
> 
> **To Reproduce** I started up Reticulum/Hubs/Hubs admin/Dialog/Spoke locally, and when I navigate to https://hubs.local:4000/admin#/server-setup, it will show Not Found, just as below image.
> 
> **Expected behavior** Since I have started Recticulum server locally, shouldn't it display the server I've startup locally? Or anything wrong with me? Here just shows the servers of Amozon or DOs? May anyone give me any tips for setup server locally here? Very appreciated.
> 
> **Screenshots** Please see screenshot here ![screenshot-no server](https://user-images.githubusercontent.com/98076577/153908045-45b34d51-efff-481d-98ee-376e57ce8fa9.png)
> 
> **Hardware**
> 
> * Device: PC/4CPU/8GMem/100G HD
> * OS: Ubuntu 20
> * Browser: Firefox
> 
> Thank you very much.

hi，have you solved this problem?

**Comment by maxmetagravity** [comment]
I HAVE THE SAME PROBLEM , HAVE YOU SOLVED THE PROBLEM?

**Comment by Gates-456** [comment]
I HAVE THE SAME PROBLEM , HAVE YOU SOLVED THE PROBLEM?

**Comment by brianpeiris** [comment]
The "Server Settings" page is meant for Hubs instances running on AWS, it cannot be used for local setups. These community-built instructions from @albirrkarim may also help: https://github.com/albirrkarim/mozilla-hubs-installation-detailed

**Comment by niitbeo** [comment]
Has anyone solved this problem?

**Comment by monukbizsoft** [comment]
I am facing same issue on local setup

**Comment by monukbizsoft** [comment]
Hi

Has anyone solved this problem?

I am facing the same problem even after setup on live server.

Thank you
