### ISSUE TITLE
[iOS] 'Enter in VR' not an option. 

### ISSUE THREAD

**Issue by matthewbcool** [mozilla/hubs#5166]
**Description**
Not sure if this is a regression or if this is a known existing limitation but it seems it's not possible to use 'Enter on Device' ---> 'Enter in VR' on iphones.

**To Reproduce**
1. 'Enter on Device' in the room entry flow
2. Not there 'Enter in VR' is not an option

**Expected behavior**
On android devices we see 'Enter in VR'. Is this the expected behavior on iOS? Tested in chrome and safari.

**Hardware** 
 - Device: iphone
 - Browser: safari, chrome

**Comment by Elevons** [comment]
I just had a friend try this with their iPhone 13 and it doesn't work there either. It keeps sending people to the .link address with a code, but then says "could not find code". They tried three times and it didn't work any of the times. One time it just sent them back to the join page.

**Comment by takahirox** [comment]
Confirmed that no "Enter in VR" on my iPhoneX Chrome while it appears on my Samsung S8+ Chrome.

**Comment by takahirox** [comment]
iOS doesn't seem to support WebXR or WebVR API. I checked the compatibility of them on my iPhoneX Chrome/Safari at

https://immersive-web.github.io/webxr-samples/
https://webvr.info/samples/

So probably no "Enter in VR" on iOS is expected. Let's close this issue. Please reopen if I'm wrong.

By the way I heard rumor that iOS (Safari?) will support WebXR likely soon. If it lands, we should see "Enter in VR" even on iOS.
