### ISSUE TITLE
Webcam Video Avatars Not Appearing Until Sharing Restarted

### ISSUE THREAD

**Issue by dylan-fox** [mozilla/hubs#5182]
**Description**
When joining a room in which someone is using a webcam video avatar, I only see a black screen until they stop and restart their video.

**To Reproduce**
 - Person A equips a webcam avatar and starts video as per https://twitter.com/mozillahubs/status/1369291386915225605 
 - Person B enters and tries to view person A's avatar.
Note that I could view their regular webcam feed as an object even upon refresh without the need to reshare - this only affected the webcam video avatar.

**Expected behavior**
Users should be able to see webcam avatars immediately upon joining.

**Screenshots**
![image](https://user-images.githubusercontent.com/5995674/155398597-0c096103-cd2c-4ffb-8adf-1c8618390baa.png)
Left browser just rejoined; right browser had been in already when camera was shared.

**Hardware** 
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
This was tested in the context of sign language accessibility, so please add an Accessibility label.

**Comment by Dayk0** [comment]
Same problem on my side. I also reported the bug previously: https://github.com/mozilla/hubs/issues/5130

**Comment by kursr** [comment]
Same problem here. 
We have 2 AWS hubs-cloud instances and both are having this issue with Avatar Cameras ever since we did a full Hubs Client / AWS stack update.

**Comment by gitvirtualmente** [comment]
Same problem here. Only works with Firefox but doesn't work with chrome. Any updates/solution? Thanks
![image](https://user-images.githubusercontent.com/14872505/160453171-b6b23eed-954f-4737-9122-4c686559e7c3.png)

**Comment by matthewbcool** [comment]
Thanks to all for the reports. The Chrome issue might be resolved with the video-texture-target chrome fix coming in the April release of hubs cloud that has been live on hubs.mozilla.

**Comment by kursr** [comment]
Thanks Matt. Will chery pick that one and fetch it back in my client. Can't believe I did not see it before. DOH!

**Comment by matthewbcool** [comment]
was not able to repro in Chrome, marking resolved.
