### ISSUE TITLE
Enabling joysticks requires the web page reload

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#5185]
**Description**

**To Reproduce**
1. Enter a room
2. Click on 'Menu" - "Preferences" - "Controls"
3. Check "Enable left on-screen joystick for moving around" and "Enable right on-screen joystick for looking around" checkboxes
4. Confirm that "the joystics don't appear even if you tap left/right bottom of the screen"
5. Reload the page and enter the room again
6. Confirm that "the joystics appear if you tap left/right bottom of the screen"

**Expected behavior**
The joysticks appear after enabling them on Preferences even without the page repload. Or if it actually needs reloading, the reload require message should appear.

**Hardware** 
 - Device: Phone (Samsung S8+)
 - OS: Android
 - Browser: Chrome 98

**Comment by takahirox** [comment]
This line causes an error

https://github.com/mozilla/hubs/blob/d038beb4fed73a4fa8d4891f4454a7c09ec1a3fa/src/components/virtual-gamepad-controls.js#L5

`referenceEl.parentNode` is `null`.

**Comment by cornelionce** [comment]
The page refresh is no longer needed when the joysticks are enabled/disabled.
