### ISSUE TITLE
env meta tags are not generating when deploy custom client

### ISSUE THREAD

**Issue by baechoofarm** [mozilla/hubs#5191]
### Discussed in https://github.com/mozilla/hubs/discussions/5174

<div type='discussions-op-text'>

<sup>Originally posted by **baechoofarm** February 23, 2022</sup>
### **meta tags before deploy**
![image](https://user-images.githubusercontent.com/9635450/155179078-c64ab0cf-69f7-49dd-ad64-76fc8a02123a.png)

### **after deploy**
![image](https://user-images.githubusercontent.com/9635450/155179260-729335fa-3e24-4955-bf29-2d9ac01427af.png)

When I deploy my custom client (based on aws), no env meta tags are generated.
So... my admin pages don't work after deploy. (if I undeploy, it works)

How can I do?
</div>

**Comment by matthewbcool** [comment]
Closing this issue and will discuss in https://github.com/mozilla/hubs/discussions/5174 Thank you for your question!
