### ISSUE TITLE
How to change color blue hilight when hover object

### ISSUE THREAD

**Issue by Sawher1999** [mozilla/hubs#5202]
I want to change color from blue to other color but I cann't find file to edit them.

![messageImage_1646290228182](https://user-images.githubusercontent.com/89853664/156512238-8c555c57-4b9c-4476-898b-c46854fe717e.jpg)

![messageImage_1646290213647](https://user-images.githubusercontent.com/89853664/156512254-5606b7b6-718c-4ad7-9228-288f89a808e4.jpg)

**Comment by matthewbcool** [comment]
This is a great question to ask in the Mozilla Hubs community discord server: https://discord.gg/XDtnubgx 
If you are looking to make a feature request, please use the feature request template. Thank you!!


Closing this issue as a bug report
