### ISSUE TITLE
rotation and offset of interactables picked up from spawners is not preserved

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#521]
When picking up a duck from a spawner, the duck's offset and rotation from the hand/cursor always get set to the same position and rotation that is not where the hand/cursor originally grabbed the spawner from.

**Comment by misslivirose** [comment]
@InfiniteLee I poked around with spawners but wasn't sure what the expected behavior was relative to what I was seeing. Is this still an issue?

**Comment by johnshaughnessy** [comment]
This has been fixed. (A while back. Not sure when it was fixed, but I remember this bug.)
