### ISSUE TITLE
Improve shadows preferences

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#5212]
**Is your feature request related to a problem? Please describe.**

Currently the shadows preferences and their behaviors may be confusing.

There is "Enable Dynamic Shadows" option in the preferences. But unchecking it doesn't disable shadows but updating shadow maps only once when environement (scene) is loaded.

This may be confusing to users. They may expect shadows are simply disabled (for the performance) if the option is unchecked. But even if updating the shadow maps only once shadow map textures are fetched and shadow depth is compared for rendering objects which receive shadows every frame, except for low quality materials. It affects the performance.

**Describe the solution you'd like**

Simply disable shadows (`renderer.shadowMap.enabled = false`) if "Enable dynamic shadows` preference is unchecked. (And rename it to "Enable shadows"?)

The current behavior of disabled dynamic shadows seemed to be implemented when light map was not supported. Now we may be able to encourage to bake light or use light map instead.

**Additional context**

Maybe related in terms of improving the preferences menu for shadow #5210

**Comment by j-conrad** [comment]
The only concern I have is that 'Enable Shadows' as a Preference might lead users to think they'll see a dramatic change by turning them off--only to discover that lightmapped shadows (which we'll likely see much more of as the tech becomes more well known) are still showing when it's toggled.
As long as there's a clear tooltip or other sort of message to indicate that it's for "Dynamic" shadows, this seems like a good change.

**Comment by takahirox** [comment]
@j-conrad Thanks for the comment. Yeah, we need clear message, tooltip, or whatever for the behavior of "Enable shadows" to avoid the confusion. So we shouldn't rename "Enable Dynamic Shadows" to "Enable Shadows"? Or even if we keep the preference label may it still be confusing or unclear?

**Comment by j-conrad** [comment]
It might be more easily understood by a non-technical user to call it "Enable Real-time Shadows". I'd still have a tooltip or message that explains it from a more technical perspective-- maybe referring to them as 'dynamic' there.
