### ISSUE TITLE
Media content handled incorrectly if raw URL does not return correct content type

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#522]
If a URL returns content without a proper content type (`application/octet-stream`), media tools fails in a few cases:

This PDF fails to load in the client and we also send an "unknown" object type to telemetry:
https://github.com/nasa/pvslib/raw/5e52ed24e8dafab5ee1de8626f6fcd721a292547/vectors/doc/intersection-paper-eberly.pdf

On the otherhand, the rawgit url for the above URL behaves correctly:
https://cdn.rawgit.com/nasa/pvslib/5e52ed24e8dafab5ee1de8626f6fcd721a292547/vectors/doc/intersection-paper-eberly.pdf

This GLB loads correctly in the client, but sends an "unknown" object type to telemetry:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Avocado/glTF-Binary/Avocado.glb?raw=true

**Comment by johnshaughnessy** [comment]
To clarify, when we upload a `glb`, we 
- Send a `POST` request with the file to media API and get `expected_content_type : "application/octet-stream"`.
- Send a `POST` request with a url + index pair to the media API (with the `uploads-prod` url and `index: 0`) and get no `expected_content_type` (in fact we get `meta: null`).
- Send a `HEAD` request to farspark to try to get the content type, which returns `"application/octet-stream; charset=utf-8"`

**Comment by netpro2k** [comment]
Other than having a simple fallback to looks for some known file extensions on the input url, I don't think its really worth us trying to support missconfigured servers (including our own)

**Comment by brianpeiris** [comment]
To be clear, I wasn't implying that this should be fixed in the client. It should probably be fixed in farspark/reticulum (I just put the issue here for visibility). But I would argue that we should probably support servers that don't serve the right content type since it's nice to be able to use a github url directly. I think this might also help with other file hosts like dropbox, mediafire, etc.

**Comment by brianpeiris** [comment]
To be clear, I wasn't implying that this should be fixed in the client. It should probably be fixed in farspark/reticulum (I just put the issue here for visibility). But I would argue that we should probably support servers that don't serve the right content type since it's nice to be able to use a github url directly. I think this might also help with other file hosts like dropbox, mediafire, etc.

**Comment by gfodor** [comment]
these URLs are all now working for me. not sure if this is still an issue (we don't do file extension checking in reticulum, so maybe we still want to do it)

**Comment by misslivirose** [comment]
These links are working for me too now - should this stay open @brianpeiris ?

**Comment by brianpeiris** [comment]
Cool, it does look to be fixed. Also verified that the Avocado.glb link sends the right object type to telemetry 👍
