### ISSUE TITLE
Audio media (uploaded in Hubs) keeps turning off

### ISSUE THREAD

**Issue by jywarren** [mozilla/hubs#5232]
**Description**

I have uploaded audio and placed it around the scene, and pressed play, and for some scenes it remains on, but for others, when I return a few days later, all the audio is off. Nobody else has access so it seems to be turning itself off only in some scenes. I tried pinning it while it's playing but it doesn't seem to have an effect. 

**To Reproduce**
1. Upload an mp3 by dragging
2. Press "Play"
3. Pin the audio
4. Close the window
5. Return some time later

**Expected behavior**
I expect audio to be playing when i come back if I've left it that way. Or at least to behave consistently.

**Hardware** 
 - Device: Desktop
 - OS: Mac OS Monterey/Sierra, others
 - Browser: latest Chrome

**Additional context**

**Comment by SV-AndreiC** [comment]
@jywarren I tried multiple items with different rooms and audio files, but was not able to reproduce this issue. Are you still experiencing this? and since it's intermittent how often does this happen?

**Comment by jywarren** [comment]
I haven't seen it happen again, but am using the platform a lot and will let you know. I haven't added new audio media recently, and the older media i added seems to be playing normally (i.e. still on when i return to a room even weeks later) now. Thank you.
