### ISSUE TITLE
In Firefox, emoji images in the React menu blink and get fetched from the server every time the menu is opened

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#5265]
**Description**
When you open the React menu in Firefox, the browser makes requests for the emoji images every time. This causes the images to flash into view a few moments after the menu is visible. Incidentally, this also happens if the react menu is open while the chat panel is open, since it seems we re-render the emoji menu whenever the chat state changes as well, though arguably that is a separate issue.

This does not happen in Chrome.

**To Reproduce**
1. Visit a Hubs room
2. Click on the "React" button in the toolbar
3. See that the emoji images flash every time you open the menu

**Expected behavior**
The menu should not have to request the emoji images every time it is opened.

**Screenshots**
https://user-images.githubusercontent.com/79419/159054771-42da2bbc-1d4d-4081-8bb0-c1815a7cc7b0.mp4

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox

**Comment by brianpeiris** [comment]
This seems to be related to the crossorigin attribute we added to [ImageGridPopover](https://github.com/mozilla/hubs/blob/master/src/react-components/popover/ImageGridPopover.js#L22-L23). It's likely a browser bug, so we could try filing a bug against Firefox, though ideally we would reproduce this in a simpler test first to verify the actual issue. We could also figure out why we need the crossorigin attribute in the first place and remove it if possible, but that might be a more complicated approach.

**Comment by takahirox** [comment]
The reason why we added crossorigin attribute to ImageGripPopover

#3357
#4400

**Comment by brianpeiris** [comment]
Turns out Firefox only does this if you set the `crossOrigin` attribute after the `src` attribute. #5269 fixes this.

**Comment by brianpeiris** [comment]
Reported the issue against Firefox while I was at it: https://bugzilla.mozilla.org/show_bug.cgi?id=1760532

**Comment by takahirox** [comment]
Oh, interesting. Good catch, thanks.
