### ISSUE TITLE
When re-entering VR mode on Oculus Go, uses Google Cardboard mode

### ISSUE THREAD

**Issue by kwadroke** [mozilla/hubs#528]
When re-entering VR mode on Oculus Go, controller movement no longer works. Cursor is linked to headset instead of Controller. Seems to Enter VR as a Google Cardboard instead of using the Bluetooth Go Controller. You have to refresh the webpage and Enter VR again.

I have mentioned it on the 17th in the Weekly Friday 12pm PDT Hub chat.

-----
How to reproduce: 
Enter a Room in Hubs using the Oculus Go. Press the Back button to go to 2D/Android mode. Click on the Enter in VR which takes you back to VR mode. Cursor is synced to HMD instead of controller.

**Comment by netpro2k** [comment]
Thanks for filing this, will try and look into it today.
