### ISSUE TITLE
[Custom Clients] Room scene failed to load

### ISSUE THREAD

**Issue by pcristianSVM** [mozilla/hubs#5308]
[Affected Versions]:
All browsers

[Affected Platforms]:
Windows 10

[Prerequisites]:	
							
- Have a beta stack created and functional.
- Have GitHub, NodeJS and Visual studio installed on your machine.
- Have a GitHub account.

[Steps to reproduce]:

1. Run the following commands to setup your forked repo on your machine:

- git clone[ https://github.com/mozilla/hubs.git](https://github.com/mozilla/hubs.git)
- cd hubs
- git checkout qa-test

2. Run "npm run login"

3. Run:
- "npm ci" -this will take awhile
- "npm start"

4. Go to[ https://localhost:8080](https://localhost:8080/) create a room and run a short smoke test.

[Expected results]:
Room should be created

[Actual results]:
Room is not created

[Notes]:
Attached is a screenshot :

![image_2022_03_29T08_07_09_561Z](https://user-images.githubusercontent.com/99749076/160608387-84d7cab6-bd78-4690-ad87-e7f590b81c0f.png)

**Comment by brianpeiris** [comment]
Presumably this was resolved before the release. Would be good to update this bug with details about the resolution.

**Comment by johnshaughnessy** [comment]
Fixed by accepting the self-signed cert as shown in this guide: https://www.youtube.com/watch?v=l33b5GTrC5Q 

Thank you @robinkwilson !
