### ISSUE TITLE
Trigger Volume isn't working.

### ISSUE THREAD

**Issue by redhatpanda** [mozilla/hubs#5319]
I've been trying to use Mozilla Hubs for quite sometime now, although I'm new to this, I found that the **Experimental Feature: Trigger-Volume**, isn't working for any rooms I create. 

I found a couple of older scenes in which Trigger Volume seems to be working fine - https://hubs.mozilla.com/scenes/vTzZ9QG

Tried debugging the code as well, but couldn't find any relevant solution. Found a similar issue #5162 , where they tried to add a debugger, but it seems the code (trigger-volume.js) isn't executing at all.

**Comment by matthewbcool** [comment]
Thanks for sharing the scene and flagging trigger volume working in older scenes, this is a potentially very useful missing piece to debugging #5162  
Adding this discovery to the issue and closing this one as a duplicate.

**Comment by davidzdavidz** [comment]
Agree with redhatpanda. I want to add this: Old implementations of trigger volume work fine abut, **as soon as you do any update** to the same room in Spoke and then publish it again, **trigger volume stops working**. According to a developer I talked to, the trigger volume code isn't executing after the update.
