### ISSUE TITLE
Add record option for meetings

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/hubs#534]
Our local webxr community organises community calls using Mozilla Hubs.

It would be great if we have option to record these meetings.

**Comment by misslivirose** [comment]
From the recording perspective, we'd like to keep that to a user's choice of program to use for recording. However, we would like to make improvements to the camera options that are available [#1872] or make the lobby camera more flexible for framing and placement. In both cases, we'd like to keep this the user's choice over providing a custom recording option.
