### ISSUE TITLE
Oculus Quest 2 tracking error

### ISSUE THREAD

**Issue by teamVRtjg** [mozilla/hubs#5373]
**Description**
Entering any hubs room with oculus quest 2 produces heavy errors with 6dof tracking. The movement, which is normally controlled by turning your head around (3dof) is now controlled by both hand controllers. It is not possible to use hubs with oculus quest 2.
Probably the Problem is produced by the new hand tracking feature of oculus since the last firmware update.

tested with oculus browser an wolvic.

https://user-images.githubusercontent.com/104131242/164416459-316e1e0c-d2f8-4cfb-9005-7bdb9fe2fc73.mp4

**Comment by arpu** [comment]
what firmware version and OculusBrowser version do you have?

**Comment by ivanreyne** [comment]
In my case:

Oculus Browser: 20.2.0.4.51.364197385
Firefox Reality: 12.2

Software update system version: 26242800497100000
Version: 39.0.0.88.366.363807235
Runtime Version: 39.0.0.100.369.363650567

Everything on the Oculus Quest 2 is up to date as for the time of this post.

**Comment by teamVRtjg** [comment]
Oculus Browser:20.2.0.4.51.364197385
Version:39.0.88.336.3638.07235
Runtime Version:39.0.0.100.369.363650567

**Comment by rogerkenny** [comment]
I’m experiencing the same issue. It seems to me like the camera is attached to the controllers, and the renderer is rapidly switching between the left and right hands.

**Comment by cabanier** [comment]
Is it only in mozilla hubs?

**Comment by ivanreyne** [comment]
> Is it only in mozilla hubs?

Yes, as far as I can tell. I have tried a few other apps (youtube 360, the "firts steps" thingy, bigscreen, the 3d sketch thing, etc) and the only one showing the problem is Hubs. As @rogerkenny pointed out it seems that Hubs is tracking the controllers instead of the headset for direction. But it is also not really doing it well because even if you try to move using the controllers for direction with careful hand movements it is also doing all kinds of strange jumps and flickers.

**Comment by rogerkenny** [comment]
> Is it only in mozilla hubs?

The rest of the system seems fine. I haven’t tested any other WebXR experiences yet but I will report back if I do.

**Comment by rogerkenny** [comment]
@cabanier  just tested several other WebXR and they all seem fine. Even the Mozilla HelloWebXR worked well.

**Comment by fearguyQ** [comment]
Her is my version info. I am also experiencing the bug

Oculus Browser: 20.2.0.4.51.364197385

Software update system version: 24721900527300000
Version: 38.0.0.63.727.351486028
Runtime Version: 38.0.0.82.728.356477935

**Comment by takahirox** [comment]
Thanks for the problem report. We confirmed the problem and are investigating it.

**Comment by cabanier** [comment]
> Thanks for the problem report. We confirmed the problem and are investigating it.

Please let us (Meta) know what changed on our site that broke this.

**Comment by takahirox** [comment]
Other WebXR apps seem to be fine so I speculate there are some problems on our Hubs Client end... Anyways, I will let you know if I get to know anything.

**Comment by netpro2k** [comment]
Fix for this is being deployed now

**Comment by rogerkenny** [comment]
I can confirm it is fixed for me! Thanks.

**Comment by ivanreyne** [comment]
I can also confirm it is working fine now. Many thanks!
