### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by agriggs2** [mozilla/hubs#5396]
**Is your feature request related to a problem? Please describe.**
At the moment, there is no way for a user to request their data be removed from hubs. 

If a user reaches out to our team, and asks for their personal information be removed from our hubs instances, I can not comply without manually deleting every record of this users account and usage within the DB.

**Describe the solution you'd like**
Make it so I can easily remove all user data from the admin page.

**Describe alternatives you've considered**
The only alternative solution at this time is manually removing records from the DB.

**Additional context**
The Hubs cloud client needs to be GDPR compliant.

**Comment by rawnsley** [comment]
Hubs doesn't actually store email addresses on the server, just a hash of the email address. I think the name might be stored in the browser as well, but that needs to be confirmed.

If this is true, I think it's already compliant.

**Comment by agriggs2** [comment]
@rawnsley the hashed email/data can still allow someone to be indirectly identified.

From Article 4 of GDPR definitions: 
```
‘personal data’ means any information relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person;
```
https://gdpr-info.eu/art-4-gdpr/

I am not a lawyer but reading this makes me believe hashing the email is not compliant as I can search by emails in the admin page, which means they can be accessed and linked back to the end users PII. 

The identity table may also have the users PII such as name, which would be easy to link back to an account in the DB.

**Comment by rawnsley** [comment]
@agriggs2 after searching around a bit more I think you might be right. Authoritative legal opinion appears to be thin on the ground and there are no obvious rulings either way. If it isn't GDPR compliant it might also not be CCPA compliant.

I think Mozilla should get their lawyers involved as they will also be at risk as much as Hubs Cloud operators.

**Comment by misslivirose** [comment]
Thank you for filing this issue! While we cannot comment on regulatory compliance of individual Hubs Cloud operators, as you've identified, it is currently possible for a Hubs Cloud operator to delete user data through their access to the database. An issue for making this easier to do is tracked [here](https://github.com/mozilla/hubs-cloud/issues/79), and we are planning to start working on this soon. As such, I am going to close this as a duplicate, and when we have this feature implemented, it will be rolled out to Hubs Cloud operators on the usual release cadence!
