### ISSUE TITLE
Upgrade Three.js for better performance

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#5414]
**Is your feature request related to a problem? Please describe.**

`getProgramCacheKey()` in Three.js seems to be one of the performance bottlenecks.

![unknown](https://user-images.githubusercontent.com/7637832/167228289-7422b33c-3a8c-4ea3-862c-df85e808cc12.png)

**Describe the solution you'd like**

The performance of it seems to be improved in r136. Maybe worth to upgrade our Three.js to the latest 

https://github.com/mrdoob/three.js/pull/22960

**Additional context**

Three.js we use now is r133 based

**Comment by blairmacintyre** [comment]
Just talked with Rik about issues I'm having on Quest2, and he pointed to some fixes in 137 that will help perf (multisampling and layers) and solve my issues (custom shader related).  

I too am wondering if upgrading is feasible.

**Comment by takahirox** [comment]
Status: I'm working on upgrading Three.js but encountered some weird problem on compilation with `npm run dev`.

**Comment by takahirox** [comment]
@blairmacintyre Still a bit at testing phase but I made a PR #5488 . You can locally merge and test.

**Comment by blairmacintyre** [comment]
@takahirox  I'm not sure I can test this;  it's against the main branch of the hubs client, but we're using the hubs-cloud branch.
