### ISSUE TITLE
Fog no longer working in Mozilla Hubs

### ISSUE THREAD

**Issue by wkrisbux** [mozilla/hubs#5428]
**Description**
Yesterday I noticed that fog doesn't seem to be working anymore in Mozilla Hubs. I tested it out in my own custom room and in rooms that others have made that I found online, and in both cases fog wasn't showing up. It works in Spoke, but not in the actual room viewer. I have tried to view rooms on multiple different devices, but no matter how I access it, the fog is gone.

**To Reproduce**
To see what I am talking about go to any room that has fog. For example, this foggy lake: https://hubs.mozilla.com/scenes/RAYtAUO/foggy-lake
In the preview of the room the fog is gone and when you create a room with the scene the fog disappears.
Oddly, when you hit "Remix in Spoke" the fog appears again.

**Expected behavior**
I expect the fog to appear more or less the same in spoke as in the actual room, but the fog doesn't seem to be working at all.

**Screenshots**
![Screen Shot 2022-05-12 at 4 40 38 PM](https://user-images.githubusercontent.com/102252218/168184814-df2d6197-c6d7-4c61-a6f0-da8c18e6a9b8.png)
![Screen Shot 2022-05-12 at 4 41 11 PM](https://user-images.githubusercontent.com/102252218/168184818-72e31ddb-aea1-426c-986a-4b8a95f99159.png)

**Hardware**
 - Device: Multiple different Macbook Air Laptops
 - OS: Apple macOS Big Sur Version 11.6
 - Browser: Chrome

**Comment by qiangjiadong** [comment]
I got the same issues, in all my scenes fogs are gone, hope it can be fixed soon!

**Comment by qiangjiadong** [comment]
console.js:35 The `background` component is deprecated, use `backgroundColor` on the `environment-settings` component instead.
e.<computed> @ console.js:35
(anonymous) @ gltf-component-mappings.js:593
(anonymous) @ gltf-model-plus.js:272
g @ hub-3f86b0b3416b9fc4136a.js:1
o @ hub-3f86b0b3416b9fc4136a.js:1
Promise.then (async)
g @ hub-3f86b0b3416b9fc4136a.js:1
o @ hub-3f86b0b3416b9fc4136a.js:1
(anonymous) @ hub-3f86b0b3416b9fc4136a.js:1
(anonymous) @ hub-3f86b0b3416b9fc4136a.js:1
(anonymous) @ gltf-model-plus.js:239
traverse @ three.module.js:7165
traverse @ three.module.js:7171
(anonymous) @ gltf-model-plus.js:239
g @ hub-3f86b0b3416b9fc4136a.js:1
o @ hub-3f86b0b3416b9fc4136a.js:1
(anonymous) @ hub-3f86b0b3416b9fc4136a.js:1
(anonymous) @ hub-3f86b0b3416b9fc4136a.js:1
(anonymous) @ hub-3f86b0b3416b9fc4136a.js:1
(anonymous) @ gltf-model-plus.js:828
g @ hub-3f86b0b3416b9fc4136a.js:1
o @ hub-3f86b0b3416b9fc4136a.js:1
Promise.then (async)
g @ hub-3f86b0b3416b9fc4136a.js:1
o @ hub-3f86b0b3416b9fc4136a.js:1
console.js:35 core:schema:warn Unknown property `type` for component/system `fog`. 
console.js:35 core:schema:warn Unknown property `color` for component/system `fog`. 
console.js:35 core:schema:warn Unknown property `density` for component/system `fog`. 
console.js:35 The fog aframe component no longer exists.

/

I think above might be helpful

**Comment by netpro2k** [comment]
Thanks for the report. Looks like this regressed in #5361 fix should be out soon.

**Comment by netpro2k** [comment]
It is fixed in https://github.com/mozilla/hubs/pull/5438, should land this week
