### ISSUE TITLE
On custom glb scene, when using step rotation the front is not relative to where you rotated

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [mozilla/hubs#544]
I've tried this and **it only happens on custom glb** scenes.

Happens with:

- HTC Vive: Pad-Right, Pad-Left to rotate & Pad-Front to move
- PC: Q and E to rotate and W to move
- Android and iOS: With the nipples (virtual joysticks) Right nipple to rotate, left nipple to move

There are no errors in the console

This is the scene we're using:
https://hubs.mozilla.com/0rkgzucpsbo/mirv

**Comment by mauriciomartinez-itesm** [comment]
Upon further exploration on PC, this only happens when the rotation is backwards, that means that it has problems with 135°, 180° and 225°. Maybe it has something to do with negative degrees.

**Comment by mauriciomartinez-itesm** [comment]
I think this bug has been fixed now

**Comment by brianpeiris** [comment]
Hmm, this still seems to be a problem.

Steps to repro:
1. On desktop, visit https://hubs.mozilla.com/
2. In the room creation panel, click on "options"
3. Enter a name
3. Enter this URL: https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/VC/glTF-Binary/VC.glb
4. Create the room and enter it
5. Hit "E" four times
6. Try moving forward

You move backwards instead.

**Comment by brianpeiris** [comment]
That said, using Spoke to create a custom room is probably a better option at this point: https://hubs.mozilla.com/spoke

**Comment by gfodor** [comment]
closing for now, given Spoke
