### ISSUE TITLE
Media Tools: Downloadable Sketchfab links on iOS show up as broken

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#546]
Using Safari on iOS 11.4.1 on an iPhone 6s on home wifi:

Pasting a Sketchfab link from the web (not the mobile Sketchfab app) of a downloadable model shows up as a broken item. The same links work fine from desktop. Here's an example:  https://sketchfab.com/models/17cf0dbe4435434eb6e04394fd5bf7ae

**Comment by brianpeiris** [comment]
Fixed with https://github.com/mozilla/hubs-ops/commit/0a6a062e95d975703f079b184d6e072abd3994e3
