### ISSUE TITLE
Easier (max) resolution configuration in the preferences dialog

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#5466]
**Is your feature request related to a problem? Please describe.**

Users can configure max resolution in the preference.

![image](https://user-images.githubusercontent.com/7637832/170577798-0f876723-0817-45d6-b7bc-c48ff45d6c58.png)

But it has some problems.

* Unclear whether the resolution is in screen device resolution or CSS resolution (screen device resolution = CSS resolution * device pixel ratio)
* For generic users it's hard to know what numbers to enter even if they want to balance the performance and the visual quality

Might be related #5465

**Describe the solution you'd like**

Provides an easier UI to control the (max) resolution for performance - quality balance.

For example, resolution multiplier slide bar?

**Comment by cornelionce** [comment]
A resolution slider was introduced and it functions correctly. It is much easier for the end-user to change the resolution now.
