### ISSUE TITLE
glTF content from Sketchfab can memory leak

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#5469]
**Description**

glTF content from Sketchfab can memory leak

* [`scene.gltf` file content is loaded as blob to `fileMap["scene.gltf
]`](https://github.com/mozilla/hubs/blob/01d8e31dbdf1f300174f0fdc17dc9d5cb4f73580/src/workers/sketchfab-zip.worker.js#L9)
* [`fileMap["scene.gltf"]` has a new value](https://github.com/mozilla/hubs/blob/01d8e31dbdf1f300174f0fdc17dc9d5cb4f73580/src/workers/sketchfab-zip.worker.js#L15)
* [The blob resource is not released here](https://github.com/mozilla/hubs/blob/01d8e31dbdf1f300174f0fdc17dc9d5cb4f73580/src/components/gltf-model-plus.js#L675)

**Expected behavior**

No memory leak

**Hardware** 
 - Device: Any
 - OS: Any
 - Browser: Any

**Additional context**

Probably the easiest solution would be not load `scene.gltf` as the blob in the loop because it doesn't seem to be used.

```javascript
for (const fileName in zip.files) {
  if (fileName !== "scene.gltf") {
    fileMap[fileName] = zip.extractAsBlobUrl(fileName);
  }
}
```

**Comment by sarhugo** [comment]
Hi, I'll look into this issue

**Comment by sarhugo** [comment]
at PR I took another approach, extracting only required references
