### ISSUE TITLE
Media Tools: Sketchfab Mobile app links need to be formatted

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#547]
Using the Sketchfab mobile app on iOS (and probably Android):

Links from the Sketchfab app add a bunch of junk that make the links not work.
**On desktop, here is a model link:** https://sketchfab.com/models/17cf0dbe4435434eb6e04394fd5bf7ae

**On mobile, here is the same model link:** 
> Check out this scene in 3D and virtual reality on Sketchfab: Low Poly Spinning Heart! https://sketchfab.com/models/17cf0dbe4435434eb6e04394fd5bf7ae

Seems like we should probably just strip out the superfluous text ourselves when the user hits the 'create' button. Otherwise, we'd have to convince Sketchfab to change their formatting.

**Comment by gfodor** [comment]
i'm going to close this for now that we have media content search in place, which should hopefully limit the severity of this.
