### ISSUE TITLE
Avatar previews appear to be broken

### ISSUE THREAD

**Issue by cvanmeurs** [mozilla/hubs#5503]
**Description**
Avatar previews don't work in the preview URL links.

**To Reproduce**
1. Go to any Hubs room.
2. Click on 'More', 'Change Name and Avatar'
3. Click on 'Change Avatar'
4. Right-click on any avatar (such as a Featured avatar) and copy the link.
5. Paste the link into a new tab.

** Result **
The avatar preview area is blank and says "Loading failed, Please choose another avatar"

**Expected behavior**
The avatar preview window shows the avatar.

**Screenshots**
n/a

**Additional context**
The avatars still work when you choose one, and the 2D preview still works when you paste it into the Hubs room chat and press the magic wand button.

**Comment by netpro2k** [comment]
Looks like the GLTFLoader module is not loaded on avatar preview pages (its required in hub.js). It should probably be imported in every file we use it (gltf-model-plus and avatar-preview) instead.

**Comment by cornelionce** [comment]
Confirming this is now fixed and the avatar is displayed.
