### ISSUE TITLE
The Leave button function is not available in the Hubs Room.

### ISSUE THREAD

**Issue by jbshin-gemiso** [mozilla/hubs#5509]
After receiving the login request, close the window and click the Leave button to display the login request popup instead of the Leave popup.

1. Access the room without logging in.
2. Click the Custom Avatar button.
3. Close the login request popup.
4. Click the Leave button.
5. Problem occurred.

An attempt was made to leave the room via the Leave button, but the operation could not be performed due to continued login requests.

**Video**

[https://youtu.be/nayToVJSUgE](https://youtu.be/nayToVJSUgE)

- Please refer to the video to reproduce the bug.

**Comment by SV-AndreiC** [comment]
This is related to https://github.com/mozilla/hubs/issues/4810

**Comment by takahirox** [comment]
Thanks for the problem report. It should have been fixed with #5581
