### ISSUE TITLE
Issue with illumination on mobile and Quest 2

### ISSUE THREAD

**Issue by maccation2109** [mozilla/hubs#5519]
I created an exhibition with hubs. When I open the result with chrome/firefox on PC the illumination is exactly how it should be. But when I open the exhibition room on smartphone or with Oculus Quest 2 the illumination is completely missing. What can I do to make it work?

This is the illumination from PC (how it should be):
![issue_merz](https://user-images.githubusercontent.com/107889537/174675331-2fe09124-6441-4647-9d39-68853509f240.JPG)

This is the illumination from smartphone/Quest 2:
![WhatsApp Image 2022-06-20 at 22 43 45](https://user-images.githubusercontent.com/107889537/174675538-076c86c7-4ac6-40b7-a346-e107dbaa114f.jpeg)

I share the room with you to see what I mean:
https://hubs.mozilla.com/fmdRn9d/charming-those-terrain

**Comment by j-conrad** [comment]
Your lighting is there, but mobile devices like the Quest will have their Material Quality set to Low by default. In your Hubs Preferences, set it to High and you’ll see it look as expected.
Here is a screenshot from my iPhone, but it would look the same on Quest.
![6D5EC6FC-D277-4F5D-8D74-6165E9D2A1E6](https://user-images.githubusercontent.com/31968496/174686955-710efa75-1dbd-4fa7-b403-636ef2055b95.jpeg)

**Comment by maccation2109** [comment]
Thank you! It worked!
