### ISSUE TITLE
Varjo VR-3 controllers (knuckles) not displayed

### ISSUE THREAD

**Issue by tobiasweede** [mozilla/hubs#5526]
**Description**
Using a Varjo VR-3, the hands / controllers (Valve Index knuckles) are not displayed.

**To Reproduce**
Join any room with a VR-3 HMD paired with Valve Index knuckles. The hands are just not displayed. This makes interaction difficult / impossible.

**Hardware** 
 - Device: Varjo VR-3 HMD with  Valve Index knuckles
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
When I use the controllers with the Index HMD everything works as expected.
Varjo use their own OpenXR provider to interact with SteamVR.
I guess the issue is related to that.

**Comment by matthewbcool** [comment]
Thank you for this report!

**Comment by emclaren** [comment]
Does this work in other WebXR experiences?

**Comment by commonolithic** [comment]
VR controllers are not visible and do not function on the Varjo Aero and Vive wands either in Chrome. Tried WebXR sample above and same situation

**Comment by tobiasweede** [comment]
I tested other WebXR apps and ideed, controller are not working as well. 
Thus, I open a ticket in the WebXR repo and see if someone there has an idea what is wrong. 
Thank you for the hint!

**Comment by tobiasweede** [comment]
If you want to follow the issue in the WebXR repo: https://github.com/immersive-web/webxr/issues/1291
