### ISSUE TITLE
The scene failed to load.

### ISSUE THREAD

**Issue by ClarkDuck** [mozilla/hubs#5542]
**Description**
I couldn't run to create room in localhost dev mode.

**To Reproduce**
1. git reset --hard with [current master](https://github.com/mozilla/hubs/commit/0d395a8f7546672f1bd2d69d6aab59e3ddb0c061)
3. npm ci
4. npm dev
5. goto https://localhost:8080/
6. create room

**Expected behavior**
goto space scene view

**Screenshots**
![Screenshot from 2022-06-30 02-58-59](https://user-images.githubusercontent.com/92729925/176613416-e0b4bb5a-0fd9-46d7-a190-fc6a87d807ce.png)

**Hardware** 
 - Device: Desktop
 - OS: Ubuntu 22
 - Browser: Chrome

**Additional context**
 but it works on the cloud environoment only. it does not work in locally.

**Comment by matthewbcool** [comment]
for running Hubs locally, please see instructions here: https://github.com/mozilla/hubs#quick-start

> The backend dev server is configured with CORS to only accept connections from "hubs.local:8080", so you will need to access it from that host. To do this, you likely want to add "hubs.local" and "hubs-proxy.local" to the [local "hosts" file](https://phoenixnap.com/kb/how-to-edit-hosts-file-in-windows-mac-or-linux) on your computer:
> 127.0.0.1	hubs.local
> 127.0.0.1	hubs-proxy.local
