### ISSUE TITLE
Some scenes are darken

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#5562]
**Description**

A bug from https://github.com/mozilla/hubs/pull/5488

Some scenes (eg: gathering hall) are darkened.

**To Reproduce**
1. Go to https://hubs.mozilla.com
2. Create and enter a room
3. Switch to the Gathering hall scene
4. Confirm the scene is darkened than before

**Expected behavior**

They are not darkened.

**Screenshots**

![image](https://user-images.githubusercontent.com/7637832/177455090-2dbd0ba9-401f-46cf-a22e-7412f90cbc71.png)

**Hardware** 
 - Device: Desktop but probably Any
 - OS: Windows 10 but probably Any
 - Browser: Chrome but probably Any

**Additional context**

Probably gamma correction and/or lightMap stuff?

**Comment by takahirox** [comment]
Maybe the problem comes from this one https://github.com/mrdoob/three.js/pull/23613

Perhaps `material.lightMapIntensity *= Math.PI` for our `MeshBasicMaterial` would be an easy solution.

**Comment by cornelionce** [comment]
![image](https://user-images.githubusercontent.com/95618558/181727263-3575e930-9ef9-4c56-9ce9-0f8a29297e2e.png)

Confirming that the scenes are now lighter.
