### ISSUE TITLE
Pen's draw is white

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#5563]
**Description**

A bug from #5488 

Pen's color is white.

**To Reproduce**
1. Go to https://hubs.mozilla.com
2. Create and enter a room
3. Draw with pen
4. Confirm that draw is white

**Expected behavior**

The draw color should be what you choose (redden default?)

**Screenshots**

![image](https://user-images.githubusercontent.com/7637832/177455708-d01ee51d-0516-4fb0-9dac-f3409682a394.png)

**Hardware** 
 - Device: Desktop but probably Any
 - OS: Windows 10 but probably Any
 - Browser: Chrome but probably Any

**Comment by cornelionce** [comment]
Confirming that now the default color is displayed, instead of white.
