### ISSUE TITLE
Textures appear black and reflections are off on scenes with reflection probes

### ISSUE THREAD

**Issue by matthewbcool** [mozilla/hubs#5570]
**Description**
Environment map reflections appear incorrectly positioned and textures are black in high quality mode

**To Reproduce**
1. Go to https://hubs.mozilla.com/scenes/gHuNHUI/cliffsideretreat
2. Spawn in a camera, 3d object with PBR materials and observe

**Expected behavior**
Materials reflections/materials should be more consistently lit with env maps IBL.

**Screenshots**
![a40b7e6b-3303-405f-a191-717dcf9b6b4f](https://user-images.githubusercontent.com/4493657/177660851-ee5ea99d-96c4-406f-b3c8-5751b20baf9c.png)
<img width="452" alt="Screen Shot 2022-07-06 at 4 06 11 PM" src="https://user-images.githubusercontent.com/4493657/177660861-bd6c5fe3-b71a-410c-9d13-2f8b2449ca24.png">

https://user-images.githubusercontent.com/4493657/177660930-b621487d-167a-456a-853c-7318fe7f5ef9.mp4

**Hardware** 
 - Device: [MacBook M1]
 - Browser: [Chrome, Firefox]

**Additional context**
also tested on PC, windows Firefox

**Comment by takahirox** [comment]
Thanks for the problem report. Probably it was broken by the recent Three.js upgrade #5488. Let me investigate...

**Comment by matthewbcool** [comment]
Scenes with only an env map and no reflection probes don't seem to have this problem: https://hubs.mozilla.com/scenes/HsSRCtj/merry-go

**Comment by takahirox** [comment]
Yes, light probe is suspicious. And I noticed that commenting this line out makes the objects non-black https://github.com/mozilla/hubs/blob/d815053b1938068d54fda517c0f9af0760423b09/src/gltf-component-mappings.js#L613

**Comment by takahirox** [comment]
Reflection Probe texture (envMap) passed to WebGL is very suspicious...

Left r131, right r141.

![image](https://user-images.githubusercontent.com/7637832/178395093-eb211172-7ce1-4cb5-b59c-29d0dfd192fc.png)

**Comment by emclaren** [comment]
is this possibly related to https://github.com/mozilla/hubs/issues/5571

**Comment by takahirox** [comment]
Ah, probably I figured out the root issue finally. The reflection proble patch has conflicts in the logic (algorithm) with Three.js r141. This is the reason why I don't like applying patches to Three.js, it's very hard to figure out the root issue if having no conflict in the code but having conflicts in logic (algorithm)...

I'll share the details soon.

**Comment by takahirox** [comment]
If I'm right the root issue seems to be that switching environment maps after setting up WebGL programs in the renderer.

The renderer and other webgl modules generate shader code, get program cache, decides whether changing program, and so on, from material (and other objects) properties.

* https://github.com/MozillaReality/three.js/blob/7c6fb585ffa7737544871d2bbd4b0864c316f148/src/renderers/WebGLRenderer.js
* https://github.com/MozillaReality/three.js/blob/262eb259a1f92c3554a11353b7f52c13900f879e/src/renderers/webgl/WebGLProgram.js
* https://github.com/MozillaReality/three.js/blob/12f550e0f44f68e5b6c946dd242ee08e42d209e4/src/renderers/webgl/WebGLPrograms.js

Switching `envMap` after setting up them can cause mismatch.

More proper implementation may be setting up envMapA/B first and include them for decision of shader code generation, program cache, and so on.

**Comment by takahirox** [comment]
A workaround PR for Hubs Blender add-on has been opened https://github.com/MozillaReality/hubs-blender-exporter/pull/88

**Comment by takahirox** [comment]
Opened an issue for the root issue of Reflection Probe implementation https://github.com/MozillaReality/three.js/issues/66

We may close this issue after https://github.com/MozillaReality/hubs-blender-exporter/pull/88 lands.

**Comment by takahirox** [comment]
Closing this issue because https://github.com/MozillaReality/hubs-blender-exporter/pull/88 has been merged.

Please re-export your scenes if you encounter the problem.
