### ISSUE TITLE
Camera view is darkened

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#5571]
**Description**

Camera view is darkened. Probably it was broken by the recent our Three.js upgrade #5488

**To Reproduce**
1. Go to https://hubs.mozilla.com
2. Create and enter a room
3. Switch the scene to Gathering Hall
4. Place a camera
5. Confirm that camera view is darkened

**Expected behavior**

Camera view is not darkened.

**Screenshots**

![image](https://user-images.githubusercontent.com/7637832/177663340-528fa365-66a5-409a-befe-cf86bec9a486.png)

**Hardware** 
 - Device: Desktop but probably any
 - OS: Windows 10 but probably any
 - Browser: Chrome but probably any

**Comment by takahirox** [comment]
Maybe this is related https://github.com/mrdoob/three.js/issues/23251

**Comment by emclaren** [comment]
Could this be related? https://github.com/mozilla/hubs/issues/5572
