### ISSUE TITLE
video-texture-target is darkened since THREE 141 update

### ISSUE THREAD

**Issue by netpro2k** [mozilla/hubs#5599]
**Description**
Similar to #5571 video-texture-targets are also darkened.

**Screenshots**
![image](https://user-images.githubusercontent.com/130735/180087250-71259914-2925-4fe0-bcb9-001d2b104339.png)

**Additional context**
The fix we applied for camera tool isn't quite as easy to apply here since `onBeforeRender` has to be applied to each object that might have the `video-texture-target` material on it. Conceptually `video-texture-target` is a "material component" so it should apply to all objects using that material. In practice we can't actually add aframe components to materials, only objects, so it might be ok to just do the same trick and set `onBeforeRender` up on the mesh we grab the material from in `video-texture-target`.

**Comment by takahirox** [comment]
Three.js has a `material.onBeforeRender` hook.
