### ISSUE TITLE
  Hubs admin menu  ”Server Setting“ not available

### ISSUE THREAD

**Issue by maxmetagravity** [mozilla/hubs#5616]
Description
Can't open Hubs admin menu   ”SERVER SEETINGS“

To Reproduce
I started up Reticulum/Hubs/Hubs admin/Dialog/Spoke locally, and when I navigate to https://hubs.local:4000/admin#/server-setup, it will show Not Found, just as below image.
![153908045-45b34d51-efff-481d-98ee-376e57ce8fa9](https://user-images.githubusercontent.com/1259331/181161684-61e46cd4-30ad-4e5f-b380-e7c7b85ecf93.png)
<img width="1251" alt="截屏2022-07-27 12 30 17" src="https://user-images.githubusercontent.com/1259331/181161946-b8f1bdf2-6822-4fd3-bbb2-ec4310e8bc9c.png">

Expected behavior
Since I have started Recticulum server locally, shouldn't it display the server I've startup locally? Or anything wrong with me? Here just shows the servers of Amozon or DOs?
May anyone give me any tips for setup server locally here? Very appreciated.

Screenshots
Please see screenshot here
screenshot-no server

Hardware

Device: PC/4CPU/8GMem/100G HD
OS: Ubuntu 20
Browser: Firefox
Thank you very much.

**Comment by maxmetagravity** [comment]
someone have the same problem ？

**Comment by matthewbcool** [comment]
Welcome you to bring this discussion to the development channels in the Hubs community discord and try asking in [#dev-self-hosting](https://discord.gg/XjSuqVc6 ). Closing this issue since we are only tracking client bugs and feature requests in this repo.

**Comment by maxmetagravity** [comment]
Hey matt, not found [#dev-self-hosting] channel in hubs Discord

**Comment by matthewbcool** [comment]
@maxmetagravity please see #roles and opt-in/read the text to access the dev channels. There is much more useful information in #dev-self-hosting.  Thank you!
