### ISSUE TITLE
bitecs require fails on hubs-cloud branch

### ISSUE THREAD

**Issue by justincolangelo** [mozilla/hubs#5642]
**Description**
`npm run build` fails after fresh clone/branch of hubs-cloud is chosen. Master branch has the package in the package.json for bitecs. The hubs-cloud branch may either need to have that also installed, or networked-aframe and aframe packages patched for this difference. The peer dependency is not installed when using hubs-cloud branch.

```
ERROR in ./node_modules/aframe/src/core/a-entity.js
Module not found: Error: Can't resolve 'bitecs' in 'hubs/node_modules/aframe/src/core'
 @ ./node_modules/aframe/src/core/a-entity.js 15:48-65
 @ ./node_modules/aframe/src/index.js
 @ ./src/scene.js

ERROR in ./node_modules/networked-aframe/src/components/networked.js
Module not found: Error: Can't resolve 'bitecs' in 'hubs/node_modules/networked-aframe/src/components'
 @ ./node_modules/networked-aframe/src/components/networked.js 9:42-59
 @ ./node_modules/networked-aframe/src/index.js
 @ ./src/hub.js
```

**To Reproduce**
1. Clone Hubs
2. Use Node v16 or 14 or 12
3. Checkout hubs-cloud branch
4. `npm ci`
5. `npm run build`

**Expected behavior**
The code compiles.

**Hardware** 
 - Device: Macbook Pro M1 
 - OS: OSX 12.2.1
 - Browser: n/a

**Comment by netpro2k** [comment]
Hmm this is surprising, the version of aframe and network-aframe pointed at by the hubs-cloud branch should not yet have the bitecs dependency...

**Comment by justincolangelo** [comment]
> Hmm this is surprising, the version of aframe and network-aframe pointed at by the hubs-cloud branch should not yet have the bitecs dependency...

I thought so, too. It seems https://github.com/mozilla/hubs/blob/hubs-cloud/package.json#L111 and https://github.com/mozilla/hubs/blob/hubs-cloud/package.json#L78 are pointing at master which both require bitecs?

**Comment by netpro2k** [comment]
Right but [package-lock.json](https://github.com/mozilla/hubs/blob/hubs-cloud/package-lock.json) in the hubs cloud branch is pointing at a pre-bitecs commits for aframe and networked-aframe, so `npm ci` should be using those versions:
```
    "aframe": {
      "version": "github:mozillareality/aframe#2cd12e184bbf7e1ff7d2100d66064f50403405c1",
...
      },
...
    "networked-aframe": {
      "version": "github:mozillareality/networked-aframe#2c3c394e3f12a7d2cc68b193c0f7c94d709a46e8",
...
    },
```

**Comment by justincolangelo** [comment]
The node version is in fact on the older side, and yes, we did start using 12 at one point, then 14.19.3. The issue is definitely on us since we tried so hard not to use v10. I suppose this could be closed if that is the case. Losing a package lock shouldn't happen, but if it does it can be detrimental.

**Comment by netpro2k** [comment]
Just want to confirm it works for you if you run on the older node version. If it does then yeah, you won't have to live with it much longer as the release in a few weeks will include the node/webpack update. (You can probably pull form master and start using it now if you are feeling adventurous, I don't know of any backend changes that happened that would make it incomparable)

**Comment by justincolangelo** [comment]
I would close this one. I'll do that. I'd like to start using 16.16.0 from the master branch. Maybe we will try that soon. We have 14.20.0 working so if I have some time I'll branch and break it. Thanks for looking at this.

**Comment by wmurphyrd** [comment]
I hit this as well. If you `npm install` to add or update a package, npm may give you the latest master versions of aframe/naf due to the way they are listed in package.json. If this happens, `npm ci` should fix it
