### ISSUE TITLE
Hi everyone, is there a backup with the Mozilla Hubs ubnutu OS? Can you send a copy? Thank you so much

### ISSUE THREAD

**Issue by Gates-456** [mozilla/hubs#5662]
Hi everyone, is there a backup with the Mozilla Hubs ubnutu OS? Can you send a copy? Thank you so much

**Comment by brianpeiris** [comment]
Sorry, I don't think this is a valid issue. If you're looking for help. Try posting on the (Discussions board](https://github.com/mozilla/hubs/discussions) or our [Discord chat server](https://discord.gg/dFJncWwHun)
