### ISSUE TITLE
Pressing 'Mute All' - button should unmute the users in the room 

### ISSUE THREAD

**Issue by mMARUF** [mozilla/hubs#5685]
**OS:**
macOS Monterey version: 12.5.1

**Browser:**
Chrome Version 104.0.5112.101

**Steps to Reproduce:**
1) Go to https://hubs.mozilla.com/
2) Inside a room Press on the button **Mute All**  for the 1st time 
3) System mutes all the users
4) Now press **Mute All** button for the 2nd time 

**Actual Result:**
After Pressing the **Mute All** button 2nd time, the users are not unmuted 

**Expected Result:**
After Pressing the **Mute All** button 2nd time, the users should be unmuted

**Attachment:**

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/45368054/187293652-869e64dd-d7c2-4934-baa8-b9d66cef9653.gif)

**Comment by matthewbcool** [comment]
We don't want to be able to unmute anyone's mic without their consent/knowledge. If this was a feature, we would want a system around doing this responsibly since there are serious privacy risks. Welcome to make a feature request on this one but closing for now. Thank you!
