### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by 06erdem** [mozilla/hubs#5715]
**Description**
Links that work perfectly will sometimes not work. I am building a virtual conference Hub for a non-profit organization and the links are very inconsistent. Sometimes, the link for YouTube videos will not work. Sometimes YouTube videos will work but links directing users to other Hubs will not work. Sometimes, images/videos that are uploaded onto Spoke will not work and show as broken link.

**To Reproduce**
1. This is the link to the main conference room. https://hubs.mozilla.com/7cUA8ux/
2. When you enter, there will be numerous links scattered across the room. At the moment of posting, almost every link shows as broken. And sometimes, this will change. It is highly likely that when you try to reproduce the issue, you will see at least one not working link,
3. If you do not see any broken links upon entry, you can enter the main room under the banner 'Welcome to the Global Co Lab', then go into the room on your left or right (both have issues). On the walls, you should see that there are certain links that might not work. This is the area that has the most trouble for some reason. There are a couple links to other Hubs rooms which are my biggest concerns.

**Expected behavior**
I would hope that all links to work properly, except for YouTube links which I know Hubs has issues with, so I am removing those one-by-one anyway. Unfortunately, as this is an inconsistent issue, I know it is likely that 

**Screenshots**
![image](https://user-images.githubusercontent.com/76748586/190209409-84240e56-d7cb-4dc5-a9a5-eefaa44518f6.png)
![image](https://user-images.githubusercontent.com/76748586/190210804-47036d13-0154-44c4-83f8-fdb5311d6072.png)

**Hardware** 
 - Device: Laptop
 - OS:  Windows
 - Browser: Chrome and Edge

**Additional context**
As this issue is not easily reproducible, it might be hard for you to diagnose. I just re-entered the room like 5 times and the issue is resolved half of the time. 
Here is a screenshot of some of the console errors that come up (incase you struggle to reproduce the issue)
![image](https://user-images.githubusercontent.com/76748586/190212126-066df416-5c50-4a93-9cfd-9708fff5076a.png)
Thank you in advance for your attention.

Edit: I have attached a link in the conversation below where the issue is always persistent.

**Comment by matthewbcool** [comment]
Thank you for your work documenting this issue, very helpful.

**Comment by 06erdem** [comment]
Also, I think the issue is even more noticeable/reproducible here:
https://hubs.mozilla.com/hdwwaL9
This was a room that I used in a class I taught. All of the students' Hubs links were scattered around in this room. However, there are never more than 1/2 links working at the same time.

**Comment by matthewbcool** [comment]
@06erdem I noticed in the above scene you are using .link links for the rooms. Can you try replacing them with room urls?

**Comment by 06erdem** [comment]
@matthewbcool that's what I tried initially, but it still caused errors.

I just did some testing again and weirdly enough all links work perfectly when I do that AND put https:// in-front of all links, This is a really useful solution that I can't exactly understand why it works, because links work without https:// as well as with the .link links when there's only a couple links in the room, but they stop working when there's more than 2-4.

Thanks for the suggestion! I'll implement this in all of my rooms from now on.

**Comment by matthewbcool** [comment]
that makes sense to me. I believe we need to account for .link @tanfarming

**Comment by karenstritz** [comment]
I'm getting the issue with YouTube videos working sometimes and becoming broken. I checked my links and I'm using https://. I noticed after one YouTube link broke, I opened that scene in Spoke and see an error message that I never saw before: 

![image](https://user-images.githubusercontent.com/7530205/210015717-9996b97d-2740-4b12-a025-4c0b5f10cd25.png)

@matthewbcool any ideas whether this is a Mozilla Bug or a YouTube issue, or if there are any workarounds? Just let me know if I should create a separate issue thread for this too.

**Comment by matthewbcool** [comment]
@karenstritz thanks for helping document that. Hubs uses an external service to handle youtube videos and this is a separate, known issue. For now, I generally don't recommend linking youtube videos until we come up with a viable alternative solution.
