### ISSUE TITLE
Arrow keys in 'add object' dialog also move avatar

### ISSUE THREAD

**Issue by DougReeder** [mozilla/hubs#583]
OS X 10.13.6 (17G65)
FF 62.0 (64-bit)

1. Enter a room
2. Click magic wand icon; dialog opens
3. Click in text field to select
4. Type left-arrow.
    Expected result: cursor moves in field
    Actual result: cursor moves in field and avatar steps left
5. Type right-arrow.
    Expected result: cursor moves in field
    Actual result: cursor moves in field and avatar steps right
6. Type up-arrow.
    Expected result: cursor moves to beginning of field
    Actual result: cursor moves to beginning of field and avatar steps forward
7.  Type down-arrow.
    Expected result: cursor moves to end of field
    Actual result: cursor moves to end of field and avatar steps backward
8.  Type command-left-arrow.
    Expected result: cursor moves to beginning of field
    Actual result: cursor moves to beginning of field and avatar continues moving left until it hits an obstacle

command-right, -forward, and -down-arrow have similar issues.

**Comment by brianpeiris** [comment]
Looks like this was fixed in #663
