### ISSUE TITLE
Early Access Hub: 25 guests vs 125 guests

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/hubs#5830]
https://hubs.mozilla.com/#subscribe says:

> 25 Online guest capacity

<img width="459" alt="Bildschirm­foto 2022-11-30 um 23 45 44" src="https://user-images.githubusercontent.com/1100614/204924487-f1e0ae22-569e-42f5-9a2c-92b76c0674c9.png">

https://subscriptions.firefox.com/checkout says:

> 125 guest capacity

<img width="345" alt="Bildschirm­foto 2022-11-30 um 23 46 06" src="https://user-images.githubusercontent.com/1100614/204924531-30b1074f-f7cc-4b1f-a733-595623c97708.png">

**Comment by matthewbcool** [comment]
Thanks for reporting, we are aware of this issue and working on correcting this. 125 is a typo and should read '25'
