### ISSUE TITLE
Unable to pin screen-sharing objects

### ISSUE THREAD

**Issue by KeiichiroHirai** [mozilla/hubs#5835]
**Explanation**.
I can't pin a screen sharing object, it doesn't change to unpin when I press the pin button, press F12 and check the log, I get this log." PinningHelper: Entity did not produce a GLTF node."

**Reproduction Method
Steps to reproduce its behavior.
1. Click on 'Share'.
2. Click 'Screen'.
3. Select the screen you want to share and click 'Share'.
4. Click 'pin' on the screen sharing object.
5. It will not change to 'unpin'.

**Expected behavior
The 'pin' changes to 'unpin' and the object is pinned.

**Hardware**.
 - Device [desktop, phone].
 - OS [Windows, iOS].
 - Browser [Chrome, Edge, Safari].

**About Other Situations**.
Images and 3D objects can be pinned. Only screen sharing is not pinnable.

Translated with www.DeepL.com/Translator (free version)

**Comment by matthewbcool** [comment]
Thanks for your report! closing as a repeat of https://github.com/mozilla/hubs/issues/5063

also relates to feature request: https://github.com/mozilla/hubs/issues/5081
