### ISSUE TITLE
Problems that do not see the selection window

### ISSUE THREAD

**Issue by jamesPPA** [mozilla/hubs#5865]
Hello I'm Hubs Mozilla korean user 박민제(park min jae)

I made a metaverse map through my friend. 

By the way, as shown in the picture, the visit room selection window is not visible on mobile

The first picture PC is fine, but The second picture mobile is the problem

It used to be there, but it suddenly disappeared

How can I solve it?

*I'm sorry that I'm not good at English

Thank you.

![pc](https://user-images.githubusercontent.com/120553398/207543521-ea3b9e63-91d1-484d-aff9-37327fbc3b99.PNG)

![mobile](https://user-images.githubusercontent.com/120553398/207543549-26e559f5-54a6-4bba-97ab-dce2312a2ddb.jpg)

**Comment by matthewbcool** [comment]
If you do a single, two finger tap on mobile can you see 'visit room'? 
Which phone and browser are you using?

**Comment by jamesPPA** [comment]
No Previously, a visit room appeared when approaching the photo.

I'm using galaxy s22 and I checked it with friend iPhone.
The browser went into chrome.

And the link is this.
https://hubs.mozilla.com/HAz4BmW/

PC is fine, but only mobile is the problem.

Thank you.

**Comment by jamesPPA** [comment]
Thank you very much for solving this problem^^

It's better than before!!!!!

Thank you so much!!!!!!

**Comment by matthewbcool** [comment]
Thanks for your help documenting and reporting this @jamesPPA, closing as fixed with https://github.com/mozilla/hubs/pull/5868
