### ISSUE TITLE
How to add custom base environment

### ISSUE THREAD

**Issue by jamesdeantv** [mozilla/hubs#587]
Browsing through the repository, I find an array of environments within the assets folder that appear to contain json data for the rooms available to explore.  However, where are these files hosted? Further, is it possible to create my own rooms in say, Blender, export them as json, even better as gltf, and add them to the base environments array?

**Comment by brianpeiris** [comment]
Currently we build our built-in environments from the assets in this repository: https://github.com/MozillaReality/mr-social-assets. If you want to deal with the internals, you could certainly generate your own GLTF and use it as an environment.

However, in the process of building a better way for users to create their own environments. It's an environment editor/creation tool called Spoke. The tool is still in development but nearing a V1 release:
https://github.com/MozillaReality/Spoke/

**Comment by jamesdeantv** [comment]
Thanks @brianpeiris for pointing me in the right direction.

**Comment by brianpeiris** [comment]
:+1: I'll call this closed for now. Feel free to open a new issue if you run into any problems or reach out to us in the #social channel in the WebVR Slack https://webvr-slack.herokuapp.com/
