### ISSUE TITLE
Unable to run Hubs client locally against the dev server or Hubs Cloud

### ISSUE THREAD

**Issue by hrithikwins** [mozilla/hubs#5873]
**Description**
Trying to run mozilla Hubs in local environment shows blank Home page in Firefox and shows a infinite loading Hubs page in Chrome. 

**To Reproduce**
1. Switch to hubs-cloud branch (mine is at [github.com/hrithikwins/hubs/tree/hubs-cloud](https://github.com/hrithikwins/hubs/tree/hubs-cloud)
2. Run npm ci
3. Login to your hubs using npm run login.. (mine custom client is deployed [here](https://block.streetverse.world/xR3NsQP/swift-media-labs/)
4. Then run `npm run dev` command to run against phoenix server
5. Open your browser window and go to [https://localhost:8080](https://localhost:8080/)
6. If you run the same with `npm start` it shows the same issue

**Expected behavior**
As always it should open the home page and you should be able to create a room and go to that room

**Screenshots**
https://www.youtube.com/watch?v=SR5Wpe-kxxw (Video showing the issue)
Firefox:
![Screenshot_20230102_025557](https://user-images.githubusercontent.com/42163313/210185071-9a9f0726-1b8d-4265-a537-4f425612937e.png)
Chrome: 
![image](https://user-images.githubusercontent.com/42163313/210185089-f6e76410-7bd9-406d-aa3f-e31c62c1a821.png)

**Hardware** 
 - Device: Desktop
 - OS: Kali GNU/Linux Rolling          
          Kernel: Linux 6.0.0-kali3-amd64
 - Browser: Firefox and Chrome

**Additional context**
Previously it worked alright, and it seems to be an issue from backend as the same source code has worked fine previously

**Comment by ravindra-wts** [comment]
I have also tried to run room in local dev server and getting "join crashed".
![image](https://user-images.githubusercontent.com/114157953/210303961-ff2c3f43-ff14-421d-b501-2e3514ca3d25.png)

**Comment by matthewbcool** [comment]
I was able to repo running against the dev sever with the latest client.

macbook pro
firefox 

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/4493657/210703304-73e8fa9c-5634-4562-8b3a-d880fb4c5a1a.png">

**Comment by hrithikwins** [comment]
Hey @matthewbcool you're also getting the same error 'join crashed'

**Comment by hrithikwins** [comment]
This issue is resolved, although the home page doesn't load in Firefox if we're not signed in...
