### ISSUE TITLE
GLB fails to load on Oculus Go

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#588]
seeing a bug where the GLTF loader is trying to load what looks like a blob URL mashed together with a real URL: blob:https://hubs.mozilla.com/c0bb11e3-3875-4c2c-b754-fb22f93352a5

for this URL: https://hubs.mozilla.com/0dvylnrzt5v/normal-focused-universe

glb is https://uploads-prod.reticulum.io/files/f368d86e-bab6-4406-a4d8-fdd25acc26f4.glb

**Comment by gfodor** [comment]
this scene is working now.

**Comment by gfodor** [comment]
Reopening because I didn't test on Go

**Comment by johnshaughnessy** [comment]
Tested on Go -- that scene works fine, although if you paste the glb it seems to have a spawner in it and maybe a nav mesh, so some weird behavior resulted. However the issue as described above seems fixed.
