### ISSUE TITLE
rpm run login - cannot find module (*.ts)

### ISSUE THREAD

**Issue by n4gava** [mozilla/hubs#5897]
**Description**
It's giving an error when I try to run "npm run login":
```
Error: Cannot find module '../utils/store-instance'
Require stack:
C:\git\hubs\src\utils\phoenix-utils.js
C:\git\hubs\scripts\login.js
    at Object.<anonymous> (C:\git\hubs\src\utils\/phoenix-utils.js:5:1)
    at Generator.next (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\git\\hubs\\src\\utils\\phoenix-utils.js',
    'C:\\git\\hubs\\scripts\\login.js'
  ]
}
```

I believe the problem is occurring on .ts files. They were not compiled on login command

**To Reproduce**
1. Clone repo
2. run `npm ci`
3. run `npm run login`

**Expected behavior**
Run the command without errors

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: N/A

**Comment by rawnsley** [comment]
Copying [my note from Discord](https://discord.com/channels/498741086295031808/819203046931693589/1064839064857096232) regarding a temporary workaround: 

> Ugly hack: change the extension of store-instance.ts to .js and comment out the include for AAModes in store.js. This is enough to allow you to login and write the credentials to .ret.credentials, which persist after you revert the hack.

**Comment by manasa15M** [comment]
Hello Users

I too have the same issue and I’m new to Hubs cloud. I have a working AWS Hubs Cloud instance and am trying to setup the custom client and seeing MODULE_NOT_FOUND error during 'npm run login'. PFB error.

Thank you!

$ npm run login

hubs@0.0.1 login
node -r @babel/register -r esm -r ./scripts/shim scripts/login.js
..
..
..

usr/bin/hubs-master/hubs/src/utils/phoenix-utils.js:1
Error: Cannot find module '../utils/store-instance'
Require stack:
usr/bin/hubs-master/hubs/src/utils/phoenix-utils.js
usr/bin/hubs-master/hubs/src/scripts/login.js
at Object. (usr/bin/hubs-master/hubs/src/utils/ phoenix-utils.js:5:1)
at Generator.next () {
code: 'MODULE_NOT_FOUND',
requireStack: [
'usr/bin/hubs-master/hubs/src/utils/ phoenix-utils.js',
usr/bin/hubs-master/hubs/src/scripts/login.js

]
}

npm -v
8.11.0
node -v
16.16.0

sudo yum info nodejs
Loaded plugins: extras_suggestioms, langpacks, priorities, update-motd
Installed Packages
Name : nodejs
Arch : x86_64
Epoch : 2
Version : 12.22.12

Note: "store-instance.ts" is located in 'usr/bin/hubs-master/hubs/src/utils/store-instance.ts'

**Comment by manasa15M** [comment]
> Copying [my note from Discord](https://discord.com/channels/498741086295031808/819203046931693589/1064839064857096232) regarding a temporary workaround:
> 
> > Ugly hack: change the extension of store-instance.ts to .js and comment out the include for AAModes in store.js. This is enough to allow you to login and write the credentials to .ret.credentials, which persist after you revert the hack.



This solved the error.. Thank you

**Comment by Elettrotecnica** [comment]
Dear Mozilla,

I want to report this issue is still relevant on current codebase. The hack suggested here still allows to overcome the problem.
