### ISSUE TITLE
No sound on videos when voice chat is disabled on room

### ISSUE THREAD

**Issue by sarhugo** [mozilla/hubs#5947]
**Description**
If the voice chat is disabled then the videos (and I guess other media) don't play any audio.

**To Reproduce**
1. Go to a room with a video
2. Disable voice chat at room settings
3. Reload
4. Videos doesn't play any audio

**Expected behavior**
Videos play with sound even with voice chat disabled

**Additional context**
I see that the problem comes from this line: https://github.com/mozilla/hubs/blob/288d638e9a5cbf2ed22d6de5a2fbfd238067d38b/src/update-audio-settings.js#L75

Commenting the line restore the audio at videos, but of course it needs further investigation

**Comment by sarhugo** [comment]
I guess we need to add an additional check for the sourceType to apply only if it's an avatar audio source?

**Comment by netpro2k** [comment]
Thanks for the report. I was just investigating this and your diagnosis (and fix) is exactly where I landed as well. Should be fixed shortly.
