### ISSUE TITLE
Hubs: new objects appear but cannot be moved

### ISSUE THREAD

**Issue by MC2023A** [mozilla/hubs#5987]
**Description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**

**Comment by matthewbcool** [comment]
Not enough context, information to reproduce. Thanks for submitting but we will need steps to reproduce.
