### ISSUE TITLE
hub.link buttons don't work on touchscreen laptops

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#606]
due to the hack put in to work around this issue:

https://github.com/facebook/react/issues/9809

if the device supports both touch and mouse, the mouse is ignored. the proper 'fix' is to break the button into separate components and use ref's as is done in the react issue above, which will re-enable the ability to use `preventDefault` on the event.

**Comment by gfodor** [comment]
PR is also updated to address https://github.com/mozilla/hubs/issues/606

**Comment by gfodor** [comment]
PR out

**Comment by johnshaughnessy** [comment]
The fix regressed entry on Go. See https://github.com/mozilla/hubs/pull/1080

**Comment by gfodor** [comment]
now fixed
