### ISSUE TITLE
Pinned objects can still be grabbed (newLoader)

### ISSUE THREAD

**Issue by stalgiag** [mozilla/hubs#6086]
**Description**
Pinned objects can be grabbed and moved when working behind `newLoader`. A cursory search suggests that the `Pinned` component is not always successfully added to the entity (either on first pinning or on load from reticulum) [causing checks like this one](https://github.com/mozilla/hubs/blob/20ba18673bbb45fa0b422d7c2c664f0f9a3387d9/src/systems/hold-system.js#L38) to behave unpredictably.

**To Reproduce**
1. Go to a room with `newLoader` URL param
2. Add an object to the room
3. Pin the object
4. Try to move the pinned object

![pinned object](https://github.com/mozilla/hubs/assets/10382506/c7a2eb3f-ca73-43dc-894a-e122947311fa)

**Comment by stalgiag** [comment]
The only place where a `Pinned` component is ever added to [an object is in the Aframe "pinnable" component](https://github.com/mozilla/hubs/blob/20ba18673bbb45fa0b422d7c2c664f0f9a3387d9/src/components/pinnable.js#L27). It appears that this system is now disconnected from the rest of the new ECS system. There is no `pinnable` jsx entity attribute.

Instead of looking for a `Pinned` component, the `objectMenuSystem` decides whether to display the "pin" or "unpin" button [based on the `isPinned()` check instead](https://github.com/mozilla/hubs/blob/20ba18673bbb45fa0b422d7c2c664f0f9a3387d9/src/bit-systems/networking.ts#L22). We can get the expected interaction behavior by replacing `hasComponent(world, Pinned, eid)` checks in interaction systems with `isPinned()`.

I am still working to wrap my head around which parts of the codebase are currently active on the `newLoader` path but my intuition is that checking if the server is the creator of an entity to determine state is not an ideal solution as it is a deviation from the ecs pattern.

**Comment by stalgiag** [comment]
This relates to task with promotion permissions with ECS path. To handle both issues, I am going to make a `pinnable` system.

**Comment by Exairnous** [comment]
Looks like this bug now affects the current loader.

**Comment by Exairnous** [comment]
@johnshaughnessy ^
