### ISSUE TITLE
Media upload (image) results in broken media link, on hubs.mozilla.com/demo

### ISSUE THREAD

**Issue by jywarren** [mozilla/hubs#6088]
**Description**

**To Reproduce**

1. Go to https://hubs.mozilla.com/ZbPnoCW/test-space
2. Dragging an image onto the page results in a 500 POST error from https://hubs.mozilla.com/api/v1/media and the below screenshot shows the missing image

**Expected behavior**

the image should appear on the screen as a media object

**Screenshots**

<img width="372" alt="image" src="https://github.com/mozilla/hubs/assets/24359/8f03349f-74a6-4b5d-b197-544e3285d39b">

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**

**Comment by matthewbcool** [comment]
Thanks for the report @jywarren, I can confirm media loading issues as well.

**Comment by jywarren** [comment]
Thanks Matt. Do you think it's something that would be resolved pretty quick or not for a few hours or days? I'm trying to think if I should reschedule this workshop that starts in an hour. Apologies that is not fun to hear for the development team, I appreciate all your time and effort and I know bugs can happen!

**Comment by jywarren** [comment]
it works now!

Just uploaded an image and it displayed properly. TY!

**Comment by jywarren** [comment]
So grateful, workshop proceeding now!
