### ISSUE TITLE
Unable to upload 3D objects

### ISSUE THREAD

**Issue by daxxterity** [mozilla/hubs#6124]
**Description**

**To Reproduce**
1. Go to https://hubs.mozilla.com/scenes/BPtCGCW/just-moon
2. Click on 'create a room with this scene' - 'join room' - 'accept' - 'enter room'
3. Once in the room, click on the 'place' icon, select '3D Model'
4. Then top right selection: 'Custom URL or file'
5. This turns the bottom bar white, and no further action is possible.

**Expected behavior**
I expected to click on 'upload 3D model' would open a selection dialogue box, to select a local 3D file from my computer to upload.

**Screenshots**
![image](https://github.com/mozilla/hubs/assets/100806585/22b4e0bd-21e0-477b-bd6f-19275bf9e577)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Additional context**
![image](https://github.com/mozilla/hubs/assets/100806585/5d1f88b9-7ee6-431a-ae0a-065476660149)
![image](https://github.com/mozilla/hubs/assets/100806585/0ecb4a73-ba6b-406a-8cdf-6156ddb73cd2)
![image](https://github.com/mozilla/hubs/assets/100806585/82577da1-f863-4181-97b8-5b826ec42056)

**Comment by keianhzo** [comment]
Fixed by https://github.com/mozilla/hubs/pull/6135
