### ISSUE TITLE
bitECS: Improve Object menu

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#6192]
**Is your feature request related to a problem? Please describe.**

Object menu with bitECS needs to improve. 

* Replace label buttons with icon buttons
* Improve layout: adjust buttons position: Some buttons (the bottom two buttons) looks being overlapped?
* Improve layout2: Dimensionally, if the object is very thick, you can no longer access the rotate, scale, delete
* Implement buttons functionalities: The fanctionaliries of some buttons are unimplemented. Even if they are click, no side effect. Implement them or remove the unimplemented buttons. It's confusing.

Before (A-Frame based)

![image](https://github.com/mozilla/hubs/assets/7637832/460723f7-1cf5-4566-8a7c-ea2580141129)

After (bitECS based)

![image](https://github.com/mozilla/hubs/assets/7637832/1dda7390-f651-490c-a673-4e73640178ad)

**Describe the solution you'd like**

Implement all the buttons and improve the layout. Perhaps less confusing if the new one looks similar to the old one.

**Describe alternatives you've considered**

Remove unimplemented buttons (until they are implemented). It would be less confusing than placing the button that don't cause any side effect.

**Additional context**

Intentionally we picked up only some of the buttons to implement, and I was going to think of icons and layout stuffs later. But in the recent bitECS test, we had many reports about the improvement mentioned above. The problems seem to be very noticable and probably we should raise the priority of the fixes.

**Comment by takahirox** [comment]
I keep this issue opened until all the buttons are implemented

**Comment by keianhzo** [comment]
Related: https://github.com/mozilla/hubs/issues/6281

**Comment by takahirox** [comment]
Yes, it is a known issue.

https://github.com/mozilla/hubs/blob/d5aefe1ab73260191d4e9f681a1644556b7ee77b/src/bit-systems/object-menu.ts#L65-L70

As I wrote somewhere, perhaps using bounding box to determine the object menu position would be safer.
