### ISSUE TITLE
Hubs not opening in Opera Browser

### ISSUE THREAD

**Issue by hrithikwins** [mozilla/hubs#6195]
**Description**

**To Reproduce**
1. Go to 'Opera browser and open Hubs'

**Expected behavior**
It should open in Opera

**Screenshots**
![image](https://github.com/mozilla/hubs/assets/42163313/14c3867f-6c45-4119-96a5-6594b25b47dd)

**Hardware** 
 - Device: Windows Laptop
 - OS: Windows
 - Browser: Opera

**Additional context**

```[tasklist]
### Tasks
```

**Comment by takahirox** [comment]
Unfortunately Opera is out of our target now.
