### ISSUE TITLE
bitECS: Links don't work if included in a GLTF file

### ISSUE THREAD

**Issue by keianhzo** [mozilla/hubs#6201]
**Description**
Links are correctly rendered when the are spawned using `loadHtml` as part of the media-loading system but we are not correctly handling it if the link component is attached to an object in a GLTF file.

**To Reproduce**
1. Create a scene with an empty that has a link component in Blender/Spoke or drag and drop a GLTF with a link component in a scene. 

**Expected behavior**
The link surface with the preview and the link menu should be rendered

**Comment by keianhzo** [comment]
This should trigger it. It's a link pointing to the mozilla website.
[link.glb.zip](https://github.com/mozilla/hubs/files/12373704/link.glb.zip)

**Comment by takahirox** [comment]
@keianhzo Thanks but it doesn't seem to contain any mesh in the glb so nothing to render, isn't it? I guess it misses an mesh object?
