### ISSUE TITLE
bitECS: F button for Focus doesn't work on objects

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#6207]
**Description**

With new loader enabled, F button for focus doesn't work on objects.

**To Reproduce**
1. Enter a scene with new loader enabled
2. Upload a glb object
3. Hover a cursor on the object
4. Press F
5. See no focus

**Expected behavior**

Focus works on objects

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Additional context**

Focusing on avatars or screenshare works.

**Comment by takahirox** [comment]
The root issue seems to be that `hoverEl` at this line is `null` with the new loader enabled

https://github.com/mozilla/hubs/blob/40bbcc41c6b5c2eac2982b0a8bf2bbebd44db195/src/systems/camera-system.js#L427

**Comment by keianhzo** [comment]
Already fixed
