### ISSUE TITLE
bitECS: Improve video controls

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#6219]
**Is your feature request related to a problem? Please describe.**

Video controls can improve with new loader. Especially it lacks of some features compared to the one without new loader, for example

* Play/Pause indicator
* Volume indicator/controls
* Forward/Backward

With new loader

![image](https://github.com/mozilla/hubs/assets/7637832/467ef4c5-8877-472e-bd82-d734672c049d)

Without new loader

![image](https://github.com/mozilla/hubs/assets/7637832/642782ef-7227-4573-8994-a6cb467bbac0)

**Comment by keianhzo** [comment]
BitECS video controls has now parity with the old loader one. Only the skip button is missing but as we have now the time slider, it doesn't seem necessary to me to have sip buttons.
