### ISSUE TITLE
bitECS: Spherical video/image objects shouldn't be grabbable

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#6225]
**Description**

Spherical video/image objects shouldn't be grabbable but they are with new loader.

**To Reproduce**
1. Enter a room with new loader enabled
2. Upload an asset including spherical video/image
3. Attempt to grab (drag) it
4. See it moves

**Expected behavior**

Spherical video/image objects shouldn't be grabbable.

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Additional context**

They are not grabbable without new loader.

**Comment by Exairnous** [comment]
I'm not sure I'd count this as a bug.  I think if it's dropped in room and is visible it should be grabbable/moveable.  I always kind of thought that links, images, etc. not being moveable was a bug/limitation in the old loader.

**Comment by keianhzo** [comment]
I agree with @Exairnous , I think this should be the correct behavior, all spawned objects should be movable. Closing.
