### ISSUE TITLE
Audio Params in glTF crashes Hubs when placed in a media frame.

### ISSUE THREAD

**Issue by Exairnous** [mozilla/hubs#6244]
**Description**
When you export a GLB file that contains the Audio Params component, drop it in a room, and then try to move it into a media frame in the scene it causes Hubs to crash

**To Reproduce**
1. Go to a room with a media frame.
2. Spawn this object into the room https://github.com/mozilla/hubs-sample-assets/raw/main/Hubs%20Components/Exported%20GLB%20Models/Audio.glb
3. Move the object into the media frame.
4. Hubs crashes.

**Expected behavior**
Hubs shouldn't crash when the object is placed in a media frame.

**Screenshots**
![image](https://github.com/mozilla/hubs/assets/9795121/72d3ee92-fee3-483f-811c-52cc4dbcf561)

**Hardware** 
 - Device: Laptop
 - OS: Linux
 - Browser: Chromium

**Additional context**
This happens in both the old and new loaders.
In the new loader, if you scale the object and it intersects the media frame in the new loader it won't crash until you click on the object, in the old loader it will crash as soon as the object intersects the media frame when scaling.

[untitled_video.glb.zip](https://github.com/mozilla/hubs/files/13364359/untitled_video.glb.zip)

**Comment by keianhzo** [comment]
All the media frame preview issues have been fixed already. Closing this.
