### ISSUE TITLE
Scene will not load unless a Global Variable exists in the Scene tab upon export.

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6261]
**Description**
If there is no Global variable listed in Blender's Scene tab, the exported scene will not load.

**To Reproduce**
1. Start with the included template .blend file.
2. Go to the Scene tab and remove the Global variable called 'DoNotDelete'
3. Export as .glb
4. Try to load the .glb in Hubs

**Expected behavior**
The scene should load regardless of the existence of a Global Variable.

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, possibly others

[StartUp.zip](https://github.com/mozilla/hubs/files/12614167/StartUp.zip)

**Comment by keianhzo** [comment]
Can you pack the images inside the Blend file and re-upload?

**Comment by keianhzo** [comment]
Fixed here: https://github.com/mozilla/hubs/commit/60b6709656c6ec79f4214bf1a1353435a2777d2e
