### ISSUE TITLE
Animation clamping seems to have stopped working.

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6262]
**Description**
Animation actions with `clampWhenFinished` set to TRUE do not clamp.
**NOTE:** This occurs on both Scene Graphs and Object Graphs.

**To Reproduce**
1. Export the included AnimTestClamp.blend file as a .glb
2. Click on the torus to play the animation
3. The animation should finish with the torus 1m off the floor.
4. Also try clicking it again, which should play the animation in reverse.
5. The animation reverses, but repeats continuously.

**Expected behavior**
When clicked, the torus should play the upward animation one time and stop. When clicked again, it should lower back down and stop.

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

[AnimTestClamp.zip](https://github.com/mozilla/hubs/files/12615081/AnimTestClamp.zip)

**Comment by keianhzo** [comment]
For future testing can you re-upload the scene with images packed?

**Comment by keianhzo** [comment]
Fixed here: https://github.com/MozillaReality/blender-gltf-behavior-graph/commit/c5cb996316e2bab163bcd74f67c96a06515be940 

Grab the latest master zip for the fix.
