### ISSUE TITLE
bitECS: No link button when Link and Image components are defined

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#6263]
Reported by Imaginer on Discord

**Description**

If image and link Hubs component is defined on the same node, Link button isn't shown even the cursor hovers on the image object.

**To Reproduce**
1. Enter a room with the new loader enabled
2. Upload an asset including a node that has both image and link Hubs component
3. Hover the cursor on the image object
4. See that no "Link" button is shown

Room for testing: https://hubs.mozilla.com/sDg4ioF/fluffy-shiny-cosmos/?newLoader

**Expected behavior**

Link button is shows when the cursor hovers on the image object

**Screenshots**

![image](https://github.com/mozilla/hubs/assets/7637832/95a00dc4-fdf5-4d91-ba5b-eba29a4c47a4)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Additional context**

I labeled this issue as P1. Although I'm not sure if Link + Image is major use, it may be worth to investigate the problem because multiple components on a node may cause the problem and the problem may not be Link + Image specific.

**Comment by Exairnous** [comment]
I would guess that Link + Image sees reasonably high usage, and it is used in the current official Mozilla demo scene/room.

**Comment by takahirox** [comment]
Thanks, then P1 makese sense more
