### ISSUE TITLE
Flow node: Sequence causes crash on start

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6268]
**Description**
Seems like a regression. Any use of a `Sequence` flow node in a Scene or Object graph causes the following error:

`oveddan-behave-graph-core.esm.js:1218 Uncaught Error: node 'flow/sequence' specifies an output '1' that doesn't exist on its node type, available outputs are: 
    at oveddan-behave-graph-core.esm.js:1218:13
    at X (oveddan-behave-graph-core.esm.js:1177:5)
    at Z (oveddan-behave-graph-core.esm.js:1085:18)
    at behavior-graph.ts:112:19
    at Array.forEach (<anonymous>)
    at behavior-graph.ts:98:34
    at hubs-systems.ts:189:3
    at app.ts:235:11
    at three.module.js:27389:35
    at r (three.module.js:12900:3)`

**To Reproduce**
1. Open the included .blend and notice the Sequence node hooked to a couple Display Notification Message nodes.
2. Export as .glb
3. Load the .glb in Hubs
4. See error as pasted above.

**Expected behavior**
Sequence nodes used to work and not crash Hubs.

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

[SequenceTest.zip](https://github.com/mozilla/hubs/files/12639688/SequenceTest.zip)

**Comment by keianhzo** [comment]
Fixed in the latest master
