### ISSUE TITLE
On Media Event node only allows 'Self'

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6269]
**Description**
The `On Media Event` node, when set to `Other` does not allow selection of any entities.

**To Reproduce**
1. Create an `On Media Event` node
2. Change `Self` dropdown to `Other`
3. No entities are listed, even when a Video component exists on one.

**Expected behavior**
Should allow selection of any entity containing a Video or Audio component.

**Screenshots**
https://gyazo.com/aa937434c3fac1be6abfe41c82082994

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: N/A

**Additional context**
This occurs in either Scene or Object graphs.

**Comment by keianhzo** [comment]
Fixed in latest main.
