### ISSUE TITLE
bitECS: Object menu is hidden behind the objects sometimes

### ISSUE THREAD

**Issue by keianhzo** [mozilla/hubs#6281]
**Description**
Object menu is hidden behind the object sometimes

**To Reproduce**
1. Enter a hubs room using new loader
2. Spawn a duck. Open the chat and type `/duck`
3. Scale the duck

**Expected behavior**
The menu should always be in front of the object

**Screenshots**
<img width="329" alt="Screenshot 2023-09-22 at 11 53 14" src="https://github.com/mozilla/hubs/assets/837184/595b5e54-f8e6-4a20-81d0-aab7a9db54fb">

**Comment by takahirox** [comment]
https://github.com/mozilla/hubs/issues/6192#issuecomment-1732749240
