### ISSUE TITLE
The word "cr*zy" is included in the random room name generator list

### ISSUE THREAD

**Issue by LaurieAnnis** [mozilla/hubs#6283]
I just got a random room name assigned with the word cr*zy in the mix.  I asked in Discord," how can I go about requesting that that word be removed from the name generator?" and the response was to pleas submit (this) as a bug report.

**To Reproduce**
1. Create a room
2. Randomly get assigned a room name with the word cr*zy (offensive term to describe mental illness) in it.

**Expected behavior**
Offensive words to be omitted from the possible random words.

**Comment by zfox23** [comment]
Thanks for your submission, @LaurieAnnis! There are two PRs in the pipeline to resolve this issue, referenced above.

**Comment by zfox23** [comment]
PRs merged :)
