### ISSUE TITLE
Behavior Graphs: Exception when gathering entities for scene level graphs

### ISSUE THREAD

**Issue by Exairnous** [mozilla/hubs#6286]
**Description**
An exception occurs when trying to gather entities that are set to self or none in scene level graphs when exporting.

**To Reproduce**
1. Open Blender to the default scene.
2. Add a new scene level behavior graph.
3. Add a `Set Entity Property` node.
4. Export a GLB.
5. If you check the console you will see an error reported and if you check the GLB you will see that no behavior graph has been exported.

**Expected behavior**
The behavior graph should export as normal without any errors.

**Hardware** 
 - Device: Laptop
 - OS: Linux
 - Browser: N/A

**Additional context**
The exception is triggered by line 117 of `utils.py` with the exception message being `KeyError: None`
I first noticed this with the `Create AnimationAction` node, I had just left the entity on its default of `Self`. 
I believe the problems are that the function is looking only for objects (not scenes) and that it hasn't been guarded against an empty field.

**Comment by keianhzo** [comment]
This has been already fixed and merged.
