### ISSUE TITLE
bitECS: Cloned object can't be pinned by other users

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#6303]
Reported by Imaginer on Discord

**Description**

Locally uploaded objects cannot be pinned by others, which matches the old loader, but if someone clones that object they still cannot pin it, which doesn't match the old loader.

**To Reproduce**
1. Enter a room with the new loader enabled from a browser and sign in
2. Enter the same room with the new loader enabled from another browser and sign in as another user
3. Upload a media file from the first browser
4. Confirm that the media object is pinnable via the object menu from the first browser but it isn't from the second browser
5. Make a clone of the media object from the first browser
6. Confirm that the cloned media object is pinnable via the object menu from the first browser and it is still not from the second browser
7. Do the same 1-6 steps without the new loader and confirm that the cloned object is pinnable from the second browser at step 6.

**Expected behavior**

Match the old loader behavior?

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Additional context**

I don't think the different behavios are intentional but also am not sure if we can prioritize the fix. I wanted to file this issue for now and discuss with the team about whether we should label it as P1.

**Comment by Exairnous** [comment]
If you don't have two email accounts/browsers to sign in with you can just use a private window to get a separate user and drop an object in with that, then clone and try to pin the object with your regular logged in user.

**Comment by keianhzo** [comment]
I believe this is already fixed. Can you confirm @Exairnous ?

**Comment by keianhzo** [comment]
Closing as fixed.
