### ISSUE TITLE
bitECS - Old scenes may have nav meshes visible by default, we should ensure reverse compatibility

### ISSUE THREAD

**Issue by mikemorran** [mozilla/hubs#6315]
**Description**
@Exairnous explained that the new system may require users to configure their nav mesh correctly to make sure they are invisible. While not a bug, this may render many older scenes incompatible with the new system, as their nav meshes will be visible and impact the quality of their work.

**To Reproduce**
1. Create a room with [this scene](https://hubs.mozilla.com/scenes/98AwrmE/pnw-asset-pack-demo-scene) and enable the new loader.

**Expected behavior**
The nav mesh should function but not be visible

**Comment by takahirox** [comment]
Thanks for the problem report. Confirmed the problem. I don't think this behavior change is intentional. It should be invisible. Let me investigate the root issue.

**Comment by takahirox** [comment]
audio debug system seems to be related. In the old loader it seems to make the nav mesh group invisible at https://github.com/mozilla/hubs/blob/a1ce4edd9ab8cac3fedd6c997f84e29fa151b979/src/systems/audio-debug-system.js#L176 while maybe in the new loader it doesn't.
