### ISSUE TITLE
BG - `Local to World` node returns errors about missing Entity

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6317]
**Description**
When attempting to use the `Local To World` node, the console returns errors, regardless of what entity is specified in the node (Self, Other, input) :

`euler localToWorld, could not find entity 147`

**To Reproduce**
1. Open the attached `.blend` file
2. Note the `Local To World` node
3. Export to .glb and run in Hubs
4. See errors

**Expected behavior**
The node should recognize the specified entity.

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

NOTE: This error occurs with **BOTH** `Local To World` nodes (Euler and Vector)

**Comment by keianhzo** [comment]
@j-conrad Fixed, it should return the right values now
