### ISSUE TITLE
Use BroadcastChannel in two tabs, in onMessage, to get the data in localStorage, there is a chance to get the old data

### ISSUE THREAD

**Issue by liu-jin-yi** [mozilla/hubs#6319]
**Description**
Use BroadcastChannel in two tabs, in onMessage, to get the data in localStorage, there is a chance to get the old data.

**To Reproduce**
1. Open Firefox on Mac and open two tabs
2. A tab visits http://localhost:3000/
3. A tag visits http://localhost:3000/?B2=%27a%27
4. Click the button in the first tab
5. Open the console in a second tab to see the output

**Expected behavior**
There is a chance of getting old data in the second tab。

**Screenshots**
<img width="2543" alt="image (15)" src="https://github.com/mozilla/hubs/assets/45869971/a502a13a-36fa-479f-b904-8ec2dbc3e6c7">

**Hardware** 
 - Device: Mac 
<img width="742" alt="image" src="https://github.com/mozilla/hubs/assets/45869971/be62af94-a306-4eae-95ee-19f4ec7add71">

 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**

Demo: 
[testguangbo.zip](https://github.com/mozilla/hubs/files/12881768/testguangbo.zip)

**Comment by mikemorran** [comment]
Hello @liu-jin-yi, this github is not for firefox related issues
