### ISSUE TITLE
Moderation: admin +o'ing

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#632]
We need to (finally) enable the ability for some users to be more privileged than others. Proposal:

- Generate an admin secret on the room record
- Add a phoenix channel message that flips a bit on the socket if the secret is sent over the hub channel, marking the user as an admin
- Add a bit of client plumbing to share the secret and get them admin rights by sending the message

**Comment by misslivirose** [comment]
@gfodor can we close this, now that we have room owners in place?

**Comment by gfodor** [comment]
yup will close after shipping
