### ISSUE TITLE
BG - Using `Set TimeScale` in a graph requires refreshing the browser each time you run 

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6330]
**Description**
When using `Set Timescale` in a behavior graph, attempting to re-run that scene and trigger that `Set Timescale` again without first refreshing the browser produces the following error:

`Uncaught TypeError: Cannot set properties of undefined (setting 'timeScale')
    at D.triggered [as triggeredInner] (animation-nodes.ts:380:14)
    at D.triggered (oveddan-behave-graph-core.esm.js:501:25)
    at q.executeStep (oveddan-behave-graph-core.esm.js:947:12)
    at Y.executeAllSync (oveddan-behave-graph-core.esm.js:1021:20)
    at behavior-graph.ts:236:12
    at Array.forEach (<anonymous>)
    at behavior-graph.ts:233:30
    at hubs-systems.ts:190:3
    at app.ts:239:11
    at three.module.js:27389:35`

It may not seem like much, but having to refresh the browser and rejoin the room after every test is a productivity killer.

**To Reproduce**
1. Open the attached `.blend` file
2. Note the use of `Set Timescale`
3. Export as `.glb` and run scene in Hubs
4. Click the monkey to see the animation start/stop
5. Without refreshing the browser, drop the `.glb` into the browser again
6. Try clicking on the monkey
7. See error

**Expected behavior**
Scenes should be able to be run/rerun without refreshing the whole browser

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

[TimeScale_Bug.zip](https://github.com/mozilla/hubs/files/12900604/TimeScale_Bug.zip)

**Comment by keianhzo** [comment]
@j-conrad This seems to have been fixed by the latest update. There were a lot of animation related updates and bug fixes so seems pretty reasonable.

If you want to re-test, here is the updated version of the file to work on the latest client:
[TimeScale_Bug.blend.zip](https://github.com/mozilla/hubs/files/13391908/TimeScale_Bug.blend.zip)
