### ISSUE TITLE
bitECS: Invalid gltf parameters can crash the client

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#6331]
Reported by Imaginer @Exairnous on Discord.

**Description**

If you drop in a glb file that includes invalid glTF (Hubs component) parameters, Hubs Client can crash with the new loader enabled. The client doesn't crash with the old loader.

For example if you drop in this file [import_dev_test_3.zip](https://github.com/mozilla/hubs/files/12900614/import_dev_test_3.zip) the client crashes with the new loader.

These are the console errors.

![image](https://github.com/mozilla/hubs/assets/7637832/515976b5-2a38-47e5-9613-61121480251f)

With the old loader, the loading cube never ends and some console errors, pasted below, happen but the client doesn't crash.

![image](https://github.com/mozilla/hubs/assets/7637832/f88d691a-97a4-451f-a6a0-e1aff5796dd8)

**To Reproduce**
1. Enter a room with the new loader enabled
2. Drop in the example file above
3. Confirm the client crash
4. See the console error

**Expected behavior**

No crash

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Additional context**

The problem is very related to how to handle invalid glTF (Hubs component) parameters that we have been discussing. glTF file can come from outside so we can't and shouldn't really trust glTF data. It may include invalid parameters.

Some solution ideas.

1. Adding a validation layer to glTF inflators. It checks inflator parameters and refuse or rescue invalid parameters.
2. Add more try - catch in systems for the code that can throw exception.

We may start to add try - catch in audio target system that seems to cause the crash with the example glb file for now if our time is very limited.

3. An easy temporary workaround, add try-catch to the top-level tick?

**Comment by Exairnous** [comment]
This should probably be handled on the Blender exporter side as well, so I've opened an issue to track it.  Curiously, the Min Delay parameter doesn't cause a crash, but I guess it should also be constrained to the same range?

**Comment by takahirox** [comment]
Yes, it's good to check parameters both in the loader (client) and exporter.

**Comment by keianhzo** [comment]
We should be able to enforce min, max, default in the inflator params definition but for now I think we can just enforce limits in the inflators explicitly.
