### ISSUE TITLE
BG - Adding variables causes graphs to lose connections

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6333]
**Description**
When adding additional variables to an object that already has variables being referenced in a behavior graph, those existing Get/Set Variable nodes will have their fields update and their input/output wires will get disconnected--even if their own variable list did not change but they share a graph with the offending object.

**To Reproduce**
1. Open the attached `.blend` file.
2. Note the annotation (circled node in the graph).
3. Note the object variable list for `Cube.001`
4. Select `Cube.002`, which shares the same object graph, but is missing the `SomeVar` boolean variable.
5. Add a new object variable to `Cube.002`.
6. The `Get Variable` node in the object graph loses its connection.
7. Selecting `Cube.001` will show that its `Get Variable` node has also lost its connection and had its field change.

**Expected behavior**
I might expect `Cube.002` to have problems or to change when it gets a new variable, but `Cube.001` does not even refer to that other object's variable list (`Cube.002`).

Some of this might be mitigated by having variables get duplicated along with the behavior graph. In general, graphs that refer to missing variables are problematic, but shared graphs seems to make it a more complicated problem.

### **Video capture of the problem:** https://gyazo.com/39d4629e8bec02983eb405540757cc9a

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

[Variable_bug.zip](https://github.com/mozilla/hubs/files/12923072/Variable_bug.zip)

**Comment by keianhzo** [comment]
This should be fixed.
