### ISSUE TITLE
Search is not working as expected when searching with random term

### ISSUE THREAD

**Issue by mMARUF** [mozilla/hubs#6348]
**OS**
Mac OS Ventura 13.6

**Browser**
Mozilla Firefox Nightly 120.0a1 (2023-10-14) (64-bit)

**Steps to Reproduce**
1. Go to https://hubs.mozilla.com/docs/welcome.html
2. Search with some random search term (Example- sjdusndusndfs email snjnfjnsfjsnjf)

**Actual Result**
Though the search term is random and does not make any sense, we still get search results regarding the term '**Email**'

**Expected Result**
As the search term together does not make sense, the system should not show any search results.

**Attachment(s)**
![search is not working as expected](https://github.com/mozilla/hubs/assets/45368054/cb8efe1c-7680-42f2-8ac7-d635d00c78b1)

**Comment by mikemorran** [comment]
Referencing in separate repo!
