### ISSUE TITLE
Search result doesn't reset when no search result found 

### ISSUE THREAD

**Issue by mMARUF** [mozilla/hubs#6349]
**OS**
Mac OS Ventura 13.6

**Browser**
Mozilla Firefox Nightly 120.0a1 (2023-10-14) (64-bit)

**Steps to Reproduce**
1. Go to https://support.mozilla.org/en-US/products/hubs#search
2. Search with some random search term 
3. Now replace the search term with space
4. Then press the search button again 

**Actual Result**
After changing the search term to blank space, the search result does not change. We still see the message:
 **Sorry! 0 results found for ‘deifjdeiefjidefjsdeifjidsf’ for ‘Hubs’** 

**Expected Result**
Search result should reset after searching with spaces

**Attachment(s)**
![search result does not get reset](https://github.com/mozilla/hubs/assets/45368054/8a1c932b-4f33-40b9-b5f8-e3f7af46e51b)

**Comment by mikemorran** [comment]
Hey @mMARUF, thanks for sharing this issue. This is located on another Mozilla service that is not managed by Hubs or this codebase

**Comment by mikemorran** [comment]
@mMARUF following up on this with the help of @Exairnous. I would recommend filling this bug with this repo: https://github.com/mozilla/kitsune/

**Comment by mMARUF** [comment]
Got it. Reported a bug in https://github.com/mozilla/kitsune/
Bug: https://github.com/mozilla/kitsune/issues/5773

**Comment by Exairnous** [comment]
Thank you!
