### ISSUE TITLE
BG - Need variable type: `Material`

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6352]
**Is your feature request related to a problem? Please describe.**
When using behavior graphs, It is useful to be able to store a `material` as a variable.

NOTE: An early version of behavior graphs had this variable type (in the side 'n' panel) but it does not exist elsewhere.

An example would be storing an object's material as a variable, changing the material to a different one, then using that variable to restore the original material later.

**Describe the solution you'd like**
The ability to choose `Material` as a variable type

**Comment by keianhzo** [comment]
@j-conrad I've added support for material variables

https://github.com/mozilla/hubs/commit/168d004c175c6dcfae48ee1951da4ae9e3162153
