### ISSUE TITLE
BG - The presence of a `Visible` component negates visibility toggling via behavior graph

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6358]
**Description**
If an object has a `Visible` component on it, attempting to control visibility via behavior graph doesn't work.

**To Reproduce**
1. Open the included `.blend`
2. Note the presence of the `Visible` component on the torus
3. Run in Hubs
4. Click the icosphere and note the visibility of the object will not change

**Expected behavior**
The presence of a `Visible` component should **not** affect the behavior graph's ability to toggle visibility.

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

[VisibilityBug.zip](https://github.com/mozilla/hubs/files/13230149/VisibilityBug.zip)

**Comment by keianhzo** [comment]
@j-conrad This has been fixed since the latest big update. I've tested and it's working as expected now.
