### ISSUE TITLE
BG - Using `Set Component Property` on any `Audio` components causes freeze

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6359]
**Description**
When using the `Set Component Property` node to set `Audio` component properties causes Hubs to freeze.

**To Reproduce**
1. Open attached `.blend`
2. Note the `Set Component Property` node with the Audio component value(s) listed
3. Export as .glb and run in Hubs
4. Click on the icosphere
5. Hubs will freeze

**Expected behavior**
You should be able to set Audio component properties without crashing.

**Screenshots**
![image](https://github.com/mozilla/hubs/assets/31968496/e17c6f97-e2ac-4ddb-9822-dc107f82e04c)

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

[AudioComponentPropertyBug.zip](https://github.com/mozilla/hubs/files/13256194/AudioComponentPropertyBug.zip)

**Comment by keianhzo** [comment]
@j-conrad Fixed, it shouldn't crash anymore.

https://github.com/mozilla/hubs/commit/8e4a2425546849c2dd0f3cec30304915c88488fe
