### ISSUE TITLE
Ability to specify environment map for IBL

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#637]
Currently Spoke and Hubs use a single static environment map. It would be nice if this were configurable. The current environment map makes it basically impossible to make nighttime environments.

https://github.com/MozillaReality/Spoke/issues/350

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-657)

**Comment by misslivirose** [comment]
This looks done given the other issues have been resolved on the Spoke side - I'm going to close this based on that assumption but if it's wrong, we can re-open.

**Comment by netpro2k** [comment]
The linked Spoke issue just generates one from the skybox, but people have still asked to be able to set one manually. We should rack that either by re-opening this or making a new issue.
