### ISSUE TITLE
glTF models with media audio/video elements crash when being captured by a media frame

### ISSUE THREAD

**Issue by keianhzo** [mozilla/hubs#6370]
**Description**
A glTF model dropped in a scene will cause a crash when being captured by a media-frame.

**To Reproduce**
1. Open a room with a media frame that can capture models
2. Create a model with a media audio/video components on it
3. Spawn the model into a scene

**Expected behavior**
The media frame should not crash when capturing models.

**Additional context**
It seems that it's crashing when cloning the audio object when creating the media frame preview.

[untitled_video.glb.zip](https://github.com/mozilla/hubs/files/13363333/untitled_video.glb.zip)

**Comment by Exairnous** [comment]
Is this the same as https://github.com/mozilla/hubs/issues/6244 ?

**Comment by keianhzo** [comment]
Oh yes, thanks.

Closing as it's a duplicate of https://github.com/mozilla/hubs/issues/6244
