### ISSUE TITLE
Spawner behaviour different in new loader

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#6374]
Spawners behave differently between old loader and new loader:

1. The initial position of the reference object is slightly different.
2. The spawned object is smaller than the reference object.
3. No fancy spawn animation.

Regarding [1]: I think the positioning of the reference object is better in new loader; it appears to recenter from the content bounds rather than respecting the original object origin, which is often arbitrary.

Regarding [2]: The smaller spawned object is unexpected and I can't think of a good reason for it to be a different scale to the reference object.

Regarding [3]: I quite liked this animation as it gave the feeling that Hubs was literally inflating these models to order, but it is not essential to replace.

**Old Loader** https://hubs.mozilla.com/uMK4k8N/loathsome-loud-realm

<img width="1802" alt="Screenshot 2023-11-17 at 08 35 11" src="https://github.com/mozilla/hubs/assets/303516/cbb8a5c2-4408-4e04-8823-b56e4bbf253e">

**New Loader** https://hubs.mozilla.com/uMK4k8N/loathsome-loud-realm?newLoader=true

<img width="1802" alt="Screenshot 2023-11-17 at 08 35 38" src="https://github.com/mozilla/hubs/assets/303516/8ce0245c-cd3b-4df1-b94f-9de76de54eca">

[Blender File](https://avnfs.com/kKi9JhVdI6gee_X_d3yhPRDVeqaNOTaO7ybtZh6DvHc?size=9562720&type=application%2Fx-blender&name=spawner-example.blend) [GLTF File](https://avnfs.com/C-yHgCagS7WVdr6CB0AAEmNiE5TAmXlCXipkFW5Mx_4?size=8972488&type=model%2Fgltf-binary%3Bdisp%3Dscene&name=spawner-example.glb)

**Comment by mikemorran** [comment]
Thanks for reporting these @rawnsley! I know @takahirox and @keianhzo are watching feedback on this as we continue work finishing up the new loader!

**Comment by keianhzo** [comment]
Thanks for reporting this @rawnsley!
