### ISSUE TITLE
BG - adding a Material variable makes Hubs crash

### ISSUE THREAD

**Issue by uhunkler** [mozilla/hubs#6379]
**Description**
When I add a Material variable Hubs crashes. Sometimes when I add one variable. In the attached blend file when I add a second variable.

**To Reproduce**
1. Export the scene as a GLB
2. Drag the GLB on a room in https://testing.dev.myhubs.net/
3. The room crashes
4. Open the blend file
5. Remove the varible »mat1«
6. Export the scene as a GLB
7. Drag the GLB on a room in https://testing.dev.myhubs.net/
8. The room does not crash

**Expected behavior**
Material variables should not make the room crash.

**Screenshots**
-

**Hardware** 
 - Blender 3.6.4
 - Desktop
 - OS: macOS
 - Firefox 119.0.1 (64-bit)

**Additional context**
I attach a blend file.
[hubs_bg_errorreport_001.blend.zip](https://github.com/mozilla/hubs/files/13416587/hubs_bg_errorreport_001.blend.zip)

**Comment by keianhzo** [comment]
Good catch! We weren't correctly resolving material variable entities, I've fixed this here: https://github.com/mozilla/hubs/commit/d5f3a71e3b86dd487014ff48d69ff014a2d7951f

**Comment by keianhzo** [comment]
Yes, this should be already available in the testing instance
