### ISSUE TITLE
BG - `Get Material Property` returns `undefined` or `NaN`

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6417]
**Description**
When attempting to use the `Get Material Property` node, the debug output returns `undefined` or `NaN`.

![image](https://github.com/mozilla/hubs/assets/31968496/de0864a4-7e8a-414c-8cfc-1a57d4da6568)

**To Reproduce**
1. Make an `On Interact` node that triggers a `Debug Log`
2. Attach a `Get Material Property` to the debug and try various parameters like `Opacity` or `Roughness`
3. Run in Hubs
4. Note the debug returns `undefined` values.

**Expected behavior**
It should return the proper parameter value

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Comment by keianhzo** [comment]
It was a silly bug when writing the node value. Fixed here: https://github.com/mozilla/hubs/commit/a6f81a801177ef68f703fdfdd5d8632b54fa6fba
