### ISSUE TITLE
Ratchet turn resizing held objects (6DOF) is annoying

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#642]
When holding a 2d or 3d object (media tools) with Touch controllers, ratchet turning with Right Stick causes the held object to be resized with each flick of the stick. This is annoying when attempting to make the object just the right size and then moving around to get the object into a specific position. There's also no feedback to let the user know this is happening, which could lead to a user thinking something is wrong with the object or with the way they're using it.
Since resizing can already be done with both hands on 6DOF controllers, consider removing ratchet turn resizing for this configuration.

**Comment by johnshaughnessy** [comment]
I am working on a change to controller bindings to let us bind a flick left/right to ratchet turn without causing the object to change size and a scroll up/down to scale the object and to have only ONE of those two happen until you release the stick (with touch) (or lift from the touchpad, in the oculus go controller's case)

**Comment by misslivirose** [comment]
I don't see this happening on the Quest - given the age of the bug, @j-conrad can you confirm if this has been fixed already?

**Comment by johnshaughnessy** [comment]
I forgot to close this issue when we removed the binding for `scaleGrabbedGrabbable` for all input devices except the mouse.
