### ISSUE TITLE
Admin Panel missing "Server Settings, Access & CDN" tab

### ISSUE THREAD

**Issue by jtopaz1** [mozilla/hubs#6489]
**Description**
Questions:
1. I setup the latest mozilla hubs and find that there is no "Server Settings" tab in the admin panel. How to enable the "Server Settings" tab in the admin panel? (this link to server settings is broken: https://xxx.xxx/admin#/server-setup) ?
2. For "Content CDN" and "Server Access" are default hidden (their like is ok) in the latest Mozilla Hubs, how to enable them in default?
3. For quick start mode (development mode), I can't find admin page. how to access the admin page in development?

Thank you.

**Screenshots**
![image](https://github.com/mozilla/hubs/assets/93673289/4713e3ff-59c7-4986-8611-5297abdd1b3c)

**Comment by Exairnous** [comment]
I'm pretty sure that the settings panels you're talking about have been removed and there are equivalent configuration parameters in the setup scripts for Community Edition.  You should be able to change them when deploying.

I'm unsure what you mean by quick start mode.  Are you referring to `npm run dev` or hubs-compose?

**Comment by mikemorran** [comment]
@jtopaz1 Please see the information here: https://hubs.mozilla.com/labs/community-edition-case-study-quick-start-on-gcp-w-aws-services/#configure-admin-settings

These configs are now moved to reticulum's configmap, where you should be able to fully control everything that used to be found in the admin panel UI. Let me know if you have any question!
