### ISSUE TITLE
Video and gifs fail to load with endless loading icon. Mirage Solo ; Firefox Reality

### ISSUE THREAD

**Issue by bsouth00** [mozilla/hubs#651]
Device: Lenovo Mirage Solo
Browser: Firefox Reality

Join three users to a room, one using the Mirage headset, one tablet and one phone using chrome browser.  Mirage user can manipulate, resize the video or animated gif, but only the loading box ever appears.  Other users on the same wifi network able to view the linked items.

**Comment by brianpeiris** [comment]
Thanks for the report! We'll try to repro on a Mirage Solo.

**Comment by brianpeiris** [comment]
Looks like this can be fixed by adding `videoEl.preload = "auto";` here: 
https://github.com/mozilla/hubs/blob/master/src/components/media-views.js#L86

**Comment by bsouth00** [comment]
Thanks for the fast turn around Brian! Looks like the fix on 652 for the re-enter vr button worked fine but this one seems to be partial.  I can see the blank video frame load now after placing a youtube link from the mobile client and hear the audio now but only see a black square instead of video in the headset, video loads fine in chrome on mobile.

**Comment by brianpeiris** [comment]
Huh. I don't seem to have that problem on my Mirage Solo. Does it happen to you for all youtube videos, or only certain ones?

**Comment by bsouth00** [comment]
Maybe I just picked a bad video to test with.  I'll try a few more in the morning.  Any gist/tips on grabbing logs that might be useful to you?  I should have adb handy, if I have the time I'll see if I can screenshot and logcat something.

**Comment by brianpeiris** [comment]
Thanks. Firefox Reality has a developer mode that you can turn on in the settings, as well as a logging option.

**Comment by bsouth00** [comment]
![screenshot_20181106_103126](https://user-images.githubusercontent.com/1957026/48075181-9e3b9a00-e1b0-11e8-81d4-4cd49ce905c3.jpg)
![screenshot_20181106_103131](https://user-images.githubusercontent.com/1957026/48075189-a09df400-e1b0-11e8-9d24-f05a4e7b71ca.jpg)
![screenshot_20181106_103145](https://user-images.githubusercontent.com/1957026/48075193-a267b780-e1b0-11e8-9a11-2469e9279cf4.jpg)
[hubs_mirage_ffr_videotest-snip.log](https://github.com/mozilla/hubs/files/2553881/hubs_mirage_ffr_videotest-snip.log)

Attempted with this video (because Ronnie Chang from the Daily Show is hilarious) https://www.youtube.com/watch?v=oANUXY3xXKM

I removed what didn't seem interesting from the logcat at the top, but I think the interesting stuff is around L235 of the output provided

**Comment by bsouth00** [comment]
Well, I may have figured out why you were not able to reproduce it.  I'm not sure what I had set custom, but after doing a reset of all the dev options in the browser and restarting FFR it is working now.

**Comment by brianpeiris** [comment]
Hmm. The log does show an error about media decoding. Not sure what would cause that though. 
I'll call this issue closed for now. Feel free to re-open or create a new issue if you run into any problems.
Thanks.
