### ISSUE TITLE
No button to re-enter VR view on Mirage Solo with Firefox Reality

### ISSUE THREAD

**Issue by bsouth00** [mozilla/hubs#652]
Device: Lenovo Mirage Solo
Browser Firefox Reality

Initial visit to a room or reload of the room url provides correct options to enter VR.
Hitting "back" exits to 2D mode with no option to re-enter VR view without completely reloading the URL to reload the room.  This makes adding any links in the room from the VR headset difficult.

**Comment by johnshaughnessy** [comment]
Thanks for filing. Perhaps we should have the "enter vr" button in the hud that other webvr apps have (and that we initially had). I think we have a mirage solo here and can repro and fix this.

**Comment by brianpeiris** [comment]
We already show an "Enter in VR" button in the Oculus Go Browser:
https://github.com/mozilla/hubs/blob/master/src/react-components/ui-root.js#L1069-L1073

Its visibility is determined by this capability detection code:
https://github.com/mozilla/hubs/blob/master/src/utils/vr-caps-detect.js#L25-L28

We may be blocked by https://github.com/MozillaReality/FirefoxReality/issues/546 on this.
