### ISSUE TITLE
Textures rendering white on Oculus Go

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#673]
In this space: https://hubs.mozilla.com/JQZIo5z/model-stress-test
(or in dev: https://hubs.local:8080/hub.html?hub_id=5Rdz4t8) models are all white on Oculus Go

**Comment by robertlong** [comment]
https://hubs.mozilla.com/JQZIo5z/model-stress-test?quality=low renders the same white textures. I think this has to do with vertex colors not working properly with MobileStandardMaterial
