### ISSUE TITLE
Media links: Broken on iOS 

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#679]
Attempting to paste image, video, or model links on iOS Safari (iPhone 6s) returns broken image icon. 
I’ve tried all kinds of variants to the URLs but nothing works.
Note: uploading photos from my phone works every time.

**Comment by j-conrad** [comment]
The new pinning feature revealed more info about this bug:

Even though those media objects showed up as broken on iOS, I pinned them last night. When I visit the room today on desktop (Firefox), all of them except the Sketchfab model load properly. So with the exception of the 3d model, it seem to be less of a bug with the links themselves, and more something about loading/rendering them on mobile.

**Comment by gfodor** [comment]
This no longer seems broken afaict
