### ISSUE TITLE
Audio problem in chrome 70.0.3538.77 64-bit OS X

### ISSUE THREAD

**Issue by jxe** [mozilla/hubs#682]
Other voice sounds distorted / unrecognizable. This was on a macbook 12-in running 10.14.1 Beta. In firefox there was no problem.

**Comment by gfodor** [comment]
thanks @jxe !

**Comment by misslivirose** [comment]
I'm going to close out this bug as no-repro, especially since there's been a lot of changes involved over the past six months, but we can re-open it if the issue is still occurring.
