### ISSUE TITLE
Snapshot camera makes some models appear transparent in photos

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#734]
Not sure if it's due to specific textures/materials, or due to animation, or both, or neither... (helpful, I know)
Here's the offending model in this example:  https://sketchfab.com/models/836312def1b84e588866500a2bf79f0f
The snapshot camera photos make some of these models transparent in the photos:
![sketchfaboddity1](https://user-images.githubusercontent.com/31968496/48441811-4e754980-e741-11e8-94d7-96278fb0b501.JPG)

NOTE:  This may be corrected if Issue  #733 gets fixed.

**Comment by gfodor** [comment]
invisible cat issue is fixed afaik
