### ISSUE TITLE
Update Firefox Reality detection to use "Mobile VR" user agent

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#742]
See update in https://github.com/MozillaReality/FirefoxReality/issues/546

The workaround implemented in #670 might be brittle. Relying on the user agent is probably a better option.

**Comment by brianpeiris** [comment]
This is gated on Firefox Reality being updated in production with the new user agent.

**Comment by cvan** [comment]
You can sniff for `Mobile VR` and `Firefox` now to detect Firefox Reality in a standalone VR environment. See aframevr/aframe#4032 for context.

**Comment by gfodor** [comment]
done
