### ISSUE TITLE
Black textures on chrome

### ISSUE THREAD

**Issue by skompc** [mozilla/hubs#747]
I'm using the latest update on chrome browser and all textures appear black. Also happens on stock browser on Android but not in latest Firefox.

**Comment by netpro2k** [comment]
Any errors in the console?

**Comment by brianpeiris** [comment]
Let us know if this is still happening. It could be related to the particular device you're using as well, so if you're willing to share that information, it would help.

**Comment by gfodor** [comment]
please re-open if more info becomes available. thanks for the report!
