### ISSUE TITLE
Importing .glb files appears with no textures

### ISSUE THREAD

**Issue by Mordax** [mozilla/hubs#758]
Opened a similar issue in [Spoke](https://github.com/MozillaReality/Spoke/issues/388).

I made a 3D model and added textures to it in Paint 3D. Exported as a binary .glb and it displays correctly in Sketchfab. Issue is when I import the object from the URL inside a Hub scene, I get a greyed out version of the model with no colours and no textures. 

Same thing happens when importing into a Spoke scene. Any idea what may be causing this?

**Comment by robertlong** [comment]
@Mordax I responded on the Spoke issue.

**Comment by gfodor** [comment]
Taken to Spoke it sounds like
