### ISSUE TITLE
Hand/teleport does not work correctly with single controller devices set to left-handed

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#767]
Tested on oculus go, but likely the same issue for any similar platform with a single pointing device (including if you turn off your right controller on oculus touch).

Set your controller to be left-handed via system settings. 

Expected: left-hand model renders in the correct position, and teleport ray comes from left hand.

Actual: left-hand model does not render, instead right-hand model renders at origin of avatar, and teleport is not possible because teleport ray also immediately hits origin.

**Comment by avmakesthings** [comment]
Hi - any updates on this?  I was just testing Hubs on an Oculus Go and encountered the same issue

**Comment by gfodor** [comment]
This doesn't totally fix the issue, but at least gets the ray working again. We need to do a fairly major overhaul of the bindings to properly deal with handedness, but this should help mitigate the major usability issue for now:

https://github.com/mozilla/hubs/pull/997

**Comment by misslivirose** [comment]
Will close this out when #1621 is finished and merged
