### ISSUE TITLE
npm ci don't work

### ISSUE THREAD

**Issue by hulnglei1** [mozilla/hubs#774]
Can not install well in my ubuntu vm.  I can run npm ci well in my vm. even if I update it to the latest. 3.5.2.
It looks it can not find the usage.

**Comment by brianpeiris** [comment]
Hi, it looks like you may be stuck on an old version of npm. The `ci` command was released in npm 5.7.0, the latest version of npm is 6.4.1. I'd recommend installing nodejs 10+ first. That should get you a newer npm version automatically.

**Comment by hulnglei1** [comment]
@brianpeiris  Thanks, you are very helpful.
I update the npm and node to 6.4.1, 10+. but run npm ci are very slow in my ubuntu vm with 4 G memory.
I try the same workflow in aliyun with Ubuntu 16. It works very.   What should I do after I run "npm start"?, I still found nothing when I open the links http://hubs.local:8080

**Comment by brianpeiris** [comment]
Glad to hear it worked out. `hubs.local` is a host name we use when running the full stack locally. You should be able to access it at https://localhost:8080/ as well.

**Comment by brianpeiris** [comment]
I'm going to go ahead and close this issue. Feel free to open a new issue if you run into any other problems or reach out on our Discord: https://discord.gg/XzrGUY8
