### ISSUE TITLE
BUG: issue with room name validation

### ISSUE THREAD

**Issue by ayunami2000** [mozilla/hubs#777]
when naming a room, you can bypass the minimum character limit by simply entering spaces at the beginning and/or end of the name. it'll strip the spaces from the string *after* it checks to see if it meets the requirements for the length.

**example** by entering 4 spaces, you can have a room with no name.
**example 2** by entering between 3 and 63 spaces and then a character either before or after all the spaces, you can have a one-char room name
what it says normally ![what it says normally](https://user-images.githubusercontent.com/24785136/49691323-92275d00-fb0d-11e8-80b3-28ce9bc053e3.png)
it with 4 spaces ![it with 4 spaces](https://user-images.githubusercontent.com/24785136/49691337-d31f7180-fb0d-11e8-8967-681dbe968b69.png)
chrome tab ![chrome tab](https://user-images.githubusercontent.com/24785136/49691325-98b5d480-fb0d-11e8-976e-4614cb14a97e.png) title's room name always appears before the line, but with no name theres nothing there. (this also shows how the spaces at the beginning and end are removed automatically)
heres the address bar ![heres the address bar](https://user-images.githubusercontent.com/24785136/49691334-c438bf00-fb0d-11e8-9a14-cffd8203690b.png), but i changed the room code. you can see how there is no title after the id thing like there is normally. (this also shows how the spaces at the beginning and end are removed automatically)
The game still works as normal b/c i dont think it relies on the title of the room in the address bar, just the id of it. I'm pretty sure that any room would still load without the added title part on the end.
btw im using [this scene](https://hubs.mozilla.com/scenes/pcRAJbi/wizards-library) for this

**Comment by gfodor** [comment]
i know you were looking at this part of the server code @mqp

**Comment by mqp** [comment]
1. I'm removing the minimum character restriction and the character set restriction, so now you don't have to do anything funny if you really want your room named "a" or "     ". Go nuts!
2. It's intentional that you only need the room ID in order to link to the room. If you like to have a shorter URL to share, feel free to share it without the title.
