### ISSUE TITLE
Mozilla Hubs for tabletop!

### ISSUE THREAD

**Issue by Yoric** [mozilla/hubs#778]
I believe that VR tabletop gaming could be a killer app of Mozilla Hubs: share a deck of cards, or a board game, or a few character sheets and dice, and get all your friend playing together even though they live on different continents.

**Comment by JollyGrin** [comment]
PLEASE PLEASE PLEASE!

I would be using Hubs everyday with friends if I could load in a few board games. Right now I load in a 9x9 Go board image and then use the pen or checker models as stones. Works okay enough for expermental play yet having broader support to make tabletop through WebVR would be GAMECHANGING

**Comment by JollyGrin** [comment]
I tried creating a game of Go by using an image of a board and pieces, but they occasionally fall through the board and easily get nudged out of the way.

**Comment by misslivirose** [comment]
Converting this to an issue since I'd love to get more discussion about what folks have in mind with this type of feature.
