### ISSUE TITLE
Avatar Name Tag Improvements

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#79]
We should tune up the nametags to look better and be easier to read.

**Comment by cvan** [comment]
forgive my ignorance: to which nametags (and where) are you referring?

**Comment by gfodor** [comment]
Ah this is a general TODO for a design pass on the over-the-avatar names we are showing. 

Now that we have freeze mode working, it's definitely worthwhile to consider alternative UX where in freeze mode we give nametags one treatment/behavior and non-freeze mode another. For example, when in freeze mode they are large and persistent, and in non-freeze mode are de-emphasized somehow, for example with some alpha or auto-hide on some heuristic like gaze.

**Comment by misslivirose** [comment]
From #2292 - feedback on the positioning: "Can it be re-positioned based on the bounding box of the avatar? Or a fixed distance above the root of the object, based on the position of the head bone?"

**Comment by misslivirose** [comment]
Closing this to track work in #3110
