### ISSUE TITLE
npm ci can not work well

### ISSUE THREAD

**Issue by hulnglei1** [mozilla/hubs#797]
Hi ， I try again in aliyun, with CentOS. npm 6 node 10. not well again. can you check the log for me

[root@iZ8vb7dliqublx3e8ju86xZ hubs]# npm -v
6.4.1
[root@iZ8vb7dliqublx3e8ju86xZ hubs]# node -v
v10.13.0
[root@iZ8vb7dliqublx3e8ju86xZ hubs]# npm ci
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.4 install /root/hubs/node_modules/fsevents
> node install

> node-sass@4.9.3 install /root/hubs/node_modules/node-sass
> node scripts/install.js

Unable to save binary /root/hubs/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/root/hubs/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:750:3)
    at sync (/root/hubs/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/root/hubs/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/root/hubs/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/root/hubs/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/hubs/node_modules/node-sass/vendor' }

> node-sass@4.9.3 postinstall /root/hubs/node_modules/node-sass
> node scripts/build.js

Building: /root/node-v10.13.0-linux-x64/bin/node /root/hubs/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/root/node-v10.13.0-linux-x64/bin/node',
gyp verb cli   '/root/hubs/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.5
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.13.0
gyp verb command install [ '10.13.0' ]
gyp verb install input version string "10.13.0"
gyp verb install installing version: 10.13.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.13.0
gyp verb ensuring nodedir is created /root/.node-gyp/10.13.0
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/hubs/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.13.0' ]
gyp verb install input version string "10.13.0"
gyp verb install installing version: 10.13.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.13.0
gyp verb ensuring nodedir is created /root/hubs/node_modules/node-sass/.node-gyp/10.13.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.13.0' ]
gyp verb remove using node-gyp dir: /root/hubs/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.13.0
gyp verb remove removing development files for version: 10.13.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.13.0' ]
gyp verb remove using node-gyp dir: /root/hubs/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.13.0
gyp verb remove removing development files for version: 10.13.0
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/hubs/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
gyp ERR! command "/root/node-v10.13.0-linux-x64/bin/node" "/root/hubs/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/hubs/node_modules/node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-20T08_34_24_632Z-debug.log

**Comment by brianpeiris** [comment]
As the error message mentions, this is not an issue with Hubs, it is an issue with the way you've installed node/npm on your server. Please read through the NPM docs: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by hulnglei1** [comment]
@brianpeiris Thank you for continuously help. It works now.  Now I can log in by the https://localhost:8080.

And because I run it in aliyun, with a public ip 39.98.43.63, So that I can not see the  hubs page in https://39.98.43.63:8080  with my laptop and android phone.

I can create room, but can not join a room.   where should I change?

I change the webpack.config.js , the sentence "host: process.env.HOST_IP || "0.0.0.0",  to "host: process.env.HOST_IP || "0.0.0.0" || "39.98.43.63,"  still not work.

**Comment by hulnglei1** [comment]
when I click "join room"  error report "Cannot GET /link"
click "create a Scene", error report " Cannot GET /spoke"

**Comment by hulnglei1** [comment]
I will keep the link, https://39.98.43.63:8080/   if you are interested

**Comment by brianpeiris** [comment]
Glad to see you've got things working. The `/link` and `/spoke` page are located at `/link.html` and `/spoke.html` respectively when running a development server.

**Comment by hulnglei1** [comment]
Hi brianpeiris, 
    Thank you for your reply.
     I write the address "https://39.98.43.63:8080/link.html", I can find a page to "Enter your codes:" but still can not join a room.
     For example I create a room in my laptop. with a address "https://39.98.43.63:8080/hub.html?hub_id=Xgprw7f", click invite button to get an code 082089. then I open  the link  "https://39.98.43.63:8080/link.html" in my android phone with chrome, enter the code 082089 . Error report "We couldn't find that code. Please try again."

**Comment by brianpeiris** [comment]
Ah, I'm afraid the link codes will not work with a self-hosted Hubs client, unless you also go to the effort of setting up our backend Phoenix server https://github.com/mozilla/reticulum, which can be fairly complex, since it involves our other services.

Of course, you can still share the full `hub.html?hub_id=..." to invite people, but getting link.html to work would take some implementation changes on our part.

**Comment by hulnglei1** [comment]
understand. thanks

**Comment by cherry-fan** [comment]
> 理解。谢谢

你好，你有在阿里云上搭建成功吗？
