### ISSUE TITLE
Animated model gets clipped

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#809]
If you paste this model, it disappears when you walk too close to it:

https://sketchfab.com/models/f6b9171340504bc9a244ea993d524632

**Comment by gfodor** [comment]
feel free to un-assign @robertlong if non-trivial

**Comment by robertlong** [comment]
Looks like https://github.com/mozilla/hubs/pull/1572 should fix it.
![Jul-26-2019 14-25-16](https://user-images.githubusercontent.com/1753624/61982312-3a146c80-afb1-11e9-956a-7598647b99d6.gif)

**Comment by gfodor** [comment]
Nice! blast from the past :)
