### ISSUE TITLE
UX Improvement: Be more explicit when we are unable to use a url pasted into the custom scene dialog box

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#811]
A user attempted to use a sketchfab model in the "Create a Room" options dialog and was confused that it didn't work, since we support loading sketchfab models in-room. Currently, we just spin on the loading page when you try to do this.

We should either disallow using sketchfab URLs in that dialog, or actually resolve the sketchfab model and use it

**Comment by Mordax** [comment]
I'd like to try working on this. I'm assuming it may be nicer to actually have it work and load the scene rather than removing it completely.

**Comment by brianpeiris** [comment]
Thanks @Mordax,

One reason we may actually want to disallow sketchfab URLs is because sketchfab models often have wildly varying scales, so most sketchfab scenes may not work as expected if you just load them through this method. 
Our current recommendation for using sketchfab models as scenes is to go through [Spoke](https://hubs.mozilla.com/spoke), which gives you other benefits, like an auto-generated nav mesh.

So, I'm not entirely sure which choice we should make. I'll let the rest of the team chime in on this.

**Comment by Mordax** [comment]
Thanks @brianpeiris for responding so quickly - that's a good point, I didn't consider that to be a problem. What's the current dimensions for generating a Hubs-ready scene? Can we do some on the fly resizing for people importing it? Or pull up a dialogue box saying the size isn't the best for a Hubs scene?

**Comment by brianpeiris** [comment]
There aren't any limits on scene size in Hubs, and I don't see how we could automatically scale a sketchfab model to an appropriate scale, since you'd really have to understand the content of the scene.

**Comment by Mordax** [comment]
@brianpeiris Sorry for the late response - what do you think about replacing the `options` with something to let the user know that they should generate their pre existing room in Spoke? If not, I'm also unsure if it's fair to make users go through putting their existing rooms through Spoke. I spoke with some fellow competitors during the VR Clubhouse challenge and [they seemed to have problems with generating accurate floor plans.](https://forum.sketchfab.com/t/vr-clubhouse-cyberpunk/24547/17)

**Comment by brianpeiris** [comment]
I think we can compromise -- if a user enters a Sketchfab URL (or Google Poly URL), show a message directing them to use Spoke, otherwise, assume that the URL points to a GLTF and load it directly using the existing mechanism.

We definitely want to improve Spoke and make it the preferred option, not to force users to use it, but because it ought to actually be a better experience. @robertlong is actually working on nav mesh improvements right now.

**Comment by Mordax** [comment]
@brianpeiris Does the hubs have a real time chat that's relatively populated (irc, discord, etc) where I can shoot some quick questions? The slack discord invite doesn't seem to work.

**Comment by brianpeiris** [comment]
@Mordax We're on Discord: https://discord.gg/wHmY4nd

**Comment by misslivirose** [comment]
I notice that the originally reported issue no longer occurs (this fails silently, but is no longer stuck spinning). Since this is no longer blocking, I'm going to update this issue to a suggestion to make the error handling more explicit.

**Comment by misslivirose** [comment]
Related: #1877

**Comment by misslivirose** [comment]
I'm going to close with with a note in #1877 to consider general error handling to encompass this case.
