### ISSUE TITLE
Bluetooth headphones don't work consistently

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#828]
Testing with a generic bluetooth headset, I find that Safari 12.1.1 on Mac does not correctly use the bluetooth headset's microphone with webrtc. I've tested this with https://appr.tc/ and Hubs. Furthermore, it seems that Safari attempts to use the Mac's built-in microphone even if you select the bluetooth microphone, however, no audio comes in on the input channel.
You can see this in https://brianpeiris.github.io/mic-test/

That said, we should test this specifically with AirPods, since users are not likely to use off-brand generic bluetooth headphones. Last we checked, several months ago, AirPods did work in Safari, but recent reports say otherwise.

**Comment by gfodor** [comment]
had a user on airpods using hubs fine yesterday

**Comment by brianpeiris** [comment]
I'm going to call this issue closed, since we haven't had any reports of it being a problem. I still have issues with my off-brand bluetooth headset, but I'm going to blame it on this particular headset -- even the built-in ios voice memo app doesn't work with it.

**Comment by emclaren** [comment]
received feedback following the XR access symposium 

 "i had difficulty with sound.  I usually use wireless ipods and ended up using plugged in headsets. " - it is unclear whether this was on mac or pc

reopening this issue in case we wish to do some further testing  or tracking of issues with bluetooth headsets

**Comment by emclaren** [comment]
Thomas & Manuel reported this happening in a meeting today. I asked them to add details of their setups here

**Comment by misslivirose** [comment]
Updating this because I hit it on Windows today. 

My bluetooth headphones have a microphone and two audio profiles. One of the audio profiles would play audio out from Hubs, but it failed to play audio out as soon as I approved microphone use. If I used the onboard (laptop) microphone instead of the bluetooth headphones, one of the two profiles played audio from the room normally. 

Windows 10, Firefox

It seems like it might be related to if the browser microphone selection is used too - if you are using the 'headphones' instead of the 'headset' option for audio out in windows, selecting the headset microphone through the browser prompt seems to break audio out in Hubs. My very unofficial test:

works - windows audio out headset, microphone headset
works - windows audio out headphones, microphone realtek built in
doesn't work - windows audio out headphones, microphone headset (selected in browser prompt)
works - windows audio out headset, microphone headset (selected in browser prompt)

**Comment by misslivirose** [comment]
Tested this on Edge - had the same results as Firefox above.

**Comment by brianpeiris** [comment]
Did some investigation on this myself today, since I regularly use bluetooth headphones. My headphones also have two audio profiles, and as Liv has reported, I also see audio output stopping when I choose the "headset" microphone. I see this happening in both Firefox and Chrome.

I think this particular issue will be partially mitigated when mic selection (#3620) lands with the redesign, since users will be able to fix the audio output issue more easily by switching mics, although they would have to discover that is the problem in the first place. 

Personally, I don't run into this myself because I actually disable the "headset" profile entirely since it can lead to this type of confusion and the audio quality on that profile is much worse with my headphones.

I believe the core issue here is that the "headset" bluetooth profile ties the microphone to the corresponding "headset" output device. When you chose the "headset" microphone, you _must_ switch to the corresponding "headset" output in order to hear anything. In Firefox, we really can't do anything about this, since Firefox does not expose audio output selection in the web audio API (at least not yet, see https://bugzilla.mozilla.org/show_bug.cgi?id=1498512). 

Chrome does expose audio output selection, so there is a path for us to fix this in Chrome at least. In fact, we could do this automatically by using the `groupId` property of the devices returned by the web audio API. The "headset" input and output devices belong to the same group, so when we detect that the user is using devices from two different groups, we could at least prompt them to switch outputs. We probably shouldn't just assume they'd want to though, since there's no way to tell if they've intentionally picked devices in different groups.

I've found another issue with these dual-profile devices. When I switch to the "headset" output device in Chrome, I cannot switch back to the "headphone" output without refreshing the page. I believe this is more of a browser/OS/hardware issue though.

I've updated my little mic-test utility to demonstrate these behaviors, if it helps debug things more easily: 
https://brianpeiris.github.io/mic-test/
https://github.com/brianpeiris/mic-test

Lastly, I would suggest we separate Windows audio issues from iOS/Mac audio issues, since not everyone on the team has the devices to test both platforms, and the underlying issues can often be very different.

**Comment by keianhzo** [comment]
@brianpeiris @reganMoz For what I understand these are mostly UX issues at this point after mic selection has landed. I see two things that we should do to improve the overall audio selection UX:
- Improve the Mic selection discoverability. We currently expose the mic selection menu in the audio preferences but that's not really easy accessible by the user and needs to go through a few hops. Most of the apps expose it in a builtin menu in the Mic menu.
- Output selection where available. As commented above mostly only Chrome exposes a mechanism to select the output device right now so we should expose a conditional way to select that too. Most of the apps expose it in the same menu as the mic input selection.
- Recover from issues in a better way. Right now when the mic get disconnected (ie. bluetooth headset run out of battery) we just mute the mic. We should either switch to the next available mic or warn the user somehow (ie. open the mic selection menu so they can choose another mic)
@reganMoz Could DPX take a look at this so we can expose all this in the right way?

**Comment by brianpeiris** [comment]
Yup, I agree it's mostly UX issues and device selection ability at this point. Thanks for digging into this!

**Comment by reganMoz** [comment]
@brianpeiris, @misslivirose and @keianhzo Seeing as the description of this issue is audio issues and those have been resolved should we close this ticket? I have taken note of the suggestions and feedback from @keianhzo above and will add that to our backlog of things for us to look into.

**Comment by keianhzo** [comment]
Closing as the comments above have already been filed.
