### ISSUE TITLE
Controller drift occurs on some Rift controllers

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#829]
This appears similar to the closed bug #292. 
The small (or lack of) dead zone on the Rift controller causes drift on some controllers, likely due to minute differences in hardware calibration.
Just resting my thumb on the Left Stick causes my avatar to drift to the right. The drift will continue even after removing my thumb from the stick. Only explicitly moving the stick will make it stop.

**Comment by johnshaughnessy** [comment]
https://github.com/mozilla/hubs/pull/844
