### ISSUE TITLE
Hubs bot TODOs/suggestions

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#866]
- [ ] Join events should have the link to the room eg `Greg joined <room url>` -- we should prevent unfurls on these messages
- [x] Consider having alternative policy for echo'ing join events (perhaps same as push notifications whereby we only show join events for when the room transitions from empty to non-empty)
- [ ] If we filter join events that way, consider changing message to `Someone has joined the room for #channel at <url>`
- [ ] Stop showing leave events
- [ ] Add a `!room` (or maybe `!hubify`?) command to create + bind a room if you have permission to do so, by adding it to the second line in the discord topic
- [ ] Consider a handy `!room off` or `!dehubify` command to unbind
- [ ] Post a message with the media URL when an object is pinned
- [ ] If we broadcast pins, consider taking a canvas screenshot + uploading + pasting it into channel when media is pinned (and use this image instead of the unfurl for the URL if possible)
- [ ] Consider rate limiting photo posts or just abandoning them in favor of broadcasting pins (to reduce spam)
- [x] When the scene is changed, consider pasting `The scene for the room <url> is now <scene name>` which will result in the room unfurl showing up with an image of the new scene. (I think pasting the scene link in this context will be too confusing)
- [x] Respond properly to room rename events (update the topic slug, perhaps paste a message)
- [x] When a binding happens, automatically paste a message to the channel saying `You can now join the Hubs room for #channel: <url>` or something similar, since topic changes are not echoed into channel

**Comment by mquander** [comment]
Ones I definitely agree with:

- Posting a message on pins (but not sure if it should be on pins or on all spawns)
- Echoing binding changes into channel
- Echoing scene changes into channel
- Handling room renames correctly

Ones I'm unsure about or against:

- Adding commands to control the topic with the bot
- Using screenshot for media echoing instead of URL unfurl (why?)

Ones I want to get more data before taking action on:

- All the ones that are about reducing spam. I want to wait to see if there is actually a spam problem first before I try to reduce it by removing information.

**Comment by gfodor** [comment]
the reason I suggest a screenshot is because it puts the media in context in the room and other objects. we'd have to try it to see. it's unclear to me how much the media post in the discord is about archiving the URL and the concept of the media being used at a high level, or more directly communicating the use of the media in the room in context.

for a concrete example, consider where you're composing a few 3d models into a little scene. you want links to the resources for sure, but i am not sure if you want to be seeing those models in the hubs room or as generic thumbnails. i realize you could take a photo if you really want to ensure someone sees what you did, but as a general rule i'm guessing showing the objects in contexts will convey the most useful information "for free"

**Comment by mquander** [comment]
Hmm, you make a good point. I'm not sure what would be best yet.

**Comment by mqp** [comment]
Closing this because the Discord bot repo is the right place for these and I have ingested all of these ideas.
