### ISSUE TITLE
Firefox Android (Nightly 67) trips Firefox Reality detection

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#879]
Our check reads:
```
const isFirefoxReality = /Firefox/.test(ua) && /Android/.test(ua) && window.hasNativeWebVRImplementation;
```

`window.hasNativeWebVRImplementation` is false in Stable Firefox 
`window.hasNativeWebVRImplementation` is true in nightly 67, so we think we are in FXR.

**Comment by brianpeiris** [comment]
See also #742

**Comment by gfodor** [comment]
this should no longer be true since we are now using `isMobileVR` A-Frame check
