### ISSUE TITLE
Complete hand gesture work on vive and rift

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#89]
Not sure but I believe hand gestures still aren't fully implemented on vive. Please close if not the case!

**Comment by johnshaughnessy** [comment]
Vive input mapping : https://github.com/mozilla/mr-social-client/pull/115
Network the animation state of the hands : https://github.com/mozilla/mr-social-client/pull/114

**Comment by gfodor** [comment]
Desired button schemes:

- Oculus Touch always uses capacitance
- On Vive:
  - Grip + trigger = thumbs up
  - Grip + trigger + d-pad touch = fist
  - D-pad touch = thumb flush?
  - Consider not moving index finger on trigger so trigger is understood to be an action button
- 3dof controllers should have fixed hand pose with index finger pointing

**Comment by johnshaughnessy** [comment]
We can't use oculus touch capacitance for grip or trigger: The gamepad api doesn't show that they're touched until they're already pressed. I'm not sure who to talk to about this issue. Going to ask Kip.

**Comment by johnshaughnessy** [comment]
We can close this issue after merging the change to the vive input mapping in https://github.com/mozilla/mr-social-client/pull/216

I reported the trigger touch capacitance issue on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1455159
