### ISSUE TITLE
Audio Setup dropdown has no content

### ISSUE THREAD

**Issue by Octavector** [mozilla/hubs#900]
Using Firefox Reality on the Oculus Go, the Audio Setup dropdown provides no content. 
Clicking on the drop down control opens another modal which also contains no text or description.

![org mozilla vrbrowser-20190217-155144](https://user-images.githubusercontent.com/9148462/52915953-f2870780-32d1-11e9-81b1-1fab719690c8.jpg)

**Comment by gfodor** [comment]
The dropdown now no longer shows if there is 1 mic (hat tip @johnshaughnessy )
