### ISSUE TITLE
Cloning a shared desktop/screen/webcam causes load forever

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#917]
Attempting to use the 'clone' button on a shared desktop/screen/webcam makes the loading cube play its animation forever. If you 'remove' the loading object, the loading sound will continue to play until you load a different object.

We should probably either support cloning of shared screens or just disable the 'clone' button on these.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/972
