### ISSUE TITLE
Add a room size cap

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#95]
We should limit room capacity to some reasonable amount. (Proposal: 100)

Unsure if this should be server or client enforced.

**Comment by gfodor** [comment]
after discussions it sounded like a more conservative value may be beneficial for initial launch. iirc 12 sounded like the most mutually agreed upon value as balancing usefulness vs mitigating concerns about too many people in a room at once.

**Comment by gfodor** [comment]
Lets do 12. I believe this should be an SFU API enhancement so assigned to you @mquander -- feel free to kick back to me if you believe a client-oriented approach is the right move if the server based approach is too involved. The cap can be a soft cap, we basically just want to make it so if a link is posted to a public internet and is flooded it will eventually converge to not allowing more people in.

**Comment by mquander** [comment]
This is fine. I'll implement it as a response to the "join" message to Janus.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/208
