### ISSUE TITLE
When screensharing mic go off

### ISSUE THREAD

**Issue by alebeta90** [mozilla/hubs#953]
Hello friends,

recently testing screensharing/window sharing feature, I realize that after few seconds the microphone stop working and we get this message from Devs Console:

`ICE failed, add a TURN server and see about:webrtc for more details`

Also I have this screenshot

![image](https://user-images.githubusercontent.com/11571266/53412660-38c32180-39ca-11e9-9d30-8858d5fca11f.png)

From Janus server I can see the message saying that if it not receive audio in the next 5 seconds it will stop the audio streaming.

Also I dont know if we should implement the TURN server as suggested.

All the best

**Comment by gfodor** [comment]
A proximate cause of this was the enabling of ICE lite in Janus. This probably means there's some bug in the version of `libnice` we are using, but in any case i'll be shutting that off for now.
