### ISSUE TITLE
In-world hud should not be visible on 2D

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#979]
![image](https://user-images.githubusercontent.com/4072106/53663593-02c8ac00-3c1b-11e9-9bdc-d6090e32a885.png)

**Comment by gfodor** [comment]
apparently repro'ing this is non-trivial -- i have seen this happen more too, if we catch it in action we should debug it live.

**Comment by johnshaughnessy** [comment]
fixed
