### ISSUE TITLE
Errors in console when joining a room with drawings

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#981]
![image](https://user-images.githubusercontent.com/4072106/53665257-c51a5200-3c1f-11e9-973b-2798da7f0dd7.png)

**Comment by InfiniteLee** [comment]
This is mostly an issue with `networked-aframe`- It really shouldn't throw an error and should just ignore messages received in this case.

**Comment by brianpeiris** [comment]
Our fork of networked-aframe will now only log these in verbose mode. Assuming that drawing sync works correctly, there should be no bug here, so I'll go ahead and close this.
