### ISSUE TITLE
User feedback from meetup March 1 2019

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#983]
feedbacks i can remember: 
- color picker for pen (like tiltbrush)
- pin pen to my hand so i don't have to grip it (hard to grip vive controller and also trigger at the same time)
- ability to pin objects to avatar (e.g. a spawned hat object)
- ability to pin objects to each other (can still pick up the grouping, not just pin to the scene)
- ability to grab + stretch to resize avatar (/shrink etc. alternative) like object scaling
- ability to preload some objects into a library i can access from my in-hubs menu so i don't have to take my headset off to go search in the browser every time
- spawn camera next to my hand like the pen (spawns quite far and i have to move to go grab it)
- it would be cool if the pictures you took were available once you exit (like steam game screenshots after you leave a game)

**Comment by gfodor** [comment]
- vrdisplay on startup again sometimes
- spawn menu nag too low
- maybe grip lock pen on vive again
- typing quick gets search reset to blank
- showing vr hud in floor in non-vr mode
- audio falloff is bad
- need to figure out a way to control video volume on mobile
- pin button getting busted on scene transitions

game crash after scene transition and mousing on objects
```
TypeError: this.entities[n].components.networked is undefined
NetworkEntities.js:64
    updateEntity Aframe
    updateEntity (index):978
    receivedData Aframe
    receivedData (index):978
    onData index.js:597
    onData (index):974
    onDataChannelMessage index.js:584
    onDataChannelMessage (index):974
    i raven.js:377
TypeError: t.parentNode is nullNetworkEntities.js:160
    Aframe 2
    removeRemoteEntity (index):978
    receivedData Aframe
    receivedData (index):978
    flushPendingUpdates index.js:554
    unfreeze index.js:545
    toggleFreeze index.js:533
    onToggle freeze-controller.js:42
    onToggle (index):972
    tick freeze-controller.js:35
    Aframe 3
    ho WebGLRenderer.js:1058
    r WebGLAnimation.js:15
    i raven.js:377
```

**Comment by gfodor** [comment]
- Remote-grab/pull toward self:  regression where it pulls all the way into hand

**Comment by gfodor** [comment]
- hand-in-floor bug

**Comment by gfodor** [comment]
- Held objects vaporize during scene transition

**Comment by gfodor** [comment]
most of the non-subjective UX issues and bugs are closed out, so closing this.
