### ISSUE TITLE
User camera overtaken by landing page camera movement

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#996]
Creating a room with this particular scene: https://hubs.mozilla.com/scenes/OC6IPxi/qwerty

When the entering the room (2d desktop mode), the landing page's 'ping-ponging preview camera' continues moving while the user is moving around the space.

Not sure why that particular scene has this problem--navmesh issue? Also not sure if it occurs with other scenes.
Note: Greg noted this room loads completely black on mobile (Android). I tested on iPhone6s and it loaded correctly with no camera problems.

**Comment by misslivirose** [comment]
@j-conrad Is this still happening for you? I'm not sure what the original flow was like and other than the z-fighting in the scene, the entry experience seems normal to me. I was also able to pop in to a room with this scene on Android.

**Comment by misslivirose** [comment]
Resolving this since it doesn't appear to repro - can re-open if it does.
